# Auto-generated by tdd_orchestrator.py — Stage: reduce_mean
# DO NOT EDIT — regenerate with: tdd_orchestrator.py add-stage ...
"""
TDD Stage: reduce_mean
Tilize input, compute row-wise mean via reduce SUM with 1/W scaler, broadcast mean to full row, untilize and output
"""

import pytest
import torch
import ttnn


from .layer_norm_rm import layer_norm_rm


def pytorch_reference(input_tensor):
    """PyTorch reference for this stage."""
    mean = input_tensor.float().mean(dim=-1, keepdim=True)
    return mean.expand_as(input_tensor).to(torch.bfloat16)


@pytest.mark.parametrize(
    "shape",
    [
        pytest.param((1, 1, 32, 32), id="1x1x32x32"),
        pytest.param((1, 1, 32, 64), id="1x1x32x64"),
        pytest.param((1, 1, 64, 128), id="1x1x64x128"),
        pytest.param((1, 1, 32, 256), id="1x1x32x256"),
        pytest.param((2, 1, 64, 64), id="2x1x64x64"),
    ],
)
def test_reduce_mean(device, shape):
    """Verify Tilize input, compute row-wise mean via reduce SUM with 1/W scaler, broadcast mean to full row, untilize and output."""
    torch.manual_seed(42)
    torch_input = torch.randn(shape, dtype=torch.bfloat16)

    expected = pytorch_reference(torch_input)

    ttnn_input = ttnn.from_torch(
        torch_input,
        dtype=ttnn.bfloat16,
        layout=ttnn.ROW_MAJOR_LAYOUT,
        device=device,
        memory_config=ttnn.DRAM_MEMORY_CONFIG,
    )

    ttnn_output = layer_norm_rm(ttnn_input)

    # Shape check
    expected_shape = list(shape)
    assert list(ttnn_output.shape) == expected_shape, f"Shape: {list(ttnn_output.shape)} vs expected {expected_shape}"

    # Numerical comparison
    torch_output = ttnn.to_torch(ttnn_output)
    assert torch.allclose(
        torch_output.float(),
        expected.float(),
        rtol=0.02,
        atol=0.1,
    ), f"Max diff: {(torch_output.float() - expected.float()).abs().max()}"
