# Auto-generated by tdd_orchestrator.py — Stage: affine_transform
# Fixed by ttnn-operation-architect (template had formatting issues)
"""
TDD Stage: affine_transform
Add optional gamma (scale) and beta (shift) affine parameters. Full layer_norm with affine.
"""

import pytest
import torch
import torch.nn.functional
import ttnn

from .layer_norm_rm import layer_norm_rm


def pytorch_reference(x, gamma_1d, beta_1d):
    """PyTorch reference for this stage."""
    return torch.nn.functional.layer_norm(x, [x.shape[-1]], weight=gamma_1d, bias=beta_1d, eps=1e-5)


@pytest.mark.parametrize(
    "shape",
    [
        pytest.param((1, 1, 32, 32), id="1x1x32x32"),
        pytest.param((1, 1, 64, 128), id="1x1x64x128"),
        pytest.param((1, 1, 32, 256), id="1x1x32x256"),
        pytest.param((4, 2, 64, 64), id="4x2x64x64"),
    ],
)
def test_affine_transform(device, shape):
    """Verify optional gamma/beta affine parameters with full layer_norm."""
    torch.manual_seed(42)
    torch_input = torch.randn(shape, dtype=torch.bfloat16)
    gamma_1d = torch.randn(torch_input.shape[-1])
    beta_1d = torch.randn(torch_input.shape[-1])

    expected = pytorch_reference(torch_input, gamma_1d, beta_1d)

    ttnn_input = ttnn.from_torch(
        torch_input,
        dtype=ttnn.bfloat16,
        layout=ttnn.ROW_MAJOR_LAYOUT,
        device=device,
        memory_config=ttnn.DRAM_MEMORY_CONFIG,
    )
    gamma_ttnn = ttnn.from_torch(
        gamma_1d.unsqueeze(0).unsqueeze(0).unsqueeze(0),
        dtype=ttnn.bfloat16,
        layout=ttnn.ROW_MAJOR_LAYOUT,
        device=device,
    )
    beta_ttnn = ttnn.from_torch(
        beta_1d.unsqueeze(0).unsqueeze(0).unsqueeze(0),
        dtype=ttnn.bfloat16,
        layout=ttnn.ROW_MAJOR_LAYOUT,
        device=device,
    )

    ttnn_output = layer_norm_rm(ttnn_input, gamma=gamma_ttnn, beta=beta_ttnn)

    # Shape check
    expected_shape = list(shape)
    assert list(ttnn_output.shape) == expected_shape, f"Shape: {list(ttnn_output.shape)} vs expected {expected_shape}"

    # Numerical comparison
    torch_output = ttnn.to_torch(ttnn_output)
    assert torch.allclose(
        torch_output.float(),
        expected.float(),
        rtol=0.05,
        atol=0.2,
    ), f"Max diff: {(torch_output.float() - expected.float()).abs().max()}"
