# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Everything a run remembers, so `--fresh` can start one that remembers nothing.

WHY THIS EXISTS. A run carries state forward on purpose -- a baseline is expensive, a coverage window
costs device probes, and the write-once anchor exists so the report and the stop gate cannot score
one run against two different ceilings. All of that is right while the tool is unchanged. It is wrong
the moment the tool IS changed, because a pinned value records what it is and never which rule
produced it, so a number from a superseded formula outlives the fix indefinitely.

Measured on Voxtral-Mini-3B, 2026-08-14. The ceiling anchor held:

    {"kind": "active_bytes", "value_ms": 3611.4831, "mode": "bytes_mb",
     "source": "checkpoint bytes + HF config"}

3611.48 MB is total_params x 1.0 -- the placeholder width, from before the ceiling learned to divide
by the width the loader actually chose. compute_target takes `bytes_per_unit` ahead of every other
source, so the corrected rule (params x 2.0 measured = 7.223 GB) never ran, and the report published
141.8 tok/s/u against a true ~71. Clearing the coverage and knob caches did not touch it: it lives in
the persistent measurement ledger, and the run that "started fresh" inherited a ceiling pinned days
earlier. The model then reads as twice as close to the hardware wall as it is, which is the input to
can_stop.

WHAT IS DELIBERATELY KEPT. Hardware facts are not run state: the board topology and the device
recovery record describe the machine, not this attempt, and re-deriving them costs device time for no
gain. Everything else here is a memory OF a run and is safe to lose -- expensive to rebuild, never
wrong to rebuild.

NOTHING TRACKED BY GIT IS TOUCHED. Model source is reverted by the run's own reset step, which git can
undo; this removes only generated state, so a mistake here costs a slow run and never a lost edit.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

# Run memory: keyed by model+task, rebuilt by the next run at the cost of device time.
_STATE_GLOBS = (
    "perf_measurements_*.jsonl",  # THE ANCHOR LIVES HERE -- ceiling bytes, BEFORE/AFTER e2e
    "perf_measurements_*.jsonl.lock",
    "perf_mcp_baseline_*.json",
    "perf_mcp_full_pipeline_baseline_1cq_*.json",
    "perf_mcp_throughput_*.json",
    "perf_mcp_stage_ms_*.json",
    "perf_mcp_gate_verdicts_*.json",
    "perf_mcp_fullpipe_consumed_*.json",
    "perf_mcp_knob_cache.json",
    "perf_integrity_resolve_cache.json",
    "perf_mcp_fullpipe_gate.log",
    "cc_kernlog_*.json",
    "cc_kernlog_*.json.cumulative",
    "cc_kernlog_*.json.target",
    "cc_kernlog_*.agent.log",
    "perftest_*.agent.log",
)
_STATE_DIRS = ("perf_mcp_profile_cache", "perf_mcp_last_profile")

# The machine, not the run. Re-deriving these costs device time and answers the same thing.
KEEP = (
    "perf_mcp_board_topology.json",
    "tt_device_recovery_model_main.json",
    # THE CLAMP POINT IS THE BOARD'S, NOT THE RUN'S. This was wiped until 2026-08-14, on the reasoning
    # that a learned number can outlive the rule that produced it. But the ceiling anchor that argument
    # was written for is a DERIVED value; these are raw observations of when this hardware dropped its
    # clock, and re-deriving them means clamping again -- paid for in killed runs, not in CPU. The
    # samples also now live one level up, beside the board they describe rather than inside one model.
    "perf_mcp_thermal_profile.json",
)

# Caches the tool writes beside its own source.
_TOOL_GLOBS = ("cc_optimize/.coverage_cache.json", "cc_optimize/.mcp_config_*.json")

# Generated by a previous run into the model directory; untracked, so git will not restore them.
_MODEL_GLOBS = (
    "perf_target_inputs.json",
    "tests/e2e/*_perf.py.trace_caps.json",
)

# THE GENERATED PERF TESTS THEMSELVES, and only when git does not own them.
#
# Clearing the sidecar but leaving the test was a half-measure: on 2026-08-15 a --fresh run cleared
# 20 items and still refused to start, because preflight checked the perf test left behind by the
# PREVIOUS run and found it declared a different workload knob than the tool expected. The run had
# asked to forget everything and inherited the one file that decides what gets measured.
#
# Tracked-only-if-untracked is the whole subtlety. These same filenames were COMMITTED model source
# on the older lineage, where deleting them would violate this module's one promise -- nothing
# tracked by git is touched -- and would fight the run's own reset step, which restores tracked
# files. On a branch that generates them, they are run output like any other and regenerating costs
# only the time it took to write them the first time.
_MODEL_GENERATED_GLOBS = ("tests/e2e/*_perf.py",)


def _untracked_generated(model_dir: Path) -> list:
    """Generated perf tests git does not track. Tracked ones are left to the run's reset step.

    `git ls-files --error-unmatch` is the question asked, per file, because it is the only one that
    distinguishes "the tool wrote this" from "this ships with the model" -- the filenames are
    identical either way. Anything git cannot be consulted about (no repo, no git binary) is treated
    as TRACKED and kept: refusing to delete is the recoverable mistake here.
    """
    import subprocess

    out: list = []
    for pat in _MODEL_GENERATED_GLOBS:
        for f in sorted(model_dir.glob(pat)):
            try:
                r = subprocess.run(
                    ["git", "ls-files", "--error-unmatch", "--", f.name],
                    cwd=str(f.parent),
                    capture_output=True,
                    timeout=30,
                )
            except Exception:  # noqa: BLE001
                continue
            # EXIT 1 MEANS UNTRACKED. Anything else -- 128 for "not a git repository", a missing git
            # binary, a broken worktree -- means the question could not be ANSWERED, which is not the
            # same as "the tool generated this". Treating every non-zero code as untracked would
            # delete model source in any checkout git cannot read.
            if r.returncode == 1:
                out.append(f)
    return out


def plan(state_dir, tool_root=None, model_dir=None) -> list:
    """Every path `--fresh` would remove, in the order it would remove them. Nothing is deleted."""
    out: list = []
    sd = Path(state_dir) if state_dir else None
    if sd and sd.is_dir():
        for pat in _STATE_GLOBS:
            out += [p for p in sorted(sd.glob(pat)) if p.name not in KEEP]
        for name in _STATE_DIRS:
            p = sd / name
            if p.exists():
                out.append(p)
    if tool_root:
        for pat in _TOOL_GLOBS:
            out += sorted(Path(tool_root).glob(pat))
    if model_dir:
        for pat in _MODEL_GLOBS:
            out += sorted(Path(model_dir).glob(pat))
        out += _untracked_generated(Path(model_dir))
    return out


def wipe(state_dir, tool_root=None, model_dir=None, dry_run: bool = False) -> list:
    """Remove the run's memory. Returns what was removed (or would be, when dry_run)."""
    removed = []
    for p in plan(state_dir, tool_root, model_dir):
        if dry_run:
            removed.append(p)
            continue
        try:
            if p.is_dir():
                shutil.rmtree(p)
            else:
                p.unlink()
            removed.append(p)
        except OSError:
            continue
    return removed


def describe(removed) -> str:
    if not removed:
        return "nothing to clear -- this model has no run memory"
    return "cleared %d item(s) of run memory:\n%s" % (
        len(removed),
        "\n".join("      - %s" % p for p in removed),
    )


def published_origin(model_dir) -> str:
    """The newest model-dir commit that exists on a REMOTE, or "" when the model was never published.

    THE CAMPAIGN'S STARTING POINT, DERIVED RATHER THAN REMEMBERED. --fresh forgets the run's memory,
    so anything it could have stored about "where this campaign began" is the first thing it deletes.
    Publication is the one record that survives it: what is on a remote is the model as it was before
    this campaign touched it, and every commit after that is the campaign's own work.

    That makes the boundary a fact about the repository rather than a guess about intent, and it
    needs no flag, no config key and no per-model list. Voxtral resolves to the last bring-up commit
    (2026-08-11) with the 38 optimization commits after it excluded, which is exactly the state whose
    baseline and ceiling belong together.

    "" when nothing is published -- a model that lives only locally has no origin to return to, and
    inventing one would reset work nobody agreed to lose.
    """
    d = Path(model_dir or "")
    if not d.is_dir():
        return ""
    try:
        # "." and not the repo-root prefix: a git pathspec resolves against the CWD, so handing it
        # `models/.../voxtral_mini_3b_2507/` while standing in that directory matches nothing and
        # returns "no published origin" for a model that has one.
        r = subprocess.run(
            ["git", "rev-list", "-1", "--remotes", "--", "."],
            cwd=str(d),
            capture_output=True,
            text=True,
            timeout=120,
        )
        return (r.stdout or "").strip()
    except (NameError, AttributeError, TypeError) as bug:  # a programming error, not a git failure
        print("  [fresh-start] BUG resolving the published origin: %r" % (bug,), file=sys.stderr, flush=True)
        return ""
    except Exception:  # noqa: BLE001 -- git said no; that is an answer, not a defect
        return ""


def reset_model_to_published(model_dir, dry_run: bool = False) -> dict:
    """Return the model dir to its published state. {"origin", "changed", "why"}.

    THE ONE OPERATION HERE THAT TOUCHES TRACKED FILES, and it is separate from wipe() for that
    reason: wipe promises never to, and that promise is worth keeping intact.

    Why it belongs to --fresh at all: the wins are committed to the model tree and survive a restart,
    while the baseline and the ceiling they are measured against live in the state that --fresh
    deletes. Keeping the first and resetting the other two is the combination that lies -- the run
    re-derives its ceiling from a model that already carries the optimizations, so the target moves
    with the work. Measured on voxtral: a fidelity lever took the pinned peak from 175.5 TFLOPS
    (HiFi4, pre-campaign) to 702.0 (LoFi), and prefill's roofline ceiling from 203.82 ms to 50.95 --
    a 4x change in the yardstick caused by a win rather than by hardware, with the report presenting
    the mid-campaign checkpoint as the model's starting point.

    Resetting all three together is what makes the numbers mean one thing. The discarded commits stay
    in history and on the branch; only the working tree returns.
    """
    d = Path(model_dir or "")
    origin = published_origin(d)
    if not origin:
        return {"origin": "", "changed": False, "why": "model has no published commit to return to"}
    try:
        diff = subprocess.run(
            ["git", "diff", "--quiet", origin, "--", "."], cwd=str(d), capture_output=True, timeout=120
        )
        if diff.returncode == 0:
            return {"origin": origin, "changed": False, "why": "already at the published state"}
        if dry_run:
            return {"origin": origin, "changed": True, "why": "would reset to %s" % origin[:9]}
        co = subprocess.run(
            ["git", "checkout", origin, "--", "."], cwd=str(d), capture_output=True, text=True, timeout=300
        )
        if co.returncode != 0:
            return {"origin": origin, "changed": False, "why": "checkout failed: %s" % (co.stderr or "").strip()[:140]}
        return {"origin": origin, "changed": True, "why": "reset to published %s" % origin[:9]}
    except Exception as exc:  # noqa: BLE001
        return {"origin": origin, "changed": False, "why": "%s: %s" % (type(exc).__name__, str(exc)[:120])}
