# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.

# SPDX-License-Identifier: Apache-2.0

"""Runtime for the per-op SDXL UNet unit tests in this directory.

Each ``test_<op>.py`` holds a ``CASES`` list of pure data: one entry per distinct way the
1024x1024 ``TtUNet2DConditionModel`` (Wormhole ``ModelOptimisations1024x1024`` configs) calls
that op: tensor shapes, dtypes, layouts, memory configs (incl. shard specs), program / conv /
compute configs and the op's kwargs. The lists were generated by tracing the model
(``generate_cases.py`` next to this file) and must not be hand-edited: fix the generator.

``run_case(device, case)`` rebuilds the inputs with random data, calls
``ttnn.experimental.quasar.<op>`` (via ``qsr``) and checks the result against a torch golden.

Grid handling (``SDXL_QSR_GRID`` env var):
* ``fit`` (default): the captured configs target the Wormhole 8x8 worker grid; Quasar has 8x4.
  Sharded memory configs are remapped onto the device grid (same strategy, shard shapes
  recomputed), matmul / layer-norm / SDPA program configs and the conv output-grid override are
  dropped (op auto-config), and group-norm ``core_grid`` follows the remapped input shard grid.
  This mode answers "does the op work functionally on Quasar for this shape".
* ``captured``: everything exactly as traced. Needs a device grid of at least 8x8.

Data types: Quasar has no block-float formats, so the traced ``BFLOAT8_B`` tensors (matmul /
conv weights, group-norm masks) are built as ``BFLOAT16`` unless ``SDXL_QSR_KEEP_BFP8=1``.
"""

import math
import os

import torch

import ttnn
from models.demos.stable_diffusion_xl_base.quasar.tt import qsr
from tests.ttnn.utils_for_testing import assert_with_pcc

DTYPE = {"BFLOAT16": ttnn.bfloat16, "BFLOAT8_B": ttnn.bfloat8_b, "FLOAT32": ttnn.float32}
LAYOUT = {"TILE": ttnn.TILE_LAYOUT, "ROW_MAJOR": ttnn.ROW_MAJOR_LAYOUT}
MEM_LAYOUT = {
    "INTERLEAVED": ttnn.TensorMemoryLayout.INTERLEAVED,
    "HEIGHT_SHARDED": ttnn.TensorMemoryLayout.HEIGHT_SHARDED,
    "WIDTH_SHARDED": ttnn.TensorMemoryLayout.WIDTH_SHARDED,
    "BLOCK_SHARDED": ttnn.TensorMemoryLayout.BLOCK_SHARDED,
}
BUFFER = {"L1": ttnn.BufferType.L1, "DRAM": ttnn.BufferType.DRAM}
ORIENT = {"ROW_MAJOR": ttnn.ShardOrientation.ROW_MAJOR, "COL_MAJOR": ttnn.ShardOrientation.COL_MAJOR}
FIDELITY = {
    "LoFi": ttnn.MathFidelity.LoFi,
    "HiFi2": ttnn.MathFidelity.HiFi2,
    "HiFi3": ttnn.MathFidelity.HiFi3,
    "HiFi4": ttnn.MathFidelity.HiFi4,
}

# PCC thresholds per op (data-movement ops are bit exact in bf16, compute ops are not).
PCC = {
    "conv2d": 0.98,
    "linear": 0.98,
    "matmul": 0.98,
    "group_norm": 0.98,
    "layer_norm": 0.98,
    "scaled_dot_product_attention": 0.98,
    "silu": 0.99,
    "reciprocal": 0.99,
    "sin": 0.99,
    "cos": 0.99,
    "upsample": 0.999,
}
DEFAULT_PCC = 0.999

# the Quasar ops take the Quasar copies of the matmul program-config structs, not the mainline ttnn.* ones
QSR_OPS = ttnn._ttnn.operations.experimental.quasar


def grid_mode():
    return os.environ.get("SDXL_QSR_GRID", "fit")


def spatial_div():
    return int(os.environ.get("SDXL_QSR_CONV_SPATIAL_DIV", "1"))


def device_grid(device):
    g = device.compute_with_storage_grid_size()
    return g.x, g.y


# ----------------------------------------------------------------------------- memory configs


def _grid_dims(ranges):
    xs = max(r[2] for r in ranges) - min(r[0] for r in ranges) + 1
    ys = max(r[3] for r in ranges) - min(r[1] for r in ranges) + 1
    return xs, ys


def _align(v, tile):
    return int(math.ceil(v / tile) * tile)


def _fit_axis(extent, want, tile_aligned, min_unit=8):
    """Largest core count <= want that splits `extent` into aligned shards (tile or 16 B)."""
    unit = 32 if tile_aligned else min_unit
    for n in range(want, 0, -1):
        if extent % n == 0 and (extent // n) % unit == 0:
            return n
    return 1


def fit_sharded(mem, shape, layout_str, device):
    """Remap a captured sharded memory config onto the device grid, keeping the strategy."""
    nx_cap, ny_cap = _grid_dims(mem["shard"]["grid"])
    dx, dy = device_grid(device)
    tile = layout_str == "TILE"
    h = int(math.prod(shape[:-1]))
    w = int(shape[-1])
    layout = mem["layout"]

    # a tiled tensor's shard must be tile sized (padded): the [.., 4]-wide conv_out result shards as [.., 32]
    def shard_dims(hh, ww):
        return [_align(hh, 32), _align(ww, 32)] if tile else [hh, ww]

    if layout == "BLOCK_SHARDED":
        nx = _fit_axis(w, min(nx_cap, dx), tile)
        ny = _fit_axis(h, min(ny_cap, dy), tile) if tile else min(ny_cap, dy)
        shard = shard_dims(math.ceil(h / ny), math.ceil(w / nx))
        grid = ttnn.CoreRangeSet({ttnn.CoreRange(ttnn.CoreCoord(0, 0), ttnn.CoreCoord(nx - 1, ny - 1))})
    elif layout == "HEIGHT_SHARDED":
        ncores = min(nx_cap * ny_cap, dx * dy)
        if tile:
            ncores = max(1, min(ncores, h // 32))
        grid = ttnn.num_cores_to_corerangeset(ncores, ttnn.CoreCoord(dx, dy), row_wise=True)
        shard = shard_dims(math.ceil(h / ncores), w)
    else:  # WIDTH_SHARDED
        ncores = _fit_axis(w, min(nx_cap * ny_cap, dx * dy), tile)
        grid = ttnn.num_cores_to_corerangeset(ncores, ttnn.CoreCoord(dx, dy), row_wise=True)
        shard = shard_dims(h, math.ceil(w / ncores))
    return ttnn.MemoryConfig(
        MEM_LAYOUT[layout], BUFFER[mem["buffer"]], ttnn.ShardSpec(grid, shard, ORIENT[mem["shard"]["orientation"]])
    )


def build_mem(mem, shape, layout_str, device):
    """Captured memory-config dict -> ttnn.MemoryConfig (None for host tensors)."""
    if mem is None:
        return None
    if mem["shard"] is None:
        return ttnn.MemoryConfig(MEM_LAYOUT[mem["layout"]], BUFFER[mem["buffer"]])
    if grid_mode() == "fit":
        return fit_sharded(mem, shape, layout_str, device)
    grid = ttnn.CoreRangeSet(
        {ttnn.CoreRange(ttnn.CoreCoord(*r[:2]), ttnn.CoreCoord(*r[2:])) for r in mem["shard"]["grid"]}
    )
    shard = list(mem["shard"]["shape"])
    if layout_str == "TILE":  # the tracer records conv / matmul output shards unpadded
        shard = [_align(shard[0], 32), _align(shard[1], 32)]
    return ttnn.MemoryConfig(
        MEM_LAYOUT[mem["layout"]],
        BUFFER[mem["buffer"]],
        ttnn.ShardSpec(grid, shard, ORIENT[mem["shard"]["orientation"]]),
    )


def mem_grid_dims(mc):
    ranges = mc.shard_spec.grid.ranges()
    return _grid_dims([[r.start.x, r.start.y, r.end.x, r.end.y] for r in ranges])


# ----------------------------------------------------------------------------- tensors


def random_data(spec, gen, scale=1.0):
    shape = spec["shape"]
    return (
        (torch.randn(shape, generator=gen, dtype=torch.float32) * scale)
        if shape != []
        else torch.randn((), generator=gen) * scale
    )


def keep_bfp8():
    return os.environ.get("SDXL_QSR_KEEP_BFP8", "0") not in ("", "0", "false", "False")


def dtype_for(name):
    """Quasar has no block-float formats: bfloat8_b (WH weights, group-norm masks) becomes bfloat16
    unless SDXL_QSR_KEEP_BFP8=1 (to reproduce the TT_FATAL / test a future MX path)."""
    if name == "BFLOAT8_B" and not keep_bfp8():
        return ttnn.bfloat16
    return DTYPE[name]


def build_tensor(spec, data, device):
    """Host ttnn tensor (host tilize) then quasar.to_device with the case's memory config."""
    host = ttnn.from_torch(data, dtype_for(spec["dtype"]), layout=LAYOUT[spec["layout"]])
    if not spec["on_device"]:
        return host
    mem = build_mem(spec["mem"], spec["shape"], spec["layout"], device)
    return qsr.to_device(host, device, memory_config=mem)


def to_torch(t):
    return ttnn.to_torch(t).float()


# ----------------------------------------------------------------------------- configs


def build_compute_config(d):
    if d is None:
        return None
    return ttnn.WormholeComputeKernelConfig(
        math_fidelity=FIDELITY[d["math_fidelity"]],
        math_approx_mode=d["math_approx_mode"],
        fp32_dest_acc_en=d["fp32_dest_acc_en"],
        packer_l1_acc=d["packer_l1_acc"],
        dst_full_sync_en=d.get("dst_full_sync_en", False),
    )


def build_activation(a):
    if a is None:
        return None
    if isinstance(a, dict) and "UnaryWithParam" in a:
        op = getattr(ttnn.UnaryOpType, a["UnaryWithParam"])
        return ttnn.UnaryWithParam(op, *a.get("params", []))
    return a


def build_activations(lst):
    return None if lst is None else [build_activation(a) for a in lst]


def _xy(d):
    for key in ("CoreCoord", "CoreGrid", "xy"):
        if key in d:
            return d[key]
    raise ValueError(d)


def _fit_2d_matmul_program_config(pc, specs, params, device):
    """Remap a captured 2D (mcast) program config onto the device grid: same structure (blocking, fused
    activation, fuse_batch), grid clamped, per-core M/N recomputed from the shapes, subblocks re-derived."""
    cx, cy = _xy(pc["compute_with_storage_grid_size"])
    dx, dy = device_grid(device)
    gx, gy = min(cx, dx), min(cy, dy)
    a_shape = specs["inputs"]["input"]["shape"]
    w_shape = specs["inputs"]["weight"]["shape"]
    Mt = math.ceil(a_shape[-2] / 32)
    Kt = math.ceil(a_shape[-1] / 32)
    Nt = math.ceil(w_shape[-1] / 32)
    per_core_M = math.ceil(Mt / gy)
    per_core_N = math.ceil(Nt / gx)
    in0_block_w = pc["in0_block_w"] if Kt % pc["in0_block_w"] == 0 else 1
    ck = params.get("compute_kernel_config") or {}
    max_dst_tiles = 4 if ck.get("fp32_dest_acc_en") else 8
    best = (1, 1)
    for h in range(1, per_core_M + 1):
        if per_core_M % h:
            continue
        for w in range(1, per_core_N + 1):
            if per_core_N % w or h * w > max_dst_tiles:
                continue
            if h * w > best[0] * best[1] or (h * w == best[0] * best[1] and w > best[1]):
                best = (h, w)
    return QSR_OPS.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(gx, gy),
        in0_block_w=in0_block_w,
        out_subblock_h=best[0],
        out_subblock_w=best[1],
        out_block_h=per_core_M,
        out_block_w=per_core_N,
        per_core_M=per_core_M,
        per_core_N=per_core_N,
        transpose_mcast=bool(pc["transpose_mcast"]),
        fused_activation=build_activation(pc.get("fused_activation")),
        fuse_batch=bool(pc["fuse_batch"]),
    )


def build_matmul_program_config(pc, specs=None, params=None, device=None):
    if pc is None:
        return None
    if grid_mode() == "fit":
        # 2D mcast configs are remapped onto the device grid (keeps the fused bias/activation path the model
        # relies on); 1D configs are dropped and the op auto-configures.
        if pc["type"] == "MatmulMultiCoreReuseMultiCastProgramConfig" and specs is not None:
            return _fit_2d_matmul_program_config(pc, specs, params or {}, device)
        return None
    x, y = _xy(pc["compute_with_storage_grid_size"])
    act = build_activation(pc.get("fused_activation"))
    if pc["type"] == "MatmulMultiCoreReuseMultiCastProgramConfig":
        return QSR_OPS.MatmulMultiCoreReuseMultiCastProgramConfig(
            compute_with_storage_grid_size=(x, y),
            in0_block_w=pc["in0_block_w"],
            out_subblock_h=pc["out_subblock_h"],
            out_subblock_w=pc["out_subblock_w"],
            out_block_h=pc["out_block_h"],
            out_block_w=pc["out_block_w"],
            per_core_M=pc["per_core_M"],
            per_core_N=pc["per_core_N"],
            transpose_mcast=bool(pc["transpose_mcast"]),
            fused_activation=act,
            fuse_batch=bool(pc["fuse_batch"]),
        )
    if pc["type"] == "MatmulMultiCoreReuseMultiCast1DProgramConfig":
        return QSR_OPS.MatmulMultiCoreReuseMultiCast1DProgramConfig(
            compute_with_storage_grid_size=(x, y),
            in0_block_w=pc["in0_block_w"],
            out_subblock_h=pc["out_subblock_h"],
            out_subblock_w=pc["out_subblock_w"],
            out_block_h=pc["out_block_h"],
            out_block_w=pc["out_block_w"],
            per_core_M=pc["per_core_M"],
            per_core_N=pc["per_core_N"],
            fuse_batch=bool(pc["fuse_batch"]),
            fused_activation=act,
            mcast_in0=bool(pc["mcast_in0"]),
            gather_in0=bool(pc.get("gather_in0", False)),
        )
    raise NotImplementedError(pc["type"])


def build_sdpa_program_config(pc, device):
    if pc is None:
        return None
    x, y = _xy(pc["compute_with_storage_grid_size"])
    if grid_mode() == "fit":
        dx, dy = device_grid(device)
        x, y = min(x, dx), min(y, dy)
    return ttnn.SDPAProgramConfig(
        compute_with_storage_grid_size=(x, y),
        q_chunk_size=pc["q_chunk_size"],
        k_chunk_size=pc["k_chunk_size"],
        exp_approx_mode=pc["exp_approx_mode"],
    )


def build_layernorm_program_config(pc, input_mem):
    if pc is None:
        return None
    if pc["type"] == "LayerNormDefaultProgramConfig":
        return ttnn.LayerNormDefaultProgramConfig(legacy_reduction=pc.get("legacy_reduction", True))
    if grid_mode() == "fit":
        # the sharded layer norm grid must match the (remapped) input shard grid
        nx, ny = mem_grid_dims(input_mem)
        shard_h, shard_w = input_mem.shard_spec.shape
        block_h, block_w = shard_h // 32, shard_w // 32
        subblock_w = next(s for s in range(min(8, block_w), 0, -1) if block_w % s == 0)
        return ttnn.LayerNormShardedMultiCoreProgramConfig(
            compute_with_storage_grid_size=ttnn.CoreCoord(nx, ny),
            subblock_w=subblock_w,
            block_h=block_h,
            block_w=block_w,
            inplace=pc["inplace"],
            legacy_reduction=pc.get("legacy_reduction", True),
        )
    x, y = _xy(pc["compute_with_storage_grid_size"])
    return ttnn.LayerNormShardedMultiCoreProgramConfig(
        compute_with_storage_grid_size=ttnn.CoreCoord(x, y),
        subblock_w=pc["subblock_w"],
        block_h=pc["block_h"],
        block_w=pc["block_w"],
        inplace=pc["inplace"],
        legacy_reduction=pc.get("legacy_reduction", True),
    )


def build_conv_config(cc):
    kwargs = dict(
        weights_dtype=dtype_for(cc["weights_dtype"]),
        shard_layout=MEM_LAYOUT[cc["shard_layout"]] if cc["shard_layout"] else None,
        deallocate_activation=cc["deallocate_activation"],
        reallocate_halo_output=cc["reallocate_halo_output"],
        enable_act_double_buffer=cc["enable_act_double_buffer"],
        enable_weights_double_buffer=cc["enable_weights_double_buffer"],
        reshard_if_not_optimal=cc["reshard_if_not_optimal"],
        act_block_w_div=cc["act_block_w_div"],
        act_block_h_override=cc["act_block_h_override"],
    )
    if cc.get("override_output_sharding_config") and cc.get("core_grid") and grid_mode() != "fit":
        ranges = cc["core_grid"]["CoreRangeSet"]
        kwargs["override_output_sharding_config"] = True
        kwargs["core_grid"] = ttnn.CoreRangeSet(
            {ttnn.CoreRange(ttnn.CoreCoord(*r[:2]), ttnn.CoreCoord(*r[2:])) for r in ranges}
        )
    return ttnn.Conv2dConfig(**kwargs)


# ----------------------------------------------------------------------------- goldens


def _apply_activation(x, act):
    if act is None:
        return x
    name = act["UnaryWithParam"] if isinstance(act, dict) else str(act)
    name = name.upper()
    if name == "SILU":
        return torch.nn.functional.silu(x)
    if name == "GELU":
        return torch.nn.functional.gelu(x, approximate="tanh")
    if name == "RELU":
        return torch.relu(x)
    raise NotImplementedError(name)


def golden_conv2d(inputs, params):
    x, w, b = inputs["input"], inputs["weight"], inputs.get("bias")
    N, H, W = params["batch_size"], params["input_height"], params["input_width"]
    xi = x.reshape(N, H, W, params["in_channels"]).permute(0, 3, 1, 2)
    pad = params["padding"]
    pad = tuple(pad) if len(pad) == 2 else (pad[0], pad[2])
    y = torch.nn.functional.conv2d(
        xi,
        w,
        bias=None if b is None else b.reshape(-1),
        stride=tuple(params["stride"]),
        padding=pad,
        dilation=tuple(params["dilation"]),
        groups=params["groups"],
    )
    oh, ow = y.shape[2], y.shape[3]
    return y.permute(0, 2, 3, 1).reshape(1, 1, N * oh * ow, params["out_channels"])


def golden_matmul(inputs, params):
    a, w, b = inputs["input"], inputs["weight"], inputs.get("bias")
    # torch.matmul broadcasting matches ttnn: a [1, 77, K] @ w [1, 1, K, N] -> [1, 1, 77, N] (rank 4, like the op)
    y = torch.matmul(a, w)
    if b is not None:
        y = y + b.reshape(-1)
    pc = params.get("program_config")
    if pc is not None and pc.get("fused_activation"):
        y = _apply_activation(y, pc["fused_activation"])
    if params.get("activation"):
        y = _apply_activation(y, {"UnaryWithParam": params["activation"]})
    return y


def golden_binary(fn):
    def g(inputs, params):
        a = inputs["input_a"]
        b = inputs["input_b"] if "input_b" in inputs else params["scalar_b"]
        y = fn(a, b)
        for act in params.get("activations") or []:
            y = _apply_activation(y, act)
        return y

    return g


def golden_group_norm(inputs, params):
    x = inputs["input"]  # [1, 1, N*H*W, C], N == 1
    C = x.shape[-1]
    xi = x.reshape(-1, C).transpose(0, 1).unsqueeze(0)  # [1, C, HW]
    y = torch.nn.functional.group_norm(
        xi, params["num_groups"], inputs["gn_weight"], inputs["gn_bias"], params["epsilon"]
    )
    return y.squeeze(0).transpose(0, 1).reshape(x.shape)


def golden_layer_norm(inputs, params):
    x = inputs["input"]
    return torch.nn.functional.layer_norm(x, (x.shape[-1],), inputs["weight"], inputs["bias"], params["epsilon"])


def golden_qkv_heads(inputs, params):
    x = inputs["input"]
    H = params["num_heads"]
    B, S, D = x.shape[0], x.shape[-2], x.shape[-1]
    if params.get("num_kv_heads") == 0:
        hd = D // H
        return (x.reshape(B, S, H, hd).permute(0, 2, 1, 3),)
    hd = D // (3 * H)
    q, k, v = x.reshape(B, S, 3, H, hd).unbind(2)
    q, k, v = (t.permute(0, 2, 1, 3) for t in (q, k, v))
    if params.get("transpose_k_heads"):
        k = k.transpose(-1, -2)
    return (q, k, v)


def golden_concat_heads(inputs, params):
    x = inputs["input"]
    B, H, S, D = x.shape
    return x.permute(0, 2, 1, 3).reshape(B, 1, S, H * D)


def golden_sdpa(inputs, params):
    return torch.nn.functional.scaled_dot_product_attention(
        inputs["query"], inputs["key"], inputs["value"], is_causal=params["is_causal"]
    )


def golden_upsample(inputs, params):
    x = inputs["input"]  # [B, H, W, C]
    y = torch.nn.functional.interpolate(
        x.permute(0, 3, 1, 2), scale_factor=tuple(params["scale_factor"]), mode="nearest"
    )
    return y.permute(0, 2, 3, 1)


def golden_slice(inputs, params):
    x = inputs["input"]
    start, end = params["slice_start"], params["slice_end"]
    idx = tuple(slice(s, e) for s, e in zip(start, end))
    return x[idx]


GOLDEN = {
    "conv2d": golden_conv2d,
    "linear": golden_matmul,
    "matmul": golden_matmul,
    "add": golden_binary(lambda a, b: a + b),
    "add_": golden_binary(lambda a, b: a + b),
    "multiply": golden_binary(lambda a, b: a * b),
    "mul_": golden_binary(lambda a, b: a * b),
    "div": golden_binary(lambda a, b: a / b),
    "reciprocal": lambda i, p: 1.0 / i["input"],
    "sin": lambda i, p: torch.sin(i["input"]),
    "cos": lambda i, p: torch.cos(i["input"]),
    "silu": lambda i, p: torch.nn.functional.silu(i["input"]),
    "group_norm": golden_group_norm,
    "layer_norm": golden_layer_norm,
    "concat": lambda i, p: torch.cat([i[k] for k in sorted(i, key=lambda n: int(n.split("_")[-1]))], dim=p["dim"]),
    "reshape": lambda i, p: i["input"].reshape(p["shape"]),
    "unsqueeze": lambda i, p: i["input"].unsqueeze(p["dim"]),
    "slice": golden_slice,
    "to_layout": lambda i, p: i["input"],
    "to_memory_config": lambda i, p: i["input"],
    "sharded_to_interleaved": lambda i, p: i["input"],
    "move": lambda i, p: i["input"],
    "to_device": lambda i, p: i["input"],
    "upsample": golden_upsample,
    "nlp_create_qkv_heads": golden_qkv_heads,
    "nlp_concat_heads": golden_concat_heads,
    "scaled_dot_product_attention": golden_sdpa,
}


# ----------------------------------------------------------------------------- op invocation


def call_op(op, tensors, params, specs, device):
    """Call ttnn.experimental.quasar.<op> with the case's kwargs. Returns a tuple of outputs."""
    p = params
    out_spec = specs["outputs"][0] if specs["outputs"] else None
    mem = (
        build_mem(p.get("memory_config"), out_spec["shape"], out_spec["layout"], device)
        if (p.get("memory_config") and out_spec)
        else None
    )

    if op == "conv2d":
        # SDXL_QSR_CONV_SPATIAL_DIV=n shrinks the image by n in H and W (channels, kernel, configs unchanged)
        # so a 30+ GFLOP conv becomes simulator-sized while exercising the same per-channel blocking.
        sd = spatial_div()
        if sd > 1:
            p = dict(p, input_height=p["input_height"] // sd, input_width=p["input_width"] // sd)
        out = qsr.conv2d(
            input_tensor=tensors["input"],
            weight_tensor=tensors["weight"],
            bias_tensor=tensors.get("bias"),
            in_channels=p["in_channels"],
            out_channels=p["out_channels"],
            device=device,
            kernel_size=tuple(p["kernel_size"]),
            stride=tuple(p["stride"]),
            padding=tuple(p["padding"]),
            dilation=tuple(p["dilation"]),
            batch_size=p["batch_size"],
            input_height=p["input_height"],
            input_width=p["input_width"],
            groups=p["groups"],
            conv_config=build_conv_config(p["conv_config"]),
            compute_config=build_compute_config(p["compute_config"]),
            slice_config=ttnn.Conv2dL1FullSliceConfig,
            memory_config=None,
            return_output_dim=False,
            return_weights_and_bias=False,
            dtype=DTYPE[p["dtype"]] if p.get("dtype") else None,
        )
        return (out,)
    if op in ("linear", "matmul"):
        pc = build_matmul_program_config(p.get("program_config"), specs, p, device)
        # with the program config dropped (fit mode, 1D configs) a block-sharded output needs the program-config
        # grid, so fall back to an interleaved output in the same buffer type
        if pc is None and mem is not None and mem.is_sharded():
            mem = ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, mem.buffer_type)
        kw = dict(
            program_config=pc,
            memory_config=mem,
            compute_kernel_config=build_compute_config(p.get("compute_kernel_config")),
        )
        if p.get("dtype"):
            kw["dtype"] = DTYPE[p["dtype"]]
        activation = p.get("activation")
        # The captured program config may carry a fused activation (GEGLU: GELU); when the config is dropped
        # (fit mode) pass it as the op's activation so the result still matches the golden.
        if pc is None and isinstance(p.get("program_config"), dict) and p["program_config"].get("fused_activation"):
            activation = p["program_config"]["fused_activation"]["UnaryWithParam"].lower()
        if activation:
            kw["activation"] = activation
        if op == "linear":
            kw["bias"] = tensors.get("bias")
            return (qsr.linear(tensors["input"], tensors["weight"], **kw),)
        return (qsr.matmul(tensors["input"], tensors["weight"], **kw),)
    if op in ("add", "add_", "multiply", "mul_", "div"):
        b = tensors["input_b"] if "input_b" in tensors else p["scalar_b"]
        kw = {}
        if p.get("activations"):
            kw["activations"] = build_activations(p["activations"])
        if "fast_and_approximate_mode" in p:
            kw["fast_and_approximate_mode"] = p["fast_and_approximate_mode"]
        return (getattr(qsr, op)(tensors["input_a"], b, **kw),)
    if op in ("silu", "sin", "cos", "reciprocal"):
        return (getattr(qsr, op)(tensors["input"]),)
    if op == "group_norm":
        cg = p["core_grid"]["CoreGrid"]
        core_grid = (
            ttnn.CoreGrid(x=tensors["_gn_cores_x"], y=tensors["_gn_cores_y"])
            if grid_mode() == "fit"
            else ttnn.CoreGrid(x=cg[0], y=cg[1])
        )
        return (
            qsr.group_norm(
                tensors["input"],
                num_groups=p["num_groups"],
                input_mask=tensors["input_mask"],
                negative_mask=tensors.get("negative_mask"),
                weight=tensors["weight"],
                bias=tensors["bias"],
                epsilon=p["epsilon"],
                memory_config=tensors["input"].memory_config(),
                core_grid=core_grid,
                inplace=p["inplace"],
                num_out_blocks=p.get("num_out_blocks"),
            ),
        )
    if op == "layer_norm":
        pc = build_layernorm_program_config(p.get("program_config"), tensors["input"].memory_config())
        out_mem = mem if (mem is not None and not mem.is_sharded()) else tensors["input"].memory_config()
        return (
            qsr.layer_norm(
                tensors["input"],
                weight=tensors["weight"],
                bias=tensors["bias"],
                epsilon=p["epsilon"],
                memory_config=out_mem,
                program_config=pc,
                compute_kernel_config=build_compute_config(p.get("compute_kernel_config")),
            ),
        )
    if op == "nlp_create_qkv_heads":
        kw = dict(num_heads=p["num_heads"], transpose_k_heads=p["transpose_k_heads"], memory_config=mem)
        if p.get("num_kv_heads") is not None:
            kw["num_kv_heads"] = p["num_kv_heads"]
        outs = qsr.nlp_create_qkv_heads(tensors["input"], **kw)
        return tuple(o for o in outs if o is not None)[: 1 if p.get("num_kv_heads") == 0 else 3]
    if op == "nlp_concat_heads":
        return (qsr.nlp_concat_heads(tensors["input"], memory_config=mem),)
    if op == "scaled_dot_product_attention":
        return (
            qsr.scaled_dot_product_attention(
                tensors["query"],
                tensors["key"],
                tensors["value"],
                is_causal=p["is_causal"],
                attn_mask=None,
                program_config=build_sdpa_program_config(p.get("program_config"), device),
                compute_kernel_config=build_compute_config(p.get("compute_kernel_config")),
                memory_config=mem,
            ),
        )
    if op == "upsample":
        return (qsr.upsample(tensors["input"], tuple(p["scale_factor"])),)
    if op == "concat":
        ins = [tensors[k] for k in sorted(tensors, key=lambda n: int(n.split("_")[-1]))]
        return (qsr.concat(ins, p["dim"]),)
    if op == "reshape":
        return (qsr.reshape(tensors["input"], tuple(p["shape"])),)
    if op == "unsqueeze":
        return (qsr.unsqueeze(tensors["input"], p["dim"]),)
    if op == "slice":
        return (qsr.slice(tensors["input"], p["slice_start"], p["slice_end"]),)
    if op == "to_layout":
        return (qsr.to_layout(tensors["input"], LAYOUT[p["layout"]]),)
    if op == "to_memory_config":
        return (qsr.to_memory_config(tensors["input"], mem),)
    if op == "sharded_to_interleaved":
        return (qsr.sharded_to_interleaved(tensors["input"], mem),)
    if op == "move":
        return (qsr.move(tensors["input"]),)
    if op == "to_device":
        host = tensors["input"]
        return (
            qsr.to_device(
                host,
                device,
                memory_config=build_mem(
                    specs["outputs"][0]["mem"], specs["outputs"][0]["shape"], specs["outputs"][0]["layout"], device
                ),
            ),
        )
    raise NotImplementedError(op)


# ----------------------------------------------------------------------------- driver


def shrink_conv_case(case):
    """Apply SDXL_QSR_CONV_SPATIAL_DIV to a conv2d case: input rows N*H*W -> N*(H/n)*(W/n), params updated."""
    sd = spatial_div()
    if case["op"] != "conv2d" or sd == 1:
        return case
    p = case["params"]
    H, W = p["input_height"] // sd, p["input_width"] // sd
    case = dict(case, params=dict(p, input_height=H, input_width=W), inputs=dict(case["inputs"]))
    spec = dict(case["inputs"]["input"])
    shape = list(spec["shape"])
    if len(shape) == 4 and shape[0] == 1 and shape[1] == 1:
        shape[2] = p["batch_size"] * H * W
    else:  # [B, H, W, C] (upsampler convs)
        shape[1], shape[2] = H, W
    spec["shape"] = shape
    case["inputs"]["input"] = spec
    return case


def run_case(device, case):
    case = shrink_conv_case(case)
    op = case["op"]
    params = case["params"]
    gen = torch.Generator().manual_seed(case.get("seed", 0))
    inputs_t = {}
    tensors = {}

    for name, spec in case["inputs"].items():
        if op == "group_norm" and name in ("input_mask", "negative_mask", "weight", "bias"):
            continue  # derived below from the raw gamma/beta
        if op == "to_device":
            spec = dict(spec, on_device=False)
        scale = 1.0
        if op in ("conv2d", "linear", "matmul") and name == "weight":
            scale = 1.0 / math.sqrt(spec["shape"][-2] if op != "conv2d" else spec["shape"][1] * 9)
        if op in ("reciprocal", "div") and name in ("input", "input_b"):
            data = torch.rand(spec["shape"] if spec["shape"] != [] else (), generator=gen) + 0.5
        else:
            data = random_data(spec, gen, scale)
        if op == "conv2d" and name == "weight":
            data = data  # [Cout, Cin, kh, kw], uploaded as the model does (host, ROW_MAJOR, fp32/bf16)
        inputs_t[name] = data
        tensors[name] = build_tensor(spec, data, device)

    if op == "group_norm":
        C = case["inputs"]["input"]["shape"][-1]
        G = params["num_groups"]
        gamma = torch.randn(C, generator=gen) * 0.1 + 1.0
        beta = torch.randn(C, generator=gen) * 0.1
        inputs_t["gn_weight"], inputs_t["gn_bias"] = gamma, beta
        in_mem = tensors["input"].memory_config()
        if grid_mode() == "fit":
            nx, ny = mem_grid_dims(in_mem)
        else:
            nx, ny = params["core_grid"]["CoreGrid"]
        tensors["_gn_cores_x"], tensors["_gn_cores_y"] = nx, ny
        gamma_rm = ttnn.create_group_norm_weight_bias_rm(gamma, C, nx)
        beta_rm = ttnn.create_group_norm_weight_bias_rm(beta, C, nx)
        tensors["weight"] = qsr.from_torch(gamma_rm, ttnn.bfloat16, layout=ttnn.ROW_MAJOR_LAYOUT, device=device)
        tensors["bias"] = qsr.from_torch(beta_rm, ttnn.bfloat16, layout=ttnn.ROW_MAJOR_LAYOUT, device=device)
        mask = ttnn.create_group_norm_input_mask(C, G, nx, dtype_for("BFLOAT8_B"))
        tensors["input_mask"] = qsr.to_device(mask, device)
        if "negative_mask" in case["inputs"]:
            nmask = ttnn.create_group_norm_input_negative_mask(C, G, nx, dtype_for("BFLOAT8_B"))
            tensors["negative_mask"] = qsr.to_device(nmask, device)

    outputs = call_op(op, tensors, params, case, device)
    golden = GOLDEN[op](inputs_t, params)
    if not isinstance(golden, tuple):
        golden = (golden,)

    pcc = PCC.get(op, DEFAULT_PCC)
    for i, (got, exp) in enumerate(zip(outputs, golden)):
        got_t = to_torch(got)
        exp_t = exp.float()
        assert list(got_t.shape) == list(exp_t.shape), f"output {i}: shape {list(got_t.shape)} != {list(exp_t.shape)}"
        if op in (
            "to_layout",
            "to_memory_config",
            "sharded_to_interleaved",
            "move",
            "to_device",
            "reshape",
            "unsqueeze",
            "slice",
            "concat",
        ):
            assert torch.equal(
                got_t.to(torch.bfloat16), exp_t.to(torch.bfloat16)
            ), f"output {i}: data movement op changed values"
        else:
            assert_with_pcc(exp_t, got_t, pcc)
