# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.

# SPDX-License-Identifier: Apache-2.0

"""Per-op unit test for ``sin`` as the 1024x1024 SDXL base UNet (Quasar port) calls it.

GENERATED by generate_cases.py from a trace of TtUNet2DConditionModel / TtEulerDiscreteScheduler;
do not edit by hand. 2 unique case(s) covering 2 call(s) in one UNet forward.

Each case lists the input tensors (shape, dtype, layout, memory config incl. shard spec), the
op kwargs / program configs, the expected output spec, how many times the model issues exactly
this call and which modules do. See op_case.py for how a case is executed and compared.

Run on craq-sim (see quasar/README.md for the environment):
  pytest models/demos/stable_diffusion_xl_base/quasar/tests/ops/test_sin.py -k <case id>
"""

import pytest

from models.demos.stable_diffusion_xl_base.quasar.tests.ops.op_case import run_case

CASES = [  # fmt: off
    {
        "id": "00_1x160_l1_il",
        "op": "sin",
        "count": 1,
        "modules": ["TtTimesteps"],
        "site": "tt_timesteps.py:forward:41",
        "inputs": {
            "input": {
                "shape": [1, 160],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"memory_config": None, "inplace": False},
        "outputs": [
            {
                "shape": [1, 160],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "01_6x128_l1_il",
        "op": "sin",
        "count": 1,
        "modules": ["TtTimesteps"],
        "site": "tt_timesteps.py:forward:41",
        "inputs": {
            "input": {
                "shape": [6, 128],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"memory_config": None, "inplace": False},
        "outputs": [
            {
                "shape": [6, 128],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
]  # fmt: on


@pytest.mark.parametrize("case", CASES, ids=[c["id"] for c in CASES])
def test_sin(device, case):
    run_case(device, case)
