# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.

# SPDX-License-Identifier: Apache-2.0

"""Per-op unit test for ``to_layout`` as the 1024x1024 SDXL base UNet (Quasar port) calls it.

GENERATED by generate_cases.py from a trace of TtUNet2DConditionModel / TtEulerDiscreteScheduler;
do not edit by hand. 29 unique case(s) covering 56 call(s) in one UNet forward.

Each case lists the input tensors (shape, dtype, layout, memory config incl. shard spec), the
op kwargs / program configs, the expected output spec, how many times the model issues exactly
this call and which modules do. See op_case.py for how a case is executed and compared.

Run on craq-sim (see quasar/README.md for the environment):
  pytest models/demos/stable_diffusion_xl_base/quasar/tests/ops/test_to_layout.py -k <case id>
"""

import pytest

from models.demos.stable_diffusion_xl_base.quasar.tests.ops.op_case import run_case

CASES = [  # fmt: off
    {
        "id": "00_6x256_l1_il",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtUNet2DConditionModel"],
        "site": "tt_unet.py:forward:275",
        "inputs": {
            "input": {
                "shape": [6, 256],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [6, 256],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "01_1x2816_l1_il",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtUNet2DConditionModel"],
        "site": "tt_unet.py:forward:278",
        "inputs": {
            "input": {
                "shape": [1, 2816],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "TILE", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 2816],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "02_1x1x16384x320_l1_il",
        "op": "to_layout",
        "count": 7,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 16384, 320],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 16384, 320],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "03_1x1x16384x320_l1_block",
        "op": "to_layout",
        "count": 2,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 16384, 320],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [2048, 40], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 16384, 320],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [2048, 40], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "04_1x1x4096x320_l1_il",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 320],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 320],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "05_1x1x4096x320_l1_block",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 320],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 40], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 320],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 40], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "06_1x1x4096x640_l1_il",
        "op": "to_layout",
        "count": 5,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:218",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 640],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "07_1x1x4096x640_dram_il",
        "op": "to_layout",
        "count": 2,
        "modules": ["TtCrossAttnUpBlock2D", "TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 640],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "08_1x1x4096x640_l1_block",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 80], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 80], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "09_1x1x1024x640_dram_il",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 1024, 640],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 1024, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "10_1x1x1024x640_l1_block",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 1024, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [128, 80], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 1024, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [128, 80], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "11_1x1x1024x1280_l1_il",
        "op": "to_layout",
        "count": 7,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:218",
        "inputs": {
            "input": {
                "shape": [1, 1, 1024, 1280],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 1024, 1280],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "12_1x1x1024x1280_dram_il",
        "op": "to_layout",
        "count": 4,
        "modules": ["TtCrossAttnUpBlock2D", "TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 1024, 1280],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 1024, 1280],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "13_1x1x1024x1280_l1_block",
        "op": "to_layout",
        "count": 3,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 1024, 1280],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [128, 160], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 1024, 1280],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [128, 160], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "14_1x1x1024x2560_dram_il",
        "op": "to_layout",
        "count": 2,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 1024, 2560],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 1024, 2560],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "15_1x1x1024x2560_l1_block",
        "op": "to_layout",
        "count": 2,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 1024, 2560],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [128, 320], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 1024, 2560],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [128, 320], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "16_1x1x1024x1920_dram_il",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 1024, 1920],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 1024, 1920],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "17_1x1x1024x1920_l1_block",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 1024, 1920],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [128, 240], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 1024, 1920],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [128, 240], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "18_1x1x4096x1920_dram_il",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 1920],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 1920],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "19_1x1x4096x1920_l1_block",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 1920],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 240], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 1920],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 240], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "20_1x1x4096x1280_dram_il",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 1280],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 1280],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "21_1x1x4096x1280_l1_block",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 1280],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 160], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 1280],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 160], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "22_1x1x4096x960_l1_il",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 960],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 960],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "23_1x1x4096x960_l1_block",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 4096, 960],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 120], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 4096, 960],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [512, 120], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "24_1x1x16384x960_l1_il",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 16384, 960],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 16384, 960],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "L1", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "25_1x1x16384x960_l1_block",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 16384, 960],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [2048, 120], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 16384, 960],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [2048, 120], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "26_1x1x16384x640_dram_il",
        "op": "to_layout",
        "count": 2,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:147",
        "inputs": {
            "input": {
                "shape": [1, 1, 16384, 640],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 16384, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {"layout": "INTERLEAVED", "buffer": "DRAM", "shard": None},
                "on_device": True,
            }
        ],
    },
    {
        "id": "27_1x1x16384x640_l1_block",
        "op": "to_layout",
        "count": 2,
        "modules": ["TtResnetBlock2D"],
        "site": "tt_resnetblock2d.py:forward:169",
        "inputs": {
            "input": {
                "shape": [1, 1, 16384, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [2048, 80], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 16384, 640],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 7, 7]], "shape": [2048, 80], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
    {
        "id": "28_1x1x16384x320_l1_block",
        "op": "to_layout",
        "count": 1,
        "modules": ["TtUNet2DConditionModel"],
        "site": "tt_unet.py:forward:355",
        "inputs": {
            "input": {
                "shape": [1, 1, 16384, 320],
                "dtype": "BFLOAT16",
                "layout": "TILE",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 4, 7]], "shape": [2048, 64], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            },
        },
        "params": {"layout": "ROW_MAJOR", "dtype": None, "memory_config": None},
        "outputs": [
            {
                "shape": [1, 1, 16384, 320],
                "dtype": "BFLOAT16",
                "layout": "ROW_MAJOR",
                "mem": {
                    "layout": "BLOCK_SHARDED",
                    "buffer": "L1",
                    "shard": {"grid": [[0, 0, 4, 7]], "shape": [2048, 64], "orientation": "ROW_MAJOR"},
                },
                "on_device": True,
            }
        ],
    },
]  # fmt: on


@pytest.mark.parametrize("case", CASES, ids=[c["id"] for c in CASES])
def test_to_layout(device, case):
    run_case(device, case)
