set(FABRIC_JIT_API_HEADERS
    hw/inc/tt_fabric_api.h
    hw/inc/tt_fabric_mux.hpp
    hw/inc/tt_fabric_mux_interface.hpp
    hw/inc/fabric_routing_mode.h
    hw/inc/edm_fabric/edm_fabric_flow_control_helpers.hpp
    hw/inc/edm_fabric/edm_fabric_utils.hpp
    hw/inc/edm_fabric/edm_fabric_worker_adapters.hpp
    hw/inc/edm_fabric/edm_handshake.hpp
    hw/inc/edm_fabric/fabric_connection_manager.hpp
    hw/inc/edm_fabric/fabric_edm_packet_header_validate.hpp
    hw/inc/edm_fabric/fabric_edm_packet_transmission.hpp
    hw/inc/edm_fabric/fabric_txq_setup.h
    hw/inc/edm_fabric/fabric_erisc_datamover_channels.hpp
    hw/inc/fabric_direction_table_interface.h
    fabric_edm_packet_header.hpp
)

set(FABRIC_SOURCES
    control_plane.cpp
    mesh_graph_descriptor.cpp
    routing_table_generator.cpp
    mesh_graph.cpp
    erisc_datamover_builder.cpp
    fabric_router_channel_mapping.cpp
    fabric_router_builder.cpp
    compute_mesh_router_builder.cpp
    fabric_builder.cpp
    builder/fabric_builder_config.cpp
    builder/fabric_builder_helpers.cpp
    builder/fabric_core_placement.cpp
    builder/fabric_channel_allocator.cpp
    builder/fabric_static_sized_channels_allocator.cpp
    builder/fabric_remote_channels_allocator.cpp
    builder/static_sized_channel_connection_writer_adapter.cpp
    builder/fabric_router_recipe.cpp
    builder/channel_to_pool_mapping.cpp
    builder/multi_pool_channel_allocator.cpp
    builder/connection_registry.cpp
    builder/router_connection_mapping.cpp
    channel_trimming_export.cpp
    channel_trimming_import.cpp
    channel_trimming_io.cpp
    channel_trimming_report.cpp
    fabric.cpp
    fabric_init.cpp
    fabric_host_utils.cpp
    fabric_switch_manager.cpp
    fabric_telemetry_reader.cpp
    fabric_context.cpp
    fabric_builder_context.cpp
    fabric_mux_config.cpp
    fabric_tensix_builder.cpp
    fabric_tensix_builder_impl.cpp
    fabric_types.cpp
    compressed_direction_table.cpp
    compressed_routing_path.cpp
    serialization/router_port_directions.cpp
    serialization/physical_system_descriptor_serialization.cpp
    serialization/intermesh_connections_serialization.cpp
    serialization/port_descriptor_serialization.cpp
    ccl/ccl_common.cpp
    physical_system_descriptor.cpp
    topology_mapper.cpp
    topology_mapper_utils.cpp
    topology_solver.cpp
    physical_grouping_descriptor_core.cpp
    physical_grouping_descriptor_graph_building.cpp
    physical_grouping_descriptor_matching.cpp
)
