"""Build a listening sampler from the CURRENT build's wavs, plus a spoken index of what is what.

STATUS 3 is explicit that the last listening pass was on 82d04f977a1, before 6.52 moved codes and
frame counts, so nobody has heard this build. These wavs are the `_prg_s0` arm of the 15x3 A/B,
generated by the exact model code at HEAD (verified: no commit since 1c91d3de4c touches tt/*.py).

Order follows the previous sampler so the two are comparable by ear: both long-form English cases
first (they carry the WER number), then prosody, then the languages. Case 6 is included
deliberately -- it is the only utterance of 90 with any click, and the fp32 reference clicks MORE
on the same seed (69 vs 60), so it is a model property; the point is to hear how bad it is.
"""
import json, os, wave
import numpy as np

HERE = os.path.join(os.environ["TT_METAL_HOME"], "models/experimental/voxtral_tts")
GEN = os.path.join(HERE, "generated")
SR, GAP = 24000, 0.6

def read(p):
    with wave.open(p, "rb") as w:
        return np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16)

def main():
    fx = json.load(open(os.path.join(HERE, "tests", "prompt_fixture.json")))["cases"]
    res = {r["case"]: r for r in json.load(open(os.path.join(GEN, "results_prg_s0.json")))}
    order = [(2, "long-form English #1, 125 words - the WER case"),
             (3, "long-form English #2"),
             (1, "prosody / cheerful"),
             (0, "neutral male"),
             (11, "casual male"),
             (10, "neutral female"),
             (5, "French"), (6, "German seed 0 - clean, 1 click"),
             (-6, "German seed 1 - 60 CLICKS, the worst of all 90; fp32 ref clicks 69 here"),
             (7, "Spanish"),
             (8, "Italian"), (9, "Portuguese"), (12, "Hindi"), (13, "Arabic"), (14, "Dutch")]
    gap = np.zeros(int(SR * GAP), dtype=np.int16)
    out, idx, t = [], [], 0.0
    for ci, note in order:
        seed = "s1" if ci < 0 else "s0"      # negative case id = same case, seed 1
        ci = abs(ci)
        p = os.path.join(GEN, f"case{ci}_{fx[ci]['voice']}_prg_{seed}.wav")
        if not os.path.exists(p):
            print(f"  MISSING {p}")
            continue
        a = read(p)
        out.append(a); out.append(gap)
        dur = len(a) / SR
        cl = res[ci]["click_count"] if seed == "s0" else json.load(
            open(os.path.join(GEN, "results_prg_s1.json")))[ci]["click_count"]
        idx.append((t, t + dur, ci, fx[ci]["voice"], note, cl,
                    fx[ci]["text"][:60]))
        t += dur + GAP
    y = np.concatenate(out)
    dst = os.path.join(GEN, "SAMPLER_p150_HEAD.wav")
    with wave.open(dst, "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR)
        w.writeframes(y.tobytes())
    print(f"  wrote {dst}  ({len(y)/SR:.1f}s, {len(order)} clips)\n")
    print(f"  {'start':>7} {'end':>7} {'case':>5} {'voice':<16} {'clicks':>6}  what")
    for a, b, ci, v, note, cl, txt in idx:
        print(f"  {a:>6.1f}s {b:>6.1f}s {ci:>5} {v:<16} {cl:>6}  {note}")
        print(f"  {'':>15} {txt!r}")

if __name__ == "__main__":
    main()
