hosts: {
  hall: "SC_Floor_5"
  aisle: "A"
  rack: 1
  shelf_u: 30
  node_type: "1x_bh_quietbox"
  host: "bh-qbae-03"
}
hosts: {
  hall: "SC_Floor_5"
  aisle: "A"
  rack: 1
  shelf_u: 40
  node_type: "1x_bh_quietbox"
  host: "bh-qbae-04"
}
