# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC

# SPDX-License-Identifier: Apache-2.0

"""TTNN operation dispatch handlers and mapping."""

from models.experimental.tt_symbiote.core.dispatchers.default_dispatcher import (
    can_dispatch_to_ttnn as default_can_dispatch_to_ttnn,
)
from models.experimental.tt_symbiote.core.dispatchers.default_dispatcher import (
    handle_add,
    handle_addmm,
    handle_bernoulli_p,
    handle_bitwise_not,
    handle_bmm,
    handle_broadcast_tensors,
    handle_cat,
    handle_chunk,
    handle_clamp,
    handle_constant_pad_nd,
    handle_contiguous,
    handle_copy_,
    handle_div,
    handle_dropout,
    handle_eq,
    handle_expand,
    handle_flatten_using_ints,
    handle_gather,
    handle_gelu,
    handle_ge,
    handle_gt,
    handle_im2col,
    handle_index,
    handle_linear,
    handle_log,
    handle_log_softmax,
    handle_lt,
    handle_masked_fill_Scalar,
    handle_masked_fill_Tensor,
    handle_max,
    handle_mean,
    handle_mse_loss,
    handle_mul,
    handle_narrow,
    handle_native_layer_norm,
    handle_neg,
    handle_new_zeros,
    handle_pad,
    handle_permute,
    handle_pixel_unshuffle,
    handle_power,
    handle_relu,
    handle_repeat,
    handle_reshape,
    handle_rsqrt,
    handle_scatter_value_inplace,
    handle_sdpa,
    handle_select,
    handle_sigmoid,
    handle_silu,
    handle_slice,
    handle_softmax,
    handle_split,
    handle_squeeze,
    handle_stack,
    handle_sub,
    handle_sum,
    handle_to_copy,
    handle_to_dtype,
    handle_topk,
    handle_transpose,
    handle_unbind,
    handle_unsqueeze,
    handle_view,
    handle_where,
    handle_zeros_like,
)

# Mapping of ATen operations to TTNN handlers (single source of truth)
func_to_ttnn_compatible = {
    "aten::view": handle_view,
    "aten::_unsafe_view": handle_view,
    "aten::transpose.int": handle_transpose,
    "aten::mul.Tensor": handle_mul,
    "aten::sub.Tensor": handle_sub,
    "aten::div.Tensor": handle_div,
    "aten::slice.Tensor": handle_slice,
    "aten::neg": handle_neg,
    "aten::cat": handle_cat,
    "aten::add.Tensor": handle_add,
    "aten::unsqueeze": handle_unsqueeze,
    "aten::squeeze.dim": handle_squeeze,
    "aten::expand": handle_expand,
    "aten::mul.Scalar": handle_mul,
    "aten::sub.Scalar": handle_sub,
    "aten::add.Scalar": handle_add,
    "aten::bmm": handle_bmm,
    "aten::_softmax": handle_softmax,
    "aten::pow.Tensor_Scalar": handle_power,
    "aten::mean.dim": handle_mean,
    "aten::rsqrt": handle_rsqrt,
    "aten::gelu": handle_gelu,
    "aten::relu": handle_relu,
    "aten::new_zeros": handle_new_zeros,
    "aten::sigmoid": handle_sigmoid,
    "aten::stack": handle_stack,
    "aten::sum.dim_IntList": handle_sum,
    "aten::sum": handle_sum,
    "aten::sum.Scalar": handle_sum,
    "aten::ge.Scalar": handle_ge,
    "aten::gt.Scalar": handle_gt,
    "aten::select.int": handle_select,
    "aten::bernoulli.p": handle_bernoulli_p,
    "aten::repeat": handle_repeat,
    "aten::eq.Scalar": handle_eq,
    "aten::eq.Tensor": handle_eq,
    "aten::lt.Tensor": handle_lt,
    "aten::where.self": handle_where,
    "aten::split.Tensor": handle_split,
    "aten::split_with_sizes": handle_split,
    "aten::chunk": handle_chunk,
    "aten::chunk.Tensor": handle_chunk,
    "aten::chunk.default": handle_chunk,
    "aten::contiguous": handle_contiguous,
    "aten::_to_copy": handle_to_copy,
    "aten::max.dim": handle_max,
    "aten::addmm": handle_addmm,
    "aten::zeros_like": handle_zeros_like,
    "aten::index.Tensor": handle_index,
    "aten::topk": handle_topk,
    "aten::permute": handle_permute,
    "aten::clamp": handle_clamp,
    "aten::constant_pad_nd": handle_constant_pad_nd,
    "aten::pad": handle_pad,
    "aten::flatten.using_ints": handle_flatten_using_ints,
    "aten::im2col": handle_im2col,
    "aten::linear": handle_linear,
    "aten::clone": handle_to_copy,
    "aten::reshape": handle_reshape,
    "aten::to.dtype": handle_to_dtype,
    "aten::dropout": handle_dropout,
    "aten::broadcast_tensors": handle_broadcast_tensors,
    "aten::_safe_softmax": handle_softmax,
    "aten::mm": handle_bmm,
    "aten::silu": handle_silu,
    "aten::scatter_.value": handle_scatter_value_inplace,
    "aten::bitwise_not": handle_bitwise_not,
    "aten::gather": handle_gather,
    "aten::native_layer_norm": handle_native_layer_norm,
    "aten::mse_loss": handle_mse_loss,
    "aten::pixel_unshuffle": handle_pixel_unshuffle,
    "aten::pixel_unshuffle.default": handle_pixel_unshuffle,
    "aten::unbind.int": handle_unbind,
    "aten::narrow": handle_narrow,
    "aten::narrow.Tensor": handle_narrow,
    "aten::log": handle_log,
    "aten::log.default": handle_log,
    "aten::log_softmax": handle_log_softmax,
    "aten::log_softmax.int": handle_log_softmax,
    "aten::masked_fill.Scalar": handle_masked_fill_Scalar,
    "aten::masked_fill.Tensor": handle_masked_fill_Tensor,
    "aten::layer_norm": handle_native_layer_norm,
    "aten::native_dropout": handle_dropout,
    "aten::copy_": handle_copy_,
    "aten::_scaled_dot_product_attention": handle_sdpa,
    "aten::_scaled_dot_product_attention_flash_attention": handle_sdpa,
}


def can_dispatch_to_ttnn(func_name: str, args=None, kwargs=None) -> bool:
    """Check if operation can be dispatched to TTNN backend."""
    return func_name in func_to_ttnn_compatible and default_can_dispatch_to_ttnn(func_name, args, kwargs)


def dispatch_to_ttnn(func_name, args, kwargs):
    """Dispatch operation to TTNN handler."""
    return func_to_ttnn_compatible[func_name](func_name, args, kwargs)
