BASIC_EMPTY_EXAMPLE_SRC = programming_examples/basic_empty_program/basic_empty_program.cpp

BASIC_EMPTY_EXAMPLES_DEPS = $(PROGRAMMING_EXAMPLES_OBJDIR)/basic_empty_program.d

-include $(BASIC_EMPTY_EXAMPLES_DEPS)

.PRECIOUS: $(PROGRAMMING_EXAMPLES_TESTDIR)/basic_empty_program
$(PROGRAMMING_EXAMPLES_TESTDIR)/basic_empty_program: $(PROGRAMMING_EXAMPLES_OBJDIR)/basic_empty_program.o $(BACKEND_LIB) $(LL_BUDA_LIB) $(VERIF_LIB)
	@mkdir -p $(@D)
	$(CXX) $(CFLAGS) $(CXXFLAGS) $(PROGRAMMING_EXAMPLES_INCLUDES) -o $@ $^ $(LDFLAGS) $(PROGRAMMING_EXAMPLES_LDFLAGS)

.PRECIOUS: $(PROGRAMMING_EXAMPLES_OBJDIR)/basic_empty_program.o
$(PROGRAMMING_EXAMPLES_OBJDIR)/basic_empty_program.o: $(BASIC_EMPTY_EXAMPLE_SRC)
	@mkdir -p $(@D)
	$(CXX) $(CFLAGS) $(CXXFLAGS) $(PROGRAMMING_EXAMPLES_INCLUDES) -c -o $@ $<
