#pragma once

#include <stdint.h>

constexpr uint32_t DRAM_SYNC_MAILBOX_MAGIC = 0x44524D42u;

enum DramSyncMailboxIndex : uint32_t {
    MB_MAGIC = 0,
    MB_VERSION,

    MB_STOP,
    MB_ERROR,

    MB_JOB_ID,
    MB_BANK_ID,
    MB_BANK_OFFSET_LO,
    MB_BANK_OFFSET_HI,
    MB_TOTAL_BYTES,
    MB_CHUNK_BYTES,
    MB_PATTERN_ID_GLOBAL,
    MB_SEED_GLOBAL,
    MB_PASS_INDEX_GLOBAL,
    MB_REPEAT_INDEX_GLOBAL,

    MB_RESULT_L1_ADDR,
    MB_EXPECT_L1_ADDR,
    MB_OBSERVE_L1_ADDR,

    MB_WRITE_NOC,
    MB_READ_NOC,
    MB_MAX_BURST_LEN,
    MB_TRANSFER_LEN_MODE,
    MB_SKIP_WRITES,
    MB_SKIP_READS,

    MB_CURRENT_STAGE,
    MB_CURRENT_CHUNK,
    MB_TOTAL_CHUNKS,
    MB_CURRENT_OFFSET_BYTES,
    MB_CURRENT_TRANSFER_BYTES,
    MB_CURRENT_WORD_COUNT,
    MB_CURRENT_BASE_WORD,

    MB_NCRISC_START,
    MB_NCRISC_DONE,
    MB_NCRISC_ERROR,
    MB_NCRISC_ACTIVE_OFFSET_BYTES,
    MB_NCRISC_ACTIVE_TRANSFER_BYTES,

    MB_OBS_PING_L1_ADDR,
    MB_OBS_PONG_L1_ADDR,
    MB_OBS_ACTIVE_SLOT,
    MB_OBS_ACTIVE_L1_ADDR,

    MB_GEN_PING_L1_ADDR,
    MB_GEN_PONG_L1_ADDR,
    MB_GEN_ACTIVE_SLOT,
    MB_GEN_ACTIVE_L1_ADDR,

    MB_GENERATE_START,
    MB_GENERATE_DONE,

    MB_GENERATE_L1_ADDR,
    MB_GENERATE_WORD_COUNT,
    MB_GENERATE_BASE_WORD_INDEX,

    MB_GENERATE_MATH_DONE,
    MB_GENERATE_PACK_DONE,

    MB_COMPARE_START,
    MB_COMPARE_DONE,

    MB_COMPARE_SOURCE_L1_ADDR,
    MB_COMPARE_OBSERVED_L1_ADDR,
    MB_COMPARE_WORD_COUNT,
    MB_COMPARE_BASE_BYTE_OFFSET,

    MB_COMPARE_MATH_DONE,
    MB_COMPARE_MATH_RESULT,
    MB_COMPARE_MATH_FIRST_ADDR,
    MB_COMPARE_MATH_FIRST_EXPECTED,
    MB_COMPARE_MATH_FIRST_OBSERVED,

    MB_COMPARE_PACK_DONE,
    MB_COMPARE_PACK_RESULT,
    MB_COMPARE_PACK_FIRST_ADDR,
    MB_COMPARE_PACK_FIRST_EXPECTED,
    MB_COMPARE_PACK_FIRST_OBSERVED,

    MB_COMPARE_UNPACK_DONE,
    MB_COMPARE_UNPACK_RESULT,
    MB_COMPARE_UNPACK_FIRST_ADDR,
    MB_COMPARE_UNPACK_FIRST_EXPECTED,
    MB_COMPARE_UNPACK_FIRST_OBSERVED,

    MB_TRANSFERS,
    MB_WORDS_CHECKED,
    MB_FAILURES,

    MB_FIRST_FAIL_ADDR,
    MB_FIRST_EXPECTED,
    MB_FIRST_OBSERVED,
    MB_FAILURE_KIND,

    MB_SUSPECTED_WRITE_FAILURES,
    MB_SUSPECTED_READ_FAILURES,

    MB_LAST_USED,
};

constexpr uint32_t kDramSyncMailboxWords = 128u;
constexpr uint32_t DRAM_OBS_SLOT_PING = 0u;
constexpr uint32_t DRAM_OBS_SLOT_PONG = 1u;
constexpr uint32_t DRAM_COMPARE_HELPER_MATH = 0u;
constexpr uint32_t DRAM_COMPARE_HELPER_PACK = 1u;
constexpr uint32_t DRAM_COMPARE_HELPER_UNPACK = 2u;
constexpr uint32_t DRAM_GEN_SLOT_PING = 0u;
constexpr uint32_t DRAM_GEN_SLOT_PONG = 1u;

enum DramSyncMailboxError : uint32_t {
    MB_ERROR_NONE = 0,
    MB_ERROR_BAD_CONFIG = 1,
    MB_ERROR_STOP_REQUESTED = 2,
    MB_ERROR_NCRISC_BAD_TRANSFER = 3,
};

enum DramSyncStage : uint32_t {
    MB_STAGE_IDLE = 0,
    MB_STAGE_JOB_START,
    MB_STAGE_PREPARE,
    MB_STAGE_WRITE,
    MB_STAGE_READ,
    MB_STAGE_VERIFY,
    MB_STAGE_REREAD,
    MB_STAGE_JOB_DONE,
};
