// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#ifndef _SYNC_MAILBOX_H
#define _SYNC_MAILBOX_H

#include <stdint.h>

constexpr uint32_t DRAM_SYNC_MAILBOX_MAGIC = 0x44524D42u;

enum DramSyncMailboxIndex : uint32_t {
    MB_MAGIC = 0,
    MB_VERSION,

    MB_STOP,
    MB_ERROR,

    MB_JOB_ID,
    MB_BANK_ID,
    MB_BANK_OFFSET_LO,
    MB_BANK_OFFSET_HI,
    MB_TOTAL_BYTES,
    MB_CHUNK_BYTES,
    MB_PATTERN_ID_GLOBAL,
    MB_SEED_GLOBAL,
    MB_PASS_INDEX_GLOBAL,
    MB_REPEAT_INDEX_GLOBAL,

    MB_RESULT_L1_ADDR,
    MB_EXPECT_L1_ADDR,
    MB_OBSERVE_L1_ADDR,

    MB_WRITE_NOC,
    MB_READ_NOC,
    MB_MAX_BURST_LEN,
    MB_TRANSFER_LEN_MODE,
    MB_SKIP_WRITES,
    MB_SKIP_READS,

    MB_CURRENT_STAGE,
    MB_CURRENT_CHUNK,
    MB_TOTAL_CHUNKS,
    MB_CURRENT_OFFSET_BYTES,
    MB_CURRENT_TRANSFER_BYTES,
    MB_CURRENT_WORD_COUNT,
    MB_CURRENT_BASE_WORD,

    MB_NCRISC_START,
    MB_NCRISC_DONE,
    MB_NCRISC_ERROR,
    MB_NCRISC_ACTIVE_OFFSET_BYTES,
    MB_NCRISC_ACTIVE_TRANSFER_BYTES,

    MB_OBS_PING_L1_ADDR,
    MB_OBS_PONG_L1_ADDR,
    MB_OBS_ACTIVE_SLOT,
    MB_OBS_ACTIVE_L1_ADDR,

    MB_GEN_PING_L1_ADDR,
    MB_GEN_PONG_L1_ADDR,
    MB_GEN_ACTIVE_SLOT,
    MB_GEN_ACTIVE_L1_ADDR,

    MB_GENERATE_START,
    MB_GENERATE_DONE,

    MB_GENERATE_L1_ADDR,
    MB_GENERATE_WORD_COUNT,
    MB_GENERATE_BASE_WORD_INDEX,

    MB_GENERATE_MATH_DONE,
    MB_GENERATE_PACK_DONE,

    MB_COMPARE_START,
    MB_COMPARE_DONE,

    MB_COMPARE_SOURCE_L1_ADDR,
    MB_COMPARE_OBSERVED_L1_ADDR,
    MB_COMPARE_WORD_COUNT,
    MB_COMPARE_BASE_BYTE_OFFSET,

    MB_COMPARE_MATH_DONE,
    MB_COMPARE_MATH_RESULT,
    MB_COMPARE_MATH_FIRST_ADDR,
    MB_COMPARE_MATH_FIRST_EXPECTED,
    MB_COMPARE_MATH_FIRST_OBSERVED,

    MB_COMPARE_PACK_DONE,
    MB_COMPARE_PACK_RESULT,
    MB_COMPARE_PACK_FIRST_ADDR,
    MB_COMPARE_PACK_FIRST_EXPECTED,
    MB_COMPARE_PACK_FIRST_OBSERVED,

    MB_COMPARE_UNPACK_DONE,
    MB_COMPARE_UNPACK_RESULT,
    MB_COMPARE_UNPACK_FIRST_ADDR,
    MB_COMPARE_UNPACK_FIRST_EXPECTED,
    MB_COMPARE_UNPACK_FIRST_OBSERVED,

    MB_COMPARE_NCRISC_DONE,
    MB_COMPARE_NCRISC_RESULT,
    MB_COMPARE_NCRISC_FIRST_ADDR,
    MB_COMPARE_NCRISC_FIRST_EXPECTED,
    MB_COMPARE_NCRISC_FIRST_OBSERVED,

    MB_TRANSFERS,
    MB_WORDS_CHECKED,
    MB_FAILURES,

    MB_FIRST_FAIL_ADDR,
    MB_FIRST_EXPECTED,
    MB_FIRST_OBSERVED,
    MB_FAILURE_KIND,

    MB_SUSPECTED_WRITE_FAILURES,
    MB_SUSPECTED_READ_FAILURES,

    // Deferred failure diagnostic re-read handled by NCRISC.
    // BRISC fills REQUEST/ADDR/EXPECTED/OBSERVED before starting the next NCRISC command.
    // NCRISC performs 5 x 32B-aligned DRAM reads and writes back READBACK* and KIND
    // before publishing MB_NCRISC_DONE for that command.
    MB_NCRISC_DIAG_REQUEST,
    MB_NCRISC_DIAG_ADDR,
    MB_NCRISC_DIAG_EXPECTED,
    MB_NCRISC_DIAG_OBSERVED,
    MB_NCRISC_DIAG_READBACK0,
    MB_NCRISC_DIAG_READBACK1,
    MB_NCRISC_DIAG_READBACK2,
    MB_NCRISC_DIAG_READBACK3,
    MB_NCRISC_DIAG_READBACK4,
    MB_NCRISC_DIAG_KIND,

    // Granular profiler counters. 64-bit values are stored as LO/HI word pairs.
    MB_PROF_NCRISC_IDLE_LO,
    MB_PROF_NCRISC_IDLE_HI,
    MB_PROF_NCRISC_WRITE_ACTIVE_LO,
    MB_PROF_NCRISC_WRITE_ACTIVE_HI,
    MB_PROF_NCRISC_READ_ACTIVE_LO,
    MB_PROF_NCRISC_READ_ACTIVE_HI,
    MB_PROF_NCRISC_DIAG_ACTIVE_LO,
    MB_PROF_NCRISC_DIAG_ACTIVE_HI,
    MB_PROF_MATH_GEN_ACTIVE_LO,
    MB_PROF_MATH_GEN_ACTIVE_HI,
    MB_PROF_PACK_GEN_ACTIVE_LO,
    MB_PROF_PACK_GEN_ACTIVE_HI,
    MB_PROF_MATH_CMP_ACTIVE_LO,
    MB_PROF_MATH_CMP_ACTIVE_HI,
    MB_PROF_PACK_CMP_ACTIVE_LO,
    MB_PROF_PACK_CMP_ACTIVE_HI,
    MB_PROF_UNPACK_CMP_ACTIVE_LO,
    MB_PROF_UNPACK_CMP_ACTIVE_HI,

    // Host writes once before kernels start; NCRISC reads directly.
    MB_INSERT_ERRORS_PATTERN_ID,
    // NCRISC sets this after the first injected corruption for this mailbox.
    MB_INSERT_ERRORS_DONE,

    MB_LAST_USED,
};

constexpr uint32_t kDramSyncMailboxWords = 128u;
constexpr uint32_t DRAM_OBS_SLOT_PING = 0u;
constexpr uint32_t DRAM_OBS_SLOT_PONG = 1u;
constexpr uint32_t DRAM_COMPARE_HELPER_MATH = 0u;
constexpr uint32_t DRAM_COMPARE_HELPER_PACK = 1u;
constexpr uint32_t DRAM_COMPARE_HELPER_UNPACK = 2u;
constexpr uint32_t DRAM_GEN_SLOT_PING = 0u;
constexpr uint32_t DRAM_GEN_SLOT_PONG = 1u;

enum DramSyncMailboxError : uint32_t {
    MB_ERROR_NONE = 0,
    MB_ERROR_BAD_CONFIG = 1,
    MB_ERROR_STOP_REQUESTED = 2,
    MB_ERROR_NCRISC_BAD_TRANSFER = 3,
};

enum DramSyncStage : uint32_t {
    MB_STAGE_IDLE = 0,
    MB_STAGE_JOB_START,
    MB_STAGE_PREPARE,
    MB_STAGE_WRITE,
    MB_STAGE_READ,
    MB_STAGE_VERIFY,
    MB_STAGE_REREAD,
    MB_STAGE_JOB_DONE,
};

#endif /* _SYNC_MAILBOX_H */
