	rm .github/workflows/models-sweep-tests-impl.yaml
	rm .github/workflows/models-t1-sweep-tests.yaml
	rm .github/workflows/models-t2-sweep-tests.yaml
	rm issues/
	rm models/demos/deepseek_v3_b1/circular_buffer_utils.py
	rm models/demos/deepseek_v3_b1/demo/pipeline.py
	rm models/demos/deepseek_v3_b1/demo/stage.py
	rm models/demos/deepseek_v3_d_p/tests/
	rm pytest.38471
	rm report.test_deepseek_perf
	rm reports/
	rm tests/didt/test_deepseek_v3_128k_matmul.py
	rm tests/pipeline_reorg/blackhole_demo_tests.yaml
	rm tests/pipeline_reorg/models_sweep_tests.yaml
	rm tests/ttnn/unit_tests/operations/fused/test_softmax_program_cache.py
	rm tests/ttnn/unit_tests/operations/reduce/test_reduction_program_cache.py
	rm tmp/
	rm tt_metal/fabric/config/
	rm tt_metal/hw/inc/internal/tt-2xx/quasar/noc_nonblocking_api_v1.h
	rm tt_metal/hw/inc/internal/tt-2xx/quasar/noc_nonblocking_api_v2.h
	rm ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/all_gather_via_broadcast_factory.cpp
	rm ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/all_gather_via_broadcast_factory.hpp
	rm ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/kernels/broadcast_rm_reader.cpp
	rm ttnn/cpp/ttnn/operations/experimental/ccl/all_gather_async/device/kernels/broadcast_rm_writer.cpp
	rm ttnn/cpp/ttnn/operations/transformer/sdpa/device/kernels/compute/compute_streaming.hpp
