# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0

"""Per-perf-test CSV schema catalog.

One entry per perf test: the deliberate, reviewed set of CSV columns that test
emits, plus a ``version`` bumped whenever those columns change, and an
``aliases`` map (old_column -> new_column) that bridges a renamed column FOR
THAT TEST only. The gate in test_perf_csv_header_gate.py re-derives each test's
live columns and fails, per test, on any drift from this catalog.
"""


PERF_TEST_SCHEMAS = {
    "perf_eltwise_bcast_col_custom": {
        "version": 1,
        "columns": [
            "broadcast_type",
            "ct_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_eltwise_binary_fpu": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "marker",
            "math_fidelity",
            "mathop",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_eltwise_binary_sfpu": {
        "version": 1,
        "columns": [
            "approx_mode",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
    },
    "perf_eltwise_typecast": {
        "version": 1,
        "columns": [
            "approx_mode",
            "dest_acc",
            "fast_mode",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "input_format",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "output_format",
            "stable_sort",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
    },
    "perf_eltwise_unary_sfpu": {
        "version": 1,
        "columns": [
            "approx_mode",
            "clamp_negative",
            "dest_acc",
            "fast_mode",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "stable_sort",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
    },
    "perf_eltwise_unary_sfpu_int32": {
        "version": 1,
        "columns": [
            "approx_mode",
            "clamp_negative",
            "dest_acc",
            "fast_mode",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "stable_sort",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
    },
    "perf_fast_tilize": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_fast_tilize_full": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_fast_untilize": {
        "version": 1,
        "columns": [
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_fast_untilize_baseline_compare": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_math_matmul": {
        "version": 1,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "in0_c_dim",
            "in0_r_dim",
            "in1_c_dim",
            "in1_r_dim",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "partial_a",
            "partial_b",
            "partial_face_math",
            "partial_face_pack",
            "r_dimm",
            "throttle_level",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
    },
    "perf_math_transpose": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "marker",
            "math_transpose_faces",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {},
    },
    "perf_matmul": {
        "version": 1,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "r_dimm",
            "throttle_level",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {},
    },
    "perf_pack_dest_bank": {
        "version": 1,
        "columns": [
            "dest_acc",
            "dst_index",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "l1_acc",
            "loop_factor",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "tile_cnt",
            "tilize",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_pack_untilize": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_reduce": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "marker",
            "mathop",
            "reduce_pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_sfpu_binop_scalar": {
        "version": 2,
        "columns": [
            "approx_mode",
            "binop_mathop",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "iterations",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
            "value_bits",
        ],
        "aliases": {
            "mathop": "binop_mathop",
        },
    },
    "perf_sfpu_comp": {
        "version": 1,
        "columns": [
            "approx_mode",
            "clamp_negative",
            "dest_acc",
            "fast_mode",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "stable_sort",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
    },
    "perf_sfpu_div_wh": {
        "version": 1,
        "columns": [
            "approx_mode",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
    },
    "perf_sfpu_erfinv_wh": {
        "version": 1,
        "columns": [
            "approx_mode",
            "clamp_negative",
            "dest_acc",
            "fast_mode",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "stable_sort",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
    },
    "perf_sfpu_reduce_row_max": {
        "version": 1,
        "columns": [
            "approx_mode",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "loop_factor",
            "marker",
            "mathop",
            "pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_sfpu_reduce_sdpa": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "loop_factor",
            "marker",
            "mathop",
            "reduce_pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_sfpu_ternary": {
        "version": 2,
        "columns": [
            "approx_mode",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "iterations",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "ternary_mathop",
            "ternary_scalar_bits",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {
            "mathop": "ternary_mathop",
            "value_bits": "ternary_scalar_bits",
        },
    },
    "perf_unpack_a_bcast_eltwise": {
        "version": 1,
        "columns": [
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "marker",
            "math_fidelity",
            "mathop",
            "srca_reuse_count",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_unpack_tilize": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {},
    },
    "perf_unpack_transpose": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
    },
}
