// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC.
//
// SPDX-License-Identifier: Apache-2.0

// DO NOT EDIT THIS FILE!  It is generated from tt_metal/hw/inc/dev_msgs.h
// by scripts/codegen/codegen.sh.
// This file is to be embedded as part of arch-specifc code in HAL, and should not be used anywhere else.
// It should be included within a arch-specific namespace.
namespace raw_structs {
#include "dev_msgs.h"
}  // namespace raw_structs
namespace offsets {
using namespace raw_structs;  // in case the generated code needs to refer to the constants defined there...
static const uintptr_t ncrisc_halt_msg_t[] = {
    sizeof(raw_structs::ncrisc_halt_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::ncrisc_halt_msg_t, stack_save)),
};
static_assert(sizeof(ncrisc_halt_msg_t) == 2 * sizeof(uintptr_t));
static const uintptr_t rta_offset_t[] = {
    sizeof(raw_structs::rta_offset_t),
    static_cast<uintptr_t>(offsetof(raw_structs::rta_offset_t, crta_offset)),
};
static_assert(sizeof(rta_offset_t) == 2 * sizeof(uintptr_t));
static const uintptr_t kernel_config_msg_t[] = {
    sizeof(raw_structs::kernel_config_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, ncrisc_kernel_size16)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, kernel_config_base)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, sem_offset)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, local_cb_offset)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, remote_cb_offset)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, rta_offset)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, mode)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, pad1)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, kernel_text_offset)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, local_cb_mask)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, brisc_noc_id)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, brisc_noc_mode)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, min_remote_cb_start_index)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, exit_erisc_kernel)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, host_assigned_id)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, sub_device_origin_x)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, sub_device_origin_y)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, enables)),
    static_cast<uintptr_t>(offsetof(raw_structs::kernel_config_msg_t, preload)),
    static_cast<uintptr_t>(DISPATCH_CLASS_MAX),
    static_cast<uintptr_t>(NUM_PROGRAMMABLE_CORE_TYPES),
    static_cast<uintptr_t>(1),
    static_cast<uintptr_t>(NUM_PROCESSORS_PER_CORE_TYPE),
    reinterpret_cast<uintptr_t>(&rta_offset_t[0]),
};
static_assert(sizeof(kernel_config_msg_t) == 25 * sizeof(uintptr_t));
static const uintptr_t go_msg_t[] = {
    sizeof(raw_structs::go_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::go_msg_t, dispatch_message_offset)),
    static_cast<uintptr_t>(offsetof(raw_structs::go_msg_t, master_x)),
    static_cast<uintptr_t>(offsetof(raw_structs::go_msg_t, master_y)),
    static_cast<uintptr_t>(offsetof(raw_structs::go_msg_t, signal)),
};
static_assert(sizeof(go_msg_t) == 5 * sizeof(uintptr_t));
static const uintptr_t launch_msg_t[] = {
    sizeof(raw_structs::launch_msg_t),
    reinterpret_cast<uintptr_t>(&kernel_config_msg_t[0]),
};
static_assert(sizeof(launch_msg_t) == 2 * sizeof(uintptr_t));
static const uintptr_t subordinate_sync_msg_t[] = {
    sizeof(raw_structs::subordinate_sync_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::subordinate_sync_msg_t, dm1)),
    static_cast<uintptr_t>(offsetof(raw_structs::subordinate_sync_msg_t, trisc0)),
    static_cast<uintptr_t>(offsetof(raw_structs::subordinate_sync_msg_t, trisc1)),
    static_cast<uintptr_t>(offsetof(raw_structs::subordinate_sync_msg_t, trisc2)),
};
static_assert(sizeof(subordinate_sync_msg_t) == 5 * sizeof(uintptr_t));
static const uintptr_t debug_waypoint_msg_t[] = {
    sizeof(raw_structs::debug_waypoint_msg_t),
    static_cast<uintptr_t>(num_waypoint_bytes_per_riscv),
};
static_assert(sizeof(debug_waypoint_msg_t) == 2 * sizeof(uintptr_t));
static const uintptr_t debug_sanitize_noc_addr_msg_t[] = {
    sizeof(raw_structs::debug_sanitize_noc_addr_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_sanitize_noc_addr_msg_t, l1_addr)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_sanitize_noc_addr_msg_t, len)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_sanitize_noc_addr_msg_t, which_risc)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_sanitize_noc_addr_msg_t, return_code)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_sanitize_noc_addr_msg_t, is_multicast)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_sanitize_noc_addr_msg_t, is_write)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_sanitize_noc_addr_msg_t, is_target)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_sanitize_noc_addr_msg_t, pad)),
};
static_assert(sizeof(debug_sanitize_noc_addr_msg_t) == 9 * sizeof(uintptr_t));
static const uintptr_t debug_insert_delays_msg_t[] = {
    sizeof(raw_structs::debug_insert_delays_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_insert_delays_msg_t, write_delay_riscv_mask)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_insert_delays_msg_t, atomic_delay_riscv_mask)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_insert_delays_msg_t, feedback)),
};
static_assert(sizeof(debug_insert_delays_msg_t) == 4 * sizeof(uintptr_t));
static const uintptr_t debug_assert_msg_t[] = {
    sizeof(raw_structs::debug_assert_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_assert_msg_t, tripped)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_assert_msg_t, which)),
};
static_assert(sizeof(debug_assert_msg_t) == 3 * sizeof(uintptr_t));
static const uintptr_t debug_pause_msg_t[] = {
    sizeof(raw_structs::debug_pause_msg_t),
    static_cast<uintptr_t>(DebugNumUniqueRiscs),
};
static_assert(sizeof(debug_pause_msg_t) == 2 * sizeof(uintptr_t));
static const uintptr_t debug_ring_buf_msg_t[] = {
    sizeof(raw_structs::debug_ring_buf_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_ring_buf_msg_t, wrapped)),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_ring_buf_msg_t, data)),
    static_cast<uintptr_t>(DEBUG_RING_BUFFER_ELEMENTS),
};
static_assert(sizeof(debug_ring_buf_msg_t) == 4 * sizeof(uintptr_t));
static const uintptr_t debug_stack_usage_per_cpu_t[] = {
    sizeof(raw_structs::debug_stack_usage_per_cpu_t),
    static_cast<uintptr_t>(offsetof(raw_structs::debug_stack_usage_per_cpu_t, watcher_kernel_id)),
};
static_assert(sizeof(debug_stack_usage_per_cpu_t) == 2 * sizeof(uintptr_t));
static const uintptr_t debug_stack_usage_t[] = {
    sizeof(raw_structs::debug_stack_usage_t),
    static_cast<uintptr_t>(DebugNumUniqueRiscs),
    reinterpret_cast<uintptr_t>(&debug_stack_usage_per_cpu_t[0]),
};
static_assert(sizeof(debug_stack_usage_t) == 3 * sizeof(uintptr_t));
static const uintptr_t watcher_msg_t[] = {
    sizeof(raw_structs::watcher_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::watcher_msg_t, debug_waypoint)),
    static_cast<uintptr_t>(offsetof(raw_structs::watcher_msg_t, sanitize_noc)),
    static_cast<uintptr_t>(offsetof(raw_structs::watcher_msg_t, noc_linked_status)),
    static_cast<uintptr_t>(offsetof(raw_structs::watcher_msg_t, pad_0)),
    static_cast<uintptr_t>(offsetof(raw_structs::watcher_msg_t, assert_status)),
    static_cast<uintptr_t>(offsetof(raw_structs::watcher_msg_t, pause_status)),
    static_cast<uintptr_t>(offsetof(raw_structs::watcher_msg_t, stack_usage)),
    static_cast<uintptr_t>(offsetof(raw_structs::watcher_msg_t, debug_insert_delays)),
    static_cast<uintptr_t>(offsetof(raw_structs::watcher_msg_t, debug_ring_buf)),
    static_cast<uintptr_t>(MAX_RISCV_PER_CORE),
    static_cast<uintptr_t>(MAX_NUM_NOCS_PER_CORE),
    static_cast<uintptr_t>(2),
    reinterpret_cast<uintptr_t>(&debug_waypoint_msg_t[0]),
    reinterpret_cast<uintptr_t>(&debug_sanitize_noc_addr_msg_t[0]),
    reinterpret_cast<uintptr_t>(&debug_assert_msg_t[0]),
    reinterpret_cast<uintptr_t>(&debug_pause_msg_t[0]),
    reinterpret_cast<uintptr_t>(&debug_stack_usage_t[0]),
    reinterpret_cast<uintptr_t>(&debug_insert_delays_msg_t[0]),
    reinterpret_cast<uintptr_t>(&debug_ring_buf_msg_t[0]),
};
static_assert(sizeof(watcher_msg_t) == 20 * sizeof(uintptr_t));
static const uintptr_t addressable_core_t[] = {
    sizeof(raw_structs::addressable_core_t),
    static_cast<uintptr_t>(offsetof(raw_structs::addressable_core_t, y)),
};
static_assert(sizeof(addressable_core_t) == 2 * sizeof(uintptr_t));
static const uintptr_t core_info_msg_t[] = {
    sizeof(raw_structs::core_info_msg_t),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, noc_pcie_addr_end)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, noc_dram_addr_base)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, noc_dram_addr_end)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, harvested_coords)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, virtual_harvested_coords)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, noc_size_x)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, noc_size_y)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, worker_grid_size_x)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, worker_grid_size_y)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, absolute_logical_x)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, absolute_logical_y)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, l1_unreserved_start)),
    static_cast<uintptr_t>(offsetof(raw_structs::core_info_msg_t, pad)),
    static_cast<uintptr_t>(MAX_HARVESTED_ON_AXIS),
};
static_assert(sizeof(core_info_msg_t) == 15 * sizeof(uintptr_t));
static const uintptr_t mailboxes_t[] = {
    sizeof(raw_structs::mailboxes_t),
    static_cast<uintptr_t>(offsetof(raw_structs::mailboxes_t, subordinate_sync)),
    static_cast<uintptr_t>(offsetof(raw_structs::mailboxes_t, launch_msg_rd_ptr)),
    static_cast<uintptr_t>(offsetof(raw_structs::mailboxes_t, launch)),
    static_cast<uintptr_t>(offsetof(raw_structs::mailboxes_t, go_messages)),
    static_cast<uintptr_t>(offsetof(raw_structs::mailboxes_t, pads_1)),
    static_cast<uintptr_t>(offsetof(raw_structs::mailboxes_t, go_message_index)),
    static_cast<uintptr_t>(offsetof(raw_structs::mailboxes_t, watcher)),
    static_cast<uintptr_t>(offsetof(raw_structs::mailboxes_t, core_info)),
    static_cast<uintptr_t>(offsetof(raw_structs::mailboxes_t, pads_2)),
    static_cast<uintptr_t>(launch_msg_buffer_num_entries),
    static_cast<uintptr_t>(go_message_num_entries),
    static_cast<uintptr_t>(3),
    static_cast<uintptr_t>(PROFILER_NOC_ALIGNMENT_PAD_COUNT),
    reinterpret_cast<uintptr_t>(&ncrisc_halt_msg_t[0]),
    reinterpret_cast<uintptr_t>(&subordinate_sync_msg_t[0]),
    reinterpret_cast<uintptr_t>(&launch_msg_t[0]),
    reinterpret_cast<uintptr_t>(&go_msg_t[0]),
    reinterpret_cast<uintptr_t>(&watcher_msg_t[0]),
    reinterpret_cast<uintptr_t>(&core_info_msg_t[0]),
};
static_assert(sizeof(mailboxes_t) == 20 * sizeof(uintptr_t));
static const uintptr_t eth_word_t[] = {
    sizeof(raw_structs::eth_word_t),
    static_cast<uintptr_t>(offsetof(raw_structs::eth_word_t, dst_cmd_valid)),
    static_cast<uintptr_t>(offsetof(raw_structs::eth_word_t, reserved_0)),
    static_cast<uintptr_t>(offsetof(raw_structs::eth_word_t, reserved_1)),
};
static_assert(sizeof(eth_word_t) == 4 * sizeof(uintptr_t));
static const uintptr_t routing_info_t[] = {
    sizeof(raw_structs::routing_info_t),
    static_cast<uintptr_t>(offsetof(raw_structs::routing_info_t, src_sent_valid_cmd)),
    static_cast<uintptr_t>(offsetof(raw_structs::routing_info_t, dst_acked_valid_cmd)),
    static_cast<uintptr_t>(offsetof(raw_structs::routing_info_t, unused_arg0)),
    static_cast<uintptr_t>(offsetof(raw_structs::routing_info_t, fd_buffer_msgs)),
    static_cast<uintptr_t>(2),
    reinterpret_cast<uintptr_t>(&eth_word_t[0]),
};
static_assert(sizeof(routing_info_t) == 7 * sizeof(uintptr_t));
}  // namespace offsets
static tt::tt_metal::hal::dev_msgs::detail::Impl impl_{
    {offsets::ncrisc_halt_msg_t},
    {offsets::rta_offset_t},
    {offsets::kernel_config_msg_t},
    {offsets::go_msg_t},
    {offsets::launch_msg_t},
    {offsets::subordinate_sync_msg_t},
    {offsets::debug_waypoint_msg_t},
    {offsets::debug_sanitize_noc_addr_msg_t},
    {offsets::debug_insert_delays_msg_t},
    {offsets::debug_assert_msg_t},
    {offsets::debug_pause_msg_t},
    {offsets::debug_ring_buf_msg_t},
    {offsets::debug_stack_usage_per_cpu_t},
    {offsets::debug_stack_usage_t},
    {offsets::watcher_msg_t},
    {offsets::addressable_core_t},
    {offsets::core_info_msg_t},
    {offsets::mailboxes_t},
    {offsets::eth_word_t},
    {offsets::routing_info_t},
};
