# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0

"""
Per-layer KV cache accuracy test for GPT-OSS prefill.

For each decoder layer, compares the K and V tensors written into the TT KV cache
during prefill against the HF reference oracle.  A mismatch in an early layer quickly
localises bugs in QKV projection, RoPE, or ttnn.fill_cache.

Requires oracle data generated by hf_reference_oracle.py --save-kv:
  python3 models/demos/gpt_oss_d_p/tests/accuracy/hf_reference_oracle.py \\
      --out /data/jmalone/gpt_oss_ref \\
      --prompt "What are the prime factors of 1?" \\
      --save-kv --max-layers 5

Then run this test (4×8 mesh, SP=4 TP=8):
  export HF_MODEL=/data/jmalone/.cache/huggingface/hub/...
  export TT_MESH_GRAPH_DESC_PATH=...
  python3 models/demos/gpt_oss_d_p/tests/accuracy/kv_cache_prefill.py \\
      --oracle-dir /data/jmalone/gpt_oss_ref \\
      --prompt "What are the prime factors of 1?" \\
      --max-layers 5

Notes:
  - Non-paged attention only. Paged cache has a different block layout and requires
    a page_table to reconstruct; handle separately if needed.
  - SP>1 (multi-row mesh): each row independently fills positions 0..isl_per_row-1 of its
    local cache with its sequence shard.  This script gathers all rows and concatenates their
    shards to reconstruct the full [num_kv_heads, real_len, head_dim] tensor.  RoPE matrices
    are also per-row offset so each row's K values use the correct absolute positions.
  - The TT cache is stored in bfloat8_b after ttnn.fill_cache; expect PCC ~0.98-0.99
    vs the bf16 HF reference rather than near 1.0.
"""

import argparse
import gc
import json
import pathlib
import sys

import numpy as np
import torch

import ttnn
from models.tt_transformers.tt.load_checkpoints import permute_1d

PCC_THRESHOLD = 0.97


def _pcc(a: torch.Tensor, b: torch.Tensor) -> float:
    a = a.flatten().float()
    b = b.flatten().float()
    am = a - a.mean()
    bm = b - b.mean()
    denom = am.norm() * bm.norm()
    return float((am * bm).sum() / (denom + 1e-8))


def _sp_shard_embed(mesh, model, padded_ids, sp, isl_per_row):
    t = torch.tensor(padded_ids, dtype=torch.int64).reshape(sp, 1, 1, isl_per_row)
    tokens = ttnn.from_torch(
        t,
        device=mesh,
        dtype=ttnn.uint32,
        layout=ttnn.ROW_MAJOR_LAYOUT,
        mesh_mapper=ttnn.ShardTensor2dMesh(mesh, mesh_shape=mesh.shape, dims=(0, None)),
    )
    emb = ttnn.embedding(tokens, model.embedding_weight, layout=ttnn.TILE_LAYOUT, dtype=ttnn.bfloat8_b)
    tokens.deallocate(True)
    if len(emb.shape) == 3:
        emb = ttnn.unsqueeze_to_4D(emb)
    return emb


def _oracle_hidden_states_to_tt(mesh, hs_np, sp, isl_per_row, max_seq_len):
    """Convert oracle layer output [1, real_len, hidden_size] to a TT tensor matching
    the shape/layout of the embedding output: per-device [1, 1, isl_per_row, hidden_size],
    SP-sharded on sequence (dim 2), replicated across TP.

    Pads the sequence dim with zeros up to max_seq_len if needed.  Padded positions
    don't affect the K/V cache PCC comparison since only real positions are read back.
    """
    hs = torch.from_numpy(hs_np).float()  # [1, real_len, hidden_size]
    real_len = hs.shape[1]
    hidden_size = hs.shape[2]
    if real_len < max_seq_len:
        pad = torch.zeros(1, max_seq_len - real_len, hidden_size, dtype=hs.dtype)
        hs = torch.cat([hs, pad], dim=1)
    # Reshape to [1, 1, max_seq_len, hidden_size]
    hs = hs.unsqueeze(0)  # [1, 1, max_seq_len, hidden_size]
    return ttnn.from_torch(
        hs,
        device=mesh,
        dtype=ttnn.bfloat8_b,
        layout=ttnn.TILE_LAYOUT,
        mesh_mapper=ttnn.ShardTensor2dMesh(mesh, mesh_shape=mesh.shape, dims=(2, None)),
    )


def _gather_kv_cache(cache_tensor, mesh, real_len, isl_per_row):
    """Read K or V cache back to CPU as float32 [num_kv_heads, real_len, head_dim].

    TP-sharded: column j holds heads [j*local_kv_heads, (j+1)*local_kv_heads).
    SP-sharded: each row r independently filled positions 0..isl_per_row-1 with its
    shard of the sequence (fill_cache always writes starting at position 0 locally).
    Row r's shard corresponds to global positions [r*isl_per_row, (r+1)*isl_per_row).

    cache_tensor per device shape: [batch, local_kv_heads, max_seq_len, head_dim]
    """
    sp, tp = mesh.shape
    device_tensors = ttnn.get_device_tensors(cache_tensor)
    col_slices = []
    for col in range(tp):
        row_shards = []
        for row in range(sp):
            shard_len = min(isl_per_row, max(0, real_len - row * isl_per_row))
            if shard_len == 0:
                break
            t = ttnn.to_torch(device_tensors[row * tp + col]).float()
            row_shards.append(t[0, :, :shard_len, :])  # [local_kv_heads, shard_len, head_dim]
        col_slices.append(torch.cat(row_shards, dim=1))  # [local_kv_heads, real_len, head_dim]
    return torch.cat(col_slices, dim=0)  # [num_kv_heads, real_len, head_dim]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rows", type=int, default=4)
    ap.add_argument("--cols", type=int, default=8)
    prompt_group = ap.add_mutually_exclusive_group()
    prompt_group.add_argument("--prompt", type=str, default=None)
    prompt_group.add_argument("--prompt-file", type=str, default=None, help="read prompt text from a file")
    ap.add_argument(
        "--num-tokens",
        type=int,
        default=None,
        help="truncate the tokenized prompt to this many tokens (must match oracle generation)",
    )
    ap.add_argument(
        "--oracle-dir",
        type=str,
        required=True,
        help="directory containing ref_results.json produced by hf_reference_oracle.py --save-kv",
    )
    ap.add_argument(
        "--max-layers",
        type=int,
        default=None,
        help="compare only the first N layers (default: all layers present in oracle)",
    )
    ap.add_argument(
        "--pcc-threshold",
        type=float,
        default=PCC_THRESHOLD,
        help=f"minimum PCC for a layer to pass (default: {PCC_THRESHOLD})",
    )
    ap.add_argument(
        "--verbose-rows",
        action="store_true",
        help="for SP>1 meshes, also print per-SP-row K/V PCC to isolate which rows diverge",
    )
    ap.add_argument(
        "--use-oracle-input",
        action="store_true",
        help="before each evaluated layer, overwrite hidden_states with the oracle output of "
        "the previous layer.  Isolates per-layer K/V correctness from upstream compounding "
        "errors.  Requires oracle produced with --save-layers as well as --save-kv.",
    )
    ap.add_argument(
        "--oracle-input-every",
        type=int,
        default=None,
        help="inject oracle hidden_states before layers whose index is a multiple of N "
        "(and layer 1, so layer 0 output is always oracle-derived once).  Reveals "
        "per-layer degradation rate.  Requires oracle with --save-layers.",
    )
    ap.add_argument(
        "--row0-buckets",
        action="store_true",
        help="for SP>1 with --verbose-rows, also print row-0 PCC split into position "
        "buckets [0..15], [16..127], [128..end].  Isolates attention-sink-sensitive "
        "short-context tokens from the rest of the row.",
    )
    args = ap.parse_args()

    if args.prompt_file is not None:
        with open(args.prompt_file) as f:
            args.prompt = f.read()
    elif args.prompt is None:
        args.prompt = "What are the prime factors of 1?"

    oracle_dir = pathlib.Path(args.oracle_dir)
    results_path = oracle_dir / "ref_results.json"
    if not results_path.exists():
        print(f"[kv_cache] ERROR: {results_path} not found. Run hf_reference_oracle.py first.", flush=True)
        return 1

    with results_path.open() as f:
        records = json.load(f)

    record = next((r for r in records if r.get("prompt") == args.prompt), None)
    if record is None:
        print(f"[kv_cache] ERROR: no oracle record for prompt {args.prompt!r}", flush=True)
        return 1

    if "kv_files" not in record or not record["kv_files"]:
        print(
            "[kv_cache] ERROR: oracle record has no kv_files. " "Re-run hf_reference_oracle.py with --save-kv.",
            flush=True,
        )
        return 1

    available_layers = sorted(int(k) for k in record["kv_files"])
    if args.max_layers is not None:
        layers_to_test = [i for i in available_layers if i < args.max_layers]
    else:
        layers_to_test = available_layers

    if not layers_to_test:
        print("[kv_cache] ERROR: no layers to test (check --max-layers vs oracle layer count)", flush=True)
        return 1

    print(
        f"[kv_cache] testing KV cache for layers {layers_to_test[0]}..{layers_to_test[-1]} "
        f"({len(layers_to_test)} total) against oracle",
        flush=True,
    )

    from transformers import AutoConfig, AutoTokenizer

    from models.common.utility_functions import is_blackhole
    from models.demos.gpt_oss.config import MeshConfig, ModeConfig
    from models.demos.gpt_oss.tt.model_config import ModelArgs
    from models.demos.gpt_oss.utils.general_utils import get_default_num_links
    from models.demos.gpt_oss_d_p.tt.ccl import CCLManager
    from models.demos.gpt_oss_d_p.tt.model import Model

    shape = (args.rows, args.cols)
    sp = shape[0]

    if shape == (1, 1):
        fabric = None
        topology = ttnn.Topology.Linear
    elif is_blackhole():
        fabric = ttnn.FabricConfig.FABRIC_1D
        topology = ttnn.Topology.Linear
    else:
        fabric = ttnn.FabricConfig.FABRIC_1D_RING
        topology = ttnn.Topology.Ring

    print(f"[kv_cache] mesh={shape} SP={shape[0]} TP={shape[1]} fabric={fabric}", flush=True)

    if fabric is not None:
        ttnn.set_fabric_config(fabric)
    mesh = ttnn.open_mesh_device(ttnn.MeshShape(*shape))
    print(f"[kv_cache] mesh opened: {tuple(mesh.shape)} ndev={mesh.get_num_devices()}", flush=True)

    try:
        model_args = ModelArgs(mesh_device=mesh)
        hf_config = AutoConfig.from_pretrained(model_args.model_path, trust_remote_code=True)
        tok = AutoTokenizer.from_pretrained(model_args.model_path, trust_remote_code=True)

        ids = tok(args.prompt)["input_ids"]
        if args.num_tokens is not None:
            ids = ids[: args.num_tokens]
        real_len = len(ids)
        block = sp * 32
        max_seq_len = ((real_len + block - 1) // block) * block
        isl_per_row = max_seq_len // sp
        padded = ids + [tok.pad_token_id or 1] * (max_seq_len - real_len)
        print(f"[kv_cache] prompt_tokens={real_len} padded_seq={max_seq_len}", flush=True)

        state_dict = ModelArgs.load_state_dict(model_args.weights_path, dummy_weights=False)
        cache = model_args.weight_cache_path(ttnn.bfloat8_b)
        mesh_config = MeshConfig(
            shape, decode=ModeConfig(tp=shape[1], ep=shape[0]), prefill=ModeConfig(tp=shape[1], sp=shape[0], ep=1)
        )
        ccl = CCLManager(mesh, num_links=get_default_num_links(mesh), topology=topology)

        model = Model(
            mesh_device=mesh,
            hf_config=hf_config,
            state_dict=state_dict,
            ccl_manager=ccl,
            mesh_config=mesh_config,
            tensor_cache_path=str(cache),
            create_kv_cache=True,
            max_local_batch_size=1,
        )
        del state_dict
        gc.collect()
        print("[kv_cache] model built; weights on device", flush=True)

        emb = _sp_shard_embed(mesh, model, padded, sp, isl_per_row)

        seq_len = emb.shape[-2]  # = isl_per_row for SP>1

        if sp > 1:
            # Each SP row needs RoPE for its own position range [r*seq_len, (r+1)*seq_len).
            # Pull the full matrices to CPU, slice per row, then reshard across mesh rows.
            # Rope matrices are replicated — read from a single device to avoid the
            # mesh_composer requirement of ttnn.to_torch on a multi-device tensor.
            cos_dev0 = ttnn.get_device_tensors(model.rope_setup.cos_matrix_prefill)[0]
            sin_dev0 = ttnn.get_device_tensors(model.rope_setup.sin_matrix_prefill)[0]
            cos_cpu = ttnn.to_torch(cos_dev0)  # [1, 1, max_seq, rope_dim]
            sin_cpu = ttnn.to_torch(sin_dev0)
            rope_dtype = cos_dev0.dtype
            cos_rows = torch.cat(
                [cos_cpu[..., row * seq_len : (row + 1) * seq_len, :] for row in range(sp)], dim=0
            )  # [sp, 1, seq_len, rope_dim]
            sin_rows = torch.cat([sin_cpu[..., row * seq_len : (row + 1) * seq_len, :] for row in range(sp)], dim=0)
            rope_mats = [
                ttnn.from_torch(
                    cos_rows,
                    device=mesh,
                    layout=ttnn.TILE_LAYOUT,
                    dtype=rope_dtype,
                    mesh_mapper=ttnn.ShardTensor2dMesh(mesh, mesh.shape, dims=(0, None)),
                ),
                ttnn.from_torch(
                    sin_rows,
                    device=mesh,
                    layout=ttnn.TILE_LAYOUT,
                    dtype=rope_dtype,
                    mesh_mapper=ttnn.ShardTensor2dMesh(mesh, mesh.shape, dims=(0, None)),
                ),
            ]
        else:
            rope_mats = [
                model.rope_setup.cos_matrix_prefill[:, :, :seq_len, :],
                model.rope_setup.sin_matrix_prefill[:, :, :seq_len, :],
            ]

        hidden_states = emb
        results_table: list[tuple[int, float, float, bool]] = []
        any_fail = False

        max_layer_idx = max(layers_to_test)

        want_oracle_input = args.use_oracle_input or args.oracle_input_every is not None
        layer_files = record.get("layer_files", {}) if want_oracle_input else {}
        if want_oracle_input and not layer_files:
            print(
                "[kv_cache] ERROR: --use-oracle-input / --oracle-input-every requires oracle "
                "produced with --save-layers (no layer_files in ref_results.json)",
                flush=True,
            )
            return 1

        def _should_inject(layer_idx: int) -> bool:
            if layer_idx == 0 or str(layer_idx - 1) not in layer_files:
                return False
            if args.use_oracle_input:
                return True
            if args.oracle_input_every is not None and args.oracle_input_every > 0:
                return layer_idx % args.oracle_input_every == 0
            return False

        for i, decoder_layer in enumerate(model.layers):
            layer_kv = decoder_layer.self_attn.kv_cache  # [k_cache, v_cache] on device

            # Optionally replace running hidden_states with oracle input for this layer.
            # For layer 0 the input is the token embedding, which is already correct
            # (layer 0 K PCC≈0.9996 in the baseline run), so we leave it as-is.
            if _should_inject(i):
                oracle_hs = np.load(oracle_dir / layer_files[str(i - 1)])  # [1, real_len, hidden_size]
                hidden_states.deallocate(True)
                hidden_states = _oracle_hidden_states_to_tt(mesh, oracle_hs, sp, isl_per_row, max_seq_len)
                print(f"[kv_cache] layer {i:3d}: injected oracle input from layer {i - 1}", flush=True)

            hidden_states = decoder_layer(
                hidden_states,
                position_embeddings=rope_mats,
                position_idx=None,
                page_table=None,
                kv_cache=layer_kv,
                is_decode=False,
            )

            if i not in layers_to_test:
                if i > max_layer_idx:
                    break
                continue

            ttnn.synchronize_device(mesh)
            k_cache, v_cache = layer_kv

            tt_k = _gather_kv_cache(k_cache, mesh, real_len, isl_per_row)  # [num_kv_heads, real_len, head_dim]
            tt_k = permute_1d(tt_k)  # convert interleaved (Meta) → block (HF) format for comparison
            tt_v = _gather_kv_cache(v_cache, mesh, real_len, isl_per_row)

            oracle_k = torch.tensor(
                np.load(oracle_dir / record["kv_files"][str(i)]["k"]), dtype=torch.float32
            )  # [num_kv_heads, seq_len, head_dim]
            oracle_v = torch.tensor(np.load(oracle_dir / record["kv_files"][str(i)]["v"]), dtype=torch.float32)

            pcc_k = _pcc(tt_k, oracle_k)
            pcc_v = _pcc(tt_v, oracle_v)
            passed = pcc_k >= args.pcc_threshold and pcc_v >= args.pcc_threshold
            if not passed:
                any_fail = True
            results_table.append((i, pcc_k, pcc_v, passed))
            status = "PASS" if passed else "FAIL"
            print(f"[kv_cache] layer {i:3d}: K PCC={pcc_k:.4f}  V PCC={pcc_v:.4f}  {status}", flush=True)

            if args.verbose_rows and sp > 1:
                for row in range(sp):
                    rs = row * isl_per_row
                    re = min((row + 1) * isl_per_row, real_len)
                    row_pcc_k = _pcc(tt_k[:, rs:re, :], oracle_k[:, rs:re, :])
                    row_pcc_v = _pcc(tt_v[:, rs:re, :], oracle_v[:, rs:re, :])
                    print(
                        f"[kv_cache]          row {row} (pos {rs:5d}-{re-1:5d}): "
                        f"K={row_pcc_k:.4f}  V={row_pcc_v:.4f}",
                        flush=True,
                    )

                if args.row0_buckets:
                    # Split row 0 into short-context vs long-context ranges to test the
                    # attention-sink hypothesis: with a sliding window of ~128, only Q
                    # tokens at positions < window have fewer than window real K neighbors
                    # in the softmax denominator and are extra sensitive to sink noise.
                    row0_end = min(isl_per_row, real_len)
                    bucket_edges = [0, 16, 128, row0_end]
                    for lo, hi in zip(bucket_edges[:-1], bucket_edges[1:]):
                        if lo >= hi:
                            continue
                        b_k = _pcc(tt_k[:, lo:hi, :], oracle_k[:, lo:hi, :])
                        b_v = _pcc(tt_v[:, lo:hi, :], oracle_v[:, lo:hi, :])
                        print(
                            f"[kv_cache]          row 0 bucket pos {lo:5d}-{hi-1:5d}: " f"K={b_k:.4f}  V={b_v:.4f}",
                            flush=True,
                        )

            if i >= max_layer_idx:
                hidden_states.deallocate(True)
                break

        print("", flush=True)
        print(f"{'Layer':>6}  {'K PCC':>8}  {'V PCC':>8}  {'Status'}", flush=True)
        print("-" * 38, flush=True)
        for layer_idx, pcc_k, pcc_v, passed in results_table:
            print(f"{layer_idx:>6}  {pcc_k:>8.4f}  {pcc_v:>8.4f}  {'PASS' if passed else 'FAIL'}", flush=True)

        if any_fail:
            failed = [i for i, _, _, p in results_table if not p]
            print(
                f"\n[kv_cache] FAIL — {len(failed)} layer(s) below PCC threshold {args.pcc_threshold}: {failed}",
                flush=True,
            )
            return 1

        print(
            f"\n[kv_cache] PASS — all {len(results_table)} layer(s) above PCC threshold {args.pcc_threshold}",
            flush=True,
        )
        return 0

    finally:
        ttnn.close_mesh_device(mesh)


if __name__ == "__main__":
    sys.exit(main())
