graph_templates {
  key: "p150_quietbox"
  value {
    children {
      name: "node1"
      node_ref { node_descriptor: "P150_QB_AE_DEFAULT" }
    }
  }
}

root_instance {
  template_name: "p150_quietbox"
  child_mappings {
    key: "node1"
    value { host_id: 0 }
  }
}