// SPDX-FileCopyrightText: © 2025 Tenstorrent Inc.
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "../std_pch.hpp"

#include "../tt_metal/public_pch.hpp"
#include <tt-metalium/allocator_types.hpp>
#include <tt-metalium/allocator.hpp>
#include <tt-metalium/assert.hpp>
#include <tt-metalium/base_types.hpp>
#include <tt-metalium/bfloat4.hpp>
#include <tt-metalium/bfloat8.hpp>
#include <tt-metalium/bfloat16.hpp>
#include <tt-metalium/blockfloat_common.hpp>
#include <tt-metalium/buffer_distribution_spec.hpp>
#include <tt-metalium/buffer_page_mapping.hpp>
#include <tt-metalium/buffer_types.hpp>
#include <tt-metalium/buffer.hpp>
#include <tt-metalium/circular_buffer_config.hpp>
#include <tt-metalium/circular_buffer_constants.h>
#include <tt-metalium/circular_buffer.hpp>
#include <tt-metalium/cluster.hpp>
#include <tt-metalium/command_queue_interface.hpp>
#include <tt-metalium/command_queue.hpp>
#include <tt-metalium/constants.hpp>
#include <tt-metalium/control_plane.hpp>
#include <tt-metalium/core_coord.hpp>
#include <tt-metalium/core_descriptor.hpp>
#include <tt-metalium/data_format.hpp>
#include <tt-metalium/data_types.hpp>
#include <tt-metalium/device_pool.hpp>
#include <tt-metalium/device.hpp>
#include <tt-metalium/dispatch_core_common.hpp>
#include <tt-metalium/distributed_context.hpp>
#include <tt-metalium/distributed_host_buffer.hpp>
#include <tt-metalium/distributed.hpp>
#include <tt-metalium/edm_fabric_counters.hpp>
#include <tt-metalium/event.hpp>
#include <tt-metalium/fabric_edm_types.hpp>
#include <tt-metalium/fabric_types.hpp>
#include <tt-metalium/fabric.hpp>
#include <tt-metalium/global_circular_buffer.hpp>
#include <tt-metalium/global_semaphore.hpp>
#include <tt-metalium/graph_tracking.hpp>
#include <tt-metalium/hal_types.hpp>
#include <tt-metalium/hal.hpp>
#include <tt-metalium/hlk_desc.hpp>
#include <tt-metalium/host_api.hpp>
#include <tt-metalium/host_buffer.hpp>
#include <tt-metalium/kernel_types.hpp>
#include <tt-metalium/kernel.hpp>
#include <tt-metalium/lightmetal_binary.hpp>
#include <tt-metalium/lightmetal_capture_utils.hpp>
#include <tt-metalium/lightmetal_replay.hpp>
#include <tt-metalium/math.hpp>
#include <tt-metalium/maybe_remote.hpp>
#include <tt-metalium/memory_pin.hpp>
#include <tt-metalium/memory_reporter.hpp>
#include <tt-metalium/mesh_buffer.hpp>
#include <tt-metalium/mesh_command_queue.hpp>
#include <tt-metalium/mesh_config.hpp>
#include <tt-metalium/mesh_coord.hpp>
#include <tt-metalium/mesh_device_view.hpp>
#include <tt-metalium/mesh_device.hpp>
#include <tt-metalium/mesh_event.hpp>
#include <tt-metalium/mesh_graph_descriptor.hpp>
#include <tt-metalium/mesh_graph.hpp>
#include <tt-metalium/mesh_socket.hpp>
#include <tt-metalium/mesh_trace_id.hpp>
#include <tt-metalium/mesh_workload.hpp>
#include <tt-metalium/metal_soc_descriptor.h>
#include <tt-metalium/multi_mesh_types.hpp>
#include <tt-metalium/persistent_kernel_cache.hpp>
#include <tt-metalium/profiler_optional_metadata.hpp>
#include <tt-metalium/profiler_types.hpp>
#include <tt-metalium/program_cache.hpp>
#include <tt-metalium/program_descriptors.hpp>
#include <tt-metalium/program.hpp>
#include <tt-metalium/routing_table_generator.hpp>
#include <tt-metalium/runtime_args_data.hpp>
#include <tt-metalium/semaphore.hpp>
#include <tt-metalium/shape_base.hpp>
#include <tt-metalium/shape.hpp>
#include <tt-metalium/shape2d.hpp>
#include <tt-metalium/sub_device_types.hpp>
#include <tt-metalium/sub_device.hpp>
#include <tt-metalium/system_mesh.hpp>
#include <tt-metalium/tensor_accessor_args.hpp>
#include <tt-metalium/tile.hpp>
#include <tt-metalium/tilize_utils.hpp>
#include <tt-metalium/tt_align.hpp>
#include <tt-metalium/tt_backend_api_types.hpp>
#include <tt-metalium/tt_metal_profiler.hpp>
#include <tt-metalium/tt_metal.hpp>
#include <tt-metalium/util.hpp>
#include <tt-metalium/utils.hpp>
#include <tt-metalium/vector_aligned.hpp>
#include <tt-metalium/work_split.hpp>

#include <flatbuffers/flatbuffers.h>

#include "../ttnn/api/ttnn/tensor/xtensor/xtensor_all_includes.hpp"

#include "../ttnn/api/tools/profiler/op_profiler.hpp"
#include "../ttnn/api/ttnn/common/constants.hpp"
#include "../ttnn/api/ttnn/common/queue_id.hpp"
#include "../ttnn/api/ttnn/distributed/api.hpp"
#include "../ttnn/api/ttnn/distributed/bidirectional_fabric_socket.hpp"
#include "../ttnn/api/ttnn/distributed/create_socket.hpp"
#include "../ttnn/api/ttnn/distributed/distributed_configs.hpp"
#include "../ttnn/api/ttnn/distributed/distributed_pybind.hpp"
#include "../ttnn/api/ttnn/distributed/distributed_tensor.hpp"
#include "../ttnn/api/ttnn/distributed/fabric_socket.hpp"
#include "../ttnn/api/ttnn/distributed/host_ccl.hpp"
#include "../ttnn/api/ttnn/distributed/isocket.hpp"
#include "../ttnn/api/ttnn/distributed/mpi_socket.hpp"
#include "../ttnn/api/ttnn/distributed/tensor_topology.hpp"
#include "../ttnn/api/ttnn/distributed/types.hpp"
#include "../ttnn/api/ttnn/graph/graph_argument_serializer.hpp"
#include "../ttnn/api/ttnn/graph/graph_consts.hpp"
#include "../ttnn/api/ttnn/graph/graph_operation_queries.hpp"
#include "../ttnn/api/ttnn/graph/graph_processor.hpp"
#include "../ttnn/api/ttnn/graph/graph_pybind.hpp"
#include "../ttnn/api/ttnn/graph/graph_query_op_constraints.hpp"
#include "../ttnn/api/ttnn/graph/graph_query_op_runtime.hpp"
#include "../ttnn/api/ttnn/graph/graph_trace_utils.hpp"
#include "../ttnn/api/ttnn/tensor/host_buffer/functions.hpp"
#include "../ttnn/api/ttnn/tensor/layout/alignment.hpp"
#include "../ttnn/api/ttnn/tensor/layout/layout.hpp"
#include "../ttnn/api/ttnn/tensor/layout/page_config.hpp"
#include "../ttnn/api/ttnn/tensor/layout/tensor_layout.hpp"
#include "../ttnn/api/ttnn/tensor/memory_config/memory_config.hpp"
#include "../ttnn/api/ttnn/tensor/shape/shape.hpp"
#include "../ttnn/api/ttnn/tensor/xtensor/conversion_utils.hpp"
#include "../ttnn/api/ttnn/tensor/xtensor/partition.hpp"
#include "../ttnn/api/ttnn/tensor/xtensor/xtensor_all_includes.hpp"
#include "../ttnn/api/ttnn/tensor/serialization.hpp"
#include "../ttnn/api/ttnn/tensor/storage.hpp"
#include "../ttnn/api/ttnn/tensor/tensor_attributes.hpp"
#include "../ttnn/api/ttnn/tensor/tensor_impl_wrapper.hpp"
#include "../ttnn/api/ttnn/tensor/tensor_impl.hpp"
#include "../ttnn/api/ttnn/tensor/tensor_spec.hpp"
#include "../ttnn/api/ttnn/tensor/tensor_utils.hpp"
#include "../ttnn/api/ttnn/tensor/tensor.hpp"
#include "../ttnn/api/ttnn/tensor/types.hpp"
#include "../ttnn/api/ttnn/async_runtime.hpp"
#include "../ttnn/api/ttnn/cluster.hpp"
#include "../ttnn/api/ttnn/config.hpp"
#include "../ttnn/api/ttnn/core.hpp"
#include "../ttnn/api/ttnn/decorators.hpp"
#include "../ttnn/api/ttnn/device_operation.hpp"
#include "../ttnn/api/ttnn/device.hpp"
#include "../ttnn/api/ttnn/events.hpp"
#include "../ttnn/api/ttnn/global_circular_buffer.hpp"
#include "../ttnn/api/ttnn/global_semaphore.hpp"
#include "../ttnn/api/ttnn/mesh_device_operation_adapter.hpp"
#include "../ttnn/api/ttnn/mesh_device_operation_utils.hpp"
#include "../ttnn/api/ttnn/old_infra_device_operation.hpp"
#include "../ttnn/api/ttnn/operation_concepts.hpp"
#include "../ttnn/api/ttnn/operation.hpp"
#include "../ttnn/api/ttnn/reports.hpp"
#include "../ttnn/api/ttnn/run_operation.hpp"
#include "../ttnn/api/ttnn/types.hpp"
