#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0

import argparse
import csv
import os
from datetime import datetime, timezone

from datasets import load_dataset
from transformers import AutoTokenizer
from ttml.common.config import DeviceConfig, TrainingConfig, get_model_config, load_config
from ttml.common.utils import get_tt_metal_runtime_root
from ttml.trainers import GRPOTrainer, TrainerCallback, get_grpo_config
from utils.llama_completer import LlamaCompletionCtx
from utils.llama_completer import LlamaGRPOCompleter

try:
    import wandb

    _WANDB_AVAILABLE = True
except ImportError:
    wandb = None
    _WANDB_AVAILABLE = False


class GRPOMonitor(TrainerCallback):
    def __init__(self, output_dir, wandb_enabled=False):
        self.file_path = os.path.join(output_dir, "grpo_metrics.csv")
        self.wandb_enabled = wandb_enabled and _WANDB_AVAILABLE
        os.makedirs(output_dir, exist_ok=True)
        with open(self.file_path, mode="w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["step", "reward", "avg_length", "step_time_s", "generation_time_s"])

    def on_step_end(self, trainer, step, **kwargs):
        reward = kwargs["reward_mean"]
        length = kwargs["mean_completion_len"]
        min_length = kwargs["min_completion_len"]
        max_length = kwargs["max_completion_len"]
        step_time_s = kwargs.get("step_time_s", float("nan"))
        generation_time_s = kwargs.get("generation_time_s", float("nan"))
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
        print(
            f"[{timestamp}] Step {step} | Reward: {reward:.4f} "
            f"| Len: {length:.2f} (min {min_length}, max {max_length}) tokens "
            f"| Step: {step_time_s:.2f}s | Gen: {generation_time_s:.2f}s"
        )
        with open(self.file_path, mode="a", newline="") as f:
            writer = csv.writer(f)
            writer.writerow([step, reward, length, step_time_s, generation_time_s])

        if self.wandb_enabled:
            wandb.log(
                {
                    "grpo/reward": reward,
                    "grpo/avg_length": length,
                    "grpo/min_length": min_length,
                    "grpo/max_length": max_length,
                    "grpo/step_time_s": step_time_s,
                    "grpo/generation_time_s": generation_time_s,
                },
                step=step,
            )

    def on_train_end(self, trainer):
        print("Training complete.")
        if self.wandb_enabled:
            wandb.finish()


def boolq_reward(completions, answer, **kwargs):
    rewards = []
    for text, ground_truth in zip(completions, answer):
        clean = text.strip().lower()
        accuracy = 2.0 if clean.startswith(ground_truth.lower()) else -1.0
        brevity = -0.1 * (len(text) / 20) ** 2
        rewards.append(accuracy + brevity)
    return rewards


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="GRPO BoolQ training example")
    parser.add_argument(
        "--wandb",
        action="store_true",
        help="Enable Weights & Biases logging of GRPO metrics",
    )
    parser.add_argument(
        "--wandb_project",
        type=str,
        default="grpo-boolq",
        help="W&B project name",
    )
    parser.add_argument(
        "--wandb_run_name",
        type=str,
        default=None,
        help="W&B run name (default: auto-generated by wandb)",
    )
    parser.add_argument(
        "--wandb_entity",
        type=str,
        default=None,
        help="W&B entity / team",
    )
    parser.add_argument(
        "--wandb_mode",
        type=str,
        default=None,
        choices=["online", "offline", "disabled"],
        help="W&B mode. If unset, uses WANDB_MODE env var or wandb default.",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="llama",
        choices=["llama", "qwen"],
        help="Model family to train: 'llama' (single device) or 'qwen' (Qwen3, tensor-parallel).",
    )
    parser.add_argument(
        "--model_id",
        type=str,
        default=None,
        help="HuggingFace model id. Defaults per --model "
        "(llama: meta-llama/Llama-3.2-1B-Instruct, qwen: Qwen/Qwen3-32B).",
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help="Path to the GRPO training YAML. Defaults per --model.",
    )
    args = parser.parse_args()

    _DEFAULT_MODEL_ID = {
        "llama": "meta-llama/Llama-3.2-1B-Instruct",
        "qwen": "Qwen/Qwen3-32B",
    }
    _DEFAULT_CONFIG = {
        "llama": "tt-train/configs/training_configs/grpo_boolq_llama_1dev.yaml",
        "qwen": "tt-train/configs/training_configs/grpo_boolq_qwen_32b.yaml",
    }
    model_id = args.model_id or _DEFAULT_MODEL_ID[args.model]
    tokenizer = AutoTokenizer.from_pretrained(model_id)

    system_prompt = "You are a wordy professor. Explain in 3 long sentences before saying Yes or No."

    def format_boolq(example):
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Question: {example['question']}? Context: {example['passage']}"},
        ]
        return {
            "prompt": tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True),
            "answer": "yes" if example["answer"] else "no",
        }

    dataset = load_dataset("google/boolq", split="train").shuffle(seed=42).map(format_boolq)

    tt_metal_root = get_tt_metal_runtime_root()
    config_path = args.config or os.path.join(tt_metal_root, _DEFAULT_CONFIG[args.model])
    raw = load_config(config_path)
    training_config = TrainingConfig(raw)
    device_config = DeviceConfig(raw)
    assert training_config.model_config, "training_config.model_config must be set"
    transformer_config = get_model_config(training_config.model_config)
    optimizer_dict = raw["training_config"]["optimizer"]

    output_dir = os.path.join(
        tt_metal_root,
        "generated/tt-train/grpo_run",
        datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S"),
    )
    grpo_config = get_grpo_config(raw, output_dir=output_dir)

    wandb_enabled = False
    if args.wandb:
        if not _WANDB_AVAILABLE:
            print("Warning: --wandb specified but the 'wandb' package is not installed; skipping W&B logging.")
        else:
            wandb.init(
                project=args.wandb_project,
                name=args.wandb_run_name,
                entity=args.wandb_entity,
                mode=args.wandb_mode,
                config={
                    "model_id": model_id,
                    "max_completion_length": grpo_config.max_completion_length,
                    "num_generations": grpo_config.num_generations,
                    "temperature": grpo_config.temperature,
                    **optimizer_dict,
                },
            )
            wandb_enabled = True
            print(f"   - W&B logging enabled (project={args.wandb_project}, run={args.wandb_run_name or '<auto>'})")

    if args.model == "qwen":
        # Imported lazily: utils.qwen_completer pulls in the vendored distributed
        # Qwen3 stack, which is unnecessary for the Llama path.
        from utils.qwen_completer import QwenCompletionCtx, QwenGRPOCompleter

        completer = QwenGRPOCompleter(
            ctx=QwenCompletionCtx(
                max_tokens_to_complete=grpo_config.max_completion_length,
                temperature=grpo_config.temperature,
                completions_per_prompt=grpo_config.num_generations,
            ),
            device_config=device_config,
            model_source=model_id,
            max_seq_len=transformer_config.max_sequence_length,
        )
    else:
        completer = LlamaGRPOCompleter(
            ctx=LlamaCompletionCtx(
                max_tokens_to_complete=grpo_config.max_completion_length,
                temperature=grpo_config.temperature,
                completions_per_prompt=grpo_config.num_generations,
            ),
            transformer_config=transformer_config,
            device_config=device_config,
            model_source=model_id,
        )

    grpo_trainer = GRPOTrainer(
        completer=completer,
        dataset=dataset,
        config=grpo_config,
        reward_func=boolq_reward,
        optimizer_dict=optimizer_dict,
        callbacks=[GRPOMonitor(output_dir, wandb_enabled=wandb_enabled)],
        model_source=model_id,
    )
    grpo_trainer.train()
