"""Streaming design, item 2 of the user's two pre-code follow-ups: before any
bucket-padded flow-encoder path is trusted, verify whether padding a chunk's input up to
a bucket size (plus masking) reproduces the true unpadded computation at the boundary --
the same class of silent-corruption risk as the STFT issue (tests that don't probe the
right shape pass while the real computation is wrong).

`TtUpsampleConformerEncoder` currently only supports `streaming=False` (all-valid masks,
no padding at all -- see tt/flow/encoder.py's module docstring). This script does NOT
modify that file or add bucketing/chunking production code; it drives the encoder's
existing real sub-modules (embed, pre_lookahead_layer, encoders, up_layer, up_embed,
up_encoders, after_norm -- all already public instance attributes) directly, from an
external script, to build a MINIMAL padded-forward variant for verification only.

Ground truth is NOT a T-length truncated call: `PreLookaheadLayer` unconditionally
zero-pads its OWN tail by `pre_lookahead_len` (`finalize=True`, `context` always empty --
the only mode this port has), so a truncated run's last few positions already reflect
zero-lookahead-at-the-true-end-of-audio semantics, not a mid-utterance chunk boundary
with real continuation available. The correct reference for "what should a mid-stream
chunk boundary produce" is the full, unmasked, real-attention computation over the WHOLE
eventual sequence (as if run once, non-streaming, on the complete utterance) -- what a
bucketed/masked chunk's output at the causal boundary should reproduce.

Two padded variants, both compared against that full-sequence ground truth, restricted to
the first `T_TRUE*2` output positions (the span a `T_TRUE`-token chunk is responsible for):

1. NAIVE ZERO-PAD: positions [T, B) are literally zero embeddings, masked invalid for
   attention. EXPECTED to diverge from ground truth at the last few valid positions,
   because `PreLookaheadLayer.conv1` is a genuine 3-token LOOK-AHEAD (right-padded by
   `pre_lookahead_len`, kernel_size=pre_lookahead_len+1) -- it reads INTO the padding
   region for any position within `pre_lookahead_len` of the true boundary, and attention
   masking cannot fix that (masking hides positions from ATTENTION; it does nothing for a
   conv kernel's local receptive field, which reads raw input directly, not through the
   mask). If this variant did NOT diverge, that would mean the mask isn't actually being
   applied where it needs to be -- also worth knowing.

2. LOOKAHEAD-AWARE PAD: same as above, EXCEPT positions [T, T+pre_lookahead_len) get the
   REAL next `pre_lookahead_len` tokens (available in real streaming, since a chunk's
   pre-lookahead is satisfied by the next few tokens of the growing prefix, already
   generated by the time the chunk is processed -- this is exactly why upstream's real
   streaming design has a lookahead window as part of the chunking scheme, not an
   afterthought). EXPECTED to recover correctness at the boundary, confirming a bucketed
   implementation is safe AS LONG AS it supplies real lookahead tokens, not just padding
   the raw bucket gap with zeros everywhere.

Real checkpoint, real encoder weights, random (but valid-range) token ids -- token
identity doesn't matter for this numerical check, only that the SAME tokens are used in
the padded and unpadded runs at every shared position.

Run: PYTHONPATH=/home/user/tt-metal/ttnn:/home/user/tt-metal/tools:/home/user/tt-metal
     timeout -s KILL 600 /opt/venv/bin/python bucket_padding_boundary_check.py
"""
import sys

import torch
import ttnn

sys.path.insert(0, "/home/user/tt-metal")

from models.demos.audio.cosyvoice2.tt.checkpoint import load_checkpoint_file, sub_state_dict
from models.demos.audio.cosyvoice2.tt.flow.encoder import (
    PRE_LOOKAHEAD_LEN,
    D_MODEL,
    TtUpsampleConformerEncoder,
    UpsampleConformerEncoderRef,
)
from models.demos.audio.cosyvoice2.tt.llm.qwen2lm import TtSmallEmbedding
from models.common.utility_functions import comp_pcc

VOCAB_SIZE = 6561
T_TRUE = 200  # true prefix length at some mid-stream chunk boundary
B_BUCKET = 256  # bucket size this length would round up to
BATCH = 1

print("=== loading real flow checkpoint, building real encoder + input_embedding ===")
flow_sd = load_checkpoint_file("flow.pt")
encoder_sd = sub_state_dict(flow_sd, "encoder.")
encoder_ref = UpsampleConformerEncoderRef.from_checkpoint(encoder_sd)
encoder_ref.eval()
input_embedding_weight = flow_sd["input_embedding.weight"]  # [VOCAB_SIZE, D_MODEL]

print("=== opening device ===")
device = ttnn.CreateDevice(0, l1_small_size=65536)

try:
    tt_encoder = TtUpsampleConformerEncoder(device, encoder_ref, dtype=ttnn.bfloat16, use_trace=False)
    tt_embedding = TtSmallEmbedding(device, input_embedding_weight, dtype=ttnn.bfloat16)

    torch.manual_seed(0)
    tokens = torch.randint(0, VOCAB_SIZE, (1, B_BUCKET), dtype=torch.int64)

    def embed(token_slice: torch.Tensor):
        ids_dev = ttnn.from_torch(
            token_slice.reshape(1, 1, 1, -1).to(torch.int32), dtype=ttnn.uint32, layout=ttnn.ROW_MAJOR_LAYOUT, device=device
        )
        return tt_embedding(ids_dev)

    def run_encoder_true(length: int):
        """The real, unmodified, production call path (real full attention, no
        masking) -- used as ground truth for what the encoder computes when given
        real content for the whole span, not truncated/zero-lookahead."""
        xs = embed(tokens[:, :length])
        out = tt_encoder(xs, length, BATCH)
        return ttnn.to_torch(out).float().reshape(1, length * 2, D_MODEL)

    def run_encoder_padded(xs_dev, true_len: int, bucket_len: int):
        """Manually replicates TtUpsampleConformerEncoder._call_eager's body (no
        production code touched -- this script only reads the encoder's own public
        sub-module attributes), with a REAL mask instead of the always-zero one
        `_call_eager` builds today, since this encoder has no padding support yet."""
        NEG = -30000.0  # large-negative, safe in bf16 (bf16 max ~3.4e38, but softmax with
        # -30000 after /sqrt(d_k) scaling and +matrix_ac is already effectively -inf for
        # softmax purposes at this precision -- matches the magnitude convention
        # `TtRelPositionMultiHeadedAttention.__call__`'s additive `attn_bias` expects).
        bias1 = torch.zeros(BATCH, 1, 1, bucket_len)
        bias1[:, :, :, true_len:] = NEG
        bias1_dev = ttnn.from_torch(bias1, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)

        h = tt_encoder.embed(xs_dev)
        pos_emb = tt_encoder._pos_emb(bucket_len)
        h = tt_encoder.pre_lookahead_layer(h, bucket_len, BATCH)
        for layer in tt_encoder.encoders:
            h = layer(h, pos_emb, bias1_dev)

        h = tt_encoder.up_layer(h, bucket_len, BATCH)
        bucket_len2 = bucket_len * tt_encoder.up_layer.stride
        true_len2 = true_len * tt_encoder.up_layer.stride
        bias2 = torch.zeros(BATCH, 1, 1, bucket_len2)
        bias2[:, :, :, true_len2:] = NEG
        bias2_dev = ttnn.from_torch(bias2, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)
        h = tt_encoder.up_embed(h)
        pos_emb2 = tt_encoder._pos_emb(bucket_len2)
        for layer in tt_encoder.up_encoders:
            h = layer(h, pos_emb2, bias2_dev)

        out = ttnn.layer_norm(h, weight=tt_encoder.after_norm_w, bias=tt_encoder.after_norm_b, epsilon=1e-5)
        return ttnn.to_torch(out).float().reshape(1, bucket_len2, D_MODEL)

    print(
        f"\n=== ground truth: real, FULL, unmasked encoder call on all B={B_BUCKET} real tokens "
        f"(what the model computes when it genuinely has the whole span, not a truncated/"
        f"zero-lookahead prefix -- see module docstring for why a T={T_TRUE}-truncated run "
        f"would NOT be a valid streaming-boundary reference) ==="
    )
    full_out = run_encoder_true(B_BUCKET)  # [1, B_BUCKET*2, D_MODEL], real full attention
    T2 = T_TRUE * 2
    ref_out = full_out[:, :T2, :]  # the span a T_TRUE-token chunk's output should reproduce

    print(f"\n=== variant 1: NAIVE zero-pad to B={B_BUCKET} (expect boundary divergence) ===")
    xs_naive = embed(tokens[:, :T_TRUE])
    xs_naive_padded = ttnn.concat(
        [xs_naive, ttnn.from_torch(torch.zeros(1, B_BUCKET - T_TRUE, D_MODEL), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)],
        dim=1,
    )
    naive_out = run_encoder_padded(xs_naive_padded, T_TRUE, B_BUCKET)[:, :T2, :]

    print(f"=== variant 2: LOOKAHEAD-AWARE pad ({PRE_LOOKAHEAD_LEN} real tokens, then zeros) (expect recovery) ===")
    xs_la = embed(tokens[:, : T_TRUE + PRE_LOOKAHEAD_LEN])  # true tokens + the real next 3
    xs_la_padded = ttnn.concat(
        [
            xs_la,
            ttnn.from_torch(
                torch.zeros(1, B_BUCKET - T_TRUE - PRE_LOOKAHEAD_LEN, D_MODEL),
                dtype=ttnn.bfloat16,
                layout=ttnn.TILE_LAYOUT,
                device=device,
            ),
        ],
        dim=1,
    )
    la_out = run_encoder_padded(xs_la_padded, T_TRUE, B_BUCKET)[:, :T2, :]

    def report(name: str, out: torch.Tensor, n_boundary: int = 6):
        p_all, r_all = comp_pcc(ref_out, out, 0.99)
        boundary_ref = ref_out[:, T2 - n_boundary : T2, :]
        boundary_out = out[:, T2 - n_boundary : T2, :]
        p_b, r_b = comp_pcc(boundary_ref, boundary_out, 0.99)
        max_diff_all = float((ref_out - out).abs().max())
        max_diff_boundary = float((boundary_ref - boundary_out).abs().max())
        max_diff_interior = float((ref_out[:, : T2 - n_boundary, :] - out[:, : T2 - n_boundary, :]).abs().max())
        print(
            f"{name}: overall PCC={r_all:.6f} max|diff|={max_diff_all:.4f}  |  "
            f"last {n_boundary} positions PCC={r_b:.6f} max|diff|={max_diff_boundary:.4f}  |  "
            f"interior (excl. last {n_boundary}) max|diff|={max_diff_interior:.4f}"
        )
        return r_all, r_b, max_diff_boundary, max_diff_interior

    print("\n=== RESULTS ===")
    r_naive = report("variant 1 (naive zero-pad)      ", naive_out)
    r_la = report("variant 2 (lookahead-aware pad)  ", la_out)

    print("\n=== VERDICT ===")
    if r_naive[2] > 0.05 and r_la[2] < r_naive[2] / 5:
        print(
            "CONFIRMED: naive zero-padding corrupts the boundary (as expected from "
            "PreLookaheadLayer.conv1's genuine 3-token lookahead reading into the pad "
            "region), and supplying the real next 3 tokens instead of zeros recovers "
            "correctness. A bucketed streaming implementation MUST supply real lookahead "
            "tokens at the true chunk boundary, not just pad-and-mask -- padding the "
            "REST of the bucket gap (beyond the lookahead window) with zeros is fine, "
            "confirmed by variant 2's interior/boundary match."
        )
    elif r_naive[2] <= 0.05:
        print(
            "UNEXPECTED: naive zero-padding did NOT measurably corrupt the boundary. "
            "Either the masking is stronger than analyzed here, or this check has a bug "
            "-- needs a closer look before trusting either conclusion."
        )
    else:
        print(
            "PARTIAL: naive zero-padding corrupts the boundary as expected, but the "
            "lookahead-aware variant did not clearly recover correctness -- needs a "
            "closer look at the encoder's masking/lookahead interaction before trusting "
            "a bucketed implementation."
        )
finally:
    ttnn.CloseDevice(device)
