groupings {
  name: "2x2_Mesh"
  preset_type: MESH
  instances: [
    { id: 0 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 1 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 2 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 3 location { asic_location: ASIC_LOCATION_UNSPECIFIED } }
  ]
  row_major_mesh {
    dims: [2, 2]
  }
}

groupings {
  name: "2x4_Mesh"
  preset_type: MESH
  instances: [
    { id: 0 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 1 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 2 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 3 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 4 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 5 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 6 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 7 location { asic_location: ASIC_LOCATION_UNSPECIFIED } }
  ]
  row_major_mesh {
    dims: [2, 4]
  }
}

groupings {
  name: "4x4_Mesh"
  preset_type: MESH
  instances: [
    { id: 0 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 1 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 2 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 3 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 4 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 5 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 6 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 7 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 8 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 9 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 10 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 11 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 12 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 13 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 14 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 15 location { asic_location: ASIC_LOCATION_UNSPECIFIED } }
  ]
  row_major_mesh {
    dims: [4, 4]
  }
}
