groupings {
  name: "1x1_Mesh"
  preset_type: MESH
  instances: [
    { id: 0 location { asic_location: ASIC_LOCATION_UNSPECIFIED } }
  ]
  row_major_mesh {
    dims: [1, 1]
  }
}

groupings {
  name: "1x2_Mesh"
  preset_type: MESH
  instances: [
    { id: 0 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 1 location { asic_location: ASIC_LOCATION_UNSPECIFIED } }
  ]
  row_major_mesh {
    dims: [1, 2]
  }
}

groupings {
  name: "2x2_Mesh"
  preset_type: MESH
  instances: [
    { id: 0 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 1 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 2 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 3 location { asic_location: ASIC_LOCATION_UNSPECIFIED } }
  ]
  row_major_mesh {
    dims: [2, 2]
  }
}

groupings {
  name: "2x4_Mesh"
  preset_type: MESH
  instances: [
    { id: 0 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 1 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 2 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 3 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 4 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 5 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 6 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 7 location { asic_location: ASIC_LOCATION_UNSPECIFIED } }
  ]
  row_major_mesh {
    dims: [2, 4]
  }
}

groupings {
  name: "4x4_Mesh"
  preset_type: MESH
  instances: [
    { id: 0 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 1 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 2 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 3 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 4 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 5 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 6 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 7 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 8 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 9 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 10 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 11 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 12 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 13 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 14 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 15 location { asic_location: ASIC_LOCATION_UNSPECIFIED } }
  ]
  row_major_mesh {
    dims: [4, 4]
  }
}

groupings {
  name: "4x8_Mesh"
  preset_type: MESH
  instances: [
    { id: 0 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 1 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 2 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 3 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 4 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 5 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 6 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 7 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 8 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 9 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 10 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 11 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 12 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 13 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 14 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 15 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 16 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 17 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 18 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 19 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 20 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 21 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 22 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 23 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 24 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 25 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 26 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 27 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 28 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 29 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 30 location { asic_location: ASIC_LOCATION_UNSPECIFIED } },
    { id: 31 location { asic_location: ASIC_LOCATION_UNSPECIFIED } }
  ]
  row_major_mesh {
    dims: [4, 8]
  }
}
