# Auto-generated by tdd_orchestrator.py — Stage: square_reduce_mean
# DO NOT EDIT — regenerate with: tdd_orchestrator.py add-stage ...
"""
TDD Stage: square_reduce_mean
Square input + reduce SUM with 1/W scaler (= mean). Output is reduced shape [..,H,32] with valid data in column 0.
"""

import pytest
import torch
import ttnn


from .rms_norm import rms_norm


def pytorch_reference(input_tensor):
    """PyTorch reference for this stage."""
    torch.mean(input_tensor**2, dim=-1, keepdim=True)


DTYPE_MAP = {
    "bfloat16": (torch.bfloat16, ttnn.bfloat16),
    "float32": (torch.float32, ttnn.float32),
}

LAYOUT_MAP = {
    "TILE_LAYOUT": ttnn.TILE_LAYOUT,
    "ROW_MAJOR_LAYOUT": ttnn.ROW_MAJOR_LAYOUT,
}


@pytest.mark.parametrize(
    "shape",
    [
        pytest.param((1, 1, 32, 32), id="1x1x32x32"),
        pytest.param((1, 1, 64, 128), id="1x1x64x128"),
        pytest.param((1, 1, 32, 256), id="1x1x32x256"),
        pytest.param((4, 2, 64, 64), id="4x2x64x64"),
    ],
)
@pytest.mark.parametrize(
    "layout_name", [Markup('"TILE_LAYOUT"'), Markup('"ROW_MAJOR_LAYOUT"')], ids=["tile_layout", "row_major_layout"]
)
@pytest.mark.parametrize("dtype_name", bfloat16)
def test_square_reduce_mean(device, shape, layout_name, dtype_name):
    """Verify Square input + reduce SUM with 1/W scaler (= mean). Output is reduced shape [..,H,32] with valid data in column 0.."""
    torch_dtype, ttnn_dtype = DTYPE_MAP[dtype_name]
    layout = LAYOUT_MAP[layout_name]
    torch.manual_seed(42)
    torch_input = torch.randn(shape, dtype=torch_dtype)

    expected = pytorch_reference(torch_input)

    ttnn_input = ttnn.from_torch(
        torch_input,
        dtype=ttnn_dtype,
        layout=layout,
        device=device,
        memory_config=ttnn.DRAM_MEMORY_CONFIG,
    )

    ttnn_output = rms_norm(ttnn_input)

    # Shape check
    expected_shape = list(shape[:-1]) + [32]
    assert list(ttnn_output.shape) == expected_shape, f"Shape: {list(ttnn_output.shape)} vs expected {expected_shape}"

    # Numerical comparison
    torch_output = ttnn.to_torch(ttnn_output)
    torch_output = torch_output[:, :, :, 0:1]
    expected = expected[:, :, :, 0:1]
    assert torch.allclose(
        torch_output.float(),
        expected.float(),
        rtol=0.02,
        atol=0.1,
    ), f"Max diff: {(torch_output.float() - expected.float()).abs().max()}"
