# Every variable in subdir must be prefixed with subdir (emulating a namespace)

TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS_HOME = tests/tt_metal/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue

TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE = ${TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS_HOME}/tests_main.cpp
TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE += $(wildcard ${TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS_HOME}/*/*.cpp)
TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE += $(wildcard ${TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS_HOME}/*/*/*.cpp)

TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_OBJ_HOME = tt_metal/tests/unit_tests_fast_dispatch_single_chip_multi_queue/
TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS = $(patsubst $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS_HOME)%, $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_OBJ_HOME)%, $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE))

TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_INCLUDES = $(TEST_INCLUDES) $(TT_METAL_INCLUDES) -I$(TT_METAL_HOME)/$(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS_HOME)/common
TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_LDFLAGS = $(TT_METAL_UNIT_TESTS_LDFLAGS)

TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_OBJS = $(addprefix $(OBJDIR)/, $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS:.cpp=.o))
TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_DEPS = $(addprefix $(OBJDIR)/, $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS:.cpp=.d))

-include $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_DEPS)

# Each module has a top level target as the entrypoint which must match the subdir name
tests/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue: $(TESTDIR)/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue

.PRECIOUS: $(TESTDIR)/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue
$(TESTDIR)/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue: $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_OBJS) $(TT_METAL_UNIT_TESTS_COMMON_OBJS) $(TT_METAL_LIB) $(TT_DNN_LIB)
	@mkdir -p $(@D)
	$(CXX) $(CFLAGS) $(CXXFLAGS) $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_INCLUDES) -o $@ $^ $(LDFLAGS) $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_LDFLAGS)

.PRECIOUS: $(OBJDIR)/$(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_OBJ_HOME)/%.o
$(OBJDIR)/$(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_OBJ_HOME)/%.o: $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_SRCS_HOME)/%.cpp
	@mkdir -p $(@D)
	$(CXX) $(CFLAGS) $(CXXFLAGS) $(TT_METAL_UNIT_TESTS_FAST_DISPATCH_SINGLE_CHIP_MULTI_QUEUE_INCLUDES) -c -o $@ $<
