# Source files for tt_metal impl library
# Module owners should update this file when adding/removing/renaming source files

set(IMPL_SRC
    sub_device/sub_device.cpp
    sub_device/sub_device_manager_tracker.cpp
    sub_device/sub_device_manager.cpp
    context/metal_context.cpp
    device/experimental/device.cpp
    device/device.cpp
    device/mock_device.cpp
    device/device_manager.cpp
    device/dispatch.cpp
    buffers/buffer.cpp
    buffers/buffer_distribution_spec.cpp
    buffers/buffer_page_mapping.cpp
    buffers/tensor_accessor_args.cpp
    buffers/dispatch.cpp
    buffers/circular_buffer.cpp
    buffers/circular_buffer_config.cpp
    buffers/global_circular_buffer.cpp
    buffers/global_semaphore.cpp
    buffers/semaphore.cpp
    data_format/blockfloat_common.cpp
    data_format/bfloat4.cpp
    data_format/bfloat8.cpp
    data_format/bfloat16.cpp
    data_format/bfloat16_utils.cpp
    data_format/tile.cpp
    data_format/tilize_utils.cpp
    kernels/kernel.cpp
    kernels/kernel_types.cpp
    allocator/algorithms/free_list_opt.cpp
    allocator/allocator.cpp
    allocator/allocator_state.cpp
    allocator/bank_manager.cpp
    allocator/l1_banking_allocator.cpp
    program/program.cpp
    program/dispatch.cpp
    program/program_descriptors.cpp
    program/program_device_map.cpp
    profiler/profiler.cpp
    profiler/tt_metal_profiler.cpp
    profiler/profiler_analysis.cpp
    profiler/profiler_state_manager.cpp
    dispatch/cq_shared_state.cpp
    dispatch/debug_tools.cpp
    dispatch/device_command.cpp
    dispatch/host_runtime_commands.cpp
    dispatch/device_command_calculator.cpp
    dispatch/dispatch_query_manager.cpp
    dispatch/dispatch_core_common.cpp
    dispatch/dispatch_core_manager.cpp
    dispatch/command_queue_common.cpp
    dispatch/dispatch_mem_map.cpp
    dispatch/system_memory_cq_interface.cpp
    dispatch/system_memory_manager.cpp
    dispatch/hardware_command_queue.cpp
    dispatch/launch_message_ring_buffer_state.cpp
    dispatch/worker_config_buffer.cpp
    dispatch/data_collection.cpp
    dispatch/data_collector.cpp
    dispatch/ringbuffer_cache.cpp
    dispatch/topology.cpp
    dispatch/kernel_config/fd_kernel.cpp
    dispatch/kernel_config/prefetch.cpp
    dispatch/kernel_config/dispatch.cpp
    dispatch/kernel_config/dispatch_s.cpp
    dispatch/kernel_config/relay_mux.cpp
    dispatch/util/dispatch_settings.cpp
    debug/dprint_server.cpp
    debug/inspector/data.cpp
    debug/inspector/inspector.cpp
    debug/inspector/logger.cpp
    debug/inspector/rpc_server_controller.cpp
    debug/noc_logging.cpp
    debug/noc_debugging.cpp
    debug/watcher_server.cpp
    debug/watcher_device_reader.cpp
    trace/trace_buffer.cpp
    trace/dispatch.cpp
    event/event.cpp
    event/dispatch.cpp
    flatbuffer/base_types_from_flatbuffer.cpp
    flatbuffer/base_types_to_flatbuffer.cpp
    flatbuffer/buffer_types_from_flatbuffer.cpp
    flatbuffer/buffer_types_to_flatbuffer.cpp
    flatbuffer/program_types_from_flatbuffer.cpp
    flatbuffer/program_types_to_flatbuffer.cpp
    lightmetal/lightmetal_replay.cpp
    lightmetal/lightmetal_replay_impl.cpp
    lightmetal/lightmetal_capture.cpp
    lightmetal/lightmetal_capture_utils.cpp
    lightmetal/host_api_capture_helpers.cpp
    debug/dprint_parser.cpp
    tensor/spec/layout/alignment.cpp
    tensor/spec/layout/layout.cpp
    tensor/spec/layout/page_config.cpp
    tensor/spec/layout/tensor_layout.cpp
    tensor/spec/memory_config/memory_config.cpp
    tensor/spec/tensor_spec.cpp
    tensor/tensor_types.cpp
    tensor/topology/distributed_tensor_configs.cpp
    tensor/topology/tensor_topology.cpp
)
