set(IMPL_SRC
    ${CMAKE_CURRENT_SOURCE_DIR}/sub_device/sub_device.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sub_device/sub_device_manager_tracker.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/sub_device/sub_device_manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/context/metal_context.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/context/metalium_env.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/context/context_descriptor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/firmware/firmware_initializer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/firmware/fabric_firmware_initializer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/firmware/dispatch_kernel_initializer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/firmware/command_queue_initializer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/firmware/profiler_initializer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/firmware/risc_firmware_initializer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/experimental/device.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/device.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/mock_device.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/mock_device_util.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/device_manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/device/dispatch.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/buffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/buffer_distribution_spec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/buffer_page_mapping.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/tensor_accessor_args.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/dispatch.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/circular_buffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/circular_buffer_config.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/global_circular_buffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/global_semaphore.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/buffers/semaphore.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/data_format/blockfloat_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/data_format/bfloat4.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/data_format/bfloat8.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/data_format/bfloat16.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/data_format/bfloat16_utils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/data_format/tile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/data_format/tilize_utils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dataflow_buffer/dataflow_buffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernels/kernel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernels/kernel_types.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/allocator/algorithms/free_list_opt.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/allocator/allocator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/allocator/allocator_state.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/allocator/bank_manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/allocator/l1_banking_allocator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/program/program.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/program/dispatch.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/program/program_descriptors.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/program/program_device_map.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/profiler/profiler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/profiler/tt_metal_profiler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/profiler/profiler_analysis.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/profiler/profiler_state_manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/cq_shared_state.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/debug_tools.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/device_command.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/host_runtime_commands.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/device_command_calculator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/dispatch_query_manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/dispatch_core_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/dispatch_core_manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/command_queue_common.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/dispatch_mem_map.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/system_memory_cq_interface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/system_memory_manager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/hardware_command_queue.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/launch_message_ring_buffer_state.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/worker_config_buffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/data_collection.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/data_collector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/ringbuffer_cache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/topology.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/kernel_config/fd_kernel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/kernel_config/prefetch.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/kernel_config/dispatch.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/kernel_config/dispatch_s.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/kernel_config/relay_mux.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/dispatch/util/dispatch_settings.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/dprint_server.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/inspector/data.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/inspector/inspector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/inspector/logger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/inspector/rpc_server_controller.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/noc_logging.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/noc_debugging.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/watcher_server.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/watcher_device_reader.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/trace/trace_buffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/trace/dispatch.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/event/event.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/event/dispatch.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/flatbuffer/base_types_from_flatbuffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/flatbuffer/base_types_to_flatbuffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/flatbuffer/buffer_types_from_flatbuffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/flatbuffer/buffer_types_to_flatbuffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/flatbuffer/program_types_from_flatbuffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/flatbuffer/program_types_to_flatbuffer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/lightmetal/lightmetal_replay.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/lightmetal/lightmetal_replay_impl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/lightmetal/lightmetal_capture.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/lightmetal/lightmetal_capture_utils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/lightmetal/host_api_capture_helpers.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/debug/dprint_parser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/tensor/tensor_types.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/tensor/spec/tensor_spec.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/tensor/spec/layout/alignment.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/tensor/spec/layout/layout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/tensor/spec/layout/page_config.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/tensor/spec/layout/tensor_layout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/tensor/spec/memory_config/memory_config.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/tensor/topology/distributed_tensor_configs.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/tensor/topology/tensor_topology.cpp
)
