transformer_config:
  model_type: "deepseek"
  embedding_dim: 1536
  num_blocks: 16
  num_heads: 12
  max_sequence_length: 2048
  dropout_prob: 0.0
  # DeepSeek MLA
  q_lora_rank: 512
  kv_lora_rank: 256
  qk_nope_head_dim: 96
  qk_rope_head_dim: 32
  v_head_dim: 128
  theta: 10000.0
  # DeepSeek MoE
  n_dense_layers: 2
  inter_dim: 4096
  moe_inter_dim: 768
  n_routed_experts: 32
  n_shared_experts: 1
  n_activated_experts: 4
  n_expert_groups: 4
  n_limited_groups: 2
  score_func: "sigmoid"
  route_scale: 2.5
  runner_type: "memory_efficient"
