# Auto-generated by tdd_orchestrator.py — Stage: normalize
# DO NOT EDIT — regenerate with: tdd_orchestrator.py add-stage ...
"""
TDD Stage: normalize
Return full-shape output and verify mean subtraction plus invstd broadcast without optional tensors.
"""

import pytest
import torch
import ttnn

from .layer_norm import layer_norm


def pytorch_reference(input_tensor):
    """PyTorch reference for this stage."""
    return torch.nn.functional.layer_norm(
        input_tensor.float(), (input_tensor.shape[-1],), weight=None, bias=None, eps=1e-5
    )


@pytest.mark.parametrize(
    "shape",
    [
        pytest.param((1, 1, 32, 32), id="1x1x32x32"),
        pytest.param((1, 1, 32, 96), id="1x1x32x96"),
        pytest.param((2, 3, 64, 70), id="2x3x64x70"),
    ],
)
def test_normalize(device, shape):
    """Verify Return full-shape output and verify mean subtraction plus invstd broadcast without optional tensors.."""
    layout = ttnn.TILE_LAYOUT
    torch.manual_seed(42)
    torch_input = torch.randn(shape, dtype=torch.bfloat16)

    expected = pytorch_reference(torch_input)

    ttnn_input = ttnn.from_torch(
        torch_input,
        dtype=ttnn.bfloat16,
        layout=layout,
        device=device,
        memory_config=ttnn.DRAM_MEMORY_CONFIG,
    )

    ttnn_output = layer_norm(ttnn_input, epsilon=1e-5)

    expected_shape = list(shape)
    assert list(ttnn_output.shape) == expected_shape, f"Shape: {list(ttnn_output.shape)} vs expected {expected_shape}"

    torch_output = ttnn.to_torch(ttnn_output)
    assert torch.allclose(
        torch_output.float(),
        expected.float(),
        rtol=0.05,
        atol=0.2,
    ), f"Max diff: {(torch_output.float() - expected.float()).abs().max()}"
