name: 'Delete Allocation'
description: 'A composable action to delete an allocation'

inputs:
  allocationName:
    description: 'Allocation name'
    required: true
  namespace:
    description: 'Target namespace for the allocation'
    required: false
    default: 'ttop-ci'
  timeoutSeconds:
    description: 'Max seconds to keep retrying the delete before failing.'
    required: false
    default: '300'

runs:
  using: 'composite'
  steps:
    - name: Delete Allocation
      uses: ./.github/actions/ttop-await-resource
      with:
        namespace: ${{ inputs.namespace }}
        resource: allocation/${{ inputs.allocationName }}
        mode: delete
        timeoutSeconds: ${{ inputs.timeoutSeconds }}