# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0

"""Blackhole program configs for matmul_perf.py, keyed by ISL."""

import ttnn

BHProgramConfig1DFirstTwoMatmuls = {
    32: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=1,
        out_subblock_h=1,
        out_subblock_w=1,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    64: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=14,
        per_core_M=2,
        per_core_N=1,
        out_subblock_h=2,
        out_subblock_w=1,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    128: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=4,
        per_core_N=1,
        out_subblock_h=4,
        out_subblock_w=1,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    192: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=6,
        per_core_N=1,
        out_subblock_h=6,
        out_subblock_w=1,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    256: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=8,
        per_core_N=1,
        out_subblock_h=8,
        out_subblock_w=1,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    384: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=12,
        per_core_N=1,
        out_subblock_h=6,
        out_subblock_w=1,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    512: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=14,
        per_core_M=16,
        per_core_N=1,
        out_subblock_h=8,
        out_subblock_w=1,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    768: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=24,
        per_core_N=1,
        out_subblock_h=8,
        out_subblock_w=1,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
}


BHProgramConfig1DThirdMatmul = {
    32: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=4,
        per_core_M=1,
        per_core_N=3,
        out_subblock_h=1,
        out_subblock_w=3,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    64: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=8,
        per_core_M=2,
        per_core_N=3,
        out_subblock_h=2,
        out_subblock_w=3,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    128: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=4,
        per_core_M=4,
        per_core_N=3,
        out_subblock_h=2,
        out_subblock_w=3,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    192: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=8,
        per_core_M=6,
        per_core_N=3,
        out_subblock_h=2,
        out_subblock_w=3,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    256: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=8,
        per_core_M=8,
        per_core_N=3,
        out_subblock_h=2,
        out_subblock_w=3,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    384: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=12,
        per_core_N=3,
        out_subblock_h=2,
        out_subblock_w=3,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    512: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=16,
        per_core_N=3,
        out_subblock_h=2,
        out_subblock_w=3,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
    768: ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=24,
        per_core_N=3,
        out_subblock_h=2,
        out_subblock_w=3,
        mcast_in0=True,
        fuse_batch=False,
        fused_activation=None,
    ),
}


BHProgramConfig2DFirstTwoMatmuls = {
    32: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=6,
        out_subblock_h=1,
        out_subblock_w=6,
        transpose_mcast=False,
        fused_activation=None,
    ),
    64: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=6,
        out_subblock_h=1,
        out_subblock_w=6,
        transpose_mcast=False,
        fused_activation=None,
    ),
    128: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=6,
        out_subblock_h=1,
        out_subblock_w=6,
        transpose_mcast=False,
        fused_activation=None,
    ),
    192: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=6,
        out_subblock_h=1,
        out_subblock_w=6,
        transpose_mcast=False,
        fused_activation=None,
    ),
    256: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=6,
        out_subblock_h=1,
        out_subblock_w=6,
        transpose_mcast=False,
        fused_activation=None,
    ),
    384: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=2,
        per_core_N=6,
        out_subblock_h=1,
        out_subblock_w=6,
        transpose_mcast=False,
        fused_activation=None,
    ),
    512: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=2,
        per_core_N=6,
        out_subblock_h=1,
        out_subblock_w=6,
        transpose_mcast=False,
        fused_activation=None,
    ),
    768: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=3,
        per_core_N=6,
        out_subblock_h=1,
        out_subblock_w=6,
        transpose_mcast=False,
        fused_activation=None,
    ),
}


BHProgramConfig2DThirdMatmul = {
    32: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=21,
        out_subblock_h=1,
        out_subblock_w=3,
        transpose_mcast=False,
        fused_activation=None,
    ),
    64: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=21,
        out_subblock_h=1,
        out_subblock_w=3,
        transpose_mcast=False,
        fused_activation=None,
    ),
    128: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=21,
        out_subblock_h=1,
        out_subblock_w=3,
        transpose_mcast=False,
        fused_activation=None,
    ),
    192: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=21,
        out_subblock_h=1,
        out_subblock_w=3,
        transpose_mcast=False,
        fused_activation=None,
    ),
    256: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=1,
        per_core_N=21,
        out_subblock_h=1,
        out_subblock_w=3,
        transpose_mcast=False,
        fused_activation=None,
    ),
    384: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=2,
        per_core_N=21,
        out_subblock_h=2,
        out_subblock_w=3,
        transpose_mcast=False,
        fused_activation=None,
    ),
    512: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=2,
        per_core_N=21,
        out_subblock_h=2,
        out_subblock_w=3,
        transpose_mcast=False,
        fused_activation=None,
    ),
    768: ttnn.MatmulMultiCoreReuseMultiCastProgramConfig(
        compute_with_storage_grid_size=(11, 10),
        in0_block_w=16,
        per_core_M=3,
        per_core_N=21,
        out_subblock_h=1,
        out_subblock_w=3,
        transpose_mcast=False,
        fused_activation=None,
    ),
}
