transformer_config:
  model_type: "llama"
  num_heads: 15
  num_groups: 5
  embedding_dim: 960
  dropout_prob: 0.0
  num_blocks: 32
  vocab_size: 49152
  max_sequence_length: 768
  runner_type: default
  theta: 100000.0
  weight_tying: "enabled"
