# Source files for ttnn_op_normalization.
# Module owners should update this file when adding/removing/renaming source files.

set(TTNN_OP_NORMALIZATION_SRCS
    batch_norm/batch_norm.cpp
    batch_norm/device/batch_norm_device_operation.cpp
    batch_norm/device/batch_norm_program_factory.cpp
    batch_norm/device/running_statistics_device_operation.cpp
    batch_norm/device/running_statistics_program_factory.cpp
    batch_norm/device/batch_norm_utils.cpp
    groupnorm/device/groupnorm_program_utils.cpp
    groupnorm/device/groupnorm_device_operation.cpp
    groupnorm/device/groupnorm_sharded_program_factory.cpp
    groupnorm/device/groupnorm_no_mcast_program_factory.cpp
    groupnorm/device/groupnorm_mcast_program_factory.cpp
    groupnorm/groupnorm.cpp
    groupnorm/groupnorm_input_mask.cpp
    groupnorm/groupnorm_grid_utils.cpp
    layernorm/device/layernorm_device_operation.cpp
    layernorm/device/layernorm_common.cpp
    layernorm/device/layernorm_op_multi_core.cpp
    layernorm/device/layernorm_op_multi_core_sharded.cpp
    layernorm/device/sharded_layernorm_factory_helpers.cpp
    layernorm/layernorm.cpp
    layernorm_distributed/device/layernorm_post_all_gather_device_operation.cpp
    layernorm_distributed/device/layernorm_post_all_gather_program_factory.cpp
    layernorm_distributed/device/layernorm_post_all_gather_welford_program_factory.cpp
    layernorm_distributed/device/layernorm_pre_all_gather_device_operation.cpp
    layernorm_distributed/device/layernorm_pre_all_gather_program_factory.cpp
    layernorm_distributed/device/layernorm_pre_all_gather_welford_program_factory.cpp
    layernorm_distributed/layernorm_post_all_gather.cpp
    layernorm_distributed/layernorm_pre_all_gather.cpp
    rmsnorm/rmsnorm.cpp
    softmax/softmax.cpp
    softmax/device/softmax_device_operation.cpp
    softmax/device/softmax_program_factory_general.cpp
    softmax/device/softmax_program_factory_general_w_small.cpp
    softmax/device/softmax_program_factory_general_w_large.cpp
    softmax/device/softmax_program_factory_general_h_small.cpp
    softmax/device/softmax_program_factory_general_h_large.cpp
    softmax/device/softmax_program_factory_general_c_large.cpp
    softmax/device/softmax_program_factory_attention_optimized.cpp
    softmax/device/softmax_program_factory_attention_optimized_sharded.cpp
)

set(TTNN_OP_NORMALIZATION_API_HEADERS
    layernorm/layernorm.hpp
    layernorm/device/layernorm_types.hpp
    layernorm_distributed/device/layernorm_distributed_types.hpp
    layernorm_distributed/device/layernorm_pre_all_gather_device_operation.hpp
    rmsnorm/rmsnorm.hpp
    softmax/device/softmax_operation_types.hpp
    softmax/device/softmax_device_operation.hpp
    softmax/device/softmax_program_factory_general.hpp
    softmax/device/softmax_program_factory_general_w_small.hpp
    softmax/device/softmax_program_factory_general_w_large.hpp
    softmax/device/softmax_program_factory_general_h_small.hpp
    softmax/device/softmax_program_factory_general_h_large.hpp
    softmax/device/softmax_program_factory_general_c_large.hpp
    softmax/device/softmax_program_factory_attention_optimized.hpp
    softmax/device/softmax_program_factory_attention_optimized_sharded.hpp
    softmax/softmax.hpp
)
