# Source files for ttnn_op_reduction.
# Module owners should update this file when adding/removing/renaming source files.

set(TTNN_OP_REDUCTION_SRCS
    argmax/device/argmax_device_operation.cpp
    argmax/device/argmax_multi_core_program_factory.cpp
    argmax/device/argmax_single_core_program_factory.cpp
    argmax/argmax.cpp
    accumulation/accumulation_common.cpp
    accumulation/cumprod/cumprod.cpp
    accumulation/cumsum/cumsum.cpp
    accumulation/ema/ema.cpp
    accumulation/ema/device/ema_device_operation.cpp
    accumulation/ema/device/ema_program_factory.cpp
    accumulation/device/accumulation_device_operation.cpp
    accumulation/device/accumulation_program_factory.cpp
    sampling/device/sampling_device_operation.cpp
    sampling/device/sampling_program_factory.cpp
    sampling/sampling.cpp
    moe/device/moe_device_operation.cpp
    moe/device/moe_program_factory.cpp
    moe/moe.cpp
    prod/device/prod_all_program_factory.cpp
    generic/device/reduce_op_device_operation.cpp
    generic/device/reduce_op_single_core_hw_program_factory.cpp
    generic/device/reduce_op_multi_core_h_program_factory.cpp
    generic/device/reduce_op_multi_core_w_program_factory.cpp
    generic/device/reduce_op.cpp
    generic/device/common.cpp
    generic/device/welford_reduce_device_operation.cpp
    generic/device/welford_reduce_program_factory.cpp
    generic/generic_reductions.cpp
    prod/device/prod_all_device_operation.cpp
    prod/device/prod_nc_op.cpp
    prod/device/prod_nc_device_operation.cpp
    prod/device/prod_nc_program_factory.cpp
    prod/device/prod_op_all.cpp
    prod/prod.cpp
    topk/device/topk_device_operation.cpp
    topk/device/topk_utils.cpp
    topk/topk.cpp
    topk/device/topk_single_core_program_factory.cpp
    topk/device/topk_multi_core_program_factory.cpp
    reduction_common/reduction_common.cpp
    manual_seed/manual_seed.cpp
    manual_seed/device/manual_seed_operation.cpp
    manual_seed/device/manual_seed_program_factory.cpp
)

set(TTNN_OP_REDUCTION_API_HEADERS
    argmax/argmax.hpp
    generic/generic_reductions.hpp
    reduction_common/reduction_common.hpp
)
