#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Generate host/l2cpu/sampling/layout.py, the Python mirror of sampling/include/l2cpu_sampling.h.

Every `#define L2S_<NAME>` and `#define L2CPU_LINK_<NAME>` integer expression is mirrored (the generic L2CPU_
constants are evaluated for the expressions but live in host/l2cpu/layout.py).
    gen_sampling_py.py            write the mirror
    gen_sampling_py.py --check    exit 1 if the committed mirror is stale
"""
import argparse
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SAMPLING = os.path.dirname(HERE)
L2CPU = os.path.dirname(SAMPLING)
BOOT_H = os.path.join(L2CPU, "include", "l2cpu_boot.h")
LINK_H = os.path.join(L2CPU, "tensix", "kernels", "l2cpu_link.h")
HEADER = os.path.join(SAMPLING, "include", "l2cpu_sampling.h")
OUT = os.path.join(L2CPU, "host", "l2cpu", "sampling", "layout.py")
DEFINE_RE = re.compile(r"^\s*#\s*define\s+((?:L2CPU|L2S)_[A-Za-z0-9_]+)\s+(.+?)\s*(?:/\*.*|//.*)?$")
EMIT = ("L2S_", "L2CPU_LINK_")


def parse(paths):
    consts, order = {}, []
    for path in paths:
        for line in open(path):
            m = DEFINE_RE.match(line)
            if not m:
                continue
            name, value = m.group(1), m.group(2)
            expr = re.sub(r"/\*.*?\*/", "", value).strip()
            expr = re.sub(r"\b(0[xX][0-9a-fA-F]+|\d+)([uU]?[lL]{0,2})\b", r"\1", expr).replace("/", "//")
            if not expr or re.search(r"[^0-9A-Za-z_xX+\-*()<>|& /~ ]", expr):
                continue
            try:
                val = eval(expr, {"__builtins__": {}}, dict(consts))
            except Exception:
                continue
            if isinstance(val, int):
                consts[name] = val
                order.append(name)
    return consts, [n for n in order if n.startswith(EMIT)]


def digest():
    h = hashlib.sha256()
    for p in (LINK_H, HEADER):
        h.update(open(p, "rb").read())
    return h.hexdigest()[:16]


def render():
    consts, order = parse([BOOT_H, LINK_H, HEADER])
    lines = [
        "# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.",
        "# SPDX-FileCopyrightText: © 2026 Kansei Motoe (kinginu)",
        "# SPDX-License-Identifier: Apache-2.0",
        '"""GENERATED by tools/l2cpu/sampling/tools/gen_sampling_py.py from sampling/include/l2cpu_sampling.h and',
        'tensix/kernels/l2cpu_link.h. DO NOT EDIT."""',
        "",
        f'HEADER_SHA256_16 = "{digest()}"',
        "",
    ]
    lines += [f"{n} = {f'0x{consts[n]:X}' if consts[n] >= 16 else consts[n]}" for n in order]
    lines += ["", "CONSTANTS = {"] + [f'    "{n}": {n},' for n in order] + ["}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.check:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print(f"{OUT} is stale: run {__file__}")
            return 1
        print("sampling layout mirror is current")
        return 0
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
