# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.

# SPDX-License-Identifier: Apache-2.0
"""
Kimi-K2.6 vision-only loader.

K2.6 is a 1T-param multimodal MoE; the full checkpoint is ~600 GB on
disk. We only need the vision tower (~834 MB) and the projector
(~108 MB) — both contained entirely in shards 63 and 64.

This module:

  1. Stages the K2.6 modeling code into a clean Python package
     (HF's `trust_remote_code` dynamic-module loader chokes on the
     `.` in `Kimi-K2.6` repo name, so we side-step it).
  2. Builds the K2.6 vision tower + projector from `config.json`
     using `transformers.modeling_utils.no_init_weights` so no
     random initialization runs.
  3. Loads the relevant tensors from shards 63 + 64 via safetensors
     (no `AutoModel.from_pretrained()` — that would try to materialize
     the 595 GB LLM half).

The end result is a torch reference module set that mirrors what HF
`KimiK25ForConditionalGeneration` would expose (`.vision_tower` and
`.mm_projector`), without the LLM weights.

Notes on the architecture vs A3B:
  - K2.6 uses the 3D variant: `MoonViT3dPretrainedModel`, expecting
    `(T, H, W)` grids. For image inputs we pass `T=1` and the 3D
    extensions degenerate to the 2D MoonViT we already implemented.
  - The projector class is `PatchMergerMLP` (Sequential layout
    `proj.0 / proj.2`), not `KimiVLMultiModalProjector` (named-attr
    `linear_1 / linear_2`).
  - Output dim is 7168 (matches DeepSeek-V3 / K2.6 LLM hidden),
    vs A3B's 2048.
"""
from __future__ import annotations

import json
import os
import shutil
import sys
from types import SimpleNamespace
from typing import Optional

import torch

# Default snapshot location — populated by huggingface_hub.snapshot_download.
DEFAULT_HF_CACHE_DIR = "/localdev/zbaczewski/hf_cache/hub"
DEFAULT_REPO_DIRNAME = "models--moonshotai--Kimi-K2.6"

# Where we stage the K2.6 modeling .py files under a sanitized package name
# (HF's auto-loader can't import the repo's modules directly because of the
# `.` in the repo name).
DEFAULT_STAGING_DIR = "/tmp/kimi_k26_pkg"

# Shard files containing vision_tower (64) and mm_projector (63).
VISION_TOWER_SHARD = "model-00064-of-000064.safetensors"
PROJECTOR_SHARD = "model-00063-of-000064.safetensors"


def _find_snapshot_dir(cache_dir: str = DEFAULT_HF_CACHE_DIR) -> str:
    """Locate the K2.6 snapshot directory inside the HF cache."""
    base = os.path.join(cache_dir, DEFAULT_REPO_DIRNAME, "snapshots")
    if not os.path.isdir(base):
        raise FileNotFoundError(
            f"K2.6 snapshot root not found at {base}. "
            "Run `huggingface-cli download moonshotai/Kimi-K2.6 --include "
            "'model-00063*' 'model-00064*' 'config.json' '*.py' 'preprocessor_config.json'` first."
        )
    snaps = [d for d in os.listdir(base) if not d.startswith(".")]
    if not snaps:
        raise FileNotFoundError(f"No snapshots inside {base}")
    if len(snaps) > 1:
        # Pick the lexicographically latest commit hash.
        snaps.sort()
    return os.path.join(base, snaps[-1])


def _stage_modeling_package(snapshot_dir: str, staging_dir: str = DEFAULT_STAGING_DIR) -> str:
    """Copy K2.6 .py files into a clean, importable Python package.

    Needed because `Kimi-K2.6`'s `.6` confuses HF's dynamic-module loader
    (Python package names can't contain `.`). We copy the modeling
    files to a sanitized directory with an `__init__.py` and import
    from there directly.
    """
    files = [
        "configuration_deepseek.py",
        "configuration_kimi_k25.py",
        "modeling_deepseek.py",
        "modeling_kimi_k25.py",
        "kimi_k25_processor.py",
        "kimi_k25_vision_processing.py",
        "media_utils.py",
        "tokenization_kimi.py",
    ]
    os.makedirs(staging_dir, exist_ok=True)
    # Mark it as a Python package.
    init = os.path.join(staging_dir, "__init__.py")
    if not os.path.exists(init):
        with open(init, "w") as f:
            f.write("# autogenerated by _k26_loader\n")

    for fn in files:
        src = os.path.join(snapshot_dir, fn)
        dst = os.path.join(staging_dir, fn)
        if os.path.exists(src) and not os.path.exists(dst):
            shutil.copy2(src, dst)
    return staging_dir


def _ensure_pkg_on_path(staging_dir: str = DEFAULT_STAGING_DIR) -> None:
    parent = os.path.dirname(staging_dir.rstrip("/"))
    if parent not in sys.path:
        sys.path.insert(0, parent)


def load_vision_config(snapshot_dir: Optional[str] = None) -> SimpleNamespace:
    """Return a SimpleNamespace that mimics K2.6's `vision_config` block.

    The K2.6 modeling classes (`VisionTowerConfig`, `ProjectorConfig`)
    take any object with the right attributes, not a specific class.
    """
    snapshot_dir = snapshot_dir or _find_snapshot_dir()
    with open(os.path.join(snapshot_dir, "config.json")) as f:
        cfg = json.load(f)
    vc = dict(cfg["vision_config"])
    # K2.6's default `_attn_implementation` is `flash_attention_2`, which
    # requires the `flash_attn` package. We register and use `sdpa` instead
    # (see `_register_sdpa_attention`): it needs no extra dependency and,
    # unlike K2.6's bundled `eager`, applies a correct block-diagonal mask
    # so multi-image packing matches our on-device attention. For a single
    # image all three variants are numerically identical.
    vc.setdefault("_attn_implementation", "sdpa")
    if vc["_attn_implementation"] == "flash_attention_2":
        vc["_attn_implementation"] = "sdpa"
    return SimpleNamespace(**vc)


def _strip_prefix(d: dict, prefix: str) -> dict:
    return {k[len(prefix) :]: v for k, v in d.items() if k.startswith(prefix)}


def _register_sdpa_attention(mdl_mod) -> None:
    """Register a correct block-diagonal `sdpa` attention in the K2.6 module.

    K2.6 ships only `flash_attention_2` (needs the `flash_attn` package)
    and `eager`. Its `eager` variant builds a boolean block mask and does
    `attn_weight += mask` — adding +1.0 *inside* each image block and 0
    outside. For a single image that's a uniform shift (invariant under
    softmax), but for packed multi-image inputs it fails to mask
    cross-image attention, so it diverges from our on-device attention
    which masks correctly via cu_seqlens.

    This `sdpa` implementation reproduces the q/k/v layout of K2.6's
    `multihead_attention`/`eager_attention` (input `(seqlen, nheads,
    headdim)`, output `(seqlen, nheads*headdim)`) but masks correctly:
    each image attends only within its own cu_seqlens block.
    """
    import torch.nn.functional as F

    def sdpa_attention(q, k, v, q_cu_seqlens=None, k_cu_seqlens=None, **kwargs):
        seqlen = q.shape[0]
        # Block-diagonal boolean mask: True == attend.
        attn_mask = torch.zeros(1, seqlen, seqlen, dtype=torch.bool, device=q.device)
        cu = q_cu_seqlens
        for i in range(1, len(cu)):
            a, b = int(cu[i - 1]), int(cu[i])
            attn_mask[..., a:b, a:b] = True
        q = q.transpose(0, 1)  # (nheads, seqlen, headdim)
        k = k.transpose(0, 1)
        v = v.transpose(0, 1)
        out = F.scaled_dot_product_attention(q, k, v, attn_mask=attn_mask)
        return out.transpose(0, 1).reshape(seqlen, -1)

    funcs = mdl_mod.VL_VISION_ATTENTION_FUNCTIONS
    funcs.setdefault("sdpa", sdpa_attention)


def load_k26_vision_reference(
    snapshot_dir: Optional[str] = None,
    staging_dir: str = DEFAULT_STAGING_DIR,
    dtype: Optional[torch.dtype] = None,
):
    """Construct the K2.6 vision tower + projector as torch reference modules.

    Args:
        snapshot_dir: K2.6 snapshot path. If None, auto-located in the HF cache.
        staging_dir: where to stage the modeling .py files. Defaults to
            ``/tmp/kimi_k26_pkg`` — survives until tmp is wiped.
        dtype: target dtype (e.g. torch.float32 for the per-submodule PCC tests).
            If None, weights are loaded as they appear in safetensors (bf16).

    Returns:
        (vision_tower, projector) — both eval-mode torch.nn.Module instances.
    """
    snapshot_dir = snapshot_dir or _find_snapshot_dir()
    _stage_modeling_package(snapshot_dir, staging_dir)
    _ensure_pkg_on_path(staging_dir)

    # Import lazily — only after staging so the relative imports resolve.
    pkg_name = os.path.basename(staging_dir.rstrip("/"))
    mdl_mod = __import__(f"{pkg_name}.modeling_kimi_k25", fromlist=["*"])
    MoonViT3dPretrainedModel = mdl_mod.MoonViT3dPretrainedModel
    PatchMergerMLP = mdl_mod.PatchMergerMLP
    VisionTowerConfig = mdl_mod.VisionTowerConfig
    ProjectorConfig = mdl_mod.ProjectorConfig

    # Make the correct `sdpa` attention available before constructing blocks.
    _register_sdpa_attention(mdl_mod)

    from safetensors.torch import load_file
    from transformers.modeling_utils import no_init_weights

    vc = load_vision_config(snapshot_dir)

    with no_init_weights():
        vt_config = VisionTowerConfig(vc)
        vt_config._attn_implementation = vc._attn_implementation
        vision_tower = MoonViT3dPretrainedModel(vt_config).eval()

        proj_config = ProjectorConfig(vc)
        projector = PatchMergerMLP(proj_config).eval()

    # Load weights from the two vision-bearing shards.
    s64 = load_file(os.path.join(snapshot_dir, VISION_TOWER_SHARD))
    s63 = load_file(os.path.join(snapshot_dir, PROJECTOR_SHARD))
    vision_tower.load_state_dict(_strip_prefix(s64, "vision_tower."), strict=True)
    projector.load_state_dict(_strip_prefix(s63, "mm_projector."), strict=True)

    # Propagate attn_implementation override to each encoder block.
    for blk in vision_tower.encoder.blocks:
        blk.attn_implementation = vc._attn_implementation

    if dtype is not None:
        vision_tower = vision_tower.to(dtype=dtype)
        projector = projector.to(dtype=dtype)

    for p in vision_tower.parameters():
        p.requires_grad_(False)
    for p in projector.parameters():
        p.requires_grad_(False)
    return vision_tower, projector
