# Source files for ttnn_op_data_movement.
# Module owners should update this file when adding/removing/renaming source files.

set(TTNN_OP_DATA_MOVEMENT_SRCS
    bcast/bcast.cpp
    bcast/bcast_types.cpp
    bcast/device/bcast_device_operation.cpp
    bcast/device/bcast_multi_core_h_program_factory.cpp
    bcast/device/bcast_sharded_h_program_factory.cpp
    bcast/device/bcast_sharded_h_optimised_program_factory.cpp
    bcast/device/bcast_multi_core_w_program_factory.cpp
    bcast/device/bcast_multi_core_hw_program_factory.cpp
    chunk/chunk.cpp
    clone/clone.cpp
    clone/device/clone_device_operation.cpp
    clone/device/clone_program_factory.cpp
    common/common.cpp
    concat/concat.cpp
    concat/device/concat_device_operation.cpp
    concat/device/concat_program_factory.cpp
    concat/device/concat_s2s_tiled_program_factory.cpp
    concat/device/concat_s2s_rm_program_factory.cpp
    concat/device/concat_s2s_multi_program_factory.cpp
    concat/device/concat_s2i_program_factory.cpp
    copy/copy.cpp
    copy/device/copy_device_operation.cpp
    copy/device/copy_same_memory_config_program_factory.cpp
    copy/device/copy_default_row_major_program_factory.cpp
    copy/device/copy_default_tilized_program_factory.cpp
    expand/expand.cpp
    fill_pad/device/fill_pad_device_operation.cpp
    fill_pad/device/fill_pad_program_factory.cpp
    fill_pad/fill_pad.cpp
    fill_rm/device/fill_rm_device_operation.cpp
    fill_rm/device/fill_rm_program_factory.cpp
    fill_rm/fill_rm.cpp
    fold/device/fold_device_op.cpp
    fold/device/fold_multi_core_dram_program_factory.cpp
    fold/device/fold_multi_core_program_factory.cpp
    fold/fold.cpp
    indexed_fill/device/indexed_fill_device_operation.cpp
    indexed_fill/device/indexed_fill_program_factory.cpp
    indexed_fill/indexed_fill.cpp
    moe_expert_token_remap/moe_expert_token_remap.cpp
    moe_expert_token_remap/device/moe_expert_token_remap_device_operation.cpp
    moe_expert_token_remap/device/moe_expert_token_remap_program_factory.cpp
    moe_routing_remap/moe_routing_remap.cpp
    moe_routing_remap/device/moe_routing_remap_device_operation.cpp
    moe_routing_remap/device/moe_routing_remap_program_factory.cpp
    move/device/move_device_operation.cpp
    move/device/move_program_factory.cpp
    move/device/move_overlap_program_factory.cpp
    move/device/move_sharded_program_factory.cpp
    move/move.cpp
    narrow/narrow.cpp
    non_zero_indices/device/non_zero_indices_device_operation.cpp
    non_zero_indices/device/non_zero_indices_program_factory.cpp
    non_zero_indices/non_zero_indices.cpp
    pad/device/pad_device_operation.cpp
    pad/device/pad_rm_reader_writer_multi_core_program_factory.cpp
    pad/device/pad_rm_reader_writer_multi_core_default_program_factory.cpp
    pad/device/pad_rm_reader_writer_program_factory.cpp
    pad/device/pad_rm_sharded_height_only_program_factory.cpp
    pad/device/pad_rm_sharded_width_only_program_factory.cpp
    pad/device/pad_tile_multicore_program_factory.cpp
    pad/device/pad_tile_program_factory.cpp
    pad/pad.cpp
    permute/device/permute_device_operation.cpp
    permute/device/permute_rm_program_factory.cpp
    permute/device/permute_tiled_program_factory.cpp
    permute/permute.cpp
    repeat/device/repeat_program_factory_last_dim.cpp
    repeat/device/repeat_program_factory_higher_dim.cpp
    repeat/device/repeat_device_operation.cpp
    repeat/repeat.cpp
    repeat_interleave/repeat_interleave.cpp
    reshape_on_device/device/reshape_op.cpp
    reshape_on_device/device/reshape_tile_program_factory.cpp
    reshape_on_device/device/reshape_rm_program_factory.cpp
    reshape_on_device/reshape.cpp
    reshape_view/device/reshape_rm_program_factory.cpp
    reshape_view/device/reshape_tiled_program_factory.cpp
    reshape_view/device/reshape_device_operation.cpp
    reshape_view/reshape.cpp
    roll/roll.cpp
    scatter/scatter.cpp
    scatter/tosa_scatter.cpp
    scatter/device/scatter_device_operation.cpp
    scatter/device/scatter_reduce_bfloat16_program_factory.cpp
    scatter/device/scatter_program_factory.cpp
    sharded/interleaved_to_sharded/device/interleaved_to_sharded_op.cpp
    sharded/interleaved_to_sharded/device/interleaved_to_sharded_program_factory.cpp
    sharded/interleaved_to_sharded/interleaved_to_sharded.cpp
    sharded/reshard/device/reshard_device_operation.cpp
    sharded/reshard/device/reshard_program_factory_same_width.cpp
    sharded/reshard/device/reshard_program_factory_same_height.cpp
    sharded/reshard/device/reshard_program_factory_generic.cpp
    sharded/reshard/device/nd_reshard_program_factory_copy_pages.cpp
    sharded/reshard/device/nd_reshard_program_factory_copy_local.cpp
    sharded/reshard/reshard.cpp
    sharded/sharded_common.cpp
    sharded/sharded_to_interleaved/device/sharded_to_interleaved_device_operation.cpp
    sharded/sharded_to_interleaved/device/sharded_to_interleaved_program_factory.cpp
    sharded/sharded_to_interleaved/sharded_to_interleaved.cpp
    sharded_partial/interleaved_to_sharded_partial/device/interleaved_to_sharded_partial_op.cpp
    sharded_partial/interleaved_to_sharded_partial/device/interleaved_to_sharded_partial_program_factory.cpp
    sharded_partial/interleaved_to_sharded_partial/interleaved_to_sharded_partial.cpp
    sharded_partial/sharded_to_interleaved_partial/device/sharded_to_interleaved_partial_device_operation.cpp
    sharded_partial/sharded_to_interleaved_partial/device/sharded_to_interleaved_partial_program_factory.cpp
    sharded_partial/sharded_to_interleaved_partial/sharded_to_interleaved_partial.cpp
    slice/device/slice_device_operation.cpp
    slice/device/slice_program_factory_rm.cpp
    slice/device/slice_program_factory_rm_sharded.cpp
    slice/device/slice_program_factory_rm_stride.cpp
    slice/device/slice_program_factory_tile.cpp
    slice/device/slice_program_factory_tile_tensor_args.cpp
    slice/slice.cpp
    split/device/split_device_operation.cpp
    split/device/split_program_factory.cpp
    split/split.cpp
    squeeze/squeeze.cpp
    stack/stack.cpp
    tilize/device/tilize_device_operation.cpp
    tilize/device/tilize_multi_core_default_program_factory.cpp
    tilize/device/tilize_multi_core_block_program_factory.cpp
    tilize/device/tilize_single_core_program_factory.cpp
    tilize/device/tilize_multi_core_sharded_program_factory.cpp
    tilize/device/tilize_multi_core_width_sharded_program_factory.cpp
    tilize/tilize.cpp
    tilize_with_val_padding/device/tilize_with_val_padding_device_operation.cpp
    tilize_with_val_padding/device/factories/tilize_with_val_padding_single_core_program_factory.cpp
    tilize_with_val_padding/device/factories/tilize_with_val_padding_multi_core_block_interleaved_program_factory.cpp
    tilize_with_val_padding/device/factories/tilize_with_val_padding_multi_core_default_program_factory.cpp
    tilize_with_val_padding/device/factories/tilize_with_val_padding_multi_core_sharded_program_factory.cpp
    tilize_with_val_padding/device/factories/tilize_with_val_padding_factory_helper.cpp
    tilize_with_val_padding/tilize_with_val_padding.cpp
    transpose/device/transpose_device_operation.cpp
    transpose/device/transpose_cn_program_factory.cpp
    transpose/device/transpose_hc_rm_program_factory.cpp
    transpose/device/transpose_hc_sharded_program_factory.cpp
    transpose/device/transpose_hc_tiled_interleaved_program_factory.cpp
    transpose/device/transpose_hc_tiled_program_factory.cpp
    transpose/device/transpose_wh_program_factory.cpp
    transpose/device/transpose_wh_sharded_program_factory.cpp
    transpose/device/transpose_wh_sharded_rm_program_factory.cpp
    transpose/transpose.cpp
    unsqueeze/unsqueeze.cpp
    untilize/device/untilize_device_operation.cpp
    untilize/device/untilize_device_operation_types.cpp
    untilize/device/factories/untilize_multi_core_parallelize_column_program_factory.cpp
    untilize/device/factories/untilize_multi_core_input_and_output_shard_type_and_shard_spec_identical_program_factory.cpp
    untilize/device/factories/untilize_multi_core_input_and_output_nd_shard_type_and_shard_spec_identical_program_factory.cpp
    untilize/device/factories/untilize_multi_core_sub_core_grids_program_factory.cpp
    untilize/device/factories/untilize_single_core_program_factory.cpp
    untilize/device/factories/untilize_multi_core_block_program_factory.cpp
    untilize/device/factories/untilize_multi_core_program_factory.cpp
    untilize/device/factories/untilize_multi_core_nd_shard_input_program_factory.cpp
    untilize/untilize.cpp
    untilize_with_unpadding/device/untilize_with_unpadding_device_operation.cpp
    untilize_with_unpadding/device/factories/untilize_with_unpadding_single_core_program_factory.cpp
    untilize_with_unpadding/device/factories/untilize_with_unpadding_multi_core_interleaved_program_factory.cpp
    untilize_with_unpadding/device/factories/untilize_with_unpadding_multi_core_sharded_program_factory.cpp
    untilize_with_unpadding/device/factories/untilize_with_unpadding_multi_core_col_interleaved_program_factory.cpp
    untilize_with_unpadding/device/factories/untilize_with_unpadding_multi_core_block_interleaved_program_factory.cpp
    untilize_with_unpadding/device/factories/untilize_with_unpadding_multi_core_nd_sharded_program_factory.cpp
    untilize_with_unpadding/untilize_with_unpadding.cpp
    view/view.cpp
    sort/sort.cpp
    sort/device/sort_device_operation.cpp
    sort/device/sort_program_factory.cpp
    gather/gather.cpp
    gather/device/gather_device_operation.cpp
    gather/device/gather_program_factory.cpp
    gather/tosa/gather_tosa.cpp
)

set(TTNN_OP_DATA_MOVEMENT_API_HEADERS
    bcast/bcast.hpp
    bcast/bcast_types.hpp
    concat/concat.hpp
    copy/copy.hpp
    copy/device/copy_device_operation.hpp
    copy/device/copy_same_memory_config_program_factory.hpp
    copy/device/copy_default_row_major_program_factory.hpp
    copy/device/copy_default_tilized_program_factory.hpp
    copy/device/copy_device_operation_types.hpp
    fill_pad/fill_pad.hpp
    fill_pad/device/fill_pad_device_operation.hpp
    fill_rm/fill_rm.hpp
    fill_rm/device/fill_rm_device_operation.hpp
    move/device/move_device_operation.hpp
    pad/pad.hpp
    permute/permute.hpp
    repeat/repeat.hpp
    reshape_view/reshape.hpp
    reshape_view/reshape_common.hpp
    sharded/interleaved_to_sharded/device/interleaved_to_sharded_op.hpp
    sharded/interleaved_to_sharded/interleaved_to_sharded.hpp
    sharded/reshard/reshard.hpp
    sharded/sharded_to_interleaved/device/sharded_to_interleaved_device_operation_types.hpp
    sharded/sharded_to_interleaved/device/sharded_to_interleaved_program_factory.hpp
    sharded/sharded_to_interleaved/device/sharded_to_interleaved_device_operation.hpp
    slice/slice.hpp
    tilize_with_val_padding/tilize_with_val_padding.hpp
    tilize_with_val_padding/device/tilize_with_val_padding_device_operation.hpp
    transpose/transpose.hpp
    untilize/untilize.hpp
    untilize_with_unpadding/untilize_with_unpadding.hpp
)
