name: 'Delete Environment'
description: 'A composable action to delete an environment'

inputs:
  environmentName:
    description: 'Environment name'
    required: true
  namespace:
    description: 'Kubernetes namespace for the environment'
    required: false
    default: 'ttop-ci'

runs:
  using: 'composite'
  steps:
    - name: Delete Environment
      shell: bash
      run: |
        kubectl -n ${{ inputs.namespace }} delete helmrelease/${{ inputs.environmentName }} --ignore-not-found
