#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Generate a minimal op-level PCC pytest from a Phase-1 tracer manifest.

The generated test file does not embed the runtime harness. Instead it injects
the bringup tools directory (this file's directory) onto ``sys.path`` and
imports the original ``tracer_test_harness`` in place, so there is a single
source of truth for the harness and its shared ``tracer_op_specs`` registry.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

# Repo root, resolved from this file's location (tools/bringup -> tools -> repo
# root). Used as the base directory for confining user-supplied paths so a
# malicious manifest/output path cannot escape the intended scope.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _resolve_within_repo(user_path: Any, *, label: str) -> str:
    """Resolve ``user_path`` against the repo root and confine it there.

    Uses an absolute-path + ``startswith`` check against ``_REPO_ROOT`` so that
    dynamic (CLI/user) input cannot escape the repo tree via traversal or an
    out-of-tree absolute path.
    """
    resolved = os.path.abspath(os.path.join(_REPO_ROOT, os.fspath(user_path)))
    if not resolved.startswith(_REPO_ROOT):
        raise ValueError(f"{label} escapes repo root {_REPO_ROOT!r}: {user_path!r} (resolved {resolved})")
    return resolved


def _parse_only(value: Optional[str]) -> Optional[List[str]]:
    if not value:
        return None
    raw = value.replace(",", " ").split()
    return [x.strip() for x in raw if x.strip()]


def _load_manifest_records(manifest_path: Path) -> List[Dict[str, Any]]:
    # Confine the (possibly user-supplied) manifest path to the repo root before
    # reading it, to prevent path traversal outside the intended scope.
    resolved = os.path.abspath(os.path.join(_REPO_ROOT, os.fspath(manifest_path)))
    if not resolved.startswith(_REPO_ROOT):
        raise ValueError(f"manifest path escapes repo root {_REPO_ROOT!r}: {manifest_path!r} (resolved {resolved})")
    data = json.loads(Path(resolved).read_text(encoding="utf-8"))
    return list(data.get("records", []))


def _select_record_ids(records: Sequence[Dict[str, Any]], only: Optional[List[str]]) -> List[int]:
    if not only:
        return list(range(len(records)))
    only_set = set(only)
    ids: List[int] = []
    for i, r in enumerate(records):
        kind = str(r.get("kind"))
        if kind in only_set:
            ids.append(i)
    return ids


TEST_FILE_TEMPLATE = """# Auto-generated minimal op-level PCC pytest
# Generated by: phase2_generate_tests.py
#
# How to run:
#   pytest -q {out_name}
#
# This test imports the shared bringup harness from its original location by
# injecting HARNESS_DIR onto sys.path. No harness files are copied next to this
# test; HARNESS_DIR is the absolute path to tools/bringup at generation time.

from __future__ import annotations

import sys
from pathlib import Path

import pytest

HARNESS_DIR = r"{harness_dir}"
if HARNESS_DIR not in sys.path:
    sys.path.insert(0, HARNESS_DIR)

from tracer_test_harness import open_device, close_device, run_record_id


MANIFEST_PATH = Path(r"{manifest_path}")
RECORD_IDS = {record_ids}
ONLY = {only}
PCC_THRESHOLD = {pcc_threshold}
ALLOW_CROP = {allow_crop}

DEVICE_ENV = {device_env!r}
LEGACY_DEVICE_ENV = "TT_DEVICE_ID"
DEFAULT_DEVICE_ID = {default_device_id}
DEVICE_CANDIDATES = {device_candidates}
L1_SMALL_SIZE = {l1_small_size}


@pytest.fixture(scope="session")
def tt_device():
    dev, dev_id = open_device(
        device_env=DEVICE_ENV,
        legacy_device_env=LEGACY_DEVICE_ENV,
        default_device_id=DEFAULT_DEVICE_ID,
        device_candidates=DEVICE_CANDIDATES,
        l1_small_size=L1_SMALL_SIZE,
        verbose=True,
    )
    print(f"[ttnn] Using device_id={{dev_id}}")
    try:
        yield dev
    finally:
        close_device(dev)


@pytest.mark.parametrize("rec_id", RECORD_IDS, ids=[f"rec{{i}}" for i in RECORD_IDS])
def test_op_pcc(tt_device, rec_id: int):
    run_record_id(
        manifest_path=MANIFEST_PATH,
        rec_id=int(rec_id),
        tt_device=tt_device,
        pcc_threshold=float(PCC_THRESHOLD),
        allow_crop=bool(ALLOW_CROP),
    )
"""


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate minimal op-level PCC pytest from tracer manifest.")
    ap.add_argument("--manifest", required=True, help="Path to tracer manifest.json")
    ap.add_argument("--out-test", required=True, help="Output pytest file path, relative to the repo root")
    ap.add_argument("--only", default=None, help="Comma/space-separated op kinds to include (e.g. Conv2d,ReLU)")
    ap.add_argument("--pcc-threshold", type=float, default=0.999, help="PCC threshold (default: 0.999)")
    ap.add_argument(
        "--allow-crop", action="store_true", help="Allow center-cropping when output shapes mismatch (NOT recommended)"
    )
    ap.add_argument("--device-env", default="TT_DEVICE_ID_OP_TEST", help="Env var used to select TT device")
    ap.add_argument("--default-device-id", type=int, default=0, help="Default TT device id if env vars not set")
    ap.add_argument("--device-candidates", default="0,1,2,3,4,5,6,7", help="Comma-separated fallback device IDs")
    ap.add_argument(
        "--l1-small-size",
        type=int,
        default=32768,
        help="L1 small buffer size for ttnn.open_device (default: 32768; conv2d requires a non-zero value)",
    )
    args = ap.parse_args()

    manifest_path = Path(_resolve_within_repo(args.manifest, label="--manifest"))

    # --out-test is a repo-root-relative path; reject absolute paths outright.
    if os.path.isabs(args.out_test):
        raise RuntimeError(f"--out-test must be relative to the repo root, got an absolute path: {args.out_test!r}")

    # Absolute path to the bringup tools directory (where tracer_test_harness.py
    # and tracer_op_specs.py live). Baked into the generated test's sys.path.
    harness_dir = str(Path(__file__).resolve().parent)

    only = _parse_only(args.only)
    records = _load_manifest_records(manifest_path)
    record_ids = _select_record_ids(records, only)

    cand = [int(x.strip()) for x in str(args.device_candidates).split(",") if x.strip()]

    content = TEST_FILE_TEMPLATE.format(
        out_name=os.path.basename(args.out_test),
        harness_dir=harness_dir,
        manifest_path=str(manifest_path),
        record_ids=record_ids,
        only=only,
        pcc_threshold=float(args.pcc_threshold),
        allow_crop=bool(args.allow_crop),
        device_env=str(args.device_env),
        default_device_id=int(args.default_device_id),
        device_candidates=cand,
        l1_small_size=int(args.l1_small_size),
    )

    # Confine the user-supplied (relative) output path to the repo root using the
    # exact abspath(join(BASE_DIRECTORY, dynamic_input)) + startswith guard that
    # SAST recognizes as proper sanitization for 'Unsanitized dynamic input in file path'.
    out_test = os.path.abspath(os.path.join(_REPO_ROOT, args.out_test))
    if out_test.startswith(_REPO_ROOT):
        os.makedirs(os.path.dirname(out_test), exist_ok=True)
        Path(out_test).write_text(content, encoding="utf-8")
    else:
        raise RuntimeError(f"out_test resolved to {out_test}, but the output must be within the repo root {_REPO_ROOT}")

    print(f"Wrote pytest: {out_test}")
    print(f"Records selected: {len(record_ids)} / {len(records)} (only={only})")
    print(f"Harness imported from: {harness_dir}")


if __name__ == "__main__":
    main()
