ELTWISE_SFPU_EXAMPLE_SRC = $(TT_METAL_HOME)/tt_metal/programming_examples/eltwise_sfpu/eltwise_sfpu.cpp

ELTWISE_SFPU_EXAMPLES_DEPS = $(PROGRAMMING_EXAMPLES_OBJDIR)/eltwise_sfpu.d

-include $(ELTWISE_SFPU_EXAMPLES_DEPS)

.PRECIOUS: $(PROGRAMMING_EXAMPLES_TESTDIR)/eltwise_sfpu
$(PROGRAMMING_EXAMPLES_TESTDIR)/eltwise_sfpu: $(PROGRAMMING_EXAMPLES_OBJDIR)/eltwise_sfpu.o $(TT_METAL_LIB)
	@mkdir -p $(@D)
	$(CXX) $(CFLAGS) $(CXXFLAGS) $(PROGRAMMING_EXAMPLES_INCLUDES) -o $@ $^ $(LDFLAGS) $(PROGRAMMING_EXAMPLES_LDFLAGS)

.PRECIOUS: $(PROGRAMMING_EXAMPLES_OBJDIR)/eltwise_sfpu.o
$(PROGRAMMING_EXAMPLES_OBJDIR)/eltwise_sfpu.o: $(ELTWISE_SFPU_EXAMPLE_SRC)
	@mkdir -p $(@D)
	$(CXX) $(CFLAGS) $(CXXFLAGS) $(PROGRAMMING_EXAMPLES_INCLUDES) -c -o $@ $<
