#loc1 = loc("p0.1")
#loc2 = loc("p1.3")
module @SyncTensorsGraph.7 attributes {mhlo.cross_program_prefetches = [], mhlo.input_output_alias = [], mhlo.is_dynamic = false, mhlo.use_auto_spmd_partitioning = false} {
  vhlo.func_v1 @main(%arg0: !vhlo.tensor_v1<256x128x3x3x!vhlo.bf16_v1> loc("p0.1"), %arg1: !vhlo.tensor_v1<1x128x256x256x!vhlo.bf16_v1> loc("p1.3")) -> (!vhlo.tensor_v1<1x256x128x128x!vhlo.bf16_v1>) {
    %0 = "vhlo.custom_call_v1"(%arg1) <{api_version = #vhlo<api_version_v1 API_VERSION_UNSPECIFIED>, backend_config = #vhlo.string_v1<"">, call_target_name = #vhlo.string_v1<"tt.mark_argument">, called_computations = #vhlo.array_v1<[]>, has_side_effect = #vhlo.bool_v1<false>, operand_layouts = #vhlo.array_v1<[]>, output_operand_aliases = #vhlo.array_v1<[]>, result_layouts = #vhlo.array_v1<[]>}> {mhlo.frontend_attributes = #vhlo.dict_v1<{#vhlo.string_v1<"ttcore.argument_type"> = #vhlo.string_v1<"input">, #vhlo.string_v1<"ttir.name"> = #vhlo.string_v1<"args_0">}>} : (!vhlo.tensor_v1<1x128x256x256x!vhlo.bf16_v1>) -> !vhlo.tensor_v1<1x128x256x256x!vhlo.bf16_v1> loc(#loc3)
    %1 = "vhlo.custom_call_v1"(%arg0) <{api_version = #vhlo<api_version_v1 API_VERSION_UNSPECIFIED>, backend_config = #vhlo.string_v1<"">, call_target_name = #vhlo.string_v1<"tt.mark_argument">, called_computations = #vhlo.array_v1<[]>, has_side_effect = #vhlo.bool_v1<false>, operand_layouts = #vhlo.array_v1<[]>, output_operand_aliases = #vhlo.array_v1<[]>, result_layouts = #vhlo.array_v1<[]>}> {mhlo.frontend_attributes = #vhlo.dict_v1<{#vhlo.string_v1<"ttcore.argument_type"> = #vhlo.string_v1<"parameter">, #vhlo.string_v1<"ttir.name"> = #vhlo.string_v1<"l__self___b_conv_weight">}>} : (!vhlo.tensor_v1<256x128x3x3x!vhlo.bf16_v1>) -> !vhlo.tensor_v1<256x128x3x3x!vhlo.bf16_v1> loc(#loc4)
    %2 = "vhlo.convolution_v1"(%0, %1) <{batch_group_count = #vhlo.integer_v1<1 : i64>, feature_group_count = #vhlo.integer_v1<1 : i64>, input_batch_dimension = #vhlo.integer_v1<0 : i64>, input_feature_dimension = #vhlo.integer_v1<1 : i64>, input_spatial_dimensions = #vhlo.tensor_v1<dense<[2, 3]> : tensor<2xi64>>, kernel_input_feature_dimension = #vhlo.integer_v1<1 : i64>, kernel_output_feature_dimension = #vhlo.integer_v1<0 : i64>, kernel_spatial_dimensions = #vhlo.tensor_v1<dense<[2, 3]> : tensor<2xi64>>, lhs_dilation = #vhlo.tensor_v1<dense<1> : tensor<2xi64>>, output_batch_dimension = #vhlo.integer_v1<0 : i64>, output_feature_dimension = #vhlo.integer_v1<1 : i64>, output_spatial_dimensions = #vhlo.tensor_v1<dense<[2, 3]> : tensor<2xi64>>, padding = #vhlo.tensor_v1<dense<1> : tensor<2x2xi64>>, precision_config = #vhlo.array_v1<[#vhlo<precision_v1 DEFAULT>, #vhlo<precision_v1 DEFAULT>]>, rhs_dilation = #vhlo.tensor_v1<dense<1> : tensor<2xi64>>, window_reversal = #vhlo.tensor_v1<dense<false> : tensor<2xi1>>, window_strides = #vhlo.tensor_v1<dense<2> : tensor<2xi64>>}> : (!vhlo.tensor_v1<1x128x256x256x!vhlo.bf16_v1>, !vhlo.tensor_v1<256x128x3x3x!vhlo.bf16_v1>) -> !vhlo.tensor_v1<1x256x128x128x!vhlo.bf16_v1> loc(#loc5)
    "vhlo.return_v1"(%2) : (!vhlo.tensor_v1<1x256x128x128x!vhlo.bf16_v1>) -> () loc(#loc)
  } {arg_attrs = #vhlo.array_v1<[]>, res_attrs = #vhlo.array_v1<[]>, sym_visibility = #vhlo.string_v1<"">} loc(#loc)
} loc(#loc)
#loc = loc(unknown)
#loc3 = loc("custom-call.4")
#loc4 = loc("custom-call.2")
#loc5 = loc("convolution.5")
