// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include "ckernel.h"
#include "ckernel_defs.h"
#include "ckernel_sfpu_exp.h"  // For _sfpu_round_nearest_int32_
#include "sfpu/ckernel_sfpu_polyval.h"

namespace ckernel {
namespace sfpu {

// Legacy tanh derivative using 1 - tanh²(x) via LUT.
// WARNING: This has catastrophic cancellation for |x| > ~3.4 (Max ULP = 15,140).
// Kept for backward compatibility. Use calculate_tanh_derivative_sech2 instead.
template <bool APPROXIMATION_MODE, int WITH_PRECOMPUTED_TANH = 0, int ITERATIONS = 8>
inline void calculate_tanh_derivative() {
    vUInt l0 = l_reg[LRegs::LReg0];
    vUInt l1 = l_reg[LRegs::LReg1];
    vUInt l2 = l_reg[LRegs::LReg2];

    // tanh'(x) = 1 - (tanh(x))^2
    for (int d = 0; d < ITERATIONS; d++) {
        vFloat val = dst_reg[0];

        if constexpr (!WITH_PRECOMPUTED_TANH) {
            val = lut(val, l0, l1, l2);
        }

        val = val * (-val) + vConst1;
        dst_reg[0] = val;

        dst_reg++;
    }

    l_reg[LRegs::LReg0] = l0;
    l_reg[LRegs::LReg1] = l1;
    l_reg[LRegs::LReg2] = l2;
}

template <bool APPROXIMATION_MODE>
inline void tanh_derivative_init() {
    uint imm0;
    uint imm1;
    uint imm2;
    imm0 = 0x1DFF;  // 0.90625*x
    imm1 = 0x481A;  // 0.09375*x + 0.8125
    imm2 = 0xFF00;  // 1
    _sfpu_load_imm16_(0, imm0);
    _sfpu_load_imm16_(1, imm1);
    _sfpu_load_imm16_(2, imm2);
}

// =============================================================================
// Inline exp for sech² tail: computes exp(-2|x| + ln4) = 4·exp(-2|x|)
// =============================================================================
// For |x| >= 3.0, the asymptotic approximation sech²(x) ≈ 4·exp(-2|x|) is
// exact to within 1 BF16 ULP (verified exhaustively).
//
// Uses the same inline Cody-Waite technique as x_times_exp_negative_tail()
// in the GELU backward kernel:
// 1. Range reduction: t = k·ln(2) + r, where k = round(t/ln2), |r| < 0.5
// 2. Degree-5 Taylor polynomial for exp(r)
// 3. Direct exponent bit manipulation for 2^k scaling (FREE bit ops)
// 4. Explicit FTZ check via exponent field
//
// The ln4 trick folds the ×4 multiplication into the exp argument:
//   4·exp(-2|x|) = exp(-2|x| + ln4)
// This avoids FP32 FTZ underflow at |x| = 43.75 where exp(-87.5) < FP32 min
// normal but 4·exp(-87.5) ≈ 3.9e-38 is still a valid BF16 value.
//
// Performance: ~17 ops (vs ~28 for _sfpu_exp_f32_accurate_)
// Accuracy: < 1 ULP for the exp, combined with asymptotic formula gives Max ULP = 1
// =============================================================================
sfpi_inline sfpi::vFloat inline_exp_sech2_tail(sfpi::vFloat a) {
    constexpr float LN4 = 1.3862943611198906f;
    constexpr float INV_LN2 = 1.4426950408889634f;
    constexpr float LN2_HI = -0.6931152343750000f;  // -ln(2) high bits (exact in float)
    constexpr float LN2_LO = -3.19461832987e-05f;   // -ln(2) low bits

    // Taylor coefficients for exp(r), |r| < 0.5
    constexpr float C2 = 0.5f;
    constexpr float C3 = 0.166666667f;
    constexpr float C4 = 0.0416666667f;
    constexpr float C5 = 0.00833333333f;

    // t = -2|x| + ln4 (always negative for |x| >= 3)
    sfpi::vFloat t = a * (-2.0f) + LN4;

    // Cody-Waite range reduction: t = k·ln(2) + r
    sfpi::vFloat z = t * INV_LN2;
    sfpi::vInt k_int;
    sfpi::vFloat k = _sfpu_round_nearest_int32_(z, k_int);

    sfpi::vFloat r = k * LN2_HI + t;  // Extended precision subtraction
    r = k * LN2_LO + r;

    // Degree-5 Taylor for exp(r)
    sfpi::vFloat poly = PolynomialEvaluator::eval(r, sfpi::vConst1, sfpi::vConst1, C2, C3, C4, C5);

    // 2^k scaling via direct exponent bit manipulation (FREE)
    sfpi::vInt p_exp = sfpi::exexp_nodebias(poly);
    sfpi::vInt new_exp = p_exp + k_int;

    // FTZ: if exponent underflows, result is 0 (natural zero saturation)
    sfpi::vFloat result = sfpi::vConst0;
    v_if(new_exp > 0) { result = sfpi::setexp(poly, new_exp); }
    v_endif;

    return result;
}

// =============================================================================
// Polynomial coefficients for sech²(x) = p(t), t = (2/9)·u - 1, u = x²
// =============================================================================
// Degree-10 minimax polynomial in scaled variable t ∈ [-1, 1], where t is
// derived from u = x² via t = (2/9)·u - 1.  Scaling to [-1, 1] keeps all
// powers bounded (|t^k| ≤ 1), eliminating the FP32 numerical instability
// that makes higher-degree unscaled polynomials diverge.
//
// Exploits even symmetry: sech²(-x) = sech²(x), so sech²(x) = f(x²) = p(t).
// Equivalent to degree-20 polynomial in x, with only 11 coefficients.
//
// Generated by generate_sech2_poly_scaled.py using weighted Chebyshev fitting
// with iterative Remez-style refinement.
// Validated in FP32 simulation: Max ULP = 1, 99.26% exact (ULP = 0).
//
// Evaluation: 1 MAD (scaling) + ~11 MAD ops (Horner) = ~12 MAD ops total.
// =============================================================================
constexpr float SECH2_POLY_C0 = 5.58971869398334972323e-02f;
constexpr float SECH2_POLY_C1 = -1.15151201975556879975e-01f;
constexpr float SECH2_POLY_C2 = 1.41578556434459129632e-01f;
constexpr float SECH2_POLY_C3 = -1.40162303416289407698e-01f;
constexpr float SECH2_POLY_C4 = 1.47692044971667296727e-01f;
constexpr float SECH2_POLY_C5 = -1.43049915574319674860e-01f;
constexpr float SECH2_POLY_C6 = 3.59505515570256450886e-02f;
constexpr float SECH2_POLY_C7 = 5.00465512420113917136e-02f;
constexpr float SECH2_POLY_C8 = 6.00316523798012785518e-02f;
constexpr float SECH2_POLY_C9 = -1.46346136132160548060e-01f;
constexpr float SECH2_POLY_C10 = 6.33840343077387569082e-02f;

// =============================================================================
// Accurate tanh derivative using piecewise polynomial + inline exp
// =============================================================================
// Avoids the catastrophic cancellation in 1 - tanh²(x) (Max ULP = 15,140).
// Uses the same mathematical approach as the GELU backward kernel:
// - Sollya-fitted minimax polynomial for the core region
// - Inline Cody-Waite exp with direct exponent bit manipulation for the tail
// No external function calls (_sfpu_exp_f32_accurate_, _sfpu_reciprocal_).
//
// Two regions (exploiting even symmetry via a = |x|):
//   |x| < 3:    Degree-10 polynomial in t = (2/9)·a² - 1 (~12 MAD ops)
//   |x| >= 3:   Inline exp(-2|x| + ln4) with FTZ (~17 ops)
//               (zero saturation at |x| >= 45 via guard)
//
// Accuracy: Max ULP = 1 across all 65,026 valid BF16 values (FP32 sim).
// Performance: ~14 ops (core) or ~19 ops (tail) vs ~40-50 ops (old version).
// =============================================================================
template <bool APPROXIMATION_MODE, bool is_fp32_dest_acc_en = false, int ITERATIONS = 8>
inline void calculate_tanh_derivative_sech2() {
    for (int d = 0; d < ITERATIONS; d++) {
        sfpi::vFloat val = sfpi::dst_reg[0];
        sfpi::vFloat result = sfpi::vConst0;

        // sech²(x) is an even function: sech²(-x) = sech²(x)
        sfpi::vFloat a = sfpi::abs(val);

        v_if(a < 3.0f) {
            // Core region: degree-10 polynomial in t = (2/9)·u - 1, u = a²
            // Scaling u ∈ [0, 9) → t ∈ [-1, 1) keeps powers bounded.
            sfpi::vFloat u = a * a;
            sfpi::vFloat t = u * (2.0f / 9.0f) + (-1.0f);
            result = PolynomialEvaluator::eval(
                t,
                SECH2_POLY_C0,
                SECH2_POLY_C1,
                SECH2_POLY_C2,
                SECH2_POLY_C3,
                SECH2_POLY_C4,
                SECH2_POLY_C5,
                SECH2_POLY_C6,
                SECH2_POLY_C7,
                SECH2_POLY_C8,
                SECH2_POLY_C9,
                SECH2_POLY_C10);
        }
        v_elseif(a < 45.0f) {
            // Tail region: inline exp(-2|x| + ln4) = 4·exp(-2|x|)
            // Asymptotic formula exact to 1 BF16 ULP for |x| >= 3.
            // For |x| >= 45, result stays 0 (sech²(45) ≈ 5.5e-39 < BF16 min normal).
            result = inline_exp_sech2_tail(a);
        }
        v_endif;

        // Explicit RNE rounding for BF16 output — SFPSTORE truncates toward zero by default.
        if constexpr (!is_fp32_dest_acc_en) {
            result = sfpi::reinterpret<sfpi::vFloat>(sfpi::float_to_fp16b(result, 0));
        }

        sfpi::dst_reg[0] = result;
        sfpi::dst_reg++;
    }
}

template <bool APPROXIMATION_MODE>
inline void tanh_derivative_sech2_init() {
    // No special initialization needed — no reciprocal, no LUT.
    // Polynomial uses only Horner evaluation, inline exp uses only arithmetic.
}

}  // namespace sfpu
}  // namespace ckernel
