// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#pragma once
#include <array>
#include <cstdint>
#include <limits>
#include "ckernel.h"
#include "ckernel_defs.h"
#include "ckernel_sfpu_recip.h"
#include "sfpu/ckernel_sfpu_converter.h"
#include "ckernel_sfpu_conversions.h"
#include "ckernel_sfpu_bf16_horner.h"
#include "ckernel_sfpu_bf16_tti_replay.h"
namespace sfpi {
#include "ckernel_sfpu_bf16_mirrored_terminals.h"
}
#if defined(RANGE_REDUCTION_EXP) || defined(RANGE_REDUCTION_LOG) || defined(RANGE_REDUCTION_TRIG)
#error "square-affine cannot inherit alternate numerical selectors"
#endif
#pragma push_macro("TT_ASYMPTOTIC_END_IF")
#undef TT_ASYMPTOTIC_END_IF
#pragma push_macro("TT_ASYMPTOTIC_IF")
#undef TT_ASYMPTOTIC_IF
#pragma push_macro("TT_SPECIAL_NEG_INF")
#undef TT_SPECIAL_NEG_INF
#pragma push_macro("TT_SPECIAL_POS_INF")
#undef TT_SPECIAL_POS_INF
#pragma push_macro("TT_TARGET_BH_BF16_RAW_NEG_NAN_RESULT")
#undef TT_TARGET_BH_BF16_RAW_NEG_NAN_RESULT
#pragma push_macro("TT_TARGET_BH_BF16_RAW_POS_NAN_RESULT")
#undef TT_TARGET_BH_BF16_RAW_POS_NAN_RESULT
#pragma push_macro("TT_TARGET_BH_BF16_SPECIAL_COMPARE_COUNT")
#undef TT_TARGET_BH_BF16_SPECIAL_COMPARE_COUNT
namespace ckernel::sfpu::ErfBwBf16Config_detail {
using namespace ::sfpi;
using ::sfpi::DataLayout;

// Auto-generated by run_csv.sh
// Degree 1, 1 segments, range [-10.0, 10.0]

constexpr uint32_t POLY_DEGREE = 1;
constexpr uint32_t NUM_SEGMENTS = 1;

constexpr uint32_t LUT_SIZE_BF16 = 4;
constexpr std::array<float, LUT_SIZE_BF16> LUT_DATA_BF16 = {
    {-1.0000000000000000e+01f, 1.0000000000000000e+01f, 1.1283752628727044e+00f, 6.1106666499469343e-16f}};

// static: a namespace-scope constexpr REFERENCE has EXTERNAL linkage (the
// internal-linkage-for-const rule covers const objects, not references),
// so without static the reference symbol pins the whole LUT array into the
// local-data-memory image of every TRISC (~1.7KB free) -- s256+ configs
// then fail to link on any kernel that reads the LUT at runtime (segment
// overflows region:1). Internal linkage lets LTO discard the dead copy;
// compile-time consumers are unaffected.
static constexpr auto& LUT_DATA = LUT_DATA_BF16;
constexpr uint32_t LUT_SIZE = LUT_SIZE_BF16;

// Asymptotic factoring: exp(-x^2)
constexpr float ASYMPTOTIC_EXP_ARG_SCALE = -1.0000000000000000e+00f;
constexpr float ASYMPTOTIC_SCALE = 1.0000000000000000e+00f;

// Typed domain actions.
struct TtDomainActionRecord {
    float bound;
    uint8_t direction;
    uint8_t inclusive;
    uint8_t action_kind;   // 0=constant, 1=identity, 2=affine, 3=class, 4=signed-inf
    uint8_t return_class;  // 0=NaN, 1=+Inf, 2=-Inf, 3=+0, 4=-0
    float value;
    float scale;
    float bias;
};
constexpr uint32_t TT_DOMAIN_ACTION_COUNT = 2;
constexpr std::array<TtDomainActionRecord, TT_DOMAIN_ACTION_COUNT> TT_DOMAIN_ACTION_DATA = {
    {{-9.3750000000000000e+00f, 0, 1, 0, 0, 0.0000000000000000e+00f, 0.0000000000000000e+00f, 0.0000000000000000e+00f},
     {9.3750000000000000e+00f, 1, 1, 0, 0, 0.0000000000000000e+00f, 0.0000000000000000e+00f, 0.0000000000000000e+00f}}};
constexpr float TT_DOMAIN_ACTION_SYMMETRIC_TAIL_BOUND = 9.3750000000000000e+00f;
constexpr float TT_DOMAIN_ACTION_SYMMETRIC_TAIL_VALUE = 0.0000000000000000e+00f;
constexpr uint8_t TT_DOMAIN_ACTION_SYMMETRIC_TAIL_INCLUSIVE = 1;

// Declared special-value policy from the typed activation specification.
// 0=NaN 1=+Inf 2=-Inf 3=+0 4=-0 5=finite_other(pass through)
#define TT_TARGET_BH_BF16_RAW_NEG_NAN_RESULT 1
constexpr float TT_TARGET_BH_BF16_RAW_NEG_NAN_CONSTANT = 0.0000000000000000e+00f;
#define TT_TARGET_BH_BF16_RAW_POS_NAN_RESULT 1
constexpr float TT_TARGET_BH_BF16_RAW_POS_NAN_CONSTANT = 0.0000000000000000e+00f;
#define TT_TARGET_BH_BF16_SPECIAL_COMPARE_COUNT 2
#define TT_SPECIAL_POS_INF 3
#define TT_SPECIAL_NEG_INF 3

#include "ckernel_sfpu_bf16_domain_prepare.inc"
#include "ckernel_sfpu_bf16_domain_action_coordinate.inc"
#include "ckernel_sfpu_bf16_raw_class_policy.inc"
#include "ckernel_sfpu_bf16_target_special_policy.inc"
#include "ckernel_sfpu_bf16_domain_symmetric_constant.inc"
#include "ckernel_sfpu_bf16_domain_finalize.inc"
#include "ckernel_sfpu_bf16_encoded_domain_finalize.inc"
#include "ckernel_sfpu_bf16_asymptotic_exp.inc"
#include "ckernel_sfpu_bf16_asymptotic_factor.inc"
#include "ckernel_sfpu_bf16_polynomial_dual_tile.inc"
inline void tile() { piecewise_generic_lut_specialized_N_dual<POLY_DEGREE, NUM_SEGMENTS, LUT_SIZE>(LUT_DATA); }

#include "ckernel_sfpu_bf16_gradient_finalize.inc"
}  // namespace ckernel::sfpu::ErfBwBf16Config_detail
namespace ckernel::sfpu::ErfBwBf16Config_initialization {
namespace sfpi = ::ckernel::sfpu::ErfBwBf16Config_detail;
inline void init() {}
}  // namespace ckernel::sfpu::ErfBwBf16Config_initialization
namespace ckernel::sfpu::ErfBwBf16Config_execution {
namespace sfpi = ::ckernel::sfpu::ErfBwBf16Config_detail;
#include "ckernel_sfpu_bf16_gradient_finalization_owner.inc"
}  // namespace ckernel::sfpu::ErfBwBf16Config_execution
namespace ckernel::sfpu {
struct ErfBwBf16Config {
    static constexpr bool needs_gradient = !ErfBwBf16Config_execution::gradient_finalized_in_evaluator;
    static inline void init() { ErfBwBf16Config_initialization::init(); }
    static inline void tile() { ErfBwBf16Config_detail::tile(); }
    struct Gradient {
        static inline void tile() { ErfBwBf16Config_detail::fuse_grad_mul(); }
    };
};
}  // namespace ckernel::sfpu
#pragma pop_macro("TT_TARGET_BH_BF16_SPECIAL_COMPARE_COUNT")
#pragma pop_macro("TT_TARGET_BH_BF16_RAW_POS_NAN_RESULT")
#pragma pop_macro("TT_TARGET_BH_BF16_RAW_NEG_NAN_RESULT")
#pragma pop_macro("TT_SPECIAL_POS_INF")
#pragma pop_macro("TT_SPECIAL_NEG_INF")
#pragma pop_macro("TT_ASYMPTOTIC_IF")
#pragma pop_macro("TT_ASYMPTOTIC_END_IF")
#include "ckernel_sfpu_bf16_config_tile.h"

namespace ckernel::sfpu {

template <int ITERATIONS = 8>
inline void calculate_erf_bw_bf16() {
    ckernel::sfpu::bf16::calculate_config_tile<ckernel::sfpu::ErfBwBf16Config, ITERATIONS>();
}
inline void init_erf_bw_bf16() { ckernel::sfpu::bf16::init_config_tile<ckernel::sfpu::ErfBwBf16Config>(); }
template <int ITERATIONS = 32>
inline void calculate_erf_bw_gradient_bf16() {
    ckernel::sfpu::bf16::calculate_config_tile<ckernel::sfpu::ErfBwBf16Config::Gradient, ITERATIONS>();
}

}  // namespace ckernel::sfpu
