// SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <cstdint>
#include <limits>

#include "cmath_common.h"
#include "sfpi.h"

// Generated by tt-polynomial-fitter from activations/products/situ_glu.json; do not edit.
//
//   result = gate_leaf(gate) * up_leaf(up)
//   gate_leaf(x) = 4*tanh(x/4)/(1+exp(-x))
//   up_leaf(x) = 25*tanh(x/25)
//
// A scaled odd-ratio leaf s * t * P(t^2) / Q(t^2), t = x / s, holds |x| at s * 4.875; P and Q are
// data/coefficients/situ_glu_n2d2_s1_uniform_rminimax_relative_block-tanh_ratio.csv:
//   P = [1.0f, 0.1031409502029419f, 0.000690968707203865f]
//   Q = [1.0f, 0.436279296875f, 0.013031005859375f]
//
// The logistic factor 1 / (1 + e^-x) is sel / (1 + e^-|x|), with sel = 1 for x >= 0 and e^-|x| below.
//
// The leaves' magnitudes multiply unscaled, and one reciprocal divides by the product of their denominators.
// A NaN input gives NaN; a result below the smallest normal float is 0.

namespace ckernel::sfpu {

// The body is fitted for these values; another config needs its own fit.
struct SituGluConfigKimi {
    static constexpr float beta_gate = 4.0f;
    static constexpr float beta_up = 25.0f;
};

// One Newton step: the denominator is a positive normal value.
sfpi_inline sfpi::vFloat _situ_glu_reciprocal_(const sfpi::vFloat a) {
    sfpi::vFloat y = sfpi::approx_recip(a);
    sfpi::vFloat t = a * y - 2.0f;
    return y * -t - 0.0f;
}

template <bool is_fp32_dest_acc_en, int ITERATIONS = 8, class Config = SituGluConfigKimi>
inline void calculate_situ_glu(
    const std::uint32_t gate_tile_idx, const std::uint32_t up_tile_idx, const std::uint32_t out_tile_idx) {
    static_assert(
        Config::beta_gate == 4.0f && Config::beta_up == 25.0f,
        "calculate_situ_glu is fitted for beta_gate = 4, beta_up = 25");
    using namespace sfpi;
    constexpr std::uint32_t dst_tile_size = 32;  // 32 rows per tile in SFPU addressing
#pragma GCC unroll 8
    for (int d = 0; d < ITERATIONS; d++) {
        vFloat gate_x = dst_reg[gate_tile_idx * dst_tile_size];
        vFloat gate_a = sfpi::setsgn(gate_x, 0);
        auto [gate_c, gate_m] = sfpi::min_max(gate_a, vFloat(19.5f));
        vFloat gate_t = gate_c * 0.25f;
        vFloat gate_s = gate_t * gate_t;
        vFloat num = sfpi::copysgn(gate_c, gate_x) * 16777216.0f;
        vFloat up_x = dst_reg[up_tile_idx * dst_tile_size];
        auto [up_c, up_m] = sfpi::min_max(sfpi::setsgn(up_x, 0), vFloat(121.875f));
        vFloat up_t = up_c * vConstFloatPrgm0;
        vFloat up_s = up_t * up_t;
        // 0, or NaN where an input is NaN: -(|x0| + |x1|) is otherwise at most 0, and SFPSWAP ranks the
        // multiply-add's positive NaN above 0.
        vFloat nan_z = sfpi::max(gate_m * -1.0f - up_m, 0.0f);
        num = num * sfpi::copysgn(up_c, up_x);
        vFloat pk = 0.000690968707203865f;
        vFloat pc = 0.1031409502029419f;
        vFloat p0 = gate_s * pk + pc;
        vFloat p1 = up_s * pk + pc;
        p0 = p0 * gate_s + 1.0f;
        p1 = p1 * up_s + 1.0f;
        num = num * p0;
        num = num * p1;
        vFloat qk = 0.013031005859375f;
        vFloat qc = 0.436279296875f;
        vFloat q0 = gate_s * qk + qc;
        vFloat q1 = up_s * qk + qc;
        q0 = q0 * gate_s + 1.0f;
        q1 = q1 * up_s + 1.0f;
        vFloat den = q0 * q1;
        vFloat w_c = gate_a * vConstFloatPrgm1 + 127.0f;
        vFloat w_z = sfpi::max(w_c, 0.5f);
        vInt w_m = sfpi::exman(w_z, sfpi::MantissaMode::ImplicitOne);
        vInt w_s = sfpi::shft(w_m, sfpi::exexp(w_z), sfpi::ShiftMode::Logical);
        vFloat w_y = sfpi::as<vFloat>(w_s);
        vMag w_q = sfpi::exman(w_y);
        vFloat w_f = sfpi::convert<vFloat>(w_q, RoundMode::Nearest);
        vFloat w = w_f * vConstFloatPrgm2 + 3.235038207097512e-15f;
        w = w * w_f + 8.286510677635306e-08f;
        w = w * w_f + 1.0f;
        w = sfpi::setexp(w, sfpi::exexp(w_y, ExponentMode::Biased));
        den = den * (w + 1.0f);
        v_if(dst_reg[gate_tile_idx * dst_tile_size] < 0.0f) { num = num * w; }
        v_endif;
        vFloat out = num * _situ_glu_reciprocal_(den) + nan_z;
        // out is 2^24 times the result: round it to BF16 while it is normal, then scale back.
        if constexpr (!is_fp32_dest_acc_en) {
            out = sfpi::convert<sfpi::vFloat16b>(out, sfpi::RoundMode::Nearest);
            out = out * 5.960464477539063e-08f;
        } else {
            vFloat lowered = out * 5.960464477539063e-08f;
            // Below the smallest normal the scaled result flushes; where the pack would round it
            // to the smallest normal, keep that.
            vFloat magnitude = sfpi::setsgn(out, 0);
            v_if(magnitude >= 1.9644485432749806e-31f && magnitude < 1.9721522630525295e-31f) {
                lowered = sfpi::copysgn(vFloat(1.1754943508222875e-38f), out);
            }
            v_endif;
            out = lowered;
        }
        dst_reg[out_tile_idx * dst_tile_size] = out;
        dst_reg++;
    }
}

// Within the state tanh_init<false, false> writes: 3 of its programmable constants.
inline void situ_glu_init() {
    math::reset_counters(p_setrwc::SET_ABD_F);
    sfpi::vConstFloatPrgm0 = 0.03999999910593033f;
    sfpi::vConstFloatPrgm1 = -1.4426950216293335f;
    sfpi::vConstFloatPrgm2 = 1.305414094153441e-22f;
}

}  // namespace ckernel::sfpu
