MATMUL_SINGLE_CORE_EXAMPLE_SRC = $(TT_METAL_HOME)/tt_metal/programming_examples/matmul_single_core/matmul_single_core.cpp

MATMUL_SINGLE_CORE_EXAMPLES_DEPS = $(PROGRAMMING_EXAMPLES_OBJDIR)/matmul_single_core.d

-include $(MATMUL_SINGLE_CORE_EXAMPLES_DEPS)

.PRECIOUS: $(PROGRAMMING_EXAMPLES_TESTDIR)/matmul_single_core
$(PROGRAMMING_EXAMPLES_TESTDIR)/matmul_single_core: $(PROGRAMMING_EXAMPLES_OBJDIR)/matmul_single_core.o $(TT_METAL_LIB)
	@mkdir -p $(@D)
	$(CXX) $(CFLAGS) $(CXXFLAGS) $(PROGRAMMING_EXAMPLES_INCLUDES) -o $@ $^ $(LDFLAGS) $(PROGRAMMING_EXAMPLES_LDFLAGS)

.PRECIOUS: $(PROGRAMMING_EXAMPLES_OBJDIR)/matmul_single_core.o
$(PROGRAMMING_EXAMPLES_OBJDIR)/matmul_single_core.o: $(MATMUL_SINGLE_CORE_EXAMPLE_SRC)
	@mkdir -p $(@D)
	$(CXX) $(CFLAGS) $(CXXFLAGS) $(PROGRAMMING_EXAMPLES_INCLUDES) -c -o $@ $<
