// SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0
// Version: FFN1.3.0

/*******************************************************************************
 * Header file for register addresses and fields
 *
 * This file was AUTO-GENERATED by this script:
 *       create_reg_c_header.py   (r2025-06-03)
 * ... from this input file:
 *       overlay.rdl
 * ... using this as the target address space:
 *       tt_t6l1_slv
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

#ifndef TT_T6L1_SLV_REG_H
#define TT_T6L1_SLV_REG_H



//==============================================================================
// Addresses for Address Map: tt_t6l1_slv
//==============================================================================


#define TT_T6L1_SLV_REG_MAP_BASE_ADDR  (0x03800000)
#define TT_T6L1_SLV_REG_MAP_SIZE       (0x00400000)



//==============================================================================
// Memory: t6l1_mem_port
//==============================================================================

#define TT_T6L1_SLV_T6L1_MEM_PORT_MEM_BASE_ADDR  (0x03800000)
#define TT_T6L1_SLV_T6L1_MEM_PORT_MEM_SIZE       (0x00400000)



#ifndef __ASSEMBLER__

#include <stdint.h>

//==============================================================================
// Structs for Address Map: tt_t6l1_slv
//==============================================================================


#endif // __ASSEMBLER__
#endif
