# SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
"""One case per distinct ttnn.bringup.dispatch call a model makes (bringup-fork-tests skill). Append only; never edit
or loosen another model's case. Shapes are per device, exactly as captured (fork_calls.json)."""

CASES = [
    {
        # MiMo-V2.6 routed experts, EP=4 on a 1x4 mesh: dispatch groups are the 4 columns, each a single chip.
        "id": "mimo_v2_6_d_p-1x4-dgs1-s5120-h4096-e256-k8",
        "model": "mimo_v2_6_d_p",
        "task": "O.1",
        "sig": "33e8891784",
        "mesh": [1, 4],
        "device_params": {"fabric_config": "FABRIC_2D", "l1_small_size": 24576},
        "seq_len_per_chip": 5120,
        "emb_dim": 4096,
        "num_routed_experts": 256,
        "num_experts_per_tok": 8,
        "experts_per_chip": 64,
        "dispatch_group_size": 1,
        "metadata_len": 3,
        "max_dispatch_buffer_token_size": 42976,
        "cluster_axis": 0,
        "num_links": 1,
        "topology": "Linear",
        "fp8_output": False,
        "num_workers_per_sender": 2,
        "subdevice_id": None,
        # input [1, S, H], indices [1, S, K], offsets [1, E], table [1, E + 1]; all DRAM interleaved
        "input": {"dtype": "BFLOAT16", "layout": "TILE"},
        "indices": {"dtype": "UINT16", "layout": "ROW_MAJOR"},
        "offsets": {"dtype": "UINT32", "layout": "ROW_MAJOR"},
        "table": {"dtype": "INT32", "layout": "ROW_MAJOR"},
        "seed": 0,
        "exact": True,
    },
    {
        # Gemma-4 A4B routed experts, EP=4 on a 1x4 mesh: dispatch groups are the 4 columns, each a single chip.
        "id": "gemma4_a4b_d_p-1x4-dgs1-s5120-h2816-e128-k8",
        "model": "gemma4_a4b_d_p",
        "task": "O.1",
        "sig": "61d407d901",
        "mesh": [1, 4],
        "device_params": {"fabric_config": "FABRIC_2D", "l1_small_size": 24576},
        "seq_len_per_chip": 5120,
        "emb_dim": 2816,
        "num_routed_experts": 128,
        "num_experts_per_tok": 8,
        "experts_per_chip": 32,
        "dispatch_group_size": 1,
        "metadata_len": 3,
        "max_dispatch_buffer_token_size": 41952,
        "cluster_axis": 0,
        "num_links": 1,
        "topology": "Linear",
        "fp8_output": False,
        "num_workers_per_sender": 2,
        "subdevice_id": None,
        # input [1, 5120, 2816], indices [1, 5120, 8], offsets [1, 128], table [1, 129]; all DRAM interleaved
        "input": {"dtype": "BFLOAT16", "layout": "TILE"},
        "indices": {"dtype": "UINT16", "layout": "ROW_MAJOR"},
        "offsets": {"dtype": "UINT32", "layout": "ROW_MAJOR"},
        "table": {"dtype": "INT32", "layout": "ROW_MAJOR"},
        "seed": 0,
        "exact": True,
    },
    {
        # ERNIE-4.5 (21B-A3B) routed experts, EP=4 on a 1x4 mesh: dispatch groups are the 4 columns, each a single
        # chip. The model opens its mesh with FABRIC_1D_RING (models/demos/ernie45_d_p/tt/common.py DEVICE_PARAMS).
        "id": "ernie45_d_p-1x4-dgs1-s5120-h2560-e64-k6",
        "model": "ernie45_d_p",
        "task": "O.1",
        "sig": "2d214aafb9",
        "mesh": [1, 4],
        "device_params": {"fabric_config": "FABRIC_1D_RING", "l1_small_size": 24576},
        "seq_len_per_chip": 5120,
        "emb_dim": 2560,
        "num_routed_experts": 64,
        "num_experts_per_tok": 6,
        "experts_per_chip": 16,
        "dispatch_group_size": 1,
        "metadata_len": 3,
        "max_dispatch_buffer_token_size": 31200,
        "cluster_axis": 0,
        "num_links": 1,
        "topology": "Linear",
        "fp8_output": False,
        "num_workers_per_sender": 2,
        "subdevice_id": None,
        # input [1, 5120, 2560], indices [1, 5120, 6], offsets [1, 64], table [1, 65]; all DRAM interleaved
        "input": {"dtype": "BFLOAT16", "layout": "TILE"},
        "indices": {"dtype": "UINT16", "layout": "ROW_MAJOR"},
        "offsets": {"dtype": "UINT32", "layout": "ROW_MAJOR"},
        "table": {"dtype": "INT32", "layout": "ROW_MAJOR"},
        "seed": 0,
        "exact": True,
    },
    {
        # MiMo-V2.6 routed experts on a 2x2 mesh: dispatch groups are the 2 columns of 2 chips each (cluster_axis 0,
        # fabric on, Linear); column c holds experts 128c .. 128c + 127, chip (r, c) 128c + 64r .. + 63.
        "id": "mimo_v2_6_d_p_2x2-2x2-dgs2-s2560-h4096-e256-k8",
        "model": "mimo_v2_6_d_p_2x2",
        "task": "O.1",
        "sig": "6920429db4",
        "mesh": [2, 2],
        "device_params": {"fabric_config": "FABRIC_2D", "l1_small_size": 24576},
        "seq_len_per_chip": 2560,
        "emb_dim": 4096,
        "num_routed_experts": 256,
        "num_experts_per_tok": 8,
        "experts_per_chip": 64,
        "dispatch_group_size": 2,
        "metadata_len": 3,
        "max_dispatch_buffer_token_size": 42976,
        "cluster_axis": 0,
        "num_links": 1,
        "topology": "Linear",
        "fp8_output": False,
        "num_workers_per_sender": 2,
        "subdevice_id": None,
        # input [1, 2560, 4096], indices [1, 2560, 8], offsets [1, 256], table [1, 257]; all DRAM interleaved
        "input": {"dtype": "BFLOAT16", "layout": "TILE"},
        "indices": {"dtype": "UINT16", "layout": "ROW_MAJOR"},
        "offsets": {"dtype": "UINT32", "layout": "ROW_MAJOR"},
        "table": {"dtype": "INT32", "layout": "ROW_MAJOR"},
        "seed": 0,
        "exact": True,
    },
    {
        # GLM-5.3-Flash routed experts on a 2x2 mesh: dispatch groups are the 2 columns of 2 chips each (cluster_axis 0,
        # fabric on, Linear); column c holds experts 144c .. 144c + 143, chip (r, c) 144c + 72r .. + 71.
        "id": "glm53_flash_d_p-2x2-dgs2-s2560-h4096-e288-k8",
        "model": "glm53_flash_d_p",
        "task": "O.1",
        "sig": "a278b0297c",
        "mesh": [2, 2],
        "device_params": {"fabric_config": "FABRIC_2D", "l1_small_size": 24576},
        "seq_len_per_chip": 2560,
        "emb_dim": 4096,
        "num_routed_experts": 288,
        "num_experts_per_tok": 8,
        "experts_per_chip": 72,
        "dispatch_group_size": 2,
        "metadata_len": 3,
        "max_dispatch_buffer_token_size": 43232,
        "cluster_axis": 0,
        "num_links": 1,
        "topology": "Linear",
        "fp8_output": False,
        "num_workers_per_sender": 2,
        "subdevice_id": None,
        # input [1, 2560, 4096], indices [1, 2560, 8], offsets [1, 288], table [1, 289]; all DRAM interleaved
        "input": {"dtype": "BFLOAT16", "layout": "TILE"},
        "indices": {"dtype": "UINT16", "layout": "ROW_MAJOR"},
        "offsets": {"dtype": "UINT32", "layout": "ROW_MAJOR"},
        "table": {"dtype": "INT32", "layout": "ROW_MAJOR"},
        "seed": 0,
        "exact": True,
    },
    {
        # Hy4 (preview) routed experts on a 2x2 mesh: dispatch groups are the 2 columns of 2 chips each (cluster_axis 0,
        # fabric on, Linear); column c holds experts 128c .. 128c + 127, chip (r, c) 128c + 64r .. + 63.
        "id": "hy4_preview_d_p-2x2-dgs2-s2560-h6144-e256-k8",
        "model": "hy4_preview_d_p",
        "task": "O.1",
        "sig": "8865b74785",
        "mesh": [2, 2],
        "device_params": {"fabric_config": "FABRIC_2D", "l1_small_size": 24576},
        "seq_len_per_chip": 2560,
        "emb_dim": 6144,
        "num_routed_experts": 256,
        "num_experts_per_tok": 8,
        "experts_per_chip": 64,
        "dispatch_group_size": 2,
        "metadata_len": 3,
        "max_dispatch_buffer_token_size": 42976,
        "cluster_axis": 0,
        "num_links": 1,
        "topology": "Linear",
        "fp8_output": False,
        "num_workers_per_sender": 2,
        "subdevice_id": None,
        # input [1, 2560, 6144], indices [1, 2560, 8], offsets [1, 256], table [1, 257]; all DRAM interleaved
        "input": {"dtype": "BFLOAT16", "layout": "TILE"},
        "indices": {"dtype": "UINT16", "layout": "ROW_MAJOR"},
        "offsets": {"dtype": "UINT32", "layout": "ROW_MAJOR"},
        "table": {"dtype": "INT32", "layout": "ROW_MAJOR"},
        "seed": 0,
        "exact": True,
    },
    {
        # Xing4.0 routed experts on the 4x2 SP x TP mesh: dispatch up / down each mesh column (cluster_axis 0, a
        # dispatch group of the column's 4 chips), 1280 tokens per chip, 64 experts (8 per chip, 32 per column), top-4.
        # Captured per device: input [1, 1280, 3584] bf16 TILE, indices [1, 1280, 4] uint16 RM, offsets [1, 64] uint32
        # RM, table [1, 65] int32 RM, all DRAM interleaved; ladder rung last (5120-token chunk).
        "id": "xing40_a4b_d_p-4x2-dgs4-s1280-h3584-e64-k4",
        "model": "xing40_a4b_d_p",
        "task": "O.1",
        "sig": "da3c0f76df",
        "mesh": [4, 2],
        "device_params": {"fabric_config": "FABRIC_2D", "l1_small_size": 24576},
        "seq_len_per_chip": 1280,
        "emb_dim": 3584,
        "num_routed_experts": 64,
        "num_experts_per_tok": 4,
        "experts_per_chip": 8,
        "dispatch_group_size": 4,
        "metadata_len": 3,
        "max_dispatch_buffer_token_size": 20704,
        "cluster_axis": 0,
        "num_links": 1,
        "topology": "Linear",
        "fp8_output": False,
        "num_workers_per_sender": 2,
        "subdevice_id": None,
        "input": {"dtype": "BFLOAT16", "layout": "TILE"},
        "indices": {"dtype": "UINT16", "layout": "ROW_MAJOR"},
        "offsets": {"dtype": "UINT32", "layout": "ROW_MAJOR"},
        "table": {"dtype": "INT32", "layout": "ROW_MAJOR"},
        "seed": 0,
        "exact": True,
    },
]
