superpods {
  superpod {
    superpod_id: 1
    superpod_type: "n300_t3k_superpod"
  }
  superpod {
    superpod_id: 2
    superpod_type: "n300_t3k_superpod"
  }
  superpod {
    superpod_id: 3
    superpod_type: "n300_t3k_superpod"
  }
  superpod {
    superpod_id: 4
    superpod_type: "n300_t3k_superpod"
  }
}
port_type_connections {
  key: "QSFP"
  value {
    connections {
      port_a {
        superpod_id: 1
        pod_id: 1
        tray_id: 2
        port_id: 1
      }
      port_b {
        superpod_id: 3
        pod_id: 1
        tray_id: 2
        port_id: 1
      }
    }
    connections {
      port_a {
        superpod_id: 1
        pod_id: 3
        tray_id: 1
        port_id: 2
      }
      port_b {
        superpod_id: 2
        pod_id: 2
        tray_id: 1
        port_id: 2
      }
    }
    connections {
      port_a {
        superpod_id: 1
        pod_id: 4
        tray_id: 4
        port_id: 2
      }
      port_b {
        superpod_id: 4
        pod_id: 1
        tray_id: 2
        port_id: 1
      }
    }
    connections {
      port_a {
        superpod_id: 3
        pod_id: 3
        tray_id: 1
        port_id: 2
      }
      port_b {
        superpod_id: 4
        pod_id: 2
        tray_id: 1
        port_id: 2
      }
    }
    connections {
      port_a {
        superpod_id: 3
        pod_id: 4
        tray_id: 4
        port_id: 2
      }
      port_b {
        superpod_id: 2
        pod_id: 1
        tray_id: 2
        port_id: 1
      }
    }
    connections {
      port_a {
        superpod_id: 2
        pod_id: 4
        tray_id: 4
        port_id: 2
      }
      port_b {
        superpod_id: 4
        pod_id: 4
        tray_id: 4
        port_id: 2
      }
    }
  }
}
