boards {
  board { tray_id: 1 board_type: "UBB" }
  board { tray_id: 2 board_type: "UBB" }
  board { tray_id: 3 board_type: "UBB" }
  board { tray_id: 4 board_type: "UBB" }
}
port_type_connections {
  key: "LINKING_BOARD_1"
  value {
    connections { p_a { tray_id: 1 port_id: 1 } p_b { tray_id: 2 port_id: 1 } }
    connections { p_a { tray_id: 1 port_id: 2 } p_b { tray_id: 2 port_id: 2 } }
    connections { p_a { tray_id: 3 port_id: 1 } p_b { tray_id: 4 port_id: 1 } }
    connections { p_a { tray_id: 3 port_id: 2 } p_b { tray_id: 4 port_id: 2 } }
  }
}
port_type_connections {
  key: "LINKING_BOARD_2"
  value {
    connections { p_a { tray_id: 1 port_id: 1 } p_b { tray_id: 2 port_id: 1 } }
    connections { p_a { tray_id: 1 port_id: 2 } p_b { tray_id: 2 port_id: 2 } }
    connections { p_a { tray_id: 3 port_id: 1 } p_b { tray_id: 4 port_id: 1 } }
    connections { p_a { tray_id: 3 port_id: 2 } p_b { tray_id: 4 port_id: 2 } }
  }
}
port_type_connections {
  key: "LINKING_BOARD_3"
  value {
    connections { p_a { tray_id: 1 port_id: 1 } p_b { tray_id: 3 port_id: 1 } }
    connections { p_a { tray_id: 1 port_id: 2 } p_b { tray_id: 3 port_id: 2 } }
    connections { p_a { tray_id: 2 port_id: 1 } p_b { tray_id: 4 port_id: 1 } }
    connections { p_a { tray_id: 2 port_id: 2 } p_b { tray_id: 4 port_id: 2 } }
  }
}
port_type_connections {
  key: "QSFP"
  value {
    connections { p_a { tray_id: 1 port_id: 2 } p_b { tray_id: 3 port_id: 2 } }
    connections { p_a { tray_id: 1 port_id: 1 } p_b { tray_id: 3 port_id: 1 } }
    connections { p_a { tray_id: 2 port_id: 1 } p_b { tray_id: 4 port_id: 1 } }
    connections { p_a { tray_id: 2 port_id: 2 } p_b { tray_id: 4 port_id: 2 } }
  }
}
