# SPDX-FileCopyrightText: Copyright (c) 2026 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

"""TTNN implementation for the exact Qwen3.8-Flash-Next text model.

The sibling :mod:`..tt` package is the frozen CPU golden.  Device code lives in
this package so that TTNN work cannot accidentally reformat or mutate the
golden implementation while the bring-up is in progress.
"""

from .contracts import Qwen38MeshContract, TensorPlacement
from .bf4 import (
    BF4CacheIdentity,
    Qwen38BF4Cache,
    Qwen38BF4Streamer,
    packed_bf4_bytes_per_device,
    packed_bf4_model_bytes_per_device,
    qualify_live_bf4_ring,
)
from .moe import (
    Qwen38TTNNMoE,
    Qwen38TTNNMoEResult,
    Qwen38TTNNMoESyncPolicy,
    Qwen38TTNNMoEWeights,
    Qwen38TTNNRouting,
)
from .mtp import (
    MTP_INPUT_TENSOR_SPECS,
    Qwen38TTNNMTPInput,
    Qwen38TTNNMTPInputCleanupError,
    Qwen38TTNNMTPInputWeights,
    validate_mtp_input_static_contract,
)
from .gr import Qwen38TTNNGatedResidual, Qwen38TTNNGatedResidualState, Qwen38TTNNGatedResidualWeights
from .gdn import Qwen38TTNNGDN, Qwen38TTNNGDNResult, Qwen38TTNNGDNSnapshot, Qwen38TTNNGDNState, Qwen38TTNNGDNWeights
from .final_mixer import Qwen38TTNNFinalMixer, Qwen38TTNNFinalMixerWeights
from .embedding import (
    Qwen38GreedyCandidates,
    Qwen38IOCache,
    Qwen38IOCacheIdentity,
    Qwen38ShardedLogits,
    Qwen38TTNNEmbeddingSyncPolicy,
    Qwen38TTNNLMHead,
    Qwen38TTNNModelIO,
    Qwen38TTNNModelIOWeights,
    Qwen38TTNNTokenEmbedding,
    Qwen38ValidatedTokens,
    validate_terminal_architecture,
)
from .ple import (
    Qwen38TTNNPLE,
    Qwen38TTNNPLEPreparedInput,
    Qwen38TTNNPLEResult,
    Qwen38TTNNPLESnapshot,
    Qwen38TTNNPLEState,
    Qwen38TTNNPLEWeights,
)
from .qsa import (
    Qwen38QSASelectionGeometry,
    Qwen38TTNNQSA,
    Qwen38TTNNQSAResult,
    Qwen38TTNNQSASelection,
    Qwen38TTNNQSAState,
    Qwen38TTNNQSAWeights,
    qsa_selection_geometry,
)
from .layer import (
    Qwen38TTNNDecoderLayer,
    Qwen38TTNNDecoderLayerAux,
    Qwen38TTNNDecoderLayerResult,
    Qwen38TTNNDecoderLayerSnapshot,
    Qwen38TTNNDecoderLayerState,
    Qwen38TTNNLayerCleanupError,
    Qwen38TTNNLayerNamespace,
    Qwen38TTNNLayerType,
    validate_layer_static_contract,
)
from .model import (
    Qwen38TTNNCleanupError,
    Qwen38TTNNGreedyStep,
    Qwen38TTNNModelPoisonedError,
    Qwen38TTNNPreparedDecodeInputs,
    Qwen38TTNNRoPE,
    Qwen38TTNNRoPEInputs,
    Qwen38TTNNTextModel,
    Qwen38TTNNTextModelOutput,
    Qwen38TTNNTextModelSnapshot,
    Qwen38TTNNTextModelState,
    validate_model_static_contract,
)
from .builder import (
    BACKBONE_PLAN,
    TARGET_OBJECT_GRAPH,
    Qwen38BuildProvenance,
    Qwen38CacheRoots,
    Qwen38LiveBuildIdentity,
    Qwen38TTNNBuilder,
    Qwen38TTNNBuiltTarget,
    Qwen38TTNNMTPComponents,
    Qwen38TTNNTargetComponents,
    validate_builder_constructor_contract,
    validate_builder_static_contract,
)
from .hybrid_decode import (
    Qwen38HybridCacheMismatchError,
    Qwen38HybridCachePolicy,
    Qwen38HybridCleanupError,
    Qwen38HybridCleanupFailure,
    Qwen38HybridConstructionError,
    Qwen38HybridDecodeError,
    Qwen38HybridDecodePoisonedError,
    Qwen38HybridFactoryError,
    Qwen38HybridFallbackReason,
    Qwen38HybridMode,
    Qwen38HybridModeCapabilities,
    Qwen38HybridSessionIdentity,
    Qwen38HybridSessionStatus,
    Qwen38HybridStep,
    Qwen38HybridStopReason,
    Qwen38HybridTiming,
    Qwen38HybridTimingPhase,
    Qwen38HybridToken,
    Qwen38HybridTokenSource,
    Qwen38TTNNHybridDecodeSession,
    validate_hybrid_decode_static_contract,
)

__all__ = [
    "Qwen38MeshContract",
    "TensorPlacement",
    "BF4CacheIdentity",
    "Qwen38BF4Cache",
    "Qwen38BF4Streamer",
    "packed_bf4_bytes_per_device",
    "packed_bf4_model_bytes_per_device",
    "qualify_live_bf4_ring",
    "Qwen38TTNNMoE",
    "Qwen38TTNNMoEResult",
    "Qwen38TTNNMoESyncPolicy",
    "Qwen38TTNNMoEWeights",
    "Qwen38TTNNRouting",
    "MTP_INPUT_TENSOR_SPECS",
    "Qwen38TTNNMTPInput",
    "Qwen38TTNNMTPInputCleanupError",
    "Qwen38TTNNMTPInputWeights",
    "validate_mtp_input_static_contract",
    "Qwen38TTNNGatedResidual",
    "Qwen38TTNNGatedResidualState",
    "Qwen38TTNNGatedResidualWeights",
    "Qwen38TTNNGDN",
    "Qwen38TTNNGDNResult",
    "Qwen38TTNNGDNSnapshot",
    "Qwen38TTNNGDNState",
    "Qwen38TTNNGDNWeights",
    "Qwen38TTNNFinalMixer",
    "Qwen38TTNNFinalMixerWeights",
    "Qwen38GreedyCandidates",
    "Qwen38IOCache",
    "Qwen38IOCacheIdentity",
    "Qwen38ShardedLogits",
    "Qwen38TTNNEmbeddingSyncPolicy",
    "Qwen38TTNNLMHead",
    "Qwen38TTNNModelIO",
    "Qwen38TTNNModelIOWeights",
    "Qwen38TTNNTokenEmbedding",
    "Qwen38ValidatedTokens",
    "validate_terminal_architecture",
    "Qwen38TTNNPLE",
    "Qwen38TTNNPLEPreparedInput",
    "Qwen38TTNNPLEResult",
    "Qwen38TTNNPLESnapshot",
    "Qwen38TTNNPLEState",
    "Qwen38TTNNPLEWeights",
    "Qwen38QSASelectionGeometry",
    "Qwen38TTNNQSA",
    "Qwen38TTNNQSAResult",
    "Qwen38TTNNQSASelection",
    "Qwen38TTNNQSAState",
    "Qwen38TTNNQSAWeights",
    "qsa_selection_geometry",
    "Qwen38TTNNDecoderLayer",
    "Qwen38TTNNDecoderLayerAux",
    "Qwen38TTNNDecoderLayerResult",
    "Qwen38TTNNDecoderLayerSnapshot",
    "Qwen38TTNNDecoderLayerState",
    "Qwen38TTNNLayerCleanupError",
    "Qwen38TTNNLayerNamespace",
    "Qwen38TTNNLayerType",
    "validate_layer_static_contract",
    "Qwen38TTNNCleanupError",
    "Qwen38TTNNGreedyStep",
    "Qwen38TTNNModelPoisonedError",
    "Qwen38TTNNPreparedDecodeInputs",
    "Qwen38TTNNRoPE",
    "Qwen38TTNNRoPEInputs",
    "Qwen38TTNNTextModel",
    "Qwen38TTNNTextModelOutput",
    "Qwen38TTNNTextModelSnapshot",
    "Qwen38TTNNTextModelState",
    "validate_model_static_contract",
    "BACKBONE_PLAN",
    "TARGET_OBJECT_GRAPH",
    "Qwen38BuildProvenance",
    "Qwen38CacheRoots",
    "Qwen38LiveBuildIdentity",
    "Qwen38TTNNBuilder",
    "Qwen38TTNNBuiltTarget",
    "Qwen38TTNNMTPComponents",
    "Qwen38TTNNTargetComponents",
    "validate_builder_constructor_contract",
    "validate_builder_static_contract",
    "Qwen38HybridCacheMismatchError",
    "Qwen38HybridCachePolicy",
    "Qwen38HybridCleanupError",
    "Qwen38HybridCleanupFailure",
    "Qwen38HybridConstructionError",
    "Qwen38HybridDecodeError",
    "Qwen38HybridDecodePoisonedError",
    "Qwen38HybridFactoryError",
    "Qwen38HybridFallbackReason",
    "Qwen38HybridMode",
    "Qwen38HybridModeCapabilities",
    "Qwen38HybridSessionIdentity",
    "Qwen38HybridSessionStatus",
    "Qwen38HybridStep",
    "Qwen38HybridStopReason",
    "Qwen38HybridTiming",
    "Qwen38HybridTimingPhase",
    "Qwen38HybridToken",
    "Qwen38HybridTokenSource",
    "Qwen38TTNNHybridDecodeSession",
    "validate_hybrid_decode_static_contract",
]
