# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0

"""Per-perf-test CSV schema catalog.

One entry per perf test: its reviewed set of CSV columns, a ``version`` bumped
when those columns change, an ``aliases`` map (old -> new) for a column
renamed in that test, and a ``test_name_aliases`` map that always includes the
current test name mapped to itself. Previous names map to the current name;
renaming a test in place requires updating this map. The gate in
test_perf_header_gate.py re-derives each test's columns and fails on any drift
from this catalog.
"""


PERF_TEST_SCHEMAS = {
    "perf_bcast": {
        "version": 2,
        "columns": [
            "acc_to_dest",
            "block_ct_dim",
            "block_rt_dim",
            "broadcast_type",
            "dest_acc",
            "disable_src_zero_flag",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "partial_a",
            "partial_b",
            "partial_face_math",
            "partial_face_pack",
            "reuse_dest_type",
            "stochastic_rounding",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_bcast": "perf_bcast"},
    },
    "perf_dense_pack_untilize": {
        "version": 2,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "in0_c_dim",
            "in0_r_dim",
            "in1_c_dim",
            "in1_r_dim",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_dense_pack_untilize": "perf_dense_pack_untilize"},
    },
    "perf_eltwise_bcast_col_custom": {
        "version": 3,
        "columns": [
            "broadcast_type",
            "ct_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_bcast_col_custom": "perf_eltwise_bcast_col_custom"
        },
    },
    "perf_eltwise_binary": {
        "version": 4,
        "columns": [
            "broadcast_type",
            "dest_acc",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary": "perf_eltwise_binary",
            "perf_eltwise_binary_fpu": "perf_eltwise_binary",
        },
    },
    "perf_eltwise_binary_sfpu": {
        "version": 3,
        "columns": [
            "approx_mode",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_eltwise_binary_sfpu": "perf_eltwise_binary_sfpu"},
    },
    "perf_eltwise_unary_datacopy": {
        "version": 2,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dst_index",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "loop_factor",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "tile_cnt",
            "tilize",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_unary_datacopy": "perf_eltwise_unary_datacopy"
        },
    },
    "perf_eltwise_unary_sfpu": {
        "version": 3,
        "columns": [
            "approx_mode",
            "clamp_negative",
            "dest_acc",
            "fast_mode",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "stable_sort",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_eltwise_unary_sfpu": "perf_eltwise_unary_sfpu"},
    },
    "perf_eltwise_unary_typecast": {
        "version": 3,
        "columns": [
            "approx_mode",
            "dest_acc",
            "fast_mode",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "input_format",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "output_format",
            "stable_sort",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_unary_typecast": "perf_eltwise_unary_typecast",
            "perf_eltwise_typecast": "perf_eltwise_unary_typecast",
        },
    },
    "perf_fast_tilize": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_fast_tilize": "perf_fast_tilize"},
    },
    "perf_fast_tilize_full": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_fast_tilize_full": "perf_fast_tilize_full"},
    },
    "perf_fast_untilize": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_fast_untilize": "perf_fast_untilize"},
    },
    "perf_fast_untilize_baseline_compare": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_fast_untilize_baseline_compare": "perf_fast_untilize_baseline_compare"
        },
    },
    "perf_fused": {
        "version": 1,
        "columns": [
            "loop_factor",
            "marker",
        ],
        "aliases": {},
        "test_name_aliases": {"perf_fused": "perf_fused"},
    },
    "perf_generalized_moe_gate": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_generalized_moe_gate": "perf_generalized_moe_gate"},
    },
    "perf_hadamard": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_hadamard": "perf_hadamard"},
    },
    "perf_math_matmul": {
        "version": 4,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "in0_c_dim",
            "in0_r_dim",
            "in1_c_dim",
            "in1_r_dim",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "partial_a",
            "partial_b",
            "partial_face_math",
            "partial_face_pack",
            "r_dimm",
            "throttle_level",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_math_matmul": "perf_math_matmul"},
    },
    "perf_matmul": {
        "version": 3,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "r_dimm",
            "throttle_level",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_matmul": "perf_matmul"},
    },
    "perf_pack": {
        "version": 2,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "loop_factor",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "relu_config",
            "tile_cnt",
            "tilize",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack": "perf_pack"},
    },
    "perf_pack_dest_bank": {
        "version": 4,
        "columns": [
            "dest_acc",
            "dst_index",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "l1_acc",
            "loop_factor",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "tile_cnt",
            "tilize",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_dest_bank": "perf_pack_dest_bank"},
    },
    "perf_pack_rows": {
        "version": 2,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "marker",
            "num_blocks",
            "num_rows_to_pack",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_rows": "perf_pack_rows"},
    },
    "perf_pack_tiny_tile_block": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_tiny_tile_block": "perf_pack_tiny_tile_block"},
    },
    "perf_pack_untilize": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_untilize": "perf_pack_untilize"},
    },
    "perf_reduce": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "loop_factor",
            "marker",
            "mathop",
            "reduce_pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_reduce": "perf_reduce"},
    },
    "perf_rope": {
        "version": 1,
        "columns": [
            "cos_base",
            "cs_stride",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "has_scale",
            "ht",
            "marker",
            "scale_fp32",
            "sin_base",
            "tile_cnt",
            "unpack_to_dest",
            "wt",
            "x_base",
            "x_stride",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_rope": "perf_rope"},
    },
    "perf_sfpu_binop_scalar": {
        "version": 3,
        "columns": [
            "approx_mode",
            "binop_mathop",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "iterations",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
            "value_bits",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src", "mathop": "binop_mathop"},
        "test_name_aliases": {"perf_sfpu_binop_scalar": "perf_sfpu_binop_scalar"},
    },
    "perf_sfpu_clamped_silu": {
        "version": 1,
        "columns": [
            "clamped_silu_op",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "scalar0",
            "scalar1",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_clamped_silu": "perf_sfpu_clamped_silu"},
    },
    "perf_sfpu_ema": {
        "version": 1,
        "columns": [
            "alpha_bits",
            "approx_mode",
            "beta_bits",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_ema": "perf_sfpu_ema"},
    },
    "perf_sfpu_logit_softcap": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
            "value_bits",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_logit_softcap": "perf_sfpu_logit_softcap"},
    },
    "perf_sfpu_reduce": {
        "version": 4,
        "columns": [
            "approx_mode",
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "loop_factor",
            "marker",
            "mathop",
            "pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_reduce": "perf_sfpu_reduce"},
    },
    "perf_sfpu_reduce_multidim": {
        "version": 2,
        "columns": [
            "approx_mode",
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "marker",
            "num_blocks",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "reduce_pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_reduce_multidim": "perf_sfpu_reduce_multidim"},
    },
    "perf_sfpu_reduce_sdpa": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "loop_factor",
            "marker",
            "mathop",
            "reduce_pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_reduce_sdpa": "perf_sfpu_reduce_sdpa"},
    },
    "perf_sfpu_sampling": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "legacy_compat",
            "marker",
            "sampling_op",
            "unpack_to_dest",
            "value_bits",
            "vector_mode",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_sampling": "perf_sfpu_sampling"},
    },
    "perf_sfpu_sdpa": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_sdpa": "perf_sfpu_sdpa"},
    },
    "perf_sfpu_sdpa_exp_unclamped": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "scale_en",
            "tile_cnt",
            "unpack_to_dest",
            "value_bits",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_sfpu_sdpa_exp_unclamped": "perf_sfpu_sdpa_exp_unclamped"
        },
    },
    "perf_sfpu_sdpa_fw": {
        "version": 1,
        "columns": [
            "approx_mode",
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "scale_bf16",
            "sdpa_fw_op",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_sdpa_fw": "perf_sfpu_sdpa_fw"},
    },
    "perf_sfpu_softmax_k": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "softmax_k",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_softmax_k": "perf_sfpu_softmax_k"},
    },
    "perf_sfpu_sparse_k_filter": {
        "version": 1,
        "columns": [
            "bank_mask",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "global_bank_shift",
            "marker",
            "my_bank",
            "out_shift",
            "sparse_k_iterations",
            "tile_cnt",
            "unpack_to_dest",
            "within_bank_mask",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_sparse_k_filter": "perf_sfpu_sparse_k_filter"},
    },
    "perf_sfpu_ternary": {
        "version": 3,
        "columns": [
            "approx_mode",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "iterations",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "ternary_mathop",
            "ternary_scalar_bits",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {
            "formats.sfpu_math": "formats.sfpu_src",
            "mathop": "ternary_mathop",
            "value_bits": "ternary_scalar_bits",
        },
        "test_name_aliases": {"perf_sfpu_ternary": "perf_sfpu_ternary"},
    },
    "perf_sfpu_zero_pad": {
        "version": 1,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "tile_cnt",
            "total_rows",
            "unpack_to_dest",
            "valid_rows",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_zero_pad": "perf_sfpu_zero_pad"},
    },
    "perf_transpose_dest": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "math_transpose_faces",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_transpose_dest": "perf_transpose_dest",
            "perf_math_transpose": "perf_transpose_dest",
        },
    },
    "perf_unpack_A": {
        "version": 2,
        "columns": [
            "acc_to_dest",
            "block_ct_dim",
            "block_rt_dim",
            "broadcast_type",
            "dest_acc",
            "disable_src_zero_flag",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "partial_a",
            "partial_b",
            "partial_face_math",
            "partial_face_pack",
            "reuse_dest_type",
            "stochastic_rounding",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_unpack_A": "perf_unpack_A"},
    },
    "perf_unpack_a_bcast_eltwise": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "marker",
            "math_fidelity",
            "mathop",
            "srca_reuse_count",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_unpack_a_bcast_eltwise": "perf_unpack_a_bcast_eltwise"
        },
    },
    "perf_unpack_tilize": {
        "version": 5,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_unpack_tilize": "perf_unpack_tilize"},
    },
    "perf_unpack_transpose": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_unpack_transpose": "perf_unpack_transpose"},
    },
}

PERF_TEST_SCHEMAS_QSR = {
    "perf_eltwise_binary_broadcast_quasar": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "broadcast_type",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary_broadcast_quasar": "perf_eltwise_binary_broadcast_quasar"
        },
    },
    "perf_eltwise_binary_quasar": {
        "version": 4,
        "columns": [
            "acc_to_dest",
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "input_num_tiles_in_block",
            "input_tile_cnt",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_tiles_in_block",
            "output_tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary_quasar": "perf_eltwise_binary_quasar"
        },
    },
    "perf_eltwise_binary_reuse_dest_quasar": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "input_tile_cnt",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "output_tile_cnt",
            "reuse_dest_type",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary_reuse_dest_quasar": "perf_eltwise_binary_reuse_dest_quasar"
        },
    },
    "perf_eltwise_binary_sfpu_quasar": {
        "version": 3,
        "columns": [
            "approx_mode",
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "dst_rounding",
            "dst_tile_idx",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "input_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "op",
            "output_format",
            "sign_magnitude",
            "src0_tile_idx",
            "src1_tile_idx",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
            "zero_point_bits",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary_sfpu_quasar": "perf_eltwise_binary_sfpu_quasar"
        },
    },
    "perf_eltwise_unary_datacopy_quasar": {
        "version": 3,
        "columns": [
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_unary_datacopy_quasar": "perf_eltwise_unary_datacopy_quasar"
        },
    },
    "perf_eltwise_unary_sfpu_quasar": {
        "version": 3,
        "columns": [
            "approx_mode",
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "input_format",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "output_format",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_unary_sfpu_quasar": "perf_eltwise_unary_sfpu_quasar"
        },
    },
    "perf_fused_quasar": {
        "version": 1,
        "columns": [
            "loop_factor",
            "marker",
        ],
        "aliases": {},
        "test_name_aliases": {"perf_fused_quasar": "perf_fused_quasar"},
    },
    "perf_matmul_quasar": {
        "version": 3,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "enable_2x_format",
            "enable_direct_indexing",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "r_dimm",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_matmul_quasar": "perf_matmul_quasar"},
    },
    "perf_pack_l1_acc_quasar": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "loop_factor",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "relu_config",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_l1_acc_quasar": "perf_pack_l1_acc_quasar"},
    },
    "perf_pack_quasar": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "relu_config",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_quasar": "perf_pack_quasar"},
    },
    "perf_pack_untilize_quasar": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_untilize_quasar": "perf_pack_untilize_quasar"},
    },
    "perf_reduce_quasar": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "pool_type",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_reduce_quasar": "perf_reduce_quasar"},
    },
    "perf_sfpu_exp_parallel_matmul_quasar": {
        "version": 2,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "enable_2x_format",
            "enable_direct_indexing",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "r_dimm",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_sfpu_exp_parallel_matmul_quasar": "perf_sfpu_exp_parallel_matmul_quasar"
        },
    },
    "perf_transpose_dest_quasar": {
        "version": 5,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
            "vector_mode",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_where_quasar": "perf_sfpu_where_quasar"},
    },
    "perf_transpose_dest_quasar": {
        "version": 5,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "loop_factor",
            "marker",
            "math_transpose_faces",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_transpose_dest_quasar": "perf_transpose_dest_quasar"
        },
    },
    "perf_unary_broadcast_quasar": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "broadcast_type",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "loop_factor",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_unary_broadcast_quasar": "perf_unary_broadcast_quasar"
        },
    },
    "perf_unpack_reduce_col_tilizeA_strided_quasar": {
        "version": 5,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_unpack_reduce_col_tilizeA_strided_quasar": "perf_unpack_reduce_col_tilizeA_strided_quasar"
        },
    },
    "perf_unpack_tilize_quasar": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_unpack_tilize_quasar": "perf_unpack_tilize_quasar"},
    },
    "perf_unpack_unary_operand_quasar": {
        "version": 4,
        "columns": [
            "block_ct_dim",
            "block_rt_dim",
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "full_ct_dim",
            "full_rt_dim",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_unpack_unary_operand_quasar": "perf_unpack_unary_operand_quasar"
        },
    },
}
