# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0

"""Per-perf-test CSV schema catalog.

One entry per perf test: its reviewed set of CSV columns, a ``version`` bumped
when those columns change, an ``aliases`` map (old -> new) for a column
renamed in that test, and a ``test_name_aliases`` map that always includes the
current test name mapped to itself. Previous names map to the current name;
renaming a test in place requires updating this map. The gate in
test_perf_header_gate.py re-derives each test's columns and fails on any drift
from this catalog.
"""


PERF_TEST_SCHEMAS = {
    "perf_eltwise_bcast_col_custom": {
        "version": 3,
        "columns": [
            "broadcast_type",
            "ct_dim",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_bcast_col_custom": "perf_eltwise_bcast_col_custom"
        },
    },
    "perf_eltwise_binary": {
        "version": 4,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary": "perf_eltwise_binary",
            "perf_eltwise_binary_fpu": "perf_eltwise_binary",
        },
    },
    "perf_eltwise_binary_sfpu": {
        "version": 3,
        "columns": [
            "approx_mode",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_eltwise_binary_sfpu": "perf_eltwise_binary_sfpu"},
    },
    "perf_eltwise_unary_typecast": {
        "version": 4,
        "columns": [
            "approx_mode",
            "dest_acc",
            "fast_mode",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "input_format",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "output_format",
            "stable_sort",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_unary_typecast": "perf_eltwise_unary_typecast",
            "perf_eltwise_typecast": "perf_eltwise_unary_typecast",
        },
    },
    "perf_eltwise_unary_sfpu": {
        "version": 4,
        "columns": [
            "approx_mode",
            "clamp_negative",
            "dest_acc",
            "fast_mode",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "fused_sort",
            "iterations",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "stable_sort",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_eltwise_unary_sfpu": "perf_eltwise_unary_sfpu"},
    },
    "perf_fast_tilize": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_fast_tilize": "perf_fast_tilize"},
    },
    "perf_fast_tilize_full": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_fast_tilize_full": "perf_fast_tilize_full"},
    },
    "perf_fast_untilize": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_fast_untilize": "perf_fast_untilize"},
    },
    "perf_fast_untilize_baseline_compare": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_fast_untilize_baseline_compare": "perf_fast_untilize_baseline_compare"
        },
    },
    "perf_fused": {
        "version": 1,
        "columns": [
            "loop_factor",
            "marker",
        ],
        "aliases": {},
        "test_name_aliases": {"perf_fused": "perf_fused"},
    },
    "perf_math_matmul": {
        "version": 3,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "in0_c_dim",
            "in0_r_dim",
            "in1_c_dim",
            "in1_r_dim",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "partial_a",
            "partial_b",
            "partial_face_math",
            "partial_face_pack",
            "r_dimm",
            "throttle_level",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_math_matmul": "perf_math_matmul"},
    },
    "perf_transpose_dest": {
        "version": 4,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "marker",
            "math_transpose_faces",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_transpose_dest": "perf_transpose_dest",
            "perf_math_transpose": "perf_transpose_dest",
        },
    },
    "perf_matmul": {
        "version": 3,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "r_dimm",
            "throttle_level",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_matmul": "perf_matmul"},
    },
    "perf_pack_dest_bank": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dst_index",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "l1_acc",
            "loop_factor",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "tile_cnt",
            "tilize",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_dest_bank": "perf_pack_dest_bank"},
    },
    "perf_pack_untilize": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_untilize": "perf_pack_untilize"},
    },
    "perf_reduce": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "mathop",
            "reduce_pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_reduce": "perf_reduce"},
    },
    "perf_sfpu_binop_scalar": {
        "version": 3,
        "columns": [
            "approx_mode",
            "binop_mathop",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "iterations",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
            "value_bits",
        ],
        "aliases": {
            "formats.sfpu_math": "formats.sfpu_src",
            "mathop": "binop_mathop",
        },
        "test_name_aliases": {"perf_sfpu_binop_scalar": "perf_sfpu_binop_scalar"},
    },
    "perf_sfpu_ema": {
        "version": 1,
        "columns": [
            "alpha_bits",
            "approx_mode",
            "beta_bits",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_dst",
            "formats.sfpu_src",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {},
        "test_name_aliases": {"perf_sfpu_ema": "perf_sfpu_ema"},
    },
    "perf_sfpu_reduce": {
        "version": 4,
        "columns": [
            "approx_mode",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "mathop",
            "pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_reduce": "perf_sfpu_reduce"},
    },
    "perf_sfpu_reduce_sdpa": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "mathop",
            "reduce_pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_sfpu_reduce_sdpa": "perf_sfpu_reduce_sdpa"},
    },
    "perf_sfpu_ternary": {
        "version": 3,
        "columns": [
            "approx_mode",
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "iterations",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "ternary_mathop",
            "ternary_scalar_bits",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {
            "formats.sfpu_math": "formats.sfpu_src",
            "mathop": "ternary_mathop",
            "value_bits": "ternary_scalar_bits",
        },
        "test_name_aliases": {"perf_sfpu_ternary": "perf_sfpu_ternary"},
    },
    "perf_unpack_a_bcast_eltwise": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dest_sync",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "marker",
            "math_fidelity",
            "mathop",
            "srca_reuse_count",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_unpack_a_bcast_eltwise": "perf_unpack_a_bcast_eltwise"
        },
    },
    "perf_unpack_tilize": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_unpack_tilize": "perf_unpack_tilize"},
    },
    "perf_unpack_transpose": {
        "version": 3,
        "columns": [
            "dest_acc",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "loop_factor",
            "marker",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_unpack_transpose": "perf_unpack_transpose"},
    },
}


PERF_TEST_SCHEMAS_QSR = {
    "perf_eltwise_binary_broadcast_quasar": {
        "version": 3,
        "columns": [
            "broadcast_type",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary_broadcast_quasar": "perf_eltwise_binary_broadcast_quasar"
        },
    },
    "perf_eltwise_binary_quasar": {
        "version": 3,
        "columns": [
            "acc_to_dest",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "input_tile_cnt",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary_quasar": "perf_eltwise_binary_quasar"
        },
    },
    "perf_eltwise_binary_reuse_dest_quasar": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "input_tile_cnt",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "output_tile_cnt",
            "reuse_dest_type",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary_reuse_dest_quasar": "perf_eltwise_binary_reuse_dest_quasar"
        },
    },
    "perf_eltwise_binary_sfpu_quasar": {
        "version": 3,
        "columns": [
            "approx_mode",
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "dst_rounding",
            "dst_tile_idx",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "input_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "op",
            "output_format",
            "sign_magnitude",
            "src0_tile_idx",
            "src1_tile_idx",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
            "zero_point_bits",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_binary_sfpu_quasar": "perf_eltwise_binary_sfpu_quasar"
        },
    },
    "perf_eltwise_unary_datacopy_quasar": {
        "version": 3,
        "columns": [
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_unary_datacopy_quasar": "perf_eltwise_unary_datacopy_quasar"
        },
    },
    "perf_eltwise_unary_sfpu_quasar": {
        "version": 3,
        "columns": [
            "approx_mode",
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "input_format",
            "loop_factor",
            "marker",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "output_format",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_eltwise_unary_sfpu_quasar": "perf_eltwise_unary_sfpu_quasar"
        },
    },
    "perf_fused_quasar": {
        "version": 1,
        "columns": [
            "loop_factor",
            "marker",
        ],
        "aliases": {},
        "test_name_aliases": {"perf_fused_quasar": "perf_fused_quasar"},
    },
    "perf_matmul_quasar": {
        "version": 3,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "enable_2x_format",
            "enable_direct_indexing",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "r_dimm",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_matmul_quasar": "perf_matmul_quasar"},
    },
    "perf_pack_l1_acc_quasar": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "loop_factor",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "relu_config",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_l1_acc_quasar": "perf_pack_l1_acc_quasar"},
    },
    "perf_pack_quasar": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "relu_config",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_quasar": "perf_pack_quasar"},
    },
    "perf_pack_untilize_quasar": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_pack_untilize_quasar": "perf_pack_untilize_quasar"},
    },
    "perf_reduce_quasar": {
        "version": 3,
        "columns": [
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "pool_type",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_reduce_quasar": "perf_reduce_quasar"},
    },
    "perf_sfpu_exp_parallel_matmul_quasar": {
        "version": 2,
        "columns": [
            "c_dimm",
            "dest_acc",
            "dest_sync",
            "enable_2x_format",
            "enable_direct_indexing",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "k_dimm",
            "loop_factor",
            "marker",
            "math_fidelity",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "r_dimm",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_sfpu_exp_parallel_matmul_quasar": "perf_sfpu_exp_parallel_matmul_quasar"
        },
    },
    "perf_transpose_dest_quasar": {
        "version": 4,
        "columns": [
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "dst_index",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "loop_factor",
            "marker",
            "math_transpose_faces",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_transpose_dest_quasar": "perf_transpose_dest_quasar"
        },
    },
    "perf_unary_broadcast_quasar": {
        "version": 3,
        "columns": [
            "broadcast_type",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "input_num_blocks",
            "input_num_tiles_in_block",
            "loop_factor",
            "marker",
            "num_blocks",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "num_tiles_in_block",
            "output_num_blocks",
            "output_num_tiles_in_block",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_unary_broadcast_quasar": "perf_unary_broadcast_quasar"
        },
    },
    "perf_unpack_reduce_col_tilizeA_strided_quasar": {
        "version": 4,
        "columns": [
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "math_fidelity",
            "mathop",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "pool_type",
            "tile_cnt",
            "unpack_to_dest",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_unpack_reduce_col_tilizeA_strided_quasar": "perf_unpack_reduce_col_tilizeA_strided_quasar"
        },
    },
    "perf_unpack_tilize_quasar": {
        "version": 3,
        "columns": [
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {"perf_unpack_tilize_quasar": "perf_unpack_tilize_quasar"},
    },
    "perf_unpack_unary_operand_quasar": {
        "version": 3,
        "columns": [
            "data_copy_type",
            "dest_acc",
            "dest_sync",
            "face_c_dim",
            "face_r_dim",
            "formats.input_A",
            "formats.input_B",
            "formats.output",
            "formats.register_A",
            "formats.register_B",
            "formats.sfpu_src",
            "formats.sfpu_dst",
            "implied_math_format",
            "loop_factor",
            "marker",
            "num_faces",
            "num_faces_A",
            "num_faces_B",
            "num_faces_c_dim_A",
            "num_faces_c_dim_B",
            "num_faces_r_dim_A",
            "num_faces_r_dim_B",
            "tile_cnt",
            "unpack_to_dest",
            "unpack_transpose_faces",
            "unpack_transpose_within_face",
            "unpacker_engine_sel",
        ],
        "aliases": {"formats.sfpu_math": "formats.sfpu_src"},
        "test_name_aliases": {
            "perf_unpack_unary_operand_quasar": "perf_unpack_unary_operand_quasar"
        },
    },
}
