set(LLRT_SRC
    llrt.cpp
    cmac_boot_params.cpp
    external_iface_sender.cpp
    core_descriptor.cpp
    firmware_capability.cpp
    rtoptions.cpp
    tlb_config.cpp
    tt_cluster.cpp
    tt_elffile.cpp
    tt_memory.cpp
    hal.cpp
    tunnels_from_mmio_device.cpp
    metal_soc_descriptor.cpp
)
