hosts: {
  hall: "Default"
  aisle: "A"
  rack: 1
  shelf_u: 10
  node_type: "P150_LB"
  host: "bh-lb-40"
}
hosts: {
  hall: "Default"
  aisle: "A"
  rack: 1
  shelf_u: 30
  node_type: "P150_LB"
  host: "bh-lb-38"
}
hosts: {
  hall: "Default"
  aisle: "A"
  rack: 1
  shelf_u: 20
  node_type: "P150_LB"
  host: "bh-lb-39"
}
hosts: {
  hall: "Default"
  aisle: "A"
  rack: 1
  shelf_u: 40
  node_type: "P150_LB"
  host: "bh-lb-37"
}
