training_config:
  batch_size: 4                # 4 prompts * 8 group_size = 32 total completions
  num_epochs: 1
  model_config: "model_configs/llama3_2_1B.yaml"

  optimizer:
    type: MorehAdamW
    lr: 5.0e-7
    beta1: 0.9
    beta2: 0.99
    epsilon: 1.0e-8
    weight_decay: 0.01
    amsgrad: false
    kahan_summation: false

grpo_config:
  group_size: 8
  micro_batch_size: 16
  warmup_steps: 100
  max_tokens_to_complete: 512
  prompts_to_train: 1536
  clip_eps: 0.2

eval_config:
  temperature: 0.8

device_config:
  enable_ddp: true
  mesh_shape: [1, 2]
