// SPDX-FileCopyrightText: © 2023 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0

#include <cstdint>

#define BCAST_LLKOP EltwiseBinaryType::ELWMUL
#define BCAST_DIM BroadcastType::COL

#include "api/compute/bcast.h"
#include "api/compute/eltwise_binary.h"
#include "api/compute/eltwise_binary_sfpu.h"
#include "api/compute/eltwise_unary/rsqrt.h"
#include "api/compute/welford.h"
#include "api/compute/transpose.h"
#include "api/compute/compute_kernel_hw_startup.h"
#include "ttnn/operations/normalization/kernel_util/compute/memory.h"
#include "ttnn/operations/normalization/kernel_util/generic/blocked_range.h"
#include "api/dataflow/circular_buffer.h"
#include "ttnn/cpp/ttnn/kernel_lib/eltwise_chain.hpp"
#include "ttnn/cpp/ttnn/kernel_lib/eltwise_convenience.hpp"
#include "ttnn/cpp/ttnn/kernel_lib/eltwise_math.hpp"

namespace ckl = compute_kernel_lib;

namespace kutil = norm::kernel_util;
namespace generic = kutil::generic;

void kernel_main() {
    uint32_t NCHt = get_arg_val<uint32_t>(0);
    constexpr uint32_t Wt = get_compile_time_arg_val(0);
    constexpr uint32_t blk = get_compile_time_arg_val(1);
    constexpr uint32_t do_gamma = get_compile_time_arg_val(2);
    constexpr uint32_t do_beta = get_compile_time_arg_val(3);
    constexpr bool FLOAT32_DTYPE = get_compile_time_arg_val(4) == 1;
    constexpr uint32_t W = get_compile_time_arg_val(5);
    constexpr uint32_t tile_width = get_compile_time_arg_val(6);
    constexpr bool fuse_pre_add = static_cast<bool>(get_compile_time_arg_val(8));

    constexpr uint32_t onetile = 1;

    // CB indices - configurable via named compile-time args for kernel chaining support
    constexpr auto cb_eps = get_named_compile_time_arg_val("cb_eps");  // single tile generated by the reader
    constexpr auto cb_in = get_named_compile_time_arg_val("cb_in");    // input x or a for fused pre-add (x=a+b)
    constexpr auto cb_inb = get_named_compile_time_arg_val("cb_inb");  // input b for fused pre-add
    constexpr auto cb_out = get_named_compile_time_arg_val("cb_out");  // output
    constexpr auto cb_gamma = get_named_compile_time_arg_val("cb_gamma");
    constexpr auto cb_beta = get_named_compile_time_arg_val("cb_beta");
    constexpr auto cb_xmm = get_named_compile_time_arg_val("cb_xmm");  // x - E[x]

    constexpr auto cb_ex = get_named_compile_time_arg_val("cb_ex");                    // E[x]
    constexpr auto cb_ex2 = get_named_compile_time_arg_val("cb_ex2");                  // E[(x-E[x])^2]
    constexpr auto cb_ex2pe = get_named_compile_time_arg_val("cb_ex2pe");              // E[(x-E[x])^2]+eps
    constexpr auto cb_fusion = get_named_compile_time_arg_val("cb_fusion");            // stream gamma/beta
    constexpr auto cb_reciprocals = get_named_compile_time_arg_val("cb_reciprocals");  // Pre-computed reciprocals
    CircularBuffer cb_eps_obj(cb_eps);
    CircularBuffer cb_in_obj(cb_in);
    CircularBuffer cb_inb_obj(cb_inb);
    CircularBuffer cb_out_obj(cb_out);
    CircularBuffer cb_gamma_obj(cb_gamma);
    CircularBuffer cb_beta_obj(cb_beta);
    CircularBuffer cb_xmm_obj(cb_xmm);
    CircularBuffer cb_ex_obj(cb_ex);
    CircularBuffer cb_ex2_obj(cb_ex2);
    CircularBuffer cb_ex2pe_obj(cb_ex2pe);
    CircularBuffer cb_fusion_obj(cb_fusion);

    constexpr auto cb_im_or_out = (do_gamma | do_beta) ? cb_fusion : cb_out;
    CircularBuffer cb_im_or_out_obj(cb_im_or_out);

    //  Either in or in + b if doing fused pre-add
    constexpr auto cb_x = []() -> auto {
        if constexpr (fuse_pre_add) {
            return get_named_compile_time_arg_val("cb_x");
        } else {
            return cb_in;
        }
    }();
    CircularBuffer cb_x_obj(cb_x);

    // Welford-fp32 alias of cb_x. Shares SRAM with cb_x but has its own buffer index
    // configured with UnpackToDestFp32. Welford's transpose_tile reads
    // through cb_x_welford to get full fp32 into DEST; the post-welford eltwise keeps reading
    // cb_x via SrcA. When welford_fp32_alias is false, cb_x_welford == cb_x.
    constexpr auto cb_x_welford = get_named_compile_time_arg_val("cb_x_welford");
    constexpr bool welford_fp32_alias = get_named_compile_time_arg_val("welford_fp32_alias") != 0;
    CircularBuffer cb_x_welford_obj(cb_x_welford);

    constexpr uint32_t dst0 = 0;
    constexpr uint32_t input_dst = 0;  // Input tile for Welford's algorithm
    constexpr uint32_t mean_dst = 1;
    constexpr uint32_t var_dst = 2;

    // The number of valid columns in the last tile in width dimension.
    // Because the Welford's llk is given transposed data, skip some rows when
    // we want to skip some columns from getting processed by layer_norm.
    constexpr uint32_t last_tile_rows = (W % tile_width) == 0 ? tile_width : W % tile_width;

    cb_eps_obj.wait_front(1);  // comes from the reader

    if constexpr (fuse_pre_add) {
        binary_op_init_common(cb_in, cb_inb, cb_x);
        pack_reconfig_data_format(cb_x);
    } else {
        compute_kernel_hw_startup(cb_in, cb_ex);
        pack_reconfig_data_format(cb_ex);
    }

    // Get pointer to the reciprocal LUT
    using recip_lut_t = std::array<uint32_t, W>;
    auto p_reciprocals = kutil::compute::memory::get_pointer_to_cb_data<recip_lut_t>(cb_reciprocals, 0);

    // Intermediate buffers need to be reserved/pushed/popped
    // in full blocks
    const auto total_buffer_size = generic::blocks(Wt, blk).total_with_remainder();

    for (uint32_t ncht = 0; ncht < NCHt; ncht++) {
        if constexpr (fuse_pre_add) {
            for (auto block : generic::blocks(Wt, blk)) {
                if constexpr (welford_fp32_alias) {
                    cb_x_welford_obj.reserve_back(block.full_block_size());
                }
                ckl::add<
                    cb_in,
                    cb_inb,
                    cb_x,
                    ckl::BroadcastDim::None,
                    ckl::input(ckl::InputLifecycle::Bulk, ckl::OperandKind::Block),
                    ckl::input(ckl::InputLifecycle::Bulk, ckl::OperandKind::Block),
                    ckl::output(ckl::OutputLifecycle::Bulk)>(
                    ckl::EltwiseShape::tiles(block.full_block_size(), /*block_size=*/blk));
                if constexpr (welford_fp32_alias) {
                    cb_x_welford_obj.push_back(block.full_block_size());
                }
            }
            reconfig_data_format(cb_in, cb_x, cb_inb, cb_ex);
        }

        // Simultaneous calculation of E[x] and Var[x] using Welford's algorithm.
        //
        // Welford reads input tiles through cb_x_welford, which shares SRAM with cb_x but
        // is configured for UnpackToDestFp32 (vs cb_x's default TF32 SrcA path).
        //
        // The post-welford eltwise reads cb_x directly (FPU binary ops can't use UnpackToDest).
        // cb_x and cb_x_welford have independent read/write pointers so we wait_front and pop_front
        // them separately. When welford_fp32_alias is 0, cb_x_welford == cb_x so the two sets
        // of semaphore ops collapse onto the same CB and the alias-side waits/pops are
        // redundant -- gated by welford_fp32_alias.
        uint32_t start_N = 0;
        reconfig_data_format_srca(cb_x_welford);
        // Reconfigure the transpose op for the welford intake CB. When the alias is active,
        // cb_x_welford has UnpackToDestFp32 mode so transpose_tile preserves fp32 precision.
        transpose_init(cb_x_welford);
        tile_regs_acquire();
        welford_init();
        // Welford's recurrence and the fp32 transpose collide in the math thread's replay
        // buffer. The buffer has 32 slots, conventionally split between SFPU [0, 16) and
        // FPU [16, 32). Welford violates that split: welford_init records 32 instructions
        // at slots [0, 32) (4 LREG variants of 8 instructions each, fully unrolled), and
        // welford_update replays all four variants per block.
        //
        // When cb_x_welford is configured for UnpackToDest fp32 (welford_fp32_alias=true),
        // transpose_tile takes the UnpackToDest path. Its math-side init
        // (llk_math_transpose_dest_init, invoked from transpose_init inside the loop
        // below) records 16 instructions at slots [16, 32) for the transpose-dest setup,
        // clobbering welford's LREG2/LREG3 portions. The recovery after each transpose_tile
        // re-records all 32 slots with the welford recurrence so welford_update replays welford
        // ops instead of stale transpose-dest ops. LREG4/5 (the running mean / M2 accumulator)
        // survive transpose_dest because it only uses FPU MOVs.
        //
        // When welford_fp32_alias is false (e.g. fp32_dest_acc_en=false path), the unpack dst
        // format is not Float32 so transpose_tile takes the SrcA path. That path skips
        // llk_math_transpose_dest entirely, so the math-thread replay buffer is untouched
        // and no recovery is needed.
        // Process all but the last tile
        for (uint32_t wt = 0; wt < (Wt - 1); ++wt) {
            if constexpr (welford_fp32_alias) {
                cb_x_welford_obj.wait_front(wt + 1);
                // SFPU replay slots [0, 32) currently hold the welford recurrence (see outer
                // comment block above). transpose_init re-records slots [16, 32) with
                // the transpose-dest setup so transpose_tile below can replay them.
                transpose_init(cb_x_welford);
            } else {
                cb_x_obj.wait_front(wt + 1);
            }
            transpose_tile(cb_x_welford, wt, input_dst);
            if constexpr (welford_fp32_alias) {
                // transpose_tile took the UnpackToDestFp32 path. Its math-side init clobbered
                // the welford recurrence at SFPU replay slots [16, 32).
                // welford_init<WelfordInitMode::PreserveStats>() re-records all 32 slots with
                // the welford recurrence; PreserveStats keeps the running mean / M2 accumulator
                // in LREG4/5. UNPACK A is left in transpose=1;
                // welford_update is pure SFPU and does not consume that state, and the next
                // iteration's transpose_init reprograms it.
                welford_init<WelfordInitMode::PreserveStats>();
            }
            welford_update<W>(input_dst, start_N, *p_reciprocals);
            start_N += tile_width;
        }

        // Process the last tile
        // cb_x is synced on full blocks, so we need to wait for the
        // last tile + any remaining in the last block
        const auto num_to_wait = generic::blocks(Wt, blk).total_with_remainder();
        if constexpr (welford_fp32_alias) {
            cb_x_welford_obj.wait_front(num_to_wait);
            transpose_init(cb_x_welford);
        } else {
            cb_x_obj.wait_front(num_to_wait);
        }
        transpose_tile(cb_x_welford, Wt - 1, input_dst);
        if constexpr (welford_fp32_alias) {
            welford_init<WelfordInitMode::PreserveStats>();
        }
        welford_update_rows<W>(input_dst, start_N, 0, last_tile_rows, *p_reciprocals);

        // Store the mean and variance to the destination registers
        welford_finalize_to_row<W>(mean_dst, W - 1, *p_reciprocals);
        tile_regs_commit();

        // Pop cb_x_welford so its rd_ptr advances in lock-step with cb_x's pop in the eltwise
        // loop below. Multi-buffer-index CB indices have independent read/write pointers
        // but share the underlying SRAM; popping the alias only
        // advances cb_x_welford's own rd_ptr, leaving cb_x's state untouched. Without this
        // pop, subsequent NCHt iterations would read stale tiles from the start of the buffer
        // (the reader's push_back advances the wr_ptr, but the alias's rd_ptr stays at 0).
        if constexpr (welford_fp32_alias) {
            cb_x_welford_obj.pop_front(total_buffer_size);
        }

        // Transpose mean and var back to columns
        cb_ex_obj.reserve_back(onetile);
        cb_ex2_obj.reserve_back(onetile);
        tile_regs_wait();
        pack_reconfig_data_format(cb_ex);
        pack_tile(mean_dst, cb_ex);
        pack_reconfig_data_format(cb_ex2);
        pack_tile(var_dst, cb_ex2);
        tile_regs_release();
        cb_ex_obj.push_back(onetile);
        cb_ex2_obj.push_back(onetile);

        cb_ex_obj.wait_front(onetile);
        cb_ex2_obj.wait_front(onetile);
        reconfig_data_format_srca(cb_ex);
        transpose_init(cb_ex);
        tile_regs_acquire();
        transpose_tile(cb_ex, 0, mean_dst);
        transpose_tile(cb_ex2, 0, var_dst);
        tile_regs_commit();

        cb_ex_obj.pop_front(onetile);
        cb_ex2_obj.pop_front(onetile);

        cb_ex_obj.reserve_back(onetile);
        cb_ex2_obj.reserve_back(onetile);

        pack_reconfig_data_format(cb_ex);
        tile_regs_wait();
        pack_tile(mean_dst, cb_ex);
        pack_reconfig_data_format(cb_ex2);
        pack_tile(var_dst, cb_ex2);
        tile_regs_release();

        cb_ex_obj.push_back(onetile);
        cb_ex2_obj.push_back(onetile);

        cb_ex_obj.wait_front(onetile);
        for (auto block : generic::blocks(Wt, blk)) {
            ckl::sub<
                cb_x,
                cb_ex,
                cb_xmm,
                ckl::BroadcastDim::Col,
                ckl::input(ckl::InputLifecycle::Bulk, ckl::OperandKind::Block),
                ckl::input(ckl::InputLifecycle::CallerManaged),
                ckl::output(ckl::OutputLifecycle::Bulk, ckl::DataFormatReconfig::Disabled)>(
                ckl::EltwiseShape::tiles(block.full_block_size(), /*block_size=*/blk));
        }
        cb_ex_obj.pop_front(1);
        cb_xmm_obj.wait_front(total_buffer_size);

        if constexpr (!fuse_pre_add) {
            reconfig_data_format_srca(cb_x, cb_xmm);
        }

        ckl::eltwise_chain(
            ckl::EltwiseShape::tiles(onetile),
            ckl::BinaryFpu<
                cb_ex2,
                cb_eps,
                ckl::BinaryFpuOp::Add,
                ckl::BroadcastDim::None,
                ckl::input(),
                ckl::input(ckl::InputLifecycle::CallerManaged)>{},
            ckl::Rsqrt<ckl::Approx::Exact, ckl::Legacy::Off, ckl::Dst::D0>{},
            ckl::PackTile<cb_ex2pe, ckl::output(ckl::OutputLifecycle::Streaming, ckl::DataFormatReconfig::Disabled)>{});

        // Remainder of the layernorm operation
        cb_ex2pe_obj.wait_front(onetile);
        for (auto block : generic::blocks(Wt, blk)) {
            ckl::eltwise_chain(
                ckl::EltwiseShape::tiles(block.full_block_size(), /*block_size=*/blk),
                ckl::BinaryFpu<
                    cb_xmm,
                    cb_ex2pe,
                    ckl::BinaryFpuOp::Mul,
                    ckl::BroadcastDim::Col,
                    ckl::input(
                        ckl::InputLifecycle::HeldBulk,
                        ckl::OperandKind::Block,
                        ckl::DataFormatReconfig::Enabled,
                        ckl::TileOffset::Set),
                    ckl::input(ckl::InputLifecycle::CallerManaged)>{block.start(), 0u},
                ckl::PackTile<cb_im_or_out, ckl::output(ckl::OutputLifecycle::Bulk)>{});

            if constexpr (do_gamma) {
                constexpr uint32_t cb_outg = do_beta ? cb_fusion : cb_out;
                ckl::eltwise_chain(
                    ckl::EltwiseShape::tiles(block.full_block_size(), /*block_size=*/blk),
                    ckl::BinaryFpu<
                        cb_fusion,
                        cb_gamma,
                        ckl::BinaryFpuOp::Mul,
                        ckl::BroadcastDim::Row,
                        ckl::input(ckl::InputLifecycle::Bulk, ckl::OperandKind::Block),
                        ckl::input(
                            ckl::InputLifecycle::HeldBulk,
                            ckl::OperandKind::Block,
                            ckl::DataFormatReconfig::Enabled,
                            ckl::TileOffset::Set)>{0u, block.start()},
                    ckl::PackTile<cb_outg, ckl::output(ckl::OutputLifecycle::Bulk)>{});
            }
            if constexpr (do_beta) {
                ckl::eltwise_chain(
                    ckl::EltwiseShape::tiles(block.full_block_size(), /*block_size=*/blk),
                    ckl::BinaryFpu<
                        cb_fusion,
                        cb_beta,
                        ckl::BinaryFpuOp::Add,
                        ckl::BroadcastDim::Row,
                        ckl::input(ckl::InputLifecycle::Bulk, ckl::OperandKind::Block),
                        ckl::input(
                            ckl::InputLifecycle::HeldBulk,
                            ckl::OperandKind::Block,
                            ckl::DataFormatReconfig::Enabled,
                            ckl::TileOffset::Set)>{0u, block.start()},
                    ckl::PackTile<cb_out, ckl::output(ckl::OutputLifecycle::Bulk)>{});
            }
        }
        cb_ex2pe_obj.pop_front(onetile);
        cb_xmm_obj.pop_front(total_buffer_size);

    }  // NCHt loop
}
