// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
//
// SPDX-License-Identifier: Apache-2.0

#include <cstdint>
#define REDUCE_OP PoolType::SUM
#define REDUCE_DIM ReduceDim::REDUCE_ROW

#define BCAST_LLKOP EltwiseBinaryType::ELWMUL
#define BCAST_DIM BroadcastType::COL

#include "api/compute/compute_kernel_api.h"
#include "api/compute/reduce.h"
#include "api/compute/bcast.h"
#include "api/compute/eltwise_binary.h"
#include "api/compute/layernorm.h"
#include "api/compute/eltwise_binary_sfpu.h"
#include "api/compute/tile_move_copy.h"
#include "api/compute/tilize.h"
#include "api/debug/dprint.h"
#include "api/compute/pack_untilize.h"
#include "ttnn/operations/normalization/kernel_util/compute/numeric.h"
#include "ttnn/operations/normalization/kernel_util/generic/blocked_range.h"

namespace kutil = norm::kernel_util;
namespace numeric = kutil::compute::numeric;
namespace policies = kutil::compute::policies;
namespace generic = kutil::generic;

/*
 * Read 1 row-major block from cb_in_rm, tilize it and write to cb_in
 */
template <typename Block>
ALWI void tilize_row_major_block(
    const uint32_t cb_in_rm, const uint32_t cb_in, const uint32_t block_size, const Block& block) {
    // TODO: Figure out where tilize unpacks to (srca or srcb)
    reconfig_data_format(cb_in_rm, cb_in_rm);
    pack_reconfig_data_format(cb_in);

    tilize_init(cb_in_rm, block_size, cb_in);
    cb_wait_front(cb_in_rm, block.full_block_size());
    cb_reserve_back(cb_in, block.full_block_size());

    tilize_block(cb_in_rm, block.full_block_size(), cb_in);
    cb_push_back(cb_in, block.full_block_size());
    cb_pop_front(cb_in_rm, block.full_block_size());

    tilize_uninit(cb_in_rm, cb_in);
}

/*
 * Read 1 tiled block from cb_out, pack it and write to cb_out_rm as row-major block
 */
template <typename Block, uint32_t block_size>
ALWI void untilize_row_major_block(const uint32_t cb_out, const uint32_t cb_out_rm, const Block& block) {
    // TODO: Figure out where untilize unpacks to (srca or srcb)
    reconfig_data_format(cb_out, cb_out);  // Handle fp32_dest_acc_en=True cases

    pack_untilize_init<block_size, block_size>(cb_out, cb_out_rm);
    cb_wait_front(cb_out, block.full_block_size());
    cb_reserve_back(cb_out_rm, block.full_block_size());
    pack_untilize_block<block_size, block_size>(cb_out, 1, cb_out_rm);
    cb_push_back(cb_out_rm, block.full_block_size());
    cb_pop_front(cb_out, block.full_block_size());
    pack_untilize_uninit(cb_out_rm);
}

void kernel_main() {
    uint32_t NCHt = get_arg_val<uint32_t>(0);
    constexpr uint32_t Wt = get_compile_time_arg_val(0);
    constexpr uint32_t block_size = get_compile_time_arg_val(1);
    constexpr uint32_t do_gamma = get_compile_time_arg_val(2);
    constexpr uint32_t do_beta = get_compile_time_arg_val(3);
    constexpr bool FLOAT32_DTYPE = get_compile_time_arg_val(4) == 1;
    constexpr bool FLOAT32_REDUCTION = get_compile_time_arg_val(5) == 1;
    constexpr bool LEGACY_RSQRT = get_compile_time_arg_val(6) == 1;
    constexpr uint32_t W = get_compile_time_arg_val(7);

    constexpr uint32_t onetile = 1;

    constexpr auto cb_scaler = tt::CBIndex::c_2;  // single tile generated by the reader
    constexpr auto cb_eps = tt::CBIndex::c_3;     // single tile generated by the reader
    constexpr auto cb_in = tt::CBIndex::c_0;      // input x or a for fused pre-add (x=a+b)
    constexpr auto cb_inb = tt::CBIndex::c_1;     // input b for fused pre-add
    constexpr auto cb_out = tt::CBIndex::c_16;    // output
    constexpr auto cb_gamma = tt::CBIndex::c_5;
    constexpr auto cb_beta = tt::CBIndex::c_6;
    constexpr uint32_t cb_xmm = tt::CBIndex::c_24;  // x minus mean
    constexpr auto cb_ex = tt::CBIndex::c_18;     // E[x]
    constexpr auto cb_ex2 = tt::CBIndex::c_19;    // E[(x-E[x])^2]
    constexpr auto cb_xmm2 = tt::CBIndex::c_20;   // xmm^2
    constexpr auto cb_ex2pe = tt::CBIndex::c_21;  // E[(x-E[x])^2]+eps
    uint32_t cb_fusion = tt::CBIndex::c_22;       // stream gamma/beta
    constexpr auto scaler0 = 0;
    constexpr auto cb_accumulate = tt::CBIndex::c_26;  // For accumulating (x-E[x])^2
#ifdef FUSE_PRE_ADD
#ifdef RMSNORM
    constexpr uint32_t cb_x = cb_xmm;
#else
    constexpr uint32_t cb_x = tt::CBIndex::c_23;
#endif
#else
    constexpr uint32_t cb_x = cb_in;
#endif

#ifdef TILIZE_IN
    constexpr auto cb_in_rm = tt::CBIndex::c_27;
#endif

#ifdef FUSE_PRE_ADD
    binary_op_init_common(cb_in, cb_inb, cb_x);
#else
    // Always call binary_op_init_common regardless of TILIZE_IN.
    // This initializes llk_pack_dest_init, which sets up the MATH-PACK DST semaphore
    // in the "available for MATH" state.  Without it, the first tilize_block call's
    // internal llk_math_wait_for_dest_available() spins forever (deadlock).
    binary_op_init_common(cb_in, cb_scaler, cb_ex);
#endif
    cb_wait_front(cb_eps, 1);     // comes from the reader

    for (uint32_t ncht = 0; ncht < NCHt; ncht++) {
        constexpr int onetile = 1;
        constexpr int dst0 = 0;
#ifndef RMSNORM
        // Start of
        //  E[x]
        //  aka   ∑(x)
        //      --------
        //         n
#ifdef FUSE_PRE_ADD
        numeric::row_wise_mean_with_pre_add<FLOAT32_REDUCTION, policies::FullBlockWithPopPolicy>(
            cb_in, cb_inb, cb_scaler, cb_ex, W, Wt, block_size);
#else
        numeric::row_wise_mean<FLOAT32_REDUCTION, policies::FullBlockWithPopPolicy>(
            cb_in, cb_scaler, cb_ex, W, Wt, block_size);
#endif
#endif  // !RMS ifdef end
        // Start of
        // Var Calculation
        // Var(X) = ∑(x-E[x])^2
        //         -----------
        //              n
        const bool last_tile_is_partial = W % tt::constants::TILE_WIDTH > 0;
        for (auto block : generic::blocks(Wt, block_size)) {
#ifdef TILIZE_IN
            // Tilize one block from cb_in_rm → cb_in per loop iteration.
            tilize_row_major_block(cb_in_rm, cb_in, block_size, block);
            // tilize_uninit (inside tilize_row_major_block) calls llk_pack_init which resets
            // the PACK dest state.  binary_op_init_common re-initializes the DST semaphore so
            // the subsequent tile_regs_acquire() and the next tilize_block don't deadlock.
            binary_op_init_common(cb_in, cb_scaler, cb_ex);
#endif
            cb_wait_front(cb_in, block.full_block_size());
            tile_regs_acquire();
#ifdef RMSNORM
            reconfig_data_format_srca(cb_in);
            copy_tile_init(cb_in);
            for (auto i : block.local()) {
                copy_tile(cb_in, i, i);
            }
#else
            // x-E[x]
            reconfig_data_format(cb_in, cb_ex);
            sub_bcast_cols_init_short(cb_in, cb_ex);
            for (auto i : block.local()) {
                sub_tiles_bcast_cols(cb_in, cb_ex, i, 0, i);
            }
#endif
            cb_pop_front(cb_in, block.full_block_size());
#ifdef FUSE_PRE_ADD
            cb_wait_front(cb_inb, block.full_block_size());
            reconfig_data_format_srca(cb_in, cb_inb);
            binary_dest_reuse_tiles_init<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb);
            for (auto i : block.local()) {
                binary_dest_reuse_tiles<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb, i, i);
            }
            cb_pop_front(cb_inb, block.full_block_size());
#endif
            // (x-E[x])^2. Pack to CB
            square_tile_init();
            for (auto i : block.local()) {
                square_tile(i);
            }
            tile_regs_commit();
            tile_regs_wait();
            cb_reserve_back(cb_xmm2, block.full_block_size());
            pack_reconfig_data_format(cb_xmm2);
            for (auto i : block.local()) {
                pack_tile(i, cb_xmm2);
            }
            tile_regs_release();

            cb_push_back(cb_xmm2, block.full_block_size());

            tile_regs_acquire();
            if (!block.is_first()) {
                cb_wait_front(cb_accumulate, onetile);
                reconfig_data_format_srca(cb_accumulate);
                copy_tile_init(cb_accumulate);
                copy_tile(cb_accumulate, 0, dst0);
                cb_pop_front(cb_accumulate, onetile);
            }
            cb_wait_front(cb_xmm2, block.full_block_size());

            // Accumulate (x-E[x])^2
            reconfig_data_format(cb_xmm2, cb_scaler);
            reduce_init<REDUCE_OP, REDUCE_DIM, FLOAT32_REDUCTION>(cb_xmm2, cb_scaler, cb_accumulate);
            for (auto i : block.local()) {
                const auto scaler_tile_idx = block.to_global(i) == Wt - 1 && last_tile_is_partial ? 1 : 0;
                reduce_tile<REDUCE_OP, REDUCE_DIM, FLOAT32_REDUCTION>(cb_xmm2, cb_scaler, i, scaler_tile_idx, dst0);
            }

            cb_pop_front(cb_xmm2, block.full_block_size());

            const auto final_iter = block.last() == Wt;
            const auto pack_cb = final_iter ? cb_ex2 : cb_accumulate;
            if (final_iter) {
                // Divide by W
                binop_with_scalar_tile_init();
                mul_unary_tile(dst0, generic::bit_cast<uint32_t>(1.0f / W));
            }

            reduce_uninit<FLOAT32_REDUCTION>();
            tile_regs_commit();
            tile_regs_wait();

            cb_reserve_back(pack_cb, onetile);
            pack_reconfig_data_format(pack_cb);
            pack_tile(dst0, pack_cb);
            tile_regs_release();
            cb_push_back(pack_cb, onetile);
        }

        // End of
        // Var Calculation
        // Var(X) = ∑(x-E[x])^2
        //         -----------

        // Start of
        // Calculation
        //                     1
        //  cb_ex2pe =   -------------
        //               √(Var(X) + ε)
        cb_wait_front(cb_ex2, onetile);
        reconfig_data_format(cb_ex2, cb_eps);
        tile_regs_acquire();

        add_tiles_init(cb_ex2, cb_eps);
        add_tiles(cb_ex2, cb_eps, 0, 0, dst0);

        rsqrt_tile_init<LEGACY_RSQRT>();
        rsqrt_tile<LEGACY_RSQRT>(dst0);

        tile_regs_commit();
        tile_regs_wait();
        pack_reconfig_data_format(cb_ex2pe);
        pack_tile(dst0, cb_ex2pe);
        tile_regs_release();
        cb_push_back(cb_ex2pe, onetile);
        cb_pop_front(cb_ex2, onetile);

        // broadcasts the tile since cb_ex2pe is a column vector that contains the important data
        cb_wait_front(cb_ex2pe, onetile);
        tile_regs_acquire();
        reconfig_data_format_srca(cb_ex2pe);

        unary_bcast_init<BroadcastType::COL>(cb_ex2pe, cb_ex2pe);
        unary_bcast<BroadcastType::COL>(cb_ex2pe, 0, dst0);
        cb_pop_front(cb_ex2pe, onetile);

        tile_regs_commit();
        tile_regs_wait();
        pack_tile(dst0, cb_ex2pe);
        tile_regs_release();
        cb_push_back(cb_ex2pe, onetile);
        cb_wait_front(cb_ex2pe, onetile);

        // End of
        // Calculation
        //                     1
        //  cb_ex2pe =   -------------
        //               √(Var(X) + ε)

        // Start of
        // Final Val Calc
        //    x-E[X]
        //(---------------*𝛄)+ß
        //  √(Var(X)+ε)
        for (auto block : generic::blocks(Wt, block_size)) {
#ifdef TILIZE_IN
            // Tilize one block from cb_in_rm → cb_in per loop iteration (Pass 2).
            // Reader supplies this second pass of data after the variance data.
            DPRINT_MATH(DPRINT << "[lt normalize] tilize block_size =" << block_size << " block.start=" << block.start()
                               << ENDL();)
            tilize_row_major_block(cb_in_rm, cb_in, block_size, block);

            binary_op_init_common(cb_in, cb_scaler, cb_ex);
#endif
            tile_regs_acquire();
            cb_wait_front(cb_in, block.full_block_size());
#ifdef RMSNORM
            reconfig_data_format_srca(cb_in);
            copy_tile_init(cb_in);
            for (auto i : block.local()) {
                copy_tile(cb_in, i, i);
            }
#else
            cb_wait_front(cb_ex, 1);
            reconfig_data_format(cb_in, cb_ex);
            sub_bcast_cols_init_short(cb_in, cb_ex);
            // x-E[x]
            for (auto i : block.local()) {
                sub_tiles_bcast_cols(cb_in, cb_ex, i, 0, i);
            }
#endif
            cb_pop_front(cb_in, block.full_block_size());
#ifdef FUSE_PRE_ADD
            cb_wait_front(cb_inb, block.full_block_size());
            reconfig_data_format_srca(cb_inb);
            binary_dest_reuse_tiles_init<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb);
            for (auto i : block.local()) {
                binary_dest_reuse_tiles<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb, i, i);
            }
            cb_pop_front(cb_inb, block.full_block_size());
#endif
            tile_regs_commit();
            tile_regs_wait();
            // Note: We shouldn't have to pack to
            // intermediate CB. We should be able to
            // do a binary dest with reuse (as we used
            // to). However, tt-llk #868 is preventing
            // that from working at the moment.
            cb_reserve_back(cb_xmm, block.full_block_size());
            pack_reconfig_data_format(cb_xmm);
            for (auto i : block.local()) {
                pack_tile(i, cb_xmm);
            }
            cb_push_back(cb_xmm, block.full_block_size());
            tile_regs_release();

            cb_wait_front(cb_xmm, block.full_block_size());
            reconfig_data_format(cb_xmm, cb_ex2pe);
            tile_regs_acquire();

            mul_tiles_init(cb_xmm, cb_ex2pe);
            for (auto i : block.local()) {
                mul_tiles(cb_xmm, cb_ex2pe, i, 0, i);
#ifdef SFPU_OP_INIT_ACTIVATION
                // Activation must be applied last. If do_gamma != 0 or do_beta != 0 then
                // activation will be applied after the gamma/beta multiplication/addition.
                // Otherwise, we can apply the activation here.
                if constexpr (!(do_gamma == 1 || do_beta == 1)) {
                    SFPU_OP_INIT_ACTIVATION
                    SFPU_OP_FUNC_ACTIVATION
                }
#endif
            }
            tile_regs_commit();
            tile_regs_wait();

            if constexpr (!(do_gamma == 1 or do_beta == 1)) {
                cb_fusion = cb_out;
            }
            cb_reserve_back(cb_fusion, block.full_block_size());
            pack_reconfig_data_format(cb_fusion);
            for (auto i : block.local()) {
                pack_tile(i, cb_fusion);
            }
            tile_regs_release();
            cb_push_back(cb_fusion, block.full_block_size());
            cb_pop_front(cb_xmm, block.full_block_size());

            if constexpr (do_gamma == 1) {
                // DPRINT << "[compute] applying gamma for block" << block.start() << ENDL();
                tile_regs_acquire();
                tile_regs_wait();
                reconfig_data_format(cb_fusion, cb_gamma);
                if constexpr (!do_beta) {
                    pack_reconfig_data_format(cb_out);
                }
                cb_wait_front(cb_gamma, block.full_block_size());
                cb_wait_front(cb_fusion, block.full_block_size());
                mul_bcast_rows_init_short(cb_fusion, cb_gamma);
                for (auto i : block.local()) {
                    mul_tiles_bcast_rows(cb_fusion, cb_gamma, i, i, i);
#ifdef SFPU_OP_INIT_ACTIVATION
                    // Activation must be applied last. If do_beta != 0 then
                    // activation will be applied after the beta addition.
                    // Otherwise, we can apply the activation here.
                    if constexpr (!(do_beta == 1)) {
                        SFPU_OP_INIT_ACTIVATION
                        SFPU_OP_FUNC_ACTIVATION
                    }
#endif
                }
                tile_regs_commit();
                cb_pop_front(cb_gamma, block.full_block_size());
                cb_pop_front(cb_fusion, block.full_block_size());
                if constexpr (!do_beta) {
                    cb_reserve_back(cb_out, block.full_block_size());
                    for (auto i : block.local()) {
                        pack_tile(i, cb_out);
                    }
                    cb_push_back(cb_out, block.full_block_size());
                } else {
                    cb_reserve_back(cb_fusion, block.full_block_size());
                    for (auto i : block.local()) {
                        pack_tile(i, cb_fusion);
                    }
                    cb_push_back(cb_fusion, block.full_block_size());
                }

                tile_regs_release();
                // DPRINT << "[compute] applied gamma for block" << block.start() << ENDL();
            }
            if constexpr (do_beta == 1) {
                // DPRINT << "[compute] applying beta for block" << block.start() << ENDL();
                tile_regs_acquire();
                tile_regs_wait();
                reconfig_data_format(cb_fusion, cb_beta);
                pack_reconfig_data_format(cb_out);
                cb_wait_front(cb_beta, block.full_block_size());
                cb_wait_front(cb_fusion, block.full_block_size());
                add_bcast_rows_init_short(cb_fusion, cb_beta);
                for (auto i : block.local()) {
                    add_tiles_bcast_rows(cb_fusion, cb_beta, i, i, i);
#ifdef SFPU_OP_INIT_ACTIVATION
                    SFPU_OP_INIT_ACTIVATION
                    SFPU_OP_FUNC_ACTIVATION
#endif
                }
                tile_regs_commit();
                cb_pop_front(cb_beta, block.full_block_size());
                cb_pop_front(cb_fusion, block.full_block_size());
                cb_reserve_back(cb_out, block.full_block_size());
                for (auto i : block.local()) {
                    pack_tile(i, cb_out);
                }
                tile_regs_release();
                cb_push_back(cb_out, block.full_block_size());
                // DPRINT << "[compute] applied beta for block" << block.start() << ENDL();
            }

#ifdef UNTILIZE_OUT
            // DPRINT_PACK(DPRINT << "[lt normalize] untilize block_size =" << block_size
            //                    << " block.start=" << block.start() << ENDL();)
            constexpr auto cb_out_rm = tt::CBIndex::c_28;
            untilize_row_major_block<decltype(block), block_size>(cb_out, cb_out_rm, block);
#endif
            // DPRINT_PACK(DPRINT << "[lt normalize] end of block_size =" << block_size << " block.start=" <<
            // block.start()
            //                    << ENDL();)
        }  // block loop
        // End of
        // Final Val Calc
        //    x-E[X]
        //(---------------*𝛄)+ß
        //  √(Var(X)+ε)
#ifndef RMSNORM
        cb_pop_front(cb_ex, onetile);
#endif
        cb_pop_front(cb_ex2pe, onetile);
    }  // NCHt loop

    DPRINT << "end of compute kernel" << ENDL();
}
