// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
//
// SPDX-License-Identifier: Apache-2.0

#include <cstdint>
#define REDUCE_OP PoolType::SUM
#define REDUCE_DIM ReduceDim::REDUCE_ROW

#define BCAST_LLKOP EltwiseBinaryType::ELWMUL
#define BCAST_DIM BroadcastType::COL

#include "compute_kernel_api.h"
#include "compute_kernel_api/reduce.h"
#include "compute_kernel_api/bcast.h"
#include "compute_kernel_api/eltwise_binary.h"
#include "compute_kernel_api/layernorm.h"
#include "compute_kernel_api/eltwise_binary_sfpu.h"
#include "compute_kernel_api/tile_move_copy.h"
#include "compute_kernel_api/welford.h"
#include "compute_kernel_api/transpose_wh_dest.h"
namespace NAMESPACE {

void MAIN {
    uint32_t NCHt = get_arg_val<uint32_t>(0);
    constexpr uint32_t Wt = get_compile_time_arg_val(0);
    constexpr uint32_t blk = get_compile_time_arg_val(1);
    constexpr uint32_t do_gamma = get_compile_time_arg_val(2);
    constexpr uint32_t do_beta = get_compile_time_arg_val(3);
    constexpr bool FLOAT32_DTYPE = get_compile_time_arg_val(4) == 1;
    constexpr uint32_t W = get_compile_time_arg_val(5);
    constexpr uint32_t tile_width = get_compile_time_arg_val(6);
    constexpr bool rms_norm = static_cast<bool>(get_compile_time_arg_val(7));
    constexpr bool fuse_pre_add = static_cast<bool>(get_compile_time_arg_val(8));

    constexpr uint32_t onetile = 1;
    // reserve one tile for zeros on cb_in2
    // TODO(AP): check that if DST is indeed zeroed by release_dst (and initially), we can use it as zeroes

    // Note that the entire W dimension must fit in the intermed0 CB for this kernel to be correct
    constexpr auto cb_scaler = tt::CBIndex::c_2;  // single tile generated by the reader
    constexpr auto cb_eps = tt::CBIndex::c_3;     // single tile generated by the reader
    constexpr auto cb_in = tt::CBIndex::c_0;      // input x or a for fused pre-add (x=a+b)
    constexpr auto cb_inb = tt::CBIndex::c_1;     // input b for fused pre-add
    constexpr auto cb_out = tt::CBIndex::c_16;    // output
    constexpr auto cb_gamma = tt::CBIndex::c_5;
    constexpr auto cb_beta = tt::CBIndex::c_6;
    uint32_t cb_xmm = tt::CBIndex::c_24;           // x minus mean (or x^2 for RMS norm)
    constexpr auto cb_ex = tt::CBIndex::c_18;      // E[x]
    constexpr auto cb_ex2 = tt::CBIndex::c_19;     // Var[x] = E[(x-E[x])^2] (or (∑x^2)/n for RMS norm)
    constexpr auto cb_ex2pe = tt::CBIndex::c_21;   // E[(x-E[x])^2]+ε (or (∑x^2)/n+ε for RMS norm)
    constexpr auto cb_fusion = tt::CBIndex::c_22;  // stream gamma/beta
    constexpr auto scaler0 = 0;
    constexpr auto layernorm = !rms_norm;

    if constexpr (fuse_pre_add) {
        if constexpr (rms_norm) {
            constexpr uint32_t cb_x = cb_xmm;
        } else {
            constexpr uint32_t cb_x = tt::CBIndex::c_23;
        }
        binary_op_init_common(cb_in, cb_inb, cb_x);
    } else {
        constexpr uint32_t cb_x = cb_in;
    }

    cb_wait_front(cb_scaler, 1);  // comes from the reader
    cb_wait_front(cb_eps, 1);     // comes from the reader

    constexpr int onetile = 1;
    constexpr int dst0 = 0;
    constexpr int dst1 = 1;
    constexpr int dst2 = 2;

    if constexpr (layernorm) {
        uint32_t start_N = 1;
    }

    for (uint32_t ncht = 0; ncht < NCHt; ncht++) {
        tile_regs_acquire();
        tile_regs_wait();

        // =====================================
        // First pass over the input.
        // Layernorm: Calculate E[x] and Var[x]
        // RMS norm: Calculate (∑x^2)/n
        // =====================================
        for (uint32_t wt = 0; wt < Wt; wt += blk) {
            // Wait for block of input
            cb_wait_front(cb_in, blk);

            if constexpr (layernorm) {
                // Layernorm: Calculate E[x] and Var[x] using Welford's algorithm
                // Go tile-by-tile in the block
                for (uint32_t j = 0; j < blk; j++) {
                    // Copy input tile to dst0
                    copy_tile_init(cb_in);  // TODO RM: Is this needed every iteration?
                    copy_tile(cb_in, j, dst0);

                    if constexpr (fuse_pre_add) {
                        // Fuse in = in + b in dst0
                        cb_wait_front(cb_inb, 1);
                        reconfig_data_format_srca(cb_in, cb_inb);
                        binary_dest_reuse_tiles_init<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb);
                        binary_dest_reuse_tiles<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb, dst0, dst0);
                        cb_pop_front(cb_inb, 1);
                    }

                    // Accumulate E[x] and Var[x].
                    // Welford's requires a transposed input tile
                    transpose_wh_dest_init_short();
                    transpose_wh_dest(dst0);
                    reconfig_data_format(cb_in, cb_scaler);  // TODO RM: Is this needed every iteration?
                    welford_init();
                    welford(dst0, dst1, dst2, start_N, W, wt + j + 1 == Wt);
                    start_N += tile_width;
                }
                // TODO RM: Is this needed every iteration?
                pack_reconfig_data_format(cb_ex);
                pack_reconfig_data_format(cb_ex2);

                cb_reserve_back(cb_ex, onetile);
                cb_reserve_back(cb_ex2, onetile);
                pack_tile(dst1, cb_ex);
                pack_tile(dst2, cb_ex2);
                cb_push_back(cb_ex, onetile);
                cb_push_back(cb_ex2, onetile);
            } else {
                // RMS: Calculate (∑x^2)/n
                // Copy tiles in block to dst regs
                copy_tile_init(cb_in);  // TODO RM: Is this needed every iteration?
                for (uint32_t j = 0; j < blk; j++) {
                    copy_tile(cb_in, j, j);
                }
                cb_pop_front(cb_in, blk);

                if constexpr (fuse_pre_add) {
                    // Fuse in = in + b
                    reconfig_data_format_srca(cb_in, cb_inb);
                    cb_wait_front(cb_inb, blk);
                    for (uint32_t j = 0; j < blk; j++) {
                        binary_dest_reuse_tiles_init<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb);
                        binary_dest_reuse_tiles<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb, j, j);
                    }
                    cb_pop_front(cb_inb, blk);
                }

                // Square tiles in dst regs
                square_tile_init();
                for (uint32_t j = 0; j < blk; j++) {
                    square_tile(j);
                }

                // Accumulate squares
                add_binary_tile_init();
                for (uint32_t j = 0; j < blk - 1; j++) {
                    add_binary_tile(j, j + 1);
                }

                // Multiply by scalar to get (∑x^2)/n
                binary_dest_reuse_tiles_init<ELWMUL, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_scaler);
                binary_dest_reuse_tiles<ELWMUL, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_scaler, 0, dst0);

                // Push to CB
                cb_reserve_back(cb_ex2, onetile);
                pack_tile(dst0, cb_ex2);
                cb_push_back(cb_ex2, onetile);
            }
        }

        // =====================================
        // Calculate 1/(√(Var(X) + ε)).
        // Var[x] for RMS norm is (∑x^2)/n
        // =====================================
        tile_regs_acquire();
        tile_regs_wait();

        cb_wait_front(cb_ex2, onetile);

        reconfig_data_format(cb_ex2, cb_eps);

        add_tiles_init(cb_ex2, cb_eps);
        add_tiles(cb_ex2, cb_eps, 0, 0, dst0);

        sqrt_tile_init();
        sqrt_tile(dst0);

        recip_tile_init();
        recip_tile(dst0);

        tile_regs_commit();

        pack_tile(dst0, cb_ex2pe);
        cb_push_back(cb_ex2pe, onetile);
        tile_regs_release();

        cb_pop_front(cb_ex2, onetile);
        cb_wait_front(cb_ex2pe, onetile);

        // broadcasts the tile since cb_ex2pe is a column vector that contains the important data
        tile_regs_acquire();
        tile_regs_wait();
        reconfig_data_format_srca(cb_ex2pe);
        unary_bcast_init<BroadcastType::COL>(cb_ex2pe, cb_ex2pe);
        unary_bcast<BroadcastType::COL>(cb_ex2pe, 0, dst0);
        cb_pop_front(cb_ex2pe, onetile);
        tile_regs_commit();
        pack_tile(dst0, cb_ex2pe);
        tile_regs_release();
        cb_push_back(cb_ex2pe, onetile);

        // =====================================
        // Second pass over the input.
        // Computes the final value.
        // Layernorm:
        //    x-E[x]
        //(---------------*𝛄)+ß
        //  √(Var(x)+ε)
        // RMS norm:
        //    x
        //(---------------*𝛄)+ß
        //  √(Var(X)+ε)
        for (uint32_t wt = 0; wt < Wt; wt += blk) {
            tile_regs_acquire();
            tile_regs_wait();
            cb_reserve_back(cb_out, blk);
            cb_wait_front(cb_ex, 1);
            cb_wait_front(cb_in, blk);
            if constexpr (rms_norm) {
                // RMS: Just copy input
                reconfig_data_format_srca(cb_in);
                copy_tile_init(cb_in);
                for (uint32_t j = 0; j < blk; j++) {
                    copy_tile(cb_in, j, j);
                }
            } else {
                // Layernorm: Calculate x-E[x]
                reconfig_data_format(cb_in, cb_ex);
                sub_bcast_cols_init_short(cb_in, cb_ex);
                // x-E[x]
                for (uint32_t j = 0; j < blk; j++) {
                    sub_tiles_bcast_cols(cb_in, cb_ex, j, 0, j);
                }
            }
            cb_pop_front(cb_in, blk);
            reconfig_data_format_srca(cb_in, cb_ex2pe);

            if constexpr (fuse_pre_add) {
                // Fuse in = in + b
                cb_wait_front(cb_inb, blk);
                reconfig_data_format_srca(cb_ex2pe, cb_inb);
                binary_dest_reuse_tiles_init<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb);
                for (uint32_t j = 0; j < blk; j++) {
                    binary_dest_reuse_tiles<ELWADD, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_inb, j, j);
                }
                cb_pop_front(cb_inb, blk);
                reconfig_data_format_srca(cb_inb, cb_ex2pe);
            }

            // Multiply by 1/(√(Var(X) + ε))
            cb_wait_front(cb_ex2pe, 1);
            binary_dest_reuse_tiles_init<ELWMUL, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_ex2pe);
            for (uint32_t j = 0; j < blk; j++) {
                binary_dest_reuse_tiles<ELWMUL, EltwiseBinaryReuseDestType::DEST_TO_SRCB>(cb_ex2pe, 0, j);
            }
            tile_regs_commit();
            if constexpr (!(do_gamma == 1 or do_beta == 1)) {
                cb_xmm = cb_out;
            }
            pack_reconfig_data_format(cb_xmm);
            cb_reserve_back(cb_xmm, blk);
            for (uint32_t j = 0; j < blk; j++) {
                pack_tile(j, cb_xmm);
            }
            cb_push_back(cb_xmm, blk);
            tile_regs_release();

            if constexpr (do_gamma == 1) {
                // Multiply by gamma
                tile_regs_acquire();
                tile_regs_wait();
                reconfig_data_format(cb_xmm, cb_gamma);
                if constexpr (!do_beta) {
                    pack_reconfig_data_format(cb_out);
                }
                cb_wait_front(cb_gamma, blk);
                if (ncht == 1) {
                    DPRINT << "\n\n\nFINAL VAL Pre Var Value wt: " << wt << ENDL();
                }
                cb_wait_front(cb_xmm, blk);
                mul_bcast_rows_init_short(cb_xmm, cb_gamma);
                for (uint32_t j = 0; j < blk; j++) {
                    mul_tiles_bcast_rows(cb_xmm, cb_gamma, j, j, j);
                }
                tile_regs_commit();
                cb_pop_front(cb_gamma, blk);
                cb_pop_front(cb_xmm, blk);
                if constexpr (!do_beta) {
                    cb_reserve_back(cb_out, blk);
                    for (uint32_t j = 0; j < blk; j++) {
                        pack_tile(j, cb_out);
                    }
                    cb_push_back(cb_out, blk);
                } else {
                    cb_reserve_back(cb_xmm, blk);
                    for (uint32_t j = 0; j < blk; j++) {
                        pack_tile(j, cb_xmm);
                    }
                    cb_push_back(cb_xmm, blk);
                }

                tile_regs_release();
            }
            if constexpr (do_beta == 1) {
                // Add beta
                tile_regs_acquire();
                tile_regs_wait();
                reconfig_data_format(cb_xmm, cb_beta);
                pack_reconfig_data_format(cb_out);
                cb_wait_front(cb_beta, blk);
                cb_wait_front(cb_xmm, blk);
                add_bcast_rows_init_short(cb_xmm, cb_beta);
                for (uint32_t j = 0; j < blk; j++) {
                    add_tiles_bcast_rows(cb_xmm, cb_beta, j, j, j);
                }
                tile_regs_commit();
                cb_pop_front(cb_beta, blk);
                cb_pop_front(cb_xmm, blk);
                cb_reserve_back(cb_out, blk);
                for (uint32_t j = 0; j < blk; j++) {
                    pack_tile(j, cb_out);
                }
                tile_regs_release();
                cb_push_back(cb_out, blk);
            }
        }

        UNPACK(DPRINT << "-----NCHt val: " << NCHt << "---------- ncht" << ncht << ENDL());
        cb_xmm = tt::CBIndex::c_24;  // x minus mean
        if constexpr (rms_norm) {
            cb_pop_front(cb_ex, 1);
        }
    }  // NCHt loop
}
}  // namespace NAMESPACE
