// SPDX-FileCopyrightText: © 2023 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0

#include <cstdint>

#define BCAST_LLKOP EltwiseBinaryType::ELWMUL
#define BCAST_DIM BroadcastType::COL

#include "api/compute/compute_kernel_api.h"
#include "api/compute/reduce.h"
#include "api/compute/bcast.h"
#include "api/compute/eltwise_binary.h"
#include "api/compute/layernorm.h"
#include "api/compute/eltwise_binary_sfpu.h"
#include "api/compute/tile_move_copy.h"
#include "experimental/kernel_args.h"
#include "ttnn/operations/normalization/kernel_util/compute/numeric.h"
#include "ttnn/operations/normalization/kernel_util/generic/blocked_range.h"
#include "api/dataflow/dataflow_buffer.h"

#include "layernorm_compute_utils.h"
#include "ttnn/cpp/ttnn/kernel_lib/reduce_helpers_compute.hpp"

namespace kutil = norm::kernel_util;
namespace numeric = kutil::compute::numeric;
namespace policies = kutil::compute::policies;
namespace generic = kutil::generic;

void kernel_main() {
    uint32_t NCHt = get_arg(args::NCHt);
    constexpr auto Wt = get_arg(args::Wt);
    constexpr auto block_size = get_arg(args::block_size);
    constexpr auto do_gamma = get_arg(args::do_gamma);
    constexpr auto do_beta = get_arg(args::do_beta);
    constexpr bool FLOAT32_DTYPE = get_arg(args::fp32_dest_acc_en) == 1;
    constexpr bool FLOAT32_REDUCTION = get_arg(args::float32_reduction) == 1;
    constexpr bool LEGACY_RSQRT = get_arg(args::legacy_rsqrt) == 1;
    constexpr auto W = get_arg(args::W);
    constexpr auto tile_width = get_arg(args::tile_width);

    constexpr uint32_t onetile = 1;

    // Buffer handles come from the host-side bindings; the kernel never sees an index.
    constexpr auto dfb_scaler_id = dfb::scaler;  // single tile generated by the reader
    constexpr auto dfb_eps_id = dfb::eps;        // single tile generated by the reader
    constexpr auto dfb_in_id = dfb::in;          // input x or a for fused pre-add (x=a+b)
#ifdef FUSE_PRE_ADD
    constexpr auto dfb_inb_id = dfb::inb;  // input b for fused pre-add
#endif
    constexpr auto dfb_out_id = dfb::out;  // output
#ifdef FUSE_GAMMA
    constexpr auto dfb_gamma_id = dfb::gamma;
#endif
#ifdef FUSE_BETA
    constexpr auto dfb_beta_id = dfb::beta;
#endif
    constexpr auto dfb_xmm_id = dfb::xmm;  // x minus mean
#ifndef RMSNORM
    constexpr auto dfb_ex_id = dfb::ex;  // E[x]
#endif
    constexpr auto dfb_ex2_id = dfb::ex2;      // E[(x-E[x])^2]
    constexpr auto dfb_xmm2_id = dfb::xmm2;    // xmm^2
    constexpr auto dfb_ex2pe_id = dfb::ex2pe;  // E[(x-E[x])^2]+eps
    // Where the normalized tiles are staged. With gamma or beta to fold in this is the streaming
    // intermediate; otherwise it is the output buffer, and the per-block reassignment below is a
    // no-op.
#if defined(FUSE_GAMMA) || defined(FUSE_BETA)
    uint32_t dfb_fusion = dfb::fusion;  // stream gamma/beta
#else
    uint32_t dfb_fusion = dfb_out_id;
#endif
    constexpr auto scaler0 = 0;
    constexpr auto dfb_accumulate_id = dfb::accumulate;  // For accumulating (x-E[x])^2

#ifdef TILIZE_IN
    constexpr auto dfb_in_rm_id = dfb::in_rm;  // row-major input staging
#endif

    DataflowBuffer dfb_eps(dfb_eps_id);
    DataflowBuffer dfb_in(dfb_in_id);
#ifdef FUSE_PRE_ADD
    DataflowBuffer dfb_inb(dfb_inb_id);
#endif
    DataflowBuffer dfb_out(dfb_out_id);
#ifdef FUSE_GAMMA
    DataflowBuffer dfb_gamma(dfb_gamma_id);
#endif
#ifdef FUSE_BETA
    DataflowBuffer dfb_beta(dfb_beta_id);
#endif
    DataflowBuffer dfb_xmm(dfb_xmm_id);
#ifndef RMSNORM
    DataflowBuffer dfb_ex(dfb_ex_id);
#endif
    DataflowBuffer dfb_ex2(dfb_ex2_id);
    DataflowBuffer dfb_xmm2(dfb_xmm2_id);
    DataflowBuffer dfb_ex2pe(dfb_ex2pe_id);
    DataflowBuffer dfb_accumulate(dfb_accumulate_id);
    DataflowBuffer dfb_scaler(dfb_scaler_id);
#ifdef TILIZE_IN
    DataflowBuffer dfb_in_rm(dfb_in_rm_id);
#endif

    // Either the input itself, or the post-add result when a residual is fused in. Only the
    // non-RMSNORM fused case needs a buffer of its own.
#ifdef FUSE_PRE_ADD
#ifdef RMSNORM
    constexpr auto dfb_x_id = dfb_xmm_id;
    DataflowBuffer& dfb_x = dfb_xmm;
#else
    constexpr auto dfb_x_id = dfb::x;
    DataflowBuffer dfb_x(dfb_x_id);
#endif
#else
    constexpr auto dfb_x_id = dfb_in_id;
    DataflowBuffer& dfb_x = dfb_in;
#endif

#ifdef FUSE_PRE_ADD
    compute_kernel_hw_startup(dfb_in_id, dfb_inb_id, dfb_x_id);
#else
    // Always call compute_kernel_hw_startup regardless of TILIZE_IN.
    // This initializes llk_pack_dest_init, which sets up the MATH-PACK DST semaphore
    // in the "available for MATH" state. Without it, the first tilize_block call's
    // internal llk_math_wait_for_dest_available() spins forever (deadlock).
#ifdef RMSNORM
    compute_kernel_hw_startup(dfb_in_id, dfb_scaler_id, dfb_xmm2_id);
#else
    compute_kernel_hw_startup(dfb_in_id, dfb_scaler_id, dfb_ex_id);
#endif
#endif
    dfb_eps.wait_front(1);  // comes from the reader

    for (uint32_t ncht = 0; ncht < NCHt; ncht++) {
        constexpr int onetile = 1;
        constexpr int dst0 = 0;
#ifndef RMSNORM
        // Start of
        //  E[x]
        //  aka   ∑(x)
        //      --------
        //         n
#ifdef FUSE_PRE_ADD
        numeric::row_wise_mean_with_pre_add<
            PoolType::SUM,
            ReduceDim::REDUCE_ROW,
            FLOAT32_REDUCTION,
            policies::FullBlockWithPopPolicy>(dfb_in, dfb_inb, dfb_scaler, dfb_ex, W, Wt, block_size, tile_width);
#else
        numeric::
            row_wise_mean<PoolType::SUM, ReduceDim::REDUCE_ROW, FLOAT32_REDUCTION, policies::FullBlockWithPopPolicy>(
                dfb_in, dfb_scaler, dfb_ex, W, Wt, block_size, tile_width);
#endif
#endif  // !RMS ifdef end
        // Start of
        // Var Calculation
        // Var(X) = ∑(x-E[x])^2
        //         -----------
        //              n
        const bool last_tile_is_partial = W % tile_width > 0;
        for (auto block : generic::blocks(Wt, block_size)) {
#ifdef TILIZE_IN
            tilize_row_major_block(dfb_in_rm, dfb_in, block_size, block);
#ifdef RMSNORM
            // TODO(#52395): compute_kernel_hw_startup is a call-once API; this mid-kernel re-init (preserving the
            // pre-cleanup full-init behaviour) should become a targeted DST re-arm.
            compute_kernel_hw_startup(dfb_in_id, dfb_scaler_id, dfb_xmm2_id);
#else
            // TODO(#52395): compute_kernel_hw_startup is a call-once API; this mid-kernel re-init (preserving the
            // pre-cleanup full-init behaviour) should become a targeted DST re-arm.
            compute_kernel_hw_startup(dfb_in_id, dfb_scaler_id, dfb_ex_id);
#endif
#endif
            dfb_in.wait_front(block.full_block_size());
            tile_regs_acquire();
#ifdef RMSNORM
            reconfig_data_format_srca(dfb_in_id);
            copy_tile_init(dfb_in_id);
            for (auto i : block.local()) {
                copy_tile(dfb_in_id, i, i);
            }
#else
            // x-E[x]
            reconfig_data_format(dfb_in_id, dfb_ex_id);
            sub_bcast_cols_init(dfb_in_id, dfb_ex_id);
            for (auto i : block.local()) {
                sub_tiles_bcast_cols(dfb_in_id, dfb_ex_id, i, 0, i);
            }
#endif
            dfb_in.pop_front(block.full_block_size());
#ifdef FUSE_PRE_ADD
            dfb_inb.wait_front(block.full_block_size());
            reconfig_data_format_srca(dfb_in_id, dfb_inb_id);
            add_reuse_dest_init<EltwiseBinaryReuseDestType::DEST_TO_SRCB>(dfb_inb_id);
            for (auto i : block.local()) {
                add_reuse_dest_tiles<EltwiseBinaryReuseDestType::DEST_TO_SRCB>(dfb_inb_id, i, i);
            }
            dfb_inb.pop_front(block.full_block_size());
#endif
            // (x-E[x])^2. Pack to the buffer
            square_tile_init();
            for (auto i : block.local()) {
                square_tile(i);
            }
            tile_regs_commit();
            tile_regs_wait();
            dfb_xmm2.reserve_back(block.full_block_size());
            pack_reconfig_data_format(dfb_xmm2_id);
            for (auto i : block.local()) {
                pack_tile(i, dfb_xmm2_id);
            }
            tile_regs_release();
            dfb_xmm2.push_back(block.full_block_size());

            tile_regs_acquire();
            if (!block.is_first()) {
                dfb_accumulate.wait_front(onetile);
                reconfig_data_format_srca(dfb_accumulate_id);
                copy_tile_init(dfb_accumulate_id);
                copy_tile(dfb_accumulate_id, 0, dst0);
                dfb_accumulate.pop_front(onetile);
            }
            dfb_xmm2.wait_front(block.full_block_size());

            // Accumulate (x-E[x])^2
            reconfig_data_format(dfb_scaler_id, dfb_xmm2_id);
            reduce_init<PoolType::SUM, ReduceDim::REDUCE_ROW>(dfb_xmm2_id, dfb_scaler_id, dfb_accumulate_id);
            for (auto i : block.local()) {
                const auto scaler_tile_idx = block.to_global(i) == Wt - 1 && last_tile_is_partial ? 1 : 0;
                reduce_tile<PoolType::SUM, ReduceDim::REDUCE_ROW>(dfb_xmm2_id, dfb_scaler_id, i, scaler_tile_idx, dst0);
            }

            dfb_xmm2.pop_front(block.full_block_size());

            const auto final_iter = block.last() == Wt;
            const auto pack_dfb = final_iter ? dfb_ex2_id : dfb_accumulate_id;
            if (final_iter) {
                // Divide by W
                binop_with_scalar_tile_init();
                mul_unary_tile(dst0, generic::bit_cast<uint32_t>(1.0f / W));
            }

            reduce_uninit();
            tile_regs_commit();
            tile_regs_wait();

            DataflowBuffer(pack_dfb).reserve_back(onetile);
            pack_reconfig_data_format(pack_dfb);
            pack_tile(dst0, pack_dfb);
            tile_regs_release();
            DataflowBuffer(pack_dfb).push_back(onetile);
        }

        // End of
        // Var Calculation
        // Var(X) = ∑(x-E[x])^2
        //         -----------

        // Start of
        // Calculation
        //                     1
        //  dfb_ex2pe =   -------------
        //               √(Var(X) + ε)
        dfb_ex2.wait_front(onetile);
        reconfig_data_format(dfb_ex2_id, dfb_eps_id);
        tile_regs_acquire();

        add_init(dfb_ex2_id, dfb_eps_id);
        add_tiles(dfb_ex2_id, dfb_eps_id, 0, 0, dst0);

        rsqrt_tile_init<LEGACY_RSQRT>();
        rsqrt_tile<LEGACY_RSQRT>(dst0);

        tile_regs_commit();
        tile_regs_wait();
        pack_reconfig_data_format(dfb_ex2pe_id);
        pack_tile(dst0, dfb_ex2pe_id);
        tile_regs_release();
        dfb_ex2pe.push_back(onetile);
        dfb_ex2.pop_front(onetile);

        // broadcasts the tile since dfb_ex2pe is a column vector that contains the important data
        dfb_ex2pe.wait_front(onetile);
        tile_regs_acquire();
        reconfig_data_format_srca(dfb_ex2pe_id);

        // TODO(#52395): compute_kernel_hw_startup is a call-once API; this mid-kernel re-init (preserving the
        // pre-cleanup full-init behaviour) should become a targeted DST re-arm.
        compute_kernel_hw_startup(dfb_ex2pe_id, dfb_ex2pe_id);
        unary_bcast_init<BroadcastType::COL>(dfb_ex2pe_id);
        unary_bcast<BroadcastType::COL>(dfb_ex2pe_id, 0, dst0);
        dfb_ex2pe.pop_front(onetile);

        tile_regs_commit();
        tile_regs_wait();
        pack_tile(dst0, dfb_ex2pe_id);
        tile_regs_release();
        dfb_ex2pe.push_back(onetile);
        dfb_ex2pe.wait_front(onetile);

        // End of
        // Calculation
        //                     1
        //  dfb_ex2pe =   -------------
        //               √(Var(X) + ε)

        // Start of
        // Final Val Calc
        //    x-E[X]
        //(---------------*𝛄)+ß
        //  √(Var(X)+ε)
        for (auto block : generic::blocks(Wt, block_size)) {
#ifdef TILIZE_IN
            // Tilize one block from dfb_in_rm → dfb_in per loop iteration (Pass 2).
            // Reader supplies this second pass of data after the variance data.
            tilize_row_major_block(dfb_in_rm, dfb_in, block_size, block);

#ifdef RMSNORM
            // TODO(#52395): compute_kernel_hw_startup is a call-once API; this mid-kernel re-init (preserving the
            // pre-cleanup full-init behaviour) should become a targeted DST re-arm.
            compute_kernel_hw_startup(dfb_in_id, dfb_scaler_id, dfb_xmm2_id);
#else
            // TODO(#52395): compute_kernel_hw_startup is a call-once API; this mid-kernel re-init (preserving the
            // pre-cleanup full-init behaviour) should become a targeted DST re-arm.
            compute_kernel_hw_startup(dfb_in_id, dfb_scaler_id, dfb_ex_id);
#endif
#endif
            tile_regs_acquire();
            dfb_in.wait_front(block.full_block_size());
#ifdef RMSNORM
            reconfig_data_format_srca(dfb_in_id);
            copy_tile_init(dfb_in_id);
            for (auto i : block.local()) {
                copy_tile(dfb_in_id, i, i);
            }
#else
            dfb_ex.wait_front(1);
            reconfig_data_format(dfb_in_id, dfb_ex_id);
            sub_bcast_cols_init(dfb_in_id, dfb_ex_id);
            // x-E[x]
            for (auto i : block.local()) {
                sub_tiles_bcast_cols(dfb_in_id, dfb_ex_id, i, 0, i);
            }
#endif
            dfb_in.pop_front(block.full_block_size());
#ifdef FUSE_PRE_ADD
            dfb_inb.wait_front(block.full_block_size());
            reconfig_data_format_srca(dfb_inb_id);
            add_reuse_dest_init<EltwiseBinaryReuseDestType::DEST_TO_SRCB>(dfb_inb_id);
            for (auto i : block.local()) {
                add_reuse_dest_tiles<EltwiseBinaryReuseDestType::DEST_TO_SRCB>(dfb_inb_id, i, i);
            }
            dfb_inb.pop_front(block.full_block_size());
#endif
            tile_regs_commit();
            tile_regs_wait();
            // Note: We shouldn't have to pack to
            // an intermediate buffer. We should be able to
            // do a binary dest with reuse (as we used
            // to). However, tt-llk #868 is preventing
            // that from working at the moment.
            dfb_xmm.reserve_back(block.full_block_size());
            pack_reconfig_data_format(dfb_xmm_id);
            for (auto i : block.local()) {
                pack_tile(i, dfb_xmm_id);
            }
            dfb_xmm.push_back(block.full_block_size());
            tile_regs_release();

            dfb_xmm.wait_front(block.full_block_size());
            reconfig_data_format(dfb_xmm_id, dfb_ex2pe_id);
            tile_regs_acquire();

            mul_init(dfb_xmm_id, dfb_ex2pe_id);
            for (auto i : block.local()) {
                mul_tiles(dfb_xmm_id, dfb_ex2pe_id, i, 0, i);
#ifdef SFPU_OP_INIT_ACTIVATION
                // Activation must be applied last. If do_gamma != 0 or do_beta != 0 then
                // activation will be applied after the gamma/beta multiplication/addition.
                // Otherwise, we can apply the activation here.
                if constexpr (!(do_gamma == 1 || do_beta == 1)) {
                    SFPU_OP_INIT_ACTIVATION
                    SFPU_OP_FUNC_ACTIVATION
                }
#endif
            }
            tile_regs_commit();
            tile_regs_wait();

            if constexpr (!(do_gamma == 1 or do_beta == 1)) {
                dfb_fusion = dfb_out_id;
            }
            DataflowBuffer(dfb_fusion).reserve_back(block.full_block_size());
            pack_reconfig_data_format(dfb_fusion);
            for (auto i : block.local()) {
                pack_tile(i, dfb_fusion);
            }
            tile_regs_release();
            DataflowBuffer(dfb_fusion).push_back(block.full_block_size());
            dfb_xmm.pop_front(block.full_block_size());

#ifdef FUSE_GAMMA
            {
                tile_regs_acquire();
                tile_regs_wait();
                reconfig_data_format(dfb_fusion, dfb_gamma_id);
#ifndef FUSE_BETA
                pack_reconfig_data_format(dfb_out_id);
#endif
                dfb_gamma.wait_front(block.full_block_size());
                DataflowBuffer(dfb_fusion).wait_front(block.full_block_size());
                mul_bcast_rows_init(dfb_fusion, dfb_gamma_id);
                for (auto i : block.local()) {
                    mul_tiles_bcast_rows(dfb_fusion, dfb_gamma_id, i, i, i);
#ifdef SFPU_OP_INIT_ACTIVATION
                    // Activation must be applied last. If do_beta != 0 then
                    // activation will be applied after the beta addition.
                    // Otherwise, we can apply the activation here.
                    if constexpr (!(do_beta == 1)) {
                        SFPU_OP_INIT_ACTIVATION
                        SFPU_OP_FUNC_ACTIVATION
                    }
#endif
                }
                tile_regs_commit();
                dfb_gamma.pop_front(block.full_block_size());
                DataflowBuffer(dfb_fusion).pop_front(block.full_block_size());
#ifndef FUSE_BETA
                dfb_out.reserve_back(block.full_block_size());
                for (auto i : block.local()) {
                    pack_tile(i, dfb_out_id);
                }
                dfb_out.push_back(block.full_block_size());
#else
                DataflowBuffer(dfb_fusion).reserve_back(block.full_block_size());
                for (auto i : block.local()) {
                    pack_tile(i, dfb_fusion);
                }
                DataflowBuffer(dfb_fusion).push_back(block.full_block_size());
#endif

                tile_regs_release();
            }
#endif
#ifdef FUSE_BETA
            {
                tile_regs_acquire();
                tile_regs_wait();
                reconfig_data_format(dfb_fusion, dfb_beta_id);
                pack_reconfig_data_format(dfb_out_id);
                dfb_beta.wait_front(block.full_block_size());
                DataflowBuffer(dfb_fusion).wait_front(block.full_block_size());
                add_bcast_rows_init(dfb_fusion, dfb_beta_id);
                for (auto i : block.local()) {
                    add_tiles_bcast_rows(dfb_fusion, dfb_beta_id, i, i, i);
#ifdef SFPU_OP_INIT_ACTIVATION
                    SFPU_OP_INIT_ACTIVATION
                    SFPU_OP_FUNC_ACTIVATION
#endif
                }
                tile_regs_commit();
                dfb_beta.pop_front(block.full_block_size());
                DataflowBuffer(dfb_fusion).pop_front(block.full_block_size());
                dfb_out.reserve_back(block.full_block_size());
                for (auto i : block.local()) {
                    pack_tile(i, dfb_out_id);
                }
                tile_regs_release();
                dfb_out.push_back(block.full_block_size());
            }
#endif

#ifdef UNTILIZE_OUT
            constexpr auto dfb_out_rm_id = dfb::out_rm;
            DataflowBuffer dfb_out_rm(dfb_out_rm_id);
            untilize_row_major_block<decltype(block), block_size>(dfb_out, dfb_out_rm, block);
#endif
        }  // block loop
        // End of
        // Final Val Calc
        //    x-E[X]
        //(---------------*𝛄)+ß
        //  √(Var(X)+ε)
#ifndef RMSNORM
        dfb_ex.pop_front(onetile);
#endif
        dfb_ex2pe.pop_front(onetile);
    }  // NCHt loop
}
