// SPDX-FileCopyrightText: © 2023 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0

#include <cstdint>

#define BCAST_LLKOP EltwiseBinaryType::ELWMUL
#define BCAST_DIM BroadcastType::COL

#include "api/compute/bcast.h"
#include "api/compute/eltwise_binary.h"
#include "api/compute/eltwise_binary_sfpu.h"
#include "api/compute/tile_move_copy.h"
#include "api/compute/eltwise_unary/rsqrt.h"
#include "api/compute/welford.h"
#include "api/compute/transpose.h"
#include "api/compute/transpose_dest.h"
#include "api/compute/compute_kernel_hw_startup.h"
#include "api/compute/experimental/layernorm.h"
#include "api/compute/sfpu_binary_bcast.h"
#include "experimental/kernel_args.h"
#include "ttnn/operations/normalization/kernel_util/compute/memory.h"
#include "ttnn/operations/normalization/kernel_util/generic/blocked_range.h"
#include "api/dataflow/dataflow_buffer.h"

namespace kutil = norm::kernel_util;
namespace generic = kutil::generic;

void kernel_main() {
    uint32_t NCHt = get_arg(args::NCHt);
    constexpr auto Wt = get_arg(args::Wt);
    constexpr auto blk = get_arg(args::block_size);
    constexpr auto do_gamma = get_arg(args::do_gamma);
    constexpr auto do_beta = get_arg(args::do_beta);
    constexpr bool FLOAT32_DTYPE = get_arg(args::fp32_dest_acc_en) == 1;
    constexpr auto W = get_arg(args::W);
    constexpr auto tile_width = get_arg(args::tile_width);
    constexpr bool fuse_pre_add = static_cast<bool>(get_arg(args::fuse_pre_add));
    constexpr auto reciprocal_w = get_arg(args::reciprocal_w);
#ifdef COMPACT_FP32_FINALIZER
    constexpr bool compact_fp32_finalizer = true;
#else
    constexpr bool compact_fp32_finalizer = false;
#endif

    constexpr uint32_t onetile = 1;

    // Buffer handles come from the host-side bindings; the kernel never sees an index.
    constexpr auto dfb_eps = dfb::eps;  // single tile generated by the reader
    constexpr auto dfb_in = dfb::in;    // input x or a for fused pre-add (x=a+b)
#ifdef FUSE_PRE_ADD
    constexpr auto dfb_inb = dfb::inb;  // input b for fused pre-add
#endif
    constexpr auto dfb_out = dfb::out;  // output
#ifdef FUSE_GAMMA
    constexpr auto dfb_gamma = dfb::gamma;
#endif
#ifdef FUSE_BETA
    constexpr auto dfb_beta = dfb::beta;
#endif
    constexpr auto dfb_xmm = dfb::xmm;  // x - E[x]

    constexpr auto dfb_ex = dfb::ex;        // E[x]
    constexpr auto dfb_ex2 = dfb::ex2;      // E[(x-E[x])^2]
    constexpr auto dfb_ex2pe = dfb::ex2pe;  // E[(x-E[x])^2]+eps
#if defined(FUSE_GAMMA) || defined(FUSE_BETA)
    constexpr auto dfb_fusion = dfb::fusion;  // stream gamma/beta
#endif
    DataflowBuffer dfb_eps_obj(dfb_eps);
    DataflowBuffer dfb_in_obj(dfb_in);
#ifdef FUSE_PRE_ADD
    DataflowBuffer dfb_inb_obj(dfb_inb);
#endif
    DataflowBuffer dfb_out_obj(dfb_out);
#ifdef FUSE_GAMMA
    DataflowBuffer dfb_gamma_obj(dfb_gamma);
#endif
#ifdef FUSE_BETA
    DataflowBuffer dfb_beta_obj(dfb_beta);
#endif
    DataflowBuffer dfb_xmm_obj(dfb_xmm);
    DataflowBuffer dfb_ex_obj(dfb_ex);
    DataflowBuffer dfb_ex2_obj(dfb_ex2);
    DataflowBuffer dfb_ex2pe_obj(dfb_ex2pe);
#if defined(FUSE_GAMMA) || defined(FUSE_BETA)
    DataflowBuffer dfb_fusion_obj(dfb_fusion);
#endif

    // Where the normalized tiles land before gamma/beta are applied: the streaming intermediate
    // when there is gamma or beta to fold in, otherwise the output buffer directly.
#if defined(FUSE_GAMMA) || defined(FUSE_BETA)
    constexpr auto dfb_im_or_out = dfb_fusion;
    DataflowBuffer& dfb_im_or_out_obj = dfb_fusion_obj;
#else
    constexpr auto dfb_im_or_out = dfb_out;
    DataflowBuffer& dfb_im_or_out_obj = dfb_out_obj;
#endif

    //  Either in or in + b if doing fused pre-add
#ifdef FUSE_PRE_ADD
    constexpr auto dfb_x = dfb::x;
    DataflowBuffer dfb_x_obj(dfb_x);
#else
    constexpr auto dfb_x = dfb_in;
    DataflowBuffer& dfb_x_obj = dfb_in_obj;
#endif

    // Welford-fp32 alias of dfb_x. Shares SRAM with dfb_x but has its own buffer index
    // configured with UnpackToDest. Welford's transpose_tile reads
    // through dfb_x_welford to get full fp32 into DEST; the post-welford eltwise keeps reading
    // dfb_x via SrcA. When the alias is inactive the name resolves to dfb_x itself.
#ifdef WELFORD_FP32_ALIAS
    constexpr bool welford_fp32_alias = true;
    constexpr auto dfb_x_welford = dfb::x_welford;
    DataflowBuffer dfb_x_welford_obj(dfb_x_welford);
#else
    constexpr bool welford_fp32_alias = false;
    constexpr auto dfb_x_welford = dfb_x;
    DataflowBuffer& dfb_x_welford_obj = dfb_x_obj;
#endif

#ifdef COMPACT_FP32_FINALIZER
    constexpr auto dfb_ex_welford = dfb::ex_welford;
    constexpr auto dfb_ex2pe_fp32 = dfb::ex2pe_fp32;
    DataflowBuffer dfb_ex_welford_obj(dfb_ex_welford);
    DataflowBuffer dfb_ex2pe_fp32_obj(dfb_ex2pe_fp32);
#else
    constexpr auto dfb_ex_welford = dfb_ex;
    constexpr auto dfb_ex2pe_fp32 = dfb_ex2pe;
    DataflowBuffer& dfb_ex_welford_obj = dfb_ex_obj;
    DataflowBuffer& dfb_ex2pe_fp32_obj = dfb_ex2pe_obj;
#endif

    constexpr uint32_t dst0 = 0;
    constexpr uint32_t input_dst = 0;
    constexpr uint32_t mean_dst = 1;
    constexpr uint32_t var_dst = 2;
    constexpr uint32_t retained_input_dst = 3;

    // The number of valid columns in the last tile in width dimension.
    // Because the statistics LLK is given transposed data, skip some rows when
    // we want to skip some columns from getting processed by layer_norm.
    constexpr uint32_t last_tile_rows = (W % tile_width) == 0 ? tile_width : W % tile_width;

    dfb_eps_obj.wait_front(1);  // comes from the reader

#ifdef FUSE_PRE_ADD
    compute_kernel_hw_startup(dfb_in, dfb_inb, dfb_x);
    pack_reconfig_data_format(dfb_x);
#else
    compute_kernel_hw_startup(dfb_in, dfb_ex);
    pack_reconfig_data_format(dfb_ex);
#endif

    // Intermediate buffers need to be reserved/pushed/popped
    // in full blocks
    const auto total_buffer_size = generic::blocks(Wt, blk).total_with_remainder();

    for (uint32_t ncht = 0; ncht < NCHt; ncht++) {
#ifdef FUSE_PRE_ADD
        // x = in + b
        add_init(dfb_in, dfb_inb);
        reconfig_data_format(dfb_in, dfb_inb);
        pack_reconfig_data_format(dfb_x);
        for (auto block : generic::blocks(Wt, blk)) {
            // In/inb come from the reader and need to be
            // synced on full block size. Keep dfb_x aligned
            // to full block size as well so pre-add/no-pre-add
            // can be handled the same way.
            dfb_in_obj.wait_front(block.full_block_size());
            dfb_inb_obj.wait_front(block.full_block_size());
            tile_regs_acquire();
            for (auto i : block.local()) {
                add_tiles(dfb_in, dfb_inb, i, i, i);
            }
            tile_regs_commit();
            dfb_in_obj.pop_front(block.full_block_size());
            dfb_inb_obj.pop_front(block.full_block_size());

            dfb_x_obj.reserve_back(block.full_block_size());
#ifdef WELFORD_FP32_ALIAS
            // Must be done in the compute kernel: on the fuse_pre_add path compute is the
            // producer of dfb_x via the add_tiles -> pack_tile sequence below; the reader
            // never writes dfb_x. Push the alias alongside dfb_x so Welford's wait_front on
            // dfb_x_welford sees the tiles.
            dfb_x_welford_obj.reserve_back(block.full_block_size());
#endif
            tile_regs_wait();
            for (auto i : block.local()) {
                pack_tile(i, dfb_x);
            }
            tile_regs_release();
            dfb_x_obj.push_back(block.full_block_size());  // push the sum into the same buffer
#ifdef WELFORD_FP32_ALIAS
            dfb_x_welford_obj.push_back(block.full_block_size());
#endif
        }
        reconfig_data_format(dfb_in, dfb_x, dfb_inb, dfb_ex);
#endif

        // Calculate E[x] and Var[x] using stable shifted two-pass statistics.
        reconfig_data_format_srca(dfb_x_welford);
        // Reconfigure the transpose op for the statistics intake buffer. When the alias is active,
        // dfb_x_welford has UnpackToDest mode so transpose_tile preserves fp32 precision.
        transpose_init(dfb_x_welford);
        tile_regs_acquire();
        two_pass_stats_init_shifted();
        // Process all but the last tile
        for (uint32_t wt = 0; wt < (Wt - 1); ++wt) {
            if constexpr (welford_fp32_alias) {
                dfb_x_welford_obj.wait_front(wt + 1);
            } else {
                dfb_x_obj.wait_front(wt + 1);
            }
            const uint32_t stats_input_dst = wt < 3 ? (wt == 0 ? retained_input_dst : wt) : input_dst;
            transpose_tile(dfb_x_welford, wt, stats_input_dst);
            if (wt == 0) {
                two_pass_stats_update_shifted_rows<false, true>(stats_input_dst, 0, tile_width);
            } else {
                two_pass_stats_update_shifted_rows<false>(stats_input_dst, 0, tile_width);
            }
        }

        // Process the last tile
        // dfb_x is synced on full blocks, so we need to wait for the
        // last tile + any remaining in the last block
        const auto num_to_wait = generic::blocks(Wt, blk).total_with_remainder();
        if constexpr (welford_fp32_alias) {
            dfb_x_welford_obj.wait_front(num_to_wait);
        } else {
            dfb_x_obj.wait_front(num_to_wait);
        }
        constexpr uint32_t last_tile_idx = Wt - 1;
        constexpr uint32_t last_pass1_dst =
            last_tile_idx < 3 ? (last_tile_idx == 0 ? retained_input_dst : last_tile_idx) : input_dst;
        transpose_tile(dfb_x_welford, Wt - 1, last_pass1_dst);
        if constexpr (Wt == 1) {
            two_pass_stats_update_shifted_rows<false, true>(last_pass1_dst, 0, last_tile_rows);
        } else {
            two_pass_stats_update_shifted_rows<false>(last_pass1_dst, 0, last_tile_rows);
        }
        two_pass_stats_finish_shifted_mean<true, true>(reciprocal_w);

        constexpr uint32_t num_front_retained = Wt < 3 ? Wt : 3;
        for (uint32_t wt = 0; wt < num_front_retained; ++wt) {
            const uint32_t stats_input_dst = wt == 0 ? retained_input_dst : wt;
            two_pass_stats_update_rows(stats_input_dst, 0, wt == last_tile_idx ? last_tile_rows : tile_width);
        }
        if constexpr (Wt > num_front_retained) {
            for (uint32_t wt = num_front_retained; wt < last_tile_idx; ++wt) {
                transpose_tile(dfb_x_welford, wt, retained_input_dst);
                two_pass_stats_update_rows(retained_input_dst, 0, tile_width);
            }
            two_pass_stats_update_rows(last_pass1_dst, 0, last_tile_rows);
        }

        // Store the mean and variance to the destination registers
        if constexpr (compact_fp32_finalizer) {
            two_pass_stats_finalize_to_row(mean_dst, reciprocal_w);
        } else {
            two_pass_stats_finalize_split_mean_to_row(mean_dst, reciprocal_w);
        }
        transpose_dest_init<DST_ACCUM_MODE>();
        transpose_dest<DST_ACCUM_MODE>(mean_dst);
        transpose_dest<DST_ACCUM_MODE>(var_dst);
        tile_regs_commit();

        // Pop dfb_x_welford so its rd_ptr advances in lock-step with dfb_x's pop in the eltwise
        // loop below. Aliased buffer indices have independent read/write pointers
        // but share the underlying SRAM; popping the alias only
        // advances dfb_x_welford's own rd_ptr, leaving dfb_x's state untouched. Without this
        // pop, subsequent NCHt iterations would read stale tiles from the start of the buffer
        // (the reader's push_back advances the wr_ptr, but the alias's rd_ptr stays at 0).
        if constexpr (welford_fp32_alias && !compact_fp32_finalizer) {
            dfb_x_welford_obj.pop_front(total_buffer_size);
        }

        // Mean and variance are already in column orientation in DEST.
        dfb_ex_obj.reserve_back(onetile);
        dfb_ex2_obj.reserve_back(onetile);
        if constexpr (compact_fp32_finalizer) {
            dfb_ex_welford_obj.reserve_back(onetile);
        }

        pack_reconfig_data_format(dfb_ex);
        tile_regs_wait();
        pack_tile(mean_dst, dfb_ex);
        pack_reconfig_data_format(dfb_ex2);
        pack_tile(var_dst, dfb_ex2);
        tile_regs_release();

        dfb_ex_obj.push_back(onetile);
        dfb_ex2_obj.push_back(onetile);
        if constexpr (compact_fp32_finalizer) {
            dfb_ex_welford_obj.push_back(onetile);
        }

        if constexpr (!compact_fp32_finalizer) {
            // x - E[x]. Reuse dfb_x since statistics did not pop it.
            if constexpr (FLOAT32_DTYPE) {
                reconfig_data_format(dfb_x, dfb_ex);
            }
            dfb_ex_obj.wait_front(onetile);  // packed anchor and low correction
            dfb_xmm_obj.reserve_back(total_buffer_size);
            sub_bcast_cols_compensated_init(dfb_x, dfb_ex);
            for (auto block : generic::blocks(Wt, blk)) {
                tile_regs_acquire();
                sub_bcast_cols_compensated(dfb_x, dfb_ex, 0, 0, block.size());
                tile_regs_commit();
                tile_regs_wait();
                for (auto i : block.local()) {
                    pack_tile(i, dfb_xmm);
                }
                tile_regs_release();
                dfb_xmm_obj.push_back(block.full_block_size());
                dfb_x_obj.pop_front(block.full_block_size());
            }
            dfb_ex_obj.pop_front(onetile);
            dfb_xmm_obj.wait_front(total_buffer_size);

            if constexpr (!fuse_pre_add) {
                reconfig_data_format_srca(dfb_x, dfb_xmm);
            }
        }

        // Var(x) + eps
        if constexpr (FLOAT32_DTYPE) {
            reconfig_data_format(dfb_ex2, dfb_eps);
        }
        dfb_ex2_obj.wait_front(onetile);  // should have 1 tile
        tile_regs_acquire();
        add_init(dfb_ex2, dfb_eps);
        add_tiles(dfb_ex2, dfb_eps, 0, 0, dst0);
        rsqrt_tile_init();
        rsqrt_tile(dst0);
        tile_regs_commit();
        dfb_ex2_obj.pop_front(onetile);

        dfb_ex2pe_obj.reserve_back(onetile);
        if constexpr (compact_fp32_finalizer) {
            dfb_ex2pe_fp32_obj.reserve_back(onetile);
        }
        tile_regs_wait();
        pack_tile(dst0, dfb_ex2pe);
        tile_regs_release();
        dfb_ex2pe_obj.push_back(onetile);
        if constexpr (compact_fp32_finalizer) {
            dfb_ex2pe_fp32_obj.push_back(onetile);

            // The two-pass finaliser writes only the statistics row; other lanes may still hold retained input, and
            // rsqrt can turn negative scratch values into NaNs. Materialise the valid statistics column through the
            // FPU before the SFPU normaliser, whose mask multiplication cannot safely suppress NaN lanes.
            dfb_ex2pe_obj.wait_front(onetile);
            dfb_ex2pe_fp32_obj.wait_front(onetile);
            tile_regs_acquire();
            reconfig_data_format_srca(dfb_ex2pe);
            compute_kernel_hw_startup(dfb_ex2pe, dfb_ex2pe);
            unary_bcast_init<BroadcastType::COL>(dfb_ex2pe);
            unary_bcast<BroadcastType::COL>(dfb_ex2pe, 0, dst0);
            dfb_ex2pe_obj.pop_front(onetile);
            dfb_ex2pe_fp32_obj.pop_front(onetile);
            tile_regs_commit();

            dfb_ex2pe_obj.reserve_back(onetile);
            dfb_ex2pe_fp32_obj.reserve_back(onetile);
            tile_regs_wait();
            pack_tile(dst0, dfb_ex2pe);
            tile_regs_release();
            dfb_ex2pe_obj.push_back(onetile);
            dfb_ex2pe_fp32_obj.push_back(onetile);
        }

        // Remainder of the layernorm operation
        // norm(x) * gamma + beta,
        // where norm(x) is:
        // (x - E[x]) / sqrt(E[(x-E[x])^2] + eps)
        dfb_ex2pe_obj.wait_front(onetile);
        if constexpr (compact_fp32_finalizer) {
            dfb_ex_obj.wait_front(onetile);
            dfb_ex_welford_obj.wait_front(onetile);
            dfb_ex2pe_fp32_obj.wait_front(onetile);
            dfb_x_welford_obj.wait_front(total_buffer_size);
            sfpu_bcast_col_init();
        }
        for (auto block : generic::blocks(Wt, blk)) {
            if constexpr (compact_fp32_finalizer) {
                reconfig_data_format(dfb_x, dfb_ex);
            } else {
                reconfig_data_format(dfb_xmm, dfb_ex2pe);
            }
#if !defined(FUSE_GAMMA) && !defined(FUSE_BETA)
            pack_reconfig_data_format(dfb_out);
#else
            pack_reconfig_data_format(dfb_fusion);
#endif
            dfb_im_or_out_obj.reserve_back(block.full_block_size());

            if constexpr (compact_fp32_finalizer) {
                constexpr uint32_t data_dst = 0;
                constexpr uint32_t second_data_dst = 1;
                constexpr uint32_t mean_col_dst = 2;
                constexpr uint32_t inv_std_col_dst = 3;
                for (uint32_t i = 0; i < block.size(); i += 2) {
                    const bool has_second_tile = i + 1 < block.size();
                    tile_regs_acquire();
                    copy_init(dfb_x_welford);
                    copy_tile(dfb_x_welford, i, data_dst);
                    if (has_second_tile) {
                        copy_tile(dfb_x_welford, i + 1, second_data_dst);
                    }
                    reconfig_data_format_srca(dfb_x_welford, dfb_ex_welford);
                    copy_init(dfb_ex_welford);
                    copy_tile(dfb_ex_welford, 0, mean_col_dst);
                    reconfig_data_format_srca(dfb_ex_welford, dfb_ex2pe_fp32);
                    copy_init(dfb_ex2pe_fp32);
                    copy_tile(dfb_ex2pe_fp32, 0, inv_std_col_dst);
                    if (has_second_tile) {
                        sfpu_normalize_bcast_col_two_tiles(data_dst, second_data_dst, mean_col_dst, inv_std_col_dst);
                    } else {
                        sfpu_normalize_bcast_col(data_dst, mean_col_dst, inv_std_col_dst);
                    }
                    tile_regs_commit();
                    tile_regs_wait();
                    pack_tile(data_dst, dfb_im_or_out, i);
                    if (has_second_tile) {
                        pack_tile(second_data_dst, dfb_im_or_out, i + 1);
                    }
                    tile_regs_release();
                }
            } else {
                mul_bcast_cols_init(dfb_xmm, dfb_ex2pe);
                tile_regs_acquire();
                for (auto i : block.local()) {
                    mul_tiles_bcast_cols(dfb_xmm, dfb_ex2pe, block.to_global(i), 0, i);
                }
                tile_regs_commit();
                tile_regs_wait();
                for (auto i : block.local()) {
                    pack_tile(i, dfb_im_or_out);
                }
                tile_regs_release();
            }
            dfb_im_or_out_obj.push_back(
                block.full_block_size());  // if no gamma/beta are provided, this will be passed on to the writer

            if constexpr (compact_fp32_finalizer) {
                dfb_x_obj.pop_front(block.full_block_size());
                dfb_x_welford_obj.pop_front(block.full_block_size());
            }

#ifdef FUSE_GAMMA
            {
#ifndef FUSE_BETA
                pack_reconfig_data_format(dfb_out);
#endif
                reconfig_data_format_srcb(dfb_ex2pe, dfb_gamma);
                // gamma's product goes to the streaming intermediate when beta still has to be
                // added, and straight to the output otherwise.
#ifdef FUSE_BETA
                constexpr auto dfb_outg = dfb_fusion;
                DataflowBuffer& dfb_outg_obj = dfb_fusion_obj;
#else
                constexpr auto dfb_outg = dfb_out;
                DataflowBuffer& dfb_outg_obj = dfb_out_obj;
#endif
                mul_bcast_rows_init(dfb_fusion, dfb_gamma);
                if (ncht == 0) {
                    // Gamma remains at the CB front for every subsequent row.
                    dfb_gamma_obj.wait_front(block.start() + block.full_block_size());
                }
                dfb_fusion_obj.wait_front(block.full_block_size());
                tile_regs_acquire();
                for (auto i : block.local()) {
                    mul_tiles_bcast_rows(dfb_fusion, dfb_gamma, i, block.to_global(i), i);  // tile *= 1/(sum(exp(x)))
                }
                tile_regs_commit();
                // We don't pop gamma since it's 1,1,1,Wt and we reuse it for all NCHt
                dfb_fusion_obj.pop_front(block.full_block_size());

                dfb_outg_obj.reserve_back(block.full_block_size());
                tile_regs_wait();
                for (auto i : block.local()) {
                    pack_tile(i, dfb_outg);  // pack either to intermediate (dfb_fusion or dfb_out)
                }
                tile_regs_release();
                dfb_outg_obj.push_back(block.full_block_size());
            }
#endif
#ifdef FUSE_BETA
            {
                pack_reconfig_data_format(dfb_out);
#ifdef FUSE_GAMMA
                reconfig_data_format_srcb(dfb_gamma, dfb_beta);
#else
                reconfig_data_format_srcb(dfb_ex2pe, dfb_beta);
#endif

                add_bcast_rows_init(dfb_fusion, dfb_beta);
                if (ncht == 0) {
                    // Beta remains at the CB front for every subsequent row.
                    dfb_beta_obj.wait_front(block.start() + block.full_block_size());
                }
                dfb_fusion_obj.wait_front(block.full_block_size());
                tile_regs_acquire();
                for (auto i : block.local()) {
                    add_tiles_bcast_rows(dfb_fusion, dfb_beta, i, block.to_global(i), i);  // tile *= 1/(sum(exp(x)))
                }
                tile_regs_commit();
                dfb_fusion_obj.pop_front(block.full_block_size());
                // We don't pop beta since it's 1,1,1,Wt and we reuse it for all NCHt

                dfb_out_obj.reserve_back(block.full_block_size());
                tile_regs_wait();
                for (auto i : block.local()) {
                    pack_tile(i, dfb_out);  // pack either to intermediate (dfb_fusion or dfb_out)
                }
                tile_regs_release();
                dfb_out_obj.push_back(block.full_block_size());
            }
#endif
        }
        dfb_ex2pe_obj.pop_front(onetile);
        if constexpr (compact_fp32_finalizer) {
            dfb_ex_obj.pop_front(onetile);
            dfb_ex_welford_obj.pop_front(onetile);
            dfb_ex2pe_fp32_obj.pop_front(onetile);
        } else {
            dfb_xmm_obj.pop_front(total_buffer_size);
        }

    }  // NCHt loop
}
