# --- Meshes ---------------------------------------------------------------

mesh_descriptors {
  name: "M0"
  arch: BLACKHOLE
  device_topology { dims: [ 32, 4 ] dim_types: [ RING, RING ] }
  host_topology   { dims: [ 4, 1 ] }
  channels { count: 2 policy: RELAXED }
}

# --- Instantiation ----------------------------------------------------------
top_level_instance { mesh { mesh_descriptor: "M0" mesh_id: 0 } }
