# --- Meshes ---------------------------------------------------------------

mesh_descriptors {
  name: "M0"
  arch: WORMHOLE_B0
  device_topology { dims: [ 8, 8 ] }
  host_topology   { dims: [ 1, 2 ] }
  channels { count: 1 policy: STRICT }
}

# --- Instantiation ----------------------------------------------------------
top_level_instance { mesh { mesh_descriptor: "M0" mesh_id: 0 } }
