# TT-Metalium Dockerfile

#############################################################

# Accept an argument to specify the Ubuntu version
ARG UBUNTU_VERSION=22.04
FROM public.ecr.aws/ubuntu/ubuntu:${UBUNTU_VERSION} AS base

ENV DEBIAN_FRONTEND=noninteractive

ENV RUSTUP_HOME=/usr/local/rustup
ENV CARGO_HOME=/usr/local/cargo
ENV PATH="$CARGO_HOME/bin:$PATH"

# Install runtime deps
COPY /install_dependencies.sh /opt/tt_metal_infra/scripts/docker/install_dependencies.sh
COPY /tt_metal/sfpi-version.sh /opt/tt_metal_infra/scripts/docker/sfpi-version.sh
RUN /bin/bash /opt/tt_metal_infra/scripts/docker/install_dependencies.sh --docker

# Set up virtual environment and TT_METAL_HOME
ENV PYTHON_ENV_DIR=/opt/venv
ENV TT_METAL_HOME=/tt-metal
ENV PYTHONPATH=/tt-metal

RUN pip3 install conan
RUN conan --version

RUN git config --global --add safe.directory /workspace

WORKDIR /tt-metal-conan
COPY conanfile.txt /tt-metal-conan/conanfile.txt
COPY tool_conanfile.txt /tt-metal-conan/tool_conanfile.txt
COPY conan_profile.txt /tt-metal-conan/conan_profile.txt
COPY install_conan_packages.sh /tt-metal-conan/install_conan_packages.sh
RUN ls -al
RUN ./install_conan_packages.sh /tt-metal-conan/conan-build

WORKDIR /tt-metal
COPY . /tt-metal
RUN ls


# # Build tt-metal and venv, then clear cache
# RUN /bin/bash -c "./build_metal.sh"
