# TT-Metalium Dockerfile

#############################################################

ARG UBUNTU_VERSION=22.04
FROM public.ecr.aws/ubuntu/ubuntu:${UBUNTU_VERSION}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    gcc build-essential \
    pkg-config \
    python3-pip python3-full python3-dev \
    wget curl \
    lsb-release software-properties-common gnupg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install LLVM
RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 20 && \
    ./llvm.sh 17 && \
    rm llvm.sh
