# TT-Metalium Dockerfile for Debian

#############################################################

ARG DEBIAN_VERSION=12
FROM debian:${DEBIAN_VERSION}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    git xxd build-essential pkg-config wget curl \
    python3-pip python3-full python3-dev python3-venv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
