# SPDX-FileCopyrightText: © 2025 Tenstorrent Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""Shared helpers for Devstral-2 / Ministral3 TT demos (mesh, prefill padding, LM head, FP8 shim)."""

from models.experimental.devstarl2_small.devstral_utils.fp8_dequantize_compat import apply_fp8_dequantize_compat
from models.experimental.devstarl2_small.devstral_utils.multimodal_demo_helpers import (
    DEFAULT_MODEL_ID,
    DEVSTRAL_DEMO_BLACKHOLE_DEFAULT_MAX_SEQ_LEN,
    apply_devstral_hf_trust_patches,
    cpu_lm_head_logits_last_token,
    default_devstral_demo_max_seq_len,
    demo_lm_head_max_columns_per_device,
    devstral_tt_kv_cache_max_seq_len,
    devstral_supports_on_device_sampling,
    eos_token_ids,
    host_input_ids_to_tt_replicated,
    image_token_placeholder_positions,
    open_devstral_demo_mesh,
    pad_input_ids_and_positions_for_tt_prefill,
    squeeze_tt_hidden_to_bsh,
    text_model_root,
    tt_append_uint32_token,
    tt_forward_prefill_from_device_ids,
    tt_forward_prefill_from_ids,
    tt_forward_prefill_multimodal_scatter_merge_from_device_ids,
    tt_lm_head_logits_block,
    tt_lm_head_logits_last_token,
    tt_multimodal_scatter_index_tt,
    tt_pad_prompt_embeddings_suffix_tt,
    tt_prefill_hidden_states_from_ids,
    tt_prefill_target_seqlen,
    tt_projected_image_rows_to_device,
    tt_replicated_ids_to_torch_long,
    tt_sampling_output_token_id,
    tt_sequence_last_uint32_token_id,
)

__all__ = (
    "DEFAULT_MODEL_ID",
    "DEVSTRAL_DEMO_BLACKHOLE_DEFAULT_MAX_SEQ_LEN",
    "apply_devstral_hf_trust_patches",
    "apply_fp8_dequantize_compat",
    "cpu_lm_head_logits_last_token",
    "default_devstral_demo_max_seq_len",
    "demo_lm_head_max_columns_per_device",
    "devstral_tt_kv_cache_max_seq_len",
    "devstral_supports_on_device_sampling",
    "eos_token_ids",
    "host_input_ids_to_tt_replicated",
    "image_token_placeholder_positions",
    "open_devstral_demo_mesh",
    "pad_input_ids_and_positions_for_tt_prefill",
    "squeeze_tt_hidden_to_bsh",
    "text_model_root",
    "tt_append_uint32_token",
    "tt_forward_prefill_from_device_ids",
    "tt_forward_prefill_from_ids",
    "tt_forward_prefill_multimodal_scatter_merge_from_device_ids",
    "tt_lm_head_logits_block",
    "tt_lm_head_logits_last_token",
    "tt_multimodal_scatter_index_tt",
    "tt_pad_prompt_embeddings_suffix_tt",
    "tt_prefill_hidden_states_from_ids",
    "tt_prefill_target_seqlen",
    "tt_projected_image_rows_to_device",
    "tt_replicated_ids_to_torch_long",
    "tt_sampling_output_token_id",
    "tt_sequence_last_uint32_token_id",
)
