system_graph {
  asic_connectivity_graph {
    host_name: "metal-wh-12"
    asic_topologies {
      asic_id: 14521786539
      topology {
        asic_connections {
          dst_asic_id: 10226819243
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 14521786438
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786451
      topology {
        asic_connections {
          dst_asic_id: 10226819155
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 14521786429
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786438
      topology {
        asic_connections {
          dst_asic_id: 14521786539
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819142
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819142
      topology {
        asic_connections {
          dst_asic_id: 14521786438
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819243
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819155
          eth_connections {
            src_chan: 1
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819281
          eth_connections {
            src_chan: 7
            dst_chan: 1
          }
          eth_connections {
            src_chan: 6
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819155
      topology {
        asic_connections {
          dst_asic_id: 14521786451
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819142
          eth_connections {
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819133
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819216
          eth_connections {
            src_chan: 7
            dst_chan: 7
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786429
      topology {
        asic_connections {
          dst_asic_id: 14521786451
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819133
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819243
      topology {
        asic_connections {
          dst_asic_id: 14521786539
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819142
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819133
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819236
          eth_connections {
            src_chan: 1
            dst_chan: 1
          }
          eth_connections {
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819133
      topology {
        asic_connections {
          dst_asic_id: 14521786429
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819155
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819243
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
  }
  asic_connectivity_graph {
    host_name: "metal-wh-11"
    asic_topologies {
      asic_id: 14521786547
      topology {
        asic_connections {
          dst_asic_id: 10226819251
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 14521786512
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786525
      topology {
        asic_connections {
          dst_asic_id: 10226819229
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 14521786425
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786512
      topology {
        asic_connections {
          dst_asic_id: 14521786547
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819216
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819251
      topology {
        asic_connections {
          dst_asic_id: 14521786547
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819216
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819129
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819275
          eth_connections {
            src_chan: 1
            dst_chan: 1
          }
          eth_connections {
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819216
      topology {
        asic_connections {
          dst_asic_id: 14521786512
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819251
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819229
          eth_connections {
            src_chan: 1
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819155
          eth_connections {
            src_chan: 7
            dst_chan: 7
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819229
      topology {
        asic_connections {
          dst_asic_id: 14521786525
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819216
          eth_connections {
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819129
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819238
          eth_connections {
            src_chan: 7
            dst_chan: 7
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786425
      topology {
        asic_connections {
          dst_asic_id: 14521786525
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819129
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819129
      topology {
        asic_connections {
          dst_asic_id: 14521786425
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819229
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819251
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
  }
  asic_connectivity_graph {
    host_name: "metal-wh-10"
    asic_topologies {
      asic_id: 14521786577
      topology {
        asic_connections {
          dst_asic_id: 10226819281
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 14521786479
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819238
      topology {
        asic_connections {
          dst_asic_id: 14521786534
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819183
          eth_connections {
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819080
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819229
          eth_connections {
            src_chan: 7
            dst_chan: 7
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786534
      topology {
        asic_connections {
          dst_asic_id: 10226819238
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 14521786376
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786479
      topology {
        asic_connections {
          dst_asic_id: 14521786577
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819183
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819183
      topology {
        asic_connections {
          dst_asic_id: 14521786479
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819281
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819238
          eth_connections {
            src_chan: 1
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819075
          eth_connections {
            src_chan: 7
            dst_chan: 7
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786376
      topology {
        asic_connections {
          dst_asic_id: 14521786534
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819080
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819281
      topology {
        asic_connections {
          dst_asic_id: 14521786577
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819183
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819080
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819142
          eth_connections {
            src_chan: 1
            dst_chan: 7
          }
          eth_connections {
            dst_chan: 6
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819080
      topology {
        asic_connections {
          dst_asic_id: 14521786376
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819238
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819281
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
  }
  asic_connectivity_graph {
    host_name: "metal-wh-09"
    asic_topologies {
      asic_id: 10226819235
      topology {
        asic_connections {
          dst_asic_id: 14521786531
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819236
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819075
          eth_connections {
            src_chan: 1
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786371
      topology {
        asic_connections {
          dst_asic_id: 14521786571
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819075
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819075
      topology {
        asic_connections {
          dst_asic_id: 14521786371
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819275
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819235
          eth_connections {
            src_chan: 1
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819183
          eth_connections {
            src_chan: 7
            dst_chan: 7
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786531
      topology {
        asic_connections {
          dst_asic_id: 14521786532
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819235
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819275
      topology {
        asic_connections {
          dst_asic_id: 14521786571
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819236
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819075
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819251
          eth_connections {
            src_chan: 1
            dst_chan: 1
          }
          eth_connections {
          }
        }
      }
    }
    asic_topologies {
      asic_id: 10226819236
      topology {
        asic_connections {
          dst_asic_id: 14521786532
          eth_connections {
            src_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 1
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819275
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819235
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 10226819243
          eth_connections {
            src_chan: 1
            dst_chan: 1
          }
          eth_connections {
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786532
      topology {
        asic_connections {
          dst_asic_id: 10226819236
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 14521786531
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 14521786571
      topology {
        asic_connections {
          dst_asic_id: 10226819275
          eth_connections {
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 9
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 14521786371
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
        }
      }
    }
  }
  host_connectivity_graph {
    src_host_name: "metal-wh-12"
    host_connections {
      dst_host_name: "metal-wh-11"
      exit_node_connections {
        src_exit_node: 10226819155
        dst_exit_node: 10226819216
        eth_conn {
          src_chan: 7
          dst_chan: 7
        }
      }
      exit_node_connections {
        src_exit_node: 10226819155
        dst_exit_node: 10226819216
        eth_conn {
          src_chan: 6
          dst_chan: 6
        }
      }
    }
    host_connections {
      dst_host_name: "metal-wh-10"
      exit_node_connections {
        src_exit_node: 10226819142
        dst_exit_node: 10226819281
        eth_conn {
          src_chan: 7
          dst_chan: 1
        }
      }
      exit_node_connections {
        src_exit_node: 10226819142
        dst_exit_node: 10226819281
        eth_conn {
          src_chan: 6
        }
      }
    }
    host_connections {
      dst_host_name: "metal-wh-09"
      exit_node_connections {
        src_exit_node: 10226819243
        dst_exit_node: 10226819236
        eth_conn {
          src_chan: 1
          dst_chan: 1
        }
      }
      exit_node_connections {
        src_exit_node: 10226819243
        dst_exit_node: 10226819236
        eth_conn {
        }
      }
    }
  }
  host_connectivity_graph {
    src_host_name: "metal-wh-11"
    host_connections {
      dst_host_name: "metal-wh-12"
      exit_node_connections {
        src_exit_node: 10226819216
        dst_exit_node: 10226819155
        eth_conn {
          src_chan: 7
          dst_chan: 7
        }
      }
      exit_node_connections {
        src_exit_node: 10226819216
        dst_exit_node: 10226819155
        eth_conn {
          src_chan: 6
          dst_chan: 6
        }
      }
    }
    host_connections {
      dst_host_name: "metal-wh-10"
      exit_node_connections {
        src_exit_node: 10226819229
        dst_exit_node: 10226819238
        eth_conn {
          src_chan: 7
          dst_chan: 7
        }
      }
      exit_node_connections {
        src_exit_node: 10226819229
        dst_exit_node: 10226819238
        eth_conn {
          src_chan: 6
          dst_chan: 6
        }
      }
    }
    host_connections {
      dst_host_name: "metal-wh-09"
      exit_node_connections {
        src_exit_node: 10226819251
        dst_exit_node: 10226819275
        eth_conn {
          src_chan: 1
          dst_chan: 1
        }
      }
      exit_node_connections {
        src_exit_node: 10226819251
        dst_exit_node: 10226819275
        eth_conn {
        }
      }
    }
  }
  host_connectivity_graph {
    src_host_name: "metal-wh-10"
    host_connections {
      dst_host_name: "metal-wh-12"
      exit_node_connections {
        src_exit_node: 10226819281
        dst_exit_node: 10226819142
        eth_conn {
          src_chan: 1
          dst_chan: 7
        }
      }
      exit_node_connections {
        src_exit_node: 10226819281
        dst_exit_node: 10226819142
        eth_conn {
          dst_chan: 6
        }
      }
    }
    host_connections {
      dst_host_name: "metal-wh-11"
      exit_node_connections {
        src_exit_node: 10226819238
        dst_exit_node: 10226819229
        eth_conn {
          src_chan: 7
          dst_chan: 7
        }
      }
      exit_node_connections {
        src_exit_node: 10226819238
        dst_exit_node: 10226819229
        eth_conn {
          src_chan: 6
          dst_chan: 6
        }
      }
    }
    host_connections {
      dst_host_name: "metal-wh-09"
      exit_node_connections {
        src_exit_node: 10226819183
        dst_exit_node: 10226819075
        eth_conn {
          src_chan: 7
          dst_chan: 7
        }
      }
      exit_node_connections {
        src_exit_node: 10226819183
        dst_exit_node: 10226819075
        eth_conn {
          src_chan: 6
          dst_chan: 6
        }
      }
    }
  }
  host_connectivity_graph {
    src_host_name: "metal-wh-09"
    host_connections {
      dst_host_name: "metal-wh-12"
      exit_node_connections {
        src_exit_node: 10226819236
        dst_exit_node: 10226819243
        eth_conn {
          src_chan: 1
          dst_chan: 1
        }
      }
      exit_node_connections {
        src_exit_node: 10226819236
        dst_exit_node: 10226819243
        eth_conn {
        }
      }
    }
    host_connections {
      dst_host_name: "metal-wh-11"
      exit_node_connections {
        src_exit_node: 10226819275
        dst_exit_node: 10226819251
        eth_conn {
          src_chan: 1
          dst_chan: 1
        }
      }
      exit_node_connections {
        src_exit_node: 10226819275
        dst_exit_node: 10226819251
        eth_conn {
        }
      }
    }
    host_connections {
      dst_host_name: "metal-wh-10"
      exit_node_connections {
        src_exit_node: 10226819075
        dst_exit_node: 10226819183
        eth_conn {
          src_chan: 7
          dst_chan: 7
        }
      }
      exit_node_connections {
        src_exit_node: 10226819075
        dst_exit_node: 10226819183
        eth_conn {
          src_chan: 6
          dst_chan: 6
        }
      }
    }
  }
}
asic_descriptors {
  asic_id: 10226819142
  asic_descriptor {
    tray_id: 2
    board_type: 4
    unique_id: 10226819142
    host_name: "metal-wh-12"
  }
}
asic_descriptors {
  asic_id: 14521786451
  asic_descriptor {
    tray_id: 3
    asic_location: 1
    board_type: 4
    unique_id: 14521786451
    host_name: "metal-wh-12"
  }
}
asic_descriptors {
  asic_id: 10226819129
  asic_descriptor {
    tray_id: 1
    board_type: 4
    unique_id: 10226819129
    host_name: "metal-wh-11"
  }
}
asic_descriptors {
  asic_id: 10226819133
  asic_descriptor {
    tray_id: 4
    board_type: 4
    unique_id: 10226819133
    host_name: "metal-wh-12"
  }
}
asic_descriptors {
  asic_id: 10226819251
  asic_descriptor {
    tray_id: 4
    board_type: 4
    unique_id: 10226819251
    host_name: "metal-wh-11"
  }
}
asic_descriptors {
  asic_id: 14521786525
  asic_descriptor {
    tray_id: 2
    asic_location: 1
    board_type: 4
    unique_id: 14521786525
    host_name: "metal-wh-11"
  }
}
asic_descriptors {
  asic_id: 14521786425
  asic_descriptor {
    tray_id: 1
    asic_location: 1
    board_type: 4
    unique_id: 14521786425
    host_name: "metal-wh-11"
  }
}
asic_descriptors {
  asic_id: 10226819229
  asic_descriptor {
    tray_id: 2
    board_type: 4
    unique_id: 10226819229
    host_name: "metal-wh-11"
  }
}
asic_descriptors {
  asic_id: 10226819243
  asic_descriptor {
    tray_id: 1
    board_type: 4
    unique_id: 10226819243
    host_name: "metal-wh-12"
  }
}
asic_descriptors {
  asic_id: 14521786429
  asic_descriptor {
    tray_id: 4
    asic_location: 1
    board_type: 4
    unique_id: 14521786429
    host_name: "metal-wh-12"
  }
}
asic_descriptors {
  asic_id: 14521786547
  asic_descriptor {
    tray_id: 4
    asic_location: 1
    board_type: 4
    unique_id: 14521786547
    host_name: "metal-wh-11"
  }
}
asic_descriptors {
  asic_id: 10226819080
  asic_descriptor {
    tray_id: 1
    board_type: 4
    unique_id: 10226819080
    host_name: "metal-wh-10"
  }
}
asic_descriptors {
  asic_id: 10226819281
  asic_descriptor {
    tray_id: 4
    board_type: 4
    unique_id: 10226819281
    host_name: "metal-wh-10"
  }
}
asic_descriptors {
  asic_id: 14521786376
  asic_descriptor {
    tray_id: 1
    asic_location: 1
    board_type: 4
    unique_id: 14521786376
    host_name: "metal-wh-10"
  }
}
asic_descriptors {
  asic_id: 10226819238
  asic_descriptor {
    tray_id: 2
    board_type: 4
    unique_id: 10226819238
    host_name: "metal-wh-10"
  }
}
asic_descriptors {
  asic_id: 10226819155
  asic_descriptor {
    tray_id: 3
    board_type: 4
    unique_id: 10226819155
    host_name: "metal-wh-12"
  }
}
asic_descriptors {
  asic_id: 14521786577
  asic_descriptor {
    tray_id: 4
    asic_location: 1
    board_type: 4
    unique_id: 14521786577
    host_name: "metal-wh-10"
  }
}
asic_descriptors {
  asic_id: 10226819183
  asic_descriptor {
    tray_id: 3
    board_type: 4
    unique_id: 10226819183
    host_name: "metal-wh-10"
  }
}
asic_descriptors {
  asic_id: 14521786479
  asic_descriptor {
    tray_id: 3
    asic_location: 1
    board_type: 4
    unique_id: 14521786479
    host_name: "metal-wh-10"
  }
}
asic_descriptors {
  asic_id: 14521786534
  asic_descriptor {
    tray_id: 2
    asic_location: 1
    board_type: 4
    unique_id: 14521786534
    host_name: "metal-wh-10"
  }
}
asic_descriptors {
  asic_id: 14521786438
  asic_descriptor {
    tray_id: 2
    asic_location: 1
    board_type: 4
    unique_id: 14521786438
    host_name: "metal-wh-12"
  }
}
asic_descriptors {
  asic_id: 10226819075
  asic_descriptor {
    tray_id: 3
    board_type: 4
    unique_id: 10226819075
    host_name: "metal-wh-09"
  }
}
asic_descriptors {
  asic_id: 14521786539
  asic_descriptor {
    tray_id: 1
    asic_location: 1
    board_type: 4
    unique_id: 14521786539
    host_name: "metal-wh-12"
  }
}
asic_descriptors {
  asic_id: 10226819235
  asic_descriptor {
    tray_id: 2
    board_type: 4
    unique_id: 10226819235
    host_name: "metal-wh-09"
  }
}
asic_descriptors {
  asic_id: 14521786371
  asic_descriptor {
    tray_id: 3
    asic_location: 1
    board_type: 4
    unique_id: 14521786371
    host_name: "metal-wh-09"
  }
}
asic_descriptors {
  asic_id: 10226819216
  asic_descriptor {
    tray_id: 3
    board_type: 4
    unique_id: 10226819216
    host_name: "metal-wh-11"
  }
}
asic_descriptors {
  asic_id: 10226819275
  asic_descriptor {
    tray_id: 4
    board_type: 4
    unique_id: 10226819275
    host_name: "metal-wh-09"
  }
}
asic_descriptors {
  asic_id: 14521786531
  asic_descriptor {
    tray_id: 2
    asic_location: 1
    board_type: 4
    unique_id: 14521786531
    host_name: "metal-wh-09"
  }
}
asic_descriptors {
  asic_id: 10226819236
  asic_descriptor {
    tray_id: 1
    board_type: 4
    unique_id: 10226819236
    host_name: "metal-wh-09"
  }
}
asic_descriptors {
  asic_id: 14521786532
  asic_descriptor {
    tray_id: 1
    asic_location: 1
    board_type: 4
    unique_id: 14521786532
    host_name: "metal-wh-09"
  }
}
asic_descriptors {
  asic_id: 14521786512
  asic_descriptor {
    tray_id: 3
    asic_location: 1
    board_type: 4
    unique_id: 14521786512
    host_name: "metal-wh-11"
  }
}
asic_descriptors {
  asic_id: 14521786571
  asic_descriptor {
    tray_id: 4
    asic_location: 1
    board_type: 4
    unique_id: 14521786571
    host_name: "metal-wh-09"
  }
}
host_to_mobo_name {
  host_name: "metal-wh-12"
  mobo_name: "X12DPG-QT6"
}
host_to_mobo_name {
  host_name: "metal-wh-11"
  mobo_name: "X12DPG-QT6"
}
host_to_mobo_name {
  host_name: "metal-wh-10"
  mobo_name: "X12DPG-QT6"
}
host_to_mobo_name {
  host_name: "metal-wh-09"
  mobo_name: "X12DPG-QT6"
}
host_to_rank {
  host_name: "metal-wh-12"
  rank: 3
}
host_to_rank {
  host_name: "metal-wh-11"
  rank: 2
}
host_to_rank {
  host_name: "metal-wh-10"
  rank: 1
}
host_to_rank {
  host_name: "metal-wh-09"
}
exit_node_connection_table {
  host_name: "metal-wh-12"
  exit_connections {
    src_exit_node: 10226819243
    dst_exit_node: 10226819236
    eth_conn {
      src_chan: 1
      dst_chan: 1
    }
  }
  exit_connections {
    src_exit_node: 10226819243
    dst_exit_node: 10226819236
    eth_conn {
    }
  }
  exit_connections {
    src_exit_node: 10226819155
    dst_exit_node: 10226819216
    eth_conn {
      src_chan: 7
      dst_chan: 7
    }
  }
  exit_connections {
    src_exit_node: 10226819155
    dst_exit_node: 10226819216
    eth_conn {
      src_chan: 6
      dst_chan: 6
    }
  }
  exit_connections {
    src_exit_node: 10226819142
    dst_exit_node: 10226819281
    eth_conn {
      src_chan: 7
      dst_chan: 1
    }
  }
  exit_connections {
    src_exit_node: 10226819142
    dst_exit_node: 10226819281
    eth_conn {
      src_chan: 6
    }
  }
}
exit_node_connection_table {
  host_name: "metal-wh-11"
  exit_connections {
    src_exit_node: 10226819251
    dst_exit_node: 10226819275
    eth_conn {
      src_chan: 1
      dst_chan: 1
    }
  }
  exit_connections {
    src_exit_node: 10226819251
    dst_exit_node: 10226819275
    eth_conn {
    }
  }
  exit_connections {
    src_exit_node: 10226819229
    dst_exit_node: 10226819238
    eth_conn {
      src_chan: 7
      dst_chan: 7
    }
  }
  exit_connections {
    src_exit_node: 10226819229
    dst_exit_node: 10226819238
    eth_conn {
      src_chan: 6
      dst_chan: 6
    }
  }
  exit_connections {
    src_exit_node: 10226819216
    dst_exit_node: 10226819155
    eth_conn {
      src_chan: 7
      dst_chan: 7
    }
  }
  exit_connections {
    src_exit_node: 10226819216
    dst_exit_node: 10226819155
    eth_conn {
      src_chan: 6
      dst_chan: 6
    }
  }
}
exit_node_connection_table {
  host_name: "metal-wh-10"
  exit_connections {
    src_exit_node: 10226819281
    dst_exit_node: 10226819142
    eth_conn {
      src_chan: 1
      dst_chan: 7
    }
  }
  exit_connections {
    src_exit_node: 10226819281
    dst_exit_node: 10226819142
    eth_conn {
      dst_chan: 6
    }
  }
  exit_connections {
    src_exit_node: 10226819238
    dst_exit_node: 10226819229
    eth_conn {
      src_chan: 7
      dst_chan: 7
    }
  }
  exit_connections {
    src_exit_node: 10226819238
    dst_exit_node: 10226819229
    eth_conn {
      src_chan: 6
      dst_chan: 6
    }
  }
  exit_connections {
    src_exit_node: 10226819183
    dst_exit_node: 10226819075
    eth_conn {
      src_chan: 7
      dst_chan: 7
    }
  }
  exit_connections {
    src_exit_node: 10226819183
    dst_exit_node: 10226819075
    eth_conn {
      src_chan: 6
      dst_chan: 6
    }
  }
}
exit_node_connection_table {
  host_name: "metal-wh-09"
  exit_connections {
    src_exit_node: 10226819275
    dst_exit_node: 10226819251
    eth_conn {
      src_chan: 1
      dst_chan: 1
    }
  }
  exit_connections {
    src_exit_node: 10226819275
    dst_exit_node: 10226819251
    eth_conn {
    }
  }
  exit_connections {
    src_exit_node: 10226819236
    dst_exit_node: 10226819243
    eth_conn {
      src_chan: 1
      dst_chan: 1
    }
  }
  exit_connections {
    src_exit_node: 10226819236
    dst_exit_node: 10226819243
    eth_conn {
    }
  }
  exit_connections {
    src_exit_node: 10226819075
    dst_exit_node: 10226819183
    eth_conn {
      src_chan: 7
      dst_chan: 7
    }
  }
  exit_connections {
    src_exit_node: 10226819075
    dst_exit_node: 10226819183
    eth_conn {
      src_chan: 6
      dst_chan: 6
    }
  }
}
ethernet_metrics {
  asic_id: 14521786451
  channel_metrics {
    metrics {
      corrected_codeword_count: 29839
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 64674
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 107
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 53
    }
  }
}
ethernet_metrics {
  asic_id: 10226819281
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 15687
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 34252
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 2992
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 1112
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 247
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 191862
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 111090
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 2844
    }
  }
}
ethernet_metrics {
  asic_id: 14521786532
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 12713
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 1839560
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 12001
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 1389
    }
  }
}
ethernet_metrics {
  asic_id: 14521786376
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 482
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 2
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 2639
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 477
    }
  }
}
ethernet_metrics {
  asic_id: 10226819183
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 39532
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 51153
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 2312
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 2677
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 802
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 357
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 34953
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 896
    }
  }
}
ethernet_metrics {
  asic_id: 10226819080
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 24345
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 61347
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 1538
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 723
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 4926045
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 245354
    }
  }
}
ethernet_metrics {
  asic_id: 14521786534
  channel_metrics {
    metrics {
      corrected_codeword_count: 13959
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 1100
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 10
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 20357
    }
  }
}
ethernet_metrics {
  asic_id: 10226819236
  channel_metrics {
    metrics {
      corrected_codeword_count: 45663
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 897157
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 23402
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 3086
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 8129654
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 8656683
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 471895
    }
  }
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 53243
    }
  }
}
ethernet_metrics {
  asic_id: 14521786371
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 77054
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 457
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 681
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 2212
    }
  }
}
ethernet_metrics {
  asic_id: 14521786479
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 990
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 34
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 23484
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 1624191
    }
  }
}
ethernet_metrics {
  asic_id: 14521786531
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 308756
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 42277
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 2087373
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 14056
    }
  }
}
ethernet_metrics {
  asic_id: 14521786438
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 52
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 97847
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 6372
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 31675
    }
  }
}
ethernet_metrics {
  asic_id: 10226819075
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 27270
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 280621
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 3
    }
  }
  channel_metrics {
    channel: 1
    metrics {
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 222
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 29
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 23881
    }
  }
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 4708
    }
  }
}
ethernet_metrics {
  asic_id: 10226819251
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 20720
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 192700
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 171
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 110
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 23660
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 1165512
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 37202
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 6538
    }
  }
}
ethernet_metrics {
  asic_id: 10226819133
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 260
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 12394
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 40
    }
  }
  channel_metrics {
    channel: 14
    metrics {
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 155863
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 2061
    }
  }
}
ethernet_metrics {
  asic_id: 14521786539
  channel_metrics {
    metrics {
      corrected_codeword_count: 16215
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 5276
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 11671
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 797
    }
  }
}
ethernet_metrics {
  asic_id: 10226819235
  channel_metrics {
    metrics {
      corrected_codeword_count: 37
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 48
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 2
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 568
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 46425
    }
  }
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 63489
    }
  }
}
ethernet_metrics {
  asic_id: 10226819238
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 1027
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 57853
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 9193
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 15680
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 361
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 4292
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 465764
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 169452
    }
  }
}
ethernet_metrics {
  asic_id: 10226819129
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 444
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 184974
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 3726
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 31000
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 322498
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 5514
    }
  }
}
ethernet_metrics {
  asic_id: 10226819275
  channel_metrics {
    metrics {
      corrected_codeword_count: 91880
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 164880
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 152
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 4801
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 1132770
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 644043
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 173548
    }
  }
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 28566
    }
  }
}
ethernet_metrics {
  asic_id: 10226819216
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 86441
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 294973
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 301
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 35774
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 2023
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 16791
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 63186
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 2486039
    }
  }
}
ethernet_metrics {
  asic_id: 14521786525
  channel_metrics {
    metrics {
      corrected_codeword_count: 507
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 13493
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 187
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 16589
    }
  }
}
ethernet_metrics {
  asic_id: 14521786425
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 6987
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 3088
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 28176
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 690549
    }
  }
}
ethernet_metrics {
  asic_id: 14521786571
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 55965
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 104
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 68146
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 28368
    }
  }
}
ethernet_metrics {
  asic_id: 14521786512
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 5517
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 6947
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 162721
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 90465
    }
  }
}
ethernet_metrics {
  asic_id: 10226819229
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 22843
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 56133
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 35
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 6006
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 73
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 3127
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 1181951
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 1449625
    }
  }
}
ethernet_metrics {
  asic_id: 10226819142
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 444
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 50048
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 769
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 201
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 1479
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 913
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 1112
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 12579959
    }
  }
}
ethernet_metrics {
  asic_id: 14521786429
  channel_metrics {
    channel: 7
    metrics {
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 9195
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 13646
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 30870
    }
  }
}
ethernet_metrics {
  asic_id: 14521786547
  channel_metrics {
    metrics {
      corrected_codeword_count: 5276
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 61557
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 4440
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 36208
    }
  }
}
ethernet_metrics {
  asic_id: 10226819243
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 2638
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 88996
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 145
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 61248
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 45405
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 241938
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 173505
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 556
    }
  }
}
ethernet_metrics {
  asic_id: 14521786577
  channel_metrics {
    metrics {
      corrected_codeword_count: 542169
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 649791
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 205
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 3658
    }
  }
}
ethernet_metrics {
  asic_id: 10226819155
  channel_metrics {
    channel: 8
    metrics {
      corrected_codeword_count: 8309
    }
  }
  channel_metrics {
    channel: 9
    metrics {
      corrected_codeword_count: 357854
    }
  }
  channel_metrics {
    metrics {
      corrected_codeword_count: 129
    }
  }
  channel_metrics {
    channel: 1
    metrics {
      corrected_codeword_count: 6551
    }
  }
  channel_metrics {
    channel: 14
    metrics {
      corrected_codeword_count: 21
    }
  }
  channel_metrics {
    channel: 15
    metrics {
      corrected_codeword_count: 129
    }
  }
  channel_metrics {
    channel: 7
    metrics {
      corrected_codeword_count: 344292
    }
  }
  channel_metrics {
    channel: 6
    metrics {
      corrected_codeword_count: 56630
    }
  }
}
