name: "Cleanup Action"
description: "Cleans up the workspace to remove root-owned files on non-ephemeral runners."

inputs:
  path:
    description: "The directory to clean up"
    required: false
    default: "/__w/tt-metal/tt-metal/docker-job"
runs:
  using: "composite"
  steps:
    - name: Cleanup
      shell: bash
      env:
        CLEANUP_PATH: ${{ inputs.path }}
      run: |
        cd /
        echo "pre rm"
        ls -al "$CLEANUP_PATH"
        rm -rf "$CLEANUP_PATH"
        echo "post rm"
        ls -al "$(dirname "$CLEANUP_PATH")"
