#!/usr/bin/env python3
"""Generate a closed-ring pipeline Mesh Graph Descriptor (MGD).

Each stage is one mesh instance; consecutive stages connect in a ring with the
last stage looping back to stage 0 (loopback is always enabled).

Examples:
  # 4x4 split-host galaxy pipeline with corner pinnings (48 stages)
  python3 tests/scripts/multihost/gen_pipeline_sweep_mgds.py \\
      --shape 4x4 --stages 48 --hosts 2 --pinnings \\
      --out /tmp/sweep_4x4_pipeline_48stage_mesh_graph_descriptor.textproto

  # 2x4 single-host pipeline, no pinnings (16 stages)
  python3 tests/scripts/multihost/gen_pipeline_sweep_mgds.py \\
      --shape 2x4 --stages 16 --hosts 1 \\
      --out /tmp/sweep_2x4_pipeline_16stage_mesh_graph_descriptor.textproto

  # Regenerate the full SC36 preset sweep into the default output directory
  python3 tests/scripts/multihost/gen_pipeline_sweep_mgds.py --all-presets
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Preset stage counts for the SC36 mock cluster (36 hosts x 32 ASICs = 1152 ASICs).
# 2x4: 8 ASICs/stage -> up to 144 stages; 4x4: 16 ASICs/stage -> up to 72 stages.
PRESET_STAGES_2X4 = [16, 32, 64, 80, 96, 112, 128, 144]
PRESET_STAGES_4X4 = [8, 16, 32, 40, 48, 56, 64, 72]

# 4x4 all-to-all corner pinnings: logical corner chips and galaxy tray/asic candidates.
PIN_CHIPS = [0, 1, 3, 12, 15]
CHIP_ID_REGEX = "0,1,3,12,15"
POS_EVEN = [(1, 3), (1, 7), (2, 3), (3, 3), (4, 3)]
POS_ODD = [(1, 2), (1, 6), (2, 2), (3, 2), (4, 2)]


def _instances(template_of_stage: list[str]) -> str:
    lines = []
    for i, tmpl in enumerate(template_of_stage):
        lines.append(f'  instances {{ mesh {{ mesh_descriptor: "{tmpl}" mesh_id: {i} }} }}')
    return "\n".join(lines)


def _ring_connections(template_of_stage: list[str], *, channels: int) -> str:
    """Closed ring: stage i connects to stage (i+1) % n (loopback on last -> 0)."""
    n = len(template_of_stage)
    blocks = []
    for i in range(n):
        j = (i + 1) % n
        src, dst = template_of_stage[i], template_of_stage[j]
        blocks.append(
            "\n".join(
                [
                    "  connections {",
                    f'    nodes {{ mesh {{ mesh_descriptor: "{src}" mesh_id: {i} }} }}',
                    f'    nodes {{ mesh {{ mesh_descriptor: "{dst}" mesh_id: {j} }} }}',
                    f"    channels {{ count: {channels} policy: RELAXED }}",
                    "  }",
                ]
            )
        )
    return "\n".join(blocks)


def _physical_positions_regex(positions: list[tuple[int, int]]) -> str:
    by_asic: dict[int, set[int]] = {}
    for tray_id, asic_location in positions:
        by_asic.setdefault(asic_location, set()).add(tray_id)

    lines: list[str] = []
    for asic_location in sorted(by_asic):
        trays = sorted(by_asic[asic_location])
        if trays == [1, 2, 3, 4]:
            lines.append(f'  physical_asic_position {{ tray_id_regex: "1-4" asic_location: {asic_location} }}')
        elif trays == [1]:
            lines.append(
                f'  physical_asic_position {{ tray_id_regex: "1" asic_location: {asic_location} }} '
                f"# Extra pin to ensure rotation and folding does not occur"
            )
        else:
            tray_expr = ",".join(str(t) for t in trays)
            lines.append(f'  physical_asic_position {{ tray_id_regex: "{tray_expr}" asic_location: {asic_location} }}')
    return "\n".join(lines)


def _pinnings_4x4_regex() -> str:
    even_pos = _physical_positions_regex(POS_EVEN)
    odd_pos = _physical_positions_regex(POS_ODD)
    return f"""# --- Pinnings ---------------------------------------------------------------
# All-to-all corner pinning per mesh: chips {PIN_CHIPS} may map to any listed tray/asic
# position (bijection enforced). Position set alternates by mesh-id parity -> two regex entries.

pinnings {{
  logical_fabric_node_id {{ mesh_id_regex: "[0-9]*[02468]" chip_id_regex: "{CHIP_ID_REGEX}" }}
{even_pos}
}}

pinnings {{
  logical_fabric_node_id {{ mesh_id_regex: "[0-9]*[13579]" chip_id_regex: "{CHIP_ID_REGEX}" }}
{odd_pos}
}}
"""


def build_2x4(*, stages: int, hosts_per_stage: int) -> str:
    if hosts_per_stage != 1:
        raise ValueError("2x4 pipeline stages use a single host per mesh ( --hosts 1 )")
    template_of_stage = ["M0"] * stages
    return f"""# --- Meshes ---------------------------------------------------------------
# GENERATED by tests/scripts/multihost/gen_pipeline_sweep_mgds.py -- do not edit by hand.
# 2x4 pipeline ring, {stages} stages ({stages} x 8 = {stages * 8} ASICs). Closed ring
# (stage {stages - 1} -> stage 0). Single-host stages; no pinnings.

mesh_descriptors {{
  name: "M0"
  arch: BLACKHOLE
  device_topology {{ dims: [ 4, 2 ] dim_types: [ RING, LINE ] }}
  host_topology   {{ dims: [ {hosts_per_stage}, 1 ] }}
  channels {{ count: 2 policy: RELAXED }}
}}

graph_descriptors {{
  name: "G0"
  type: "FABRIC"
{_instances(template_of_stage)}

{_ring_connections(template_of_stage, channels=8)}
}}

top_level_instance {{ graph {{ graph_descriptor: "G0" graph_id: 0 }} }}
"""


def build_4x4(*, stages: int, hosts_per_stage: int, pinnings: bool) -> str:
    if hosts_per_stage < 1:
        raise ValueError("--hosts must be >= 1")
    template_of_stage = ["M0"] * stages
    pinning_block = f"\n{_pinnings_4x4_regex()}" if pinnings else ""
    pinning_note = "with all-to-all corner pinnings" if pinnings else "without pinnings"
    return f"""# --- Meshes ---------------------------------------------------------------
# GENERATED by tests/scripts/multihost/gen_pipeline_sweep_mgds.py -- do not edit by hand.
# 4x4 pipeline ring, {stages} stages ({stages} x 16 = {stages * 16} ASICs), {pinning_note}.
# Closed ring (stage {stages - 1} -> stage 0). host_topology [ {hosts_per_stage}, 1 ].

mesh_descriptors {{
  name: "M0"
  arch: BLACKHOLE
  device_topology {{ dims: [ 4, 4 ] dim_types: [ RING, RING ] }}
  host_topology   {{ dims: [ {hosts_per_stage}, 1 ] }}
  channels {{ count: 2 policy: STRICT }}
}}

graph_descriptors {{
  name: "G0"
  type: "FABRIC"
{_instances(template_of_stage)}

{_ring_connections(template_of_stage, channels=8)}
}}

top_level_instance {{ graph {{ graph_descriptor: "G0" graph_id: 0 }} }}
{pinning_block}"""


def generate_mgd(*, shape: str, stages: int, hosts_per_stage: int, pinnings: bool) -> str:
    if stages < 1:
        raise ValueError("--stages must be >= 1")
    if shape == "2x4":
        if pinnings:
            raise ValueError("Pinnings are only supported for --shape 4x4")
        return build_2x4(stages=stages, hosts_per_stage=hosts_per_stage)
    if shape == "4x4":
        return build_4x4(stages=stages, hosts_per_stage=hosts_per_stage, pinnings=pinnings)
    raise ValueError(f"Unsupported --shape {shape!r}; use 2x4 or 4x4")


def default_output_path(out_dir: Path, *, shape: str, stages: int) -> Path:
    return out_dir / f"sweep_{shape}_pipeline_{stages}stage_mesh_graph_descriptor.textproto"


def write_mgd(
    path: Path,
    *,
    shape: str,
    stages: int,
    hosts_per_stage: int,
    pinnings: bool,
) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_mgd(shape=shape, stages=stages, hosts_per_stage=hosts_per_stage, pinnings=pinnings))
    return path


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    default_out_dir = (
        Path(__file__).resolve().parents[3] / "tests/tt_metal/tt_fabric/custom_mesh_descriptors/pipeline_sweep"
    )
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--shape", choices=["2x4", "4x4"], help="Pipeline mesh shape (8 or 16 ASICs per stage).")
    ap.add_argument("--stages", type=int, help="Number of pipeline stages (meshes in the closed ring).")
    ap.add_argument(
        "--hosts",
        type=int,
        metavar="N",
        help="Hosts per stage mesh (host_topology width). Default: 1 for 2x4, 2 for 4x4.",
    )
    ap.add_argument(
        "--pinnings",
        action="store_true",
        help="Emit all-to-all corner pinnings (4x4 only; uses even/odd mesh_id_regex entries).",
    )
    ap.add_argument("--out", type=Path, help="Write a single MGD to this file path.")
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=default_out_dir,
        help=f"Output directory when using default naming (default: {default_out_dir}).",
    )
    ap.add_argument(
        "--all-presets",
        action="store_true",
        help="Generate the full SC36 preset sweep (all 2x4 and 4x4 stage counts) into --out-dir.",
    )
    return ap.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if args.all_presets:
        written: list[Path] = []
        for stages in PRESET_STAGES_2X4:
            path = default_output_path(args.out_dir, shape="2x4", stages=stages)
            write_mgd(path, shape="2x4", stages=stages, hosts_per_stage=1, pinnings=False)
            written.append(path)
        for stages in PRESET_STAGES_4X4:
            path = default_output_path(args.out_dir, shape="4x4", stages=stages)
            write_mgd(path, shape="4x4", stages=stages, hosts_per_stage=2, pinnings=True)
            written.append(path)
        print(f"Wrote {len(written)} MGDs to {args.out_dir}:")
        for path in written:
            print(f"  {path.name}")
        return 0

    if args.shape is None or args.stages is None:
        print("error: --shape and --stages are required unless --all-presets is set", file=sys.stderr)
        return 2

    hosts = args.hosts
    if hosts is None:
        hosts = 1 if args.shape == "2x4" else 2

    out_path = args.out
    if out_path is None:
        out_path = default_output_path(args.out_dir, shape=args.shape, stages=args.stages)

    write_mgd(out_path, shape=args.shape, stages=args.stages, hosts_per_stage=hosts, pinnings=args.pinnings)
    print(out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
