// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

// Runtime reload wire layout. Keep blaze/reload/abi.py in sync.
#pragma once

#define RELOAD_ABI_VERSION 3
#define RELOAD_ABI_NUM_PROCESSORS 5
#define RELOAD_ABI_NUM_CORE_TYPES 4
#define RELOAD_ABI_HEADER_WORDS 22
#define RELOAD_ABI_ENTRY_WORDS 16
#define RELOAD_ABI_WEIGHT_WORDS 7
#define RELOAD_ABI_TAP_WORDS 7
#define RELOAD_ABI_ENABLES_CAPTURED 0xFFFFFFFFu

// reload_table_t: word offsets
#define RELOAD_ABI_HDR_NUM_STAGES 0
#define RELOAD_ABI_HDR_MODE 1
#define RELOAD_ABI_HDR_NUM_ROUNDS 2
#define RELOAD_ABI_HDR_TERM_SEM_ADDR 3
#define RELOAD_ABI_HDR_ABI_VERSION 4
#define RELOAD_ABI_HDR_SYNC_ARRIVE_ADDR 5
#define RELOAD_ABI_HDR_SYNC_RELEASE_ADDR 6
#define RELOAD_ABI_HDR_SYNC_COORD_X 7
#define RELOAD_ABI_HDR_SYNC_COORD_Y 8
#define RELOAD_ABI_HDR_SYNC_NUM_CORES 9
#define RELOAD_ABI_HDR_SYNC_IS_COORD 10
#define RELOAD_ABI_HDR_SYNC_MCAST_START_X 11
#define RELOAD_ABI_HDR_SYNC_MCAST_START_Y 12
#define RELOAD_ABI_HDR_SYNC_MCAST_END_X 13
#define RELOAD_ABI_HDR_SYNC_MCAST_END_Y 14
#define RELOAD_ABI_HDR_SYNC_MCAST_DESTS 15
#define RELOAD_ABI_HDR_DBG_RELOAD_COUNT 16
#define RELOAD_ABI_HDR_DBG_LAST_STAGE 17
#define RELOAD_ABI_HDR_DBG_PHASE 18
#define RELOAD_ABI_HDR_DBG_WEIGHT_CYCLES 19
#define RELOAD_ABI_HDR_DBG_BARRIER_CYCLES 20
#define RELOAD_ABI_HDR_CONFIG_SCRATCH_ADDR 21

// stage_entry_t: word offsets
#define RELOAD_ABI_ENTRY_SRC_NOC_X 0
#define RELOAD_ABI_ENTRY_SRC_NOC_Y 1
#define RELOAD_ABI_ENTRY_SRC_NOC 2
#define RELOAD_ABI_ENTRY_SRC_ADDR 3
#define RELOAD_ABI_ENTRY_BLOCK_BYTES 4
#define RELOAD_ABI_ENTRY_LAUNCH_KERNEL_CONFIG_BYTES 5
#define RELOAD_ABI_ENTRY_ENABLES 6
#define RELOAD_ABI_ENTRY_WEIGHT_COUNT 7
#define RELOAD_ABI_ENTRY_WEIGHT_FIRST 8
#define RELOAD_ABI_ENTRY_TAP_BYTES 9
#define RELOAD_ABI_ENTRY_TAP_SRC_L1 10
#define RELOAD_ABI_ENTRY_TAP_DST_NOC_X 11
#define RELOAD_ABI_ENTRY_TAP_DST_NOC_Y 12
#define RELOAD_ABI_ENTRY_TAP_DST_ADDR 13
#define RELOAD_ABI_ENTRY_TAP_NOC 14
#define RELOAD_ABI_ENTRY_TAP_LIMIT 15

// weight_entry_t: word offsets
#define RELOAD_ABI_WEIGHT_SRC_NOC_X 0
#define RELOAD_ABI_WEIGHT_SRC_NOC_Y 1
#define RELOAD_ABI_WEIGHT_SRC_ADDR 2
#define RELOAD_ABI_WEIGHT_BYTES 3
#define RELOAD_ABI_WEIGHT_DST_L1 4
#define RELOAD_ABI_WEIGHT_VC 5
#define RELOAD_ABI_WEIGHT_NOC 6

// reload_mode
#define RELOAD_ABI_MODE_BOUNDED 0
#define RELOAD_ABI_MODE_FIRMWARE_PERSISTENT 1

// reload_phase
#define RELOAD_ABI_PHASE_IDLE 0
#define RELOAD_ABI_PHASE_ENTER 1
#define RELOAD_ABI_PHASE_BARRIER 2
#define RELOAD_ABI_PHASE_FETCH 3
#define RELOAD_ABI_PHASE_INSTALLED 4
#define RELOAD_ABI_PHASE_DONE 5
#define RELOAD_ABI_PHASE_TAP_ENTER 6
#define RELOAD_ABI_PHASE_TAP_DONE 7
#define RELOAD_ABI_PHASE_ABI_MISMATCH 8
