COMPILER_GRAPH_DESERIALIZER = ${LIBDIR}/libgraph_deserializer.a
COMPILER_GRAPH_DESERIALIZER_SRCS = compiler/graph_deserializer/graph_deserializer.cpp

COMPILER_GRAPH_DESERIALIZER_OBJS = $(addprefix $(OBJDIR)/, $(COMPILER_GRAPH_DESERIALIZER_SRCS:.cpp=.o))
COMPILER_GRAPH_DESERIALIZER_DEPS = $(addprefix $(OBJDIR)/, $(COMPILER_GRAPH_DESERIALIZER_SRCS:.cpp=.d))

COMPILER_GRAPH_DESERIALIZER_INCLUDES = $(COMPILER_INCLUDES)
COMPILER_GRAPH_DESERIALIZER_LDFLAGS = -lreportify -lgraph_lib -lcommon

-include $(COMPILER_GRAPH_DESERIALIZER_DEPS)

compiler/graph_deserializer: $(COMPILER_GRAPH_DESERIALIZER)

$(COMPILER_GRAPH_DESERIALIZER): $(COMPILER_GRAPH_LIB) $(COMPILER_REPORTIFY) $(COMPILER_GRAPH_DESERIALIZER_OBJS)
	@mkdir -p $(LIBDIR)
	ar rcs $@ $^

$(OBJDIR)/compiler/graph_deserializer/%.o: compiler/graph_deserializer/%.cpp
	@mkdir -p $(@D)
	$(CXX) $(COMPILER_CFLAGS) $(CXXFLAGS) $(STATIC_LIB_FLAGS) $(COMPILER_GRAPH_DESERIALIZER_INCLUDES) -c -o $@ $<

