// SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0

#include <stdint.h>
#include "api/dataflow/dataflow_api.h"
#include "api/dataflow/noc.h"
#include "api/dataflow/noc_semaphore.h"
#include "api/dataflow/circular_buffer.h"
#include "api/core_local_mem.h"
#include "api/tensor/noc_traits.h"
#include "ckernel_defs.h"
#include "tt-metalium/constants.hpp"
#include "api/debug/dprint_pages.h"

void kernel_main() {
    // Compile time arguments
    constexpr uint32_t layer_id = get_named_compile_time_arg_val("layer_id");
    constexpr uint32_t num_cores = get_named_compile_time_arg_val("num_cores");
    constexpr uint32_t collector_physical_x = get_named_compile_time_arg_val("collector_physical_x");
    constexpr uint32_t collector_physical_y = get_named_compile_time_arg_val("collector_physical_y");
    constexpr uint32_t num_group_mask_dsts = get_named_compile_time_arg_val("num_group_mask_dsts");

    // Physical (x, y) of every core the collector sends the group masks to. Generated by the program
    // factory; see the note there on why this is a unicast list and not a multicast rectangle.
    constexpr uint8_t group_mask_dst_coords[num_group_mask_dsts][2] = GROUP_MASK_DST_COORDS;

    constexpr auto in_args = TensorAccessorArgs<0>();
    constexpr auto w_args = TensorAccessorArgs<in_args.next_compile_time_args_offset()>();
    constexpr auto out_args = TensorAccessorArgs<w_args.next_compile_time_args_offset()>();

    // Run-time arguments
    uint32_t argidx = 0;
    const auto dram_bank_id = get_arg_val<uint32_t>(argidx++);
    const auto vchannel = get_arg_val<uint32_t>(argidx++);
    const auto in_addr = get_arg_val<uint32_t>(argidx++);
    const auto w_addr = get_arg_val<uint32_t>(argidx++);
    const auto out_addr = get_arg_val<uint32_t>(argidx++);
    const auto partial_semaphore = get_arg_val<uint32_t>(argidx++);
    const auto is_send_core = get_arg_val<uint32_t>(argidx++);
    const auto neighbor1_physical_x = get_arg_val<uint32_t>(argidx++);
    const auto neighbor1_physical_y = get_arg_val<uint32_t>(argidx++);
    const auto neighbor2_physical_x = get_arg_val<uint32_t>(argidx++);
    const auto neighbor2_physical_y = get_arg_val<uint32_t>(argidx++);
    const auto core_id = get_arg_val<uint32_t>(argidx++);
    const auto raw_scores_semaphore = get_arg_val<uint32_t>(argidx++);

    // CBs
    constexpr auto cb_r2c_w_id = tt::CBIndex::c_0;
    constexpr auto cb_s2c_in_id = tt::CBIndex::c_1;
    constexpr auto cb_c2w_rdy_id = tt::CBIndex::c_2;
    constexpr auto cb_w2c_in2_id = tt::CBIndex::c_3;
    constexpr auto cb_s2c_out_id = tt::CBIndex::c_4;
    constexpr auto cb_w2c_in3_id = tt::CBIndex::c_5;
    constexpr auto cb_w2c_in4_id = tt::CBIndex::c_6;
    constexpr auto cb_w2c_in5_id = tt::CBIndex::c_7;
    constexpr auto cb_w2c_in6_id = tt::CBIndex::c_8;
    constexpr auto cb_w2c_in7_id = tt::CBIndex::c_9;

    // Aliases
    constexpr auto cb_w2c_in8_id = tt::CBIndex::c_6;

    CircularBuffer cb_c2w_rdy(cb_c2w_rdy_id);
    CircularBuffer cb_w2c_in2(cb_w2c_in2_id);
    CircularBuffer cb_s2c_out(cb_s2c_out_id);
    CircularBuffer cb_w2c_in4(cb_w2c_in4_id);
    CircularBuffer cb_w2c_in5(cb_w2c_in5_id);
    CircularBuffer cb_w2c_in6(cb_w2c_in6_id);
    CircularBuffer cb_w2c_in8(cb_w2c_in8_id);

    // Tile sizes
    constexpr uint32_t in_tile_size = get_tile_size(cb_s2c_in_id);
    constexpr uint32_t w_tile_size = get_tile_size(cb_r2c_w_id);
    constexpr uint32_t out_tile_size = get_tile_size(cb_s2c_out_id);

    // NOC Packet size
    constexpr uint32_t noc_packet_size = 8192;

    // Constants for MoE Gate MM
    const uint32_t num_w_tiles_h = is_send_core ? 2 * 72 : 2 * 76;
    constexpr uint32_t num_w_tiles_w = 1;

    //-------------------------------------------------------------------------
    // Reduction transactions
    //-------------------------------------------------------------------------
    uint32_t semaphore_addr = get_semaphore(partial_semaphore);
    volatile tt_l1_ptr uint32_t* my_semaphore_ptr = reinterpret_cast<volatile tt_l1_ptr uint32_t*>(semaphore_addr);

    const uint64_t partial_semaphore_noc_addr1 =
        get_noc_addr(neighbor1_physical_x, neighbor1_physical_y, semaphore_addr);

    const uint64_t partial_semaphore_noc_addr2 =
        get_noc_addr(neighbor2_physical_x, neighbor2_physical_y, semaphore_addr);

    const uint32_t local_src_addr = cb_s2c_out.get_write_ptr();
    const uint32_t local_dst_addr = cb_w2c_in2.get_write_ptr();
    const uint64_t neighbor_dst_addr1 = get_noc_addr(neighbor1_physical_x, neighbor1_physical_y, local_dst_addr);
    const uint64_t neighbor_dst_addr2 = get_noc_addr(neighbor2_physical_x, neighbor2_physical_y, local_dst_addr);

    // Use semaphore_inc<posted=true> with 1 transaction ID and flush barrier for trids
    constexpr uint32_t semaphore_trid = 0x4;

    //-------------------------------------------------------------------------
    // Collector core
    //-------------------------------------------------------------------------
    constexpr uint32_t COLLECTOR_CORE_ID = 7;

    const uint32_t local_collector_addr = 1024 + cb_w2c_in4.get_write_ptr();
    const uint64_t collector_dst_base_addr =
        get_noc_addr(collector_physical_x, collector_physical_y, local_collector_addr);
    const uint32_t collector_offset = core_id * out_tile_size;

    constexpr uint32_t group_score_size = tt::constants::FACE_WIDTH * sizeof(uint16_t);

    //-------------------------------------------------------------------------
    // Group scores (7 cores -> 1 collector core)
    //-------------------------------------------------------------------------

    // Group scores: data exists in 1st and 4th row of the first face of the bfloat16 tile
    constexpr uint32_t group_score_offset1 = 0;
    constexpr uint32_t group_score_offset2 = 4 * group_score_size;
    const uint32_t local_group_score_base_addr = cb_c2w_rdy.get_write_ptr();
    const uint32_t local_group_score_src_addr1 = local_group_score_base_addr + group_score_offset1;
    const uint32_t local_group_score_src_addr2 = local_group_score_base_addr + group_score_offset2;

    const uint32_t local_group_scores_dst_addr1 = local_collector_addr + core_id * group_score_size;
    const uint32_t local_group_scores_dst_addr2 = local_group_scores_dst_addr1 + 8 * group_score_size;

    const uint64_t collector_semaphore_noc_addr =
        get_noc_addr(collector_physical_x, collector_physical_y, semaphore_addr);

    //-------------------------------------------------------------------------
    // Group masks (1 collector core -> 7 cores)
    //-------------------------------------------------------------------------
    constexpr uint32_t group_masks_size = get_tile_size(cb_w2c_in5_id);
    const uint32_t local_group_masks_addr = cb_w2c_in5.get_write_ptr();

    //-------------------------------------------------------------------------
    // Top8 partials (7 cores -> 1 collector core)
    //-------------------------------------------------------------------------
    constexpr uint32_t partials_size = 2 * tt::constants::FACE_HW * sizeof(uint16_t);  // values and indices

    // Top8 partials: data exists in first 16 rows
    const uint32_t local_top8_partials_src_addr = cb_w2c_in8.get_write_ptr();

    const uint32_t local_top8_dst_base_addr = cb_w2c_in6.get_write_ptr();
    const uint32_t local_top8_dst_addr = local_top8_dst_base_addr + core_id * partials_size;

    //-------------------------------------------------------------------------
    *my_semaphore_ptr = 0;

    if (is_send_core) {
        // Since neighbor2 is farther, we send it first.
        // Set state for the writes
        noc_async_write_one_packet_set_state</*posted=*/true>(neighbor_dst_addr2, out_tile_size, /*noc=*/1, vchannel);

        // Wait for the data1 to be ready
        cb_c2w_rdy.wait_front(1);

        // Send the data to the neighbor1
        noc_async_write_one_packet_with_state</*posted=*/true>(local_src_addr, neighbor_dst_addr2);

        // The partial (write_cmd_buf) and the semaphore set that publishes it (write_at_cmd_buf)
        // come from different NIU command buffers, so the partial has to be on the NOC before the
        // semaphore is issued; otherwise neighbor2 can reduce a partial that has not arrived.
        noc_async_posted_writes_flushed(/*noc=*/1);

        // Signal neighbor2 that data is ready (increment their semaphore)
        noc_inline_dw_write_set_state</*posted=*/true, /*set_val=*/true>(
            partial_semaphore_noc_addr2, /*val=*/1, /*be=*/0xF, /*cmd_buf=*/write_at_cmd_buf, /*noc=*/1, vchannel);
        noc_inline_dw_write_with_state<
            /*update_addr_lo=*/false,
            /*update_counter=*/true,
            /*posted=*/true,
            /*update_addr_hi=*/false,
            /*update_val=*/false>(/*val=*/1);

        // Ensure write and semaphore have left the core before continuing
        noc_async_posted_writes_flushed();

        cb_c2w_rdy.pop_front(1);

        noc_async_write_one_packet_set_state</*posted=*/true>(neighbor_dst_addr1, out_tile_size, /*noc=*/1, vchannel);

        // Wait for the data2 to be ready
        cb_c2w_rdy.wait_front(1);

        // Send the data to the neighbor1
        noc_async_write_one_packet_with_state</*posted=*/true>(local_src_addr, neighbor_dst_addr1);

        // Same ordering requirement as for neighbor2 above.
        noc_async_posted_writes_flushed(/*noc=*/1);

        // Signal neighbor1 that data is ready (increment their semaphore)
        noc_inline_dw_write_set_state</*posted=*/true, /*set_val=*/true>(
            partial_semaphore_noc_addr1, /*val=*/1, /*be=*/0xF, /*cmd_buf=*/write_at_cmd_buf, /*noc=*/1, vchannel);
        noc_inline_dw_write_with_state<
            /*update_addr_lo=*/false,
            /*update_counter=*/true,
            /*posted=*/true,
            /*update_addr_hi=*/false,
            /*update_val=*/false>(/*val=*/1);

        // Ensure write and semaphore have left the core before continuing
        noc_async_posted_writes_flushed();

        cb_c2w_rdy.pop_front(1);

        return;
    }

    // -------------------------------------------------------------------------
    // Rest of the 8 cores do more
    // -------------------------------------------------------------------------
    cb_w2c_in2.reserve_back(1);

    // Wait for the data from sender cores to be ready
    noc_semaphore_wait_min(my_semaphore_ptr, 1);
    *my_semaphore_ptr = 0;
    cb_w2c_in2.push_back(1);

    // Wait for group scores to be ready from compute
    cb_c2w_rdy.wait_front(1);

    //-------------------------------------------------------------------------
    // Cores sending data to the collector core
    //-------------------------------------------------------------------------
    if (core_id != COLLECTOR_CORE_ID) {
        noc_async_write_one_packet_set_state</*posted=*/true>(
            collector_dst_base_addr, group_score_size, /*noc=*/1, vchannel);

        // Send them over to the collector core
        noc_async_write_one_packet_with_state</*posted=*/true>(
            local_group_score_src_addr1, local_group_scores_dst_addr1);
        noc_async_write_one_packet_with_state</*posted=*/true>(
            local_group_score_src_addr2, local_group_scores_dst_addr2);

        // The payload writes (write_cmd_buf) and the semaphore increment that publishes them
        // (write_at_cmd_buf) are issued from different NIU command buffers, so without this the
        // increment can be launched before the group scores have left this core. This also has to
        // precede the cb_c2w_rdy.pop_front() below, which releases the source buffer.
        noc_async_posted_writes_flushed(/*noc=*/1);

        // Signal the collector core that data is ready (increment their semaphore)
        noc_async_write_set_trid(semaphore_trid, /*noc=*/1);
        noc_semaphore_inc</*posted=*/true>(collector_semaphore_noc_addr, /*incr=*/1, /*noc_id=*/1, /*vc=*/vchannel);
        noc_async_write_flushed_with_trid(semaphore_trid, /*noc=*/1);
        noc_async_write_set_trid(0, /*noc=*/1);

        // We are done with the group scores
        cb_c2w_rdy.pop_front(1);

        cb_w2c_in5.reserve_back(1);

        // Wait for the group mask to be ready in the collector core
        noc_semaphore_wait_min(my_semaphore_ptr, 1);
        *my_semaphore_ptr = 0;

        // Let compute know we got the group masks
        cb_w2c_in5.push_back(1);

        // Wait for compute to send the top-8 values and indices
        cb_w2c_in8.wait_front(1);

        noc_async_write_one_packet_set_state</*posted=*/true>(
            collector_dst_base_addr, partials_size, /*noc=*/1, vchannel);

        // Send them over to the collector core
        noc_async_write_one_packet_with_state</*posted=*/true>(local_top8_partials_src_addr, local_top8_dst_addr);

        // Same ordering requirement as for the group scores above: the posted payload write must
        // leave this core before the atomic that publishes it, and before cb_w2c_in8.pop_front()
        // releases the source buffer.
        noc_async_posted_writes_flushed(/*noc=*/1);

        // Signal the collector core that data is ready (increment their semaphore)
        noc_async_write_set_trid(semaphore_trid, /*noc=*/1);
        noc_semaphore_inc</*posted=*/true>(collector_semaphore_noc_addr, /*incr=*/1, /*noc_id=*/1, /*vc=*/vchannel);
        noc_async_write_flushed_with_trid(semaphore_trid, /*noc=*/1);
        noc_async_write_set_trid(0, /*noc=*/1);

        cb_w2c_in8.pop_front(1);
    }

    //-------------------------------------------------------------------------
    // Collector core
    //-------------------------------------------------------------------------
    if (core_id == COLLECTOR_CORE_ID) {
        // Rejig the group scores to be in the correct location -> where everyone else also puts it
        auto src_ptr = reinterpret_cast<volatile tt_l1_ptr uint32_t*>(local_group_score_src_addr1);
        auto dst_ptr = reinterpret_cast<volatile tt_l1_ptr uint32_t*>(local_group_scores_dst_addr1);
        for (uint32_t i = 0; i < 8; i++) {
            dst_ptr[i] = src_ptr[i];
        }

        // Same, but for the second row of the group scores
        src_ptr = reinterpret_cast<volatile tt_l1_ptr uint32_t*>(local_group_score_src_addr2);
        dst_ptr = reinterpret_cast<volatile tt_l1_ptr uint32_t*>(local_group_scores_dst_addr2);
        for (uint32_t i = 0; i < 8; i++) {
            dst_ptr[i] = src_ptr[i];
        }

        // We are done with the group scores
        cb_c2w_rdy.pop_front(1);

        cb_w2c_in4.reserve_back(1);

        // I am collecting, let us wait for everyone else to finish sending their data to me
        noc_semaphore_wait_min(my_semaphore_ptr, 7);
        *my_semaphore_ptr = 0;

        // Let compute know that we got the group scores
        cb_w2c_in4.push_back(1);

        //-----------------------------------------------------------------
        // Get the group masks
        //-----------------------------------------------------------------
        cb_w2c_in5.wait_front(1);

        // Send this data to every other core taking part in the reduction. This is a unicast fan-out
        // rather than a multicast: the op runs on the DRAM-adjacent workers, which are not a
        // contiguous rectangle, so any bounding box around them would also cover cores that are not
        // part of this program and the semaphore write would land inside their kernel-config window.
        for (uint32_t dst_id = 0; dst_id < num_group_mask_dsts; ++dst_id) {
            const uint64_t dst_noc_addr = get_noc_addr(
                group_mask_dst_coords[dst_id][0], group_mask_dst_coords[dst_id][1], local_group_masks_addr, /*noc=*/1);
            noc_async_write_one_packet(local_group_masks_addr, dst_noc_addr, group_masks_size, /*noc=*/1, vchannel);
        }

        // The masks must be committed in the destinations' L1 before they can observe the semaphore,
        // so wait for all of the above writes to be acked before publishing.
        noc_async_write_barrier(/*noc=*/1);

        // Set the semaphore to let the clients know they got the data
        *my_semaphore_ptr = 1;
        for (uint32_t dst_id = 0; dst_id < num_group_mask_dsts; ++dst_id) {
            const uint64_t dst_semaphore_noc_addr = get_noc_addr(
                group_mask_dst_coords[dst_id][0], group_mask_dst_coords[dst_id][1], semaphore_addr, /*noc=*/1);
            noc_semaphore_set_remote(semaphore_addr, dst_semaphore_noc_addr, /*noc=*/1);
        }

        cb_w2c_in5.pop_front(1);

        cb_w2c_in6.reserve_back(4);

        // Wait for the top8 partials to arrive
        noc_semaphore_wait_min(my_semaphore_ptr, 1 + 7);

        // Let compute know that we got the top8 partials
        cb_w2c_in6.push_back(4);

        // Wait for final top8 to be ready from compute
        cb_c2w_rdy.wait_front(1);
        cb_c2w_rdy.pop_front(1);

        // Drain the group-mask payload writes and the semaphore writes that publish them before
        // leaving the kernel, so nothing is still in flight when this program tears down.
        noc_async_write_barrier(/*noc=*/1);
    }
}
