// SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

/*******************************************************************************
 * Header file for register addresses and fields
 *
 * This file was AUTO-GENERATED by this script:
 *       create_reg_c_header.py   (r2024-08-02)
 * ... from this input file:
 *       tensix_noc_overlay.rdl
 * ... using this as the target address space:
 *       tt_tensix_noc_overlay
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

#ifndef TT_TENSIX_NOC_OVERLAY_REG_H
#define TT_TENSIX_NOC_OVERLAY_REG_H

#include <stdint.h>

//==============================================================================
// Addresses for Address Map: tt_tensix_noc_overlay
//==============================================================================

#define TT_TENSIX_NOC_OVERLAY_REG_MAP_BASE_ADDR (0x00000000)
#define TT_TENSIX_NOC_OVERLAY_REG_MAP_SIZE (0x1000000000)

//==============================================================================
// Addresses for Address Map: tt_t6_l1_memory
//==============================================================================

#define TT_T6_L1_MEMORY_REG_MAP_BASE_ADDR (0x00000000)
#define TT_T6_L1_MEMORY_REG_MAP_SIZE (0x00800000)

//==============================================================================
// Memory: t6_l1
//==============================================================================

#define TT_T6_L1_MEMORY_T6_L1_MEM_BASE_ADDR (0x00000000)
#define TT_T6_L1_MEMORY_T6_L1_MEM_SIZE (0x00800000)

//==============================================================================
// Addresses for Address Map: tt_local_tensix
//==============================================================================

#define TT_LOCAL_TENSIX_REG_MAP_BASE_ADDR (0x00800000)
#define TT_LOCAL_TENSIX_REG_MAP_SIZE (0x01000000)

//==============================================================================
// Memory: local_tensix_regs
//==============================================================================

#define TT_LOCAL_TENSIX_LOCAL_TENSIX_REGS_MEM_BASE_ADDR (0x00800000)
#define TT_LOCAL_TENSIX_LOCAL_TENSIX_REGS_MEM_SIZE (0x01000000)

//==============================================================================
// Addresses for Address Map: tt_tensix
//==============================================================================

#define TT_TENSIX_REG_MAP_BASE_ADDR (0x01800000)
#define TT_TENSIX_REG_MAP_SIZE (0x00800000)

//==============================================================================
// Memory: tensix_regs
//==============================================================================

#define TT_TENSIX_TENSIX_REGS_MEM_BASE_ADDR (0x01800000)
#define TT_TENSIX_TENSIX_REGS_MEM_SIZE (0x00800000)

//==============================================================================
// Addresses for Address Map: tt_noc
//==============================================================================

#define TT_NOC_REG_MAP_BASE_ADDR (0x02000000)
#define TT_NOC_REG_MAP_SIZE (0x01000000)

//==============================================================================
// Memory: noc_regs
//==============================================================================

#define TT_NOC_NOC_REGS_MEM_BASE_ADDR (0x02000000)
#define TT_NOC_NOC_REGS_MEM_SIZE (0x01000000)

//==============================================================================
// Addresses for Address Map: tt_overlay
//==============================================================================

#define TT_OVERLAY_REG_MAP_BASE_ADDR (0x03000000)
#define TT_OVERLAY_REG_MAP_SIZE (0x01000000)

//==============================================================================
// Memory: overlay_regs
//==============================================================================

#define TT_OVERLAY_OVERLAY_REGS_MEM_BASE_ADDR (0x03000000)
#define TT_OVERLAY_OVERLAY_REGS_MEM_SIZE (0x01000000)

//==============================================================================
// Addresses for Address Map: tt_local_overlay
//==============================================================================

#define TT_LOCAL_OVERLAY_REG_MAP_BASE_ADDR (0x04000000)
#define TT_LOCAL_OVERLAY_REG_MAP_SIZE (0x08000000)

//==============================================================================
// Memory: local_overlay_regs
//==============================================================================

#define TT_LOCAL_OVERLAY_LOCAL_OVERLAY_REGS_MEM_BASE_ADDR (0x04000000)
#define TT_LOCAL_OVERLAY_LOCAL_OVERLAY_REGS_MEM_SIZE (0x08000000)

//==============================================================================
// Addresses for Address Map: reserved
//==============================================================================

#define RESERVED_REG_MAP_BASE_ADDR (0x0C000000)
#define RESERVED_REG_MAP_SIZE (0xFF4000000)

//==============================================================================
// Memory: reserved_regs
//==============================================================================

#define RESERVED_RESERVED_REGS_MEM_BASE_ADDR (0x0C000000)
#define RESERVED_RESERVED_REGS_MEM_SIZE (0xFF4000000)

//==============================================================================
// Structs for Address Map: tt_tensix_noc_overlay
//==============================================================================

using tt_tensix_noc_overlay_regmap_t = struct {};

//==============================================================================
// Bit Fields for Address Map: tt_tensix_noc_overlay
//==============================================================================

#endif
