# Source files for ttnn_op_experimental_cache_bundle_allocation.

set(TTNN_OP_EXPERIMENTAL_CACHE_BUNDLE_ALLOCATION_API_HEADERS cache_bundle_allocation.hpp)
set(TTNN_OP_EXPERIMENTAL_CACHE_BUNDLE_ALLOCATION_SRCS device/update_cache_bundle_allocation_device_operation.cpp)
set(TTNN_OP_EXPERIMENTAL_CACHE_BUNDLE_ALLOCATION_NANOBIND_SRCS cache_bundle_allocation_nanobind.cpp)
set(TTNN_OP_EXPERIMENTAL_CACHE_BUNDLE_ALLOCATION_KERNELS kernels/update_cache_bundle_allocation.cpp)
