#!/usr/bin/env bash
[[ -n ${HWLOCK_HELD:-} || -n ${GITHUB_ACTIONS:-} ]] || { echo "not under hwlock" >&2; exit 2; }
# Round 3 eltwise binary, sixth pass, final head merged with main: the tests of the per-define A/Bs, every hand-off define of
# their kernels removed against the head, outputs hashed and compared (seeded); the DiT and bge cases by -k.
cd /work
cut -d'|' -f1 tests/eb_r3_ci/r9opt/off_h.txt tests/eb_r3_ci/r9opt/off_b.txt tests/eb_r3_ci/r9opt/off_w.txt | sort -u > /tmp/kern_r9.txt
wc -l < /tmp/kern_r9.txt
echo "##### bits ids"
EB_NODES_FILE=/work/tests/eb_r3_ci/r9opt/ids_bits.txt bash tests/eb_r3_ci/bits_strip.sh /tmp/kern_r9.txt -p eb_select_plugin -p eb_unskip_plugin -p eb_seed_plugin tests/eb_r3_ci/test_eb_r3_ops.py tests/eb_r3_ci/test_eb_x3.py tests/tt_eager/python_api_testing/unit_testing/misc/test_rotary_embedding_hf.py tests/ttnn/nightly/unit_tests/operations/experimental/deepseek_prefill/test_mhc_split_sinkhorn.py tests/ttnn/nightly/unit_tests/operations/experimental/deepseek_prefill/test_moe_hash_gate.py tests/ttnn/nightly/unit_tests/operations/experimental/kda/test_prepare_chunk_recurrence.py tests/ttnn/nightly/unit_tests/operations/experimental/kda/test_sigmoid_gated_rms_norm.py tests/ttnn/nightly/unit_tests/operations/experimental/test_topk_router_gpt.py tests/ttnn/nightly/unit_tests/operations/fused/test_layernorm_sharded.py tests/ttnn/nightly/unit_tests/operations/moreh/test_moreh_adamw.py tests/ttnn/nightly/unit_tests/operations/moreh/test_moreh_clip_grad_norm.py tests/ttnn/nightly/unit_tests/operations/moreh/test_moreh_layer_norm.py tests/ttnn/nightly/unit_tests/operations/moreh/test_moreh_matmul.py tests/ttnn/nightly/unit_tests/operations/moreh/test_moreh_nll_loss.py tests/ttnn/nightly/unit_tests/operations/moreh/test_moreh_norm.py tests/ttnn/nightly/unit_tests/operations/moreh/test_moreh_softmax.py tests/ttnn/nightly/unit_tests/operations/ssm/test_ssm_prefix_scan.py tests/ttnn/nightly/unit_tests/operations/ssm/test_ssm_repeat_and_interleave_eltwise_mul.py tests/ttnn/nightly/unit_tests/operations/transformers/test_distributed_fused_rmsnorm.py tests/ttnn/unit_tests/operations/fused/test_distributed_layernorm_sharded.py tests/ttnn/unit_tests/operations/reduce/test_moe.py tests/ttnn/unit_tests/operations/sdpa/test_sdpa_decode.py tests/ttnn/unit_tests/operations/transformers/test_chunk_gated_delta_rule.py tests/ttnn/unit_tests/operations/transformers/test_chunk_gdn_prims.py 
echo "##### bits dit bge"
bash tests/eb_r3_ci/bits_strip.sh /tmp/kern_r9.txt -p eb_seed_plugin tests/eb_r3_ci/test_eb_dit.py models/tt_dit/tests/unit/test_dit_rmsnorm_local.py tests/eb_r3_ci/test_eb_r3_ops.py -k "test_dit_tp1 or test_dit_ln_tp1 or (test_local_rmsnorm_rope and single_device) or test_bge_balanced_layernorm"
