// SPDX-FileCopyrightText: © 2024 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

enum class SfpuType {
    unused = 0,
    frac,
    swish,
    atanh,
    sinh,
    softcap,
    // Placeholders referenced by third_party/tt_llk headers
    abs,
    acosh,
    add1,
    add_top_row,
    asinh,
    cosine,
    equal_zero,
    exp2,
    fill,
    greater_than_equal_zero,
    greater_than_zero,
    hardsigmoid,
    isfinite,
    isinf,
    isnan,
    isneginf,
    isposinf,
    less_than_equal_zero,
    less_than_zero,
    log1p,
    max,
    max_int32,
    max_uint32,
    min,
    min_int32,
    min_uint32,
    mul_int32,
    mul_uint16,
    neg,
    negative,
    not_equal_zero,
    reciprocal,
    reduce,
    relu,
    rsqrt,
    signbit,
    sine,
    sqrt,
    square,
    threshold,
    topk_local_sort,
    topk_merge,
    topk_rebuild,
    typecast,
    unary_eq,
    unary_ge,
    unary_gt,
    unary_le,
    unary_lt,
    unary_max,
    unary_max_int32,
    unary_max_uint32,
    unary_min,
    unary_min_int32,
    unary_min_uint32,
    unary_ne,
    where,
};
