# Two 16x4 LINE,RING meshes spanning two Galaxies each.
# Both meshes enable dim-0 ex4 and ex8 express-link patterns.

mesh_descriptors {
  name: "M_16x4"
  arch: BLACKHOLE
  device_topology { dims: [ 16, 4 ] dim_types: [ LINE, RING ] }
  host_topology   { dims: [ 2, 1 ] }
  channels { count: 2 policy: RELAXED }
  express_links { dim_idx: 0 pattern { start: 2 step: 4 } }
  express_links { dim_idx: 0 pattern { start: 0 step: 8 } }
}

graph_descriptors {
  name: "G0"
  type: "FABRIC"
  instances { mesh { mesh_descriptor: "M_16x4" mesh_id: 0 } }
  instances { mesh { mesh_descriptor: "M_16x4" mesh_id: 1 } }

  connections {
    nodes { mesh { mesh_descriptor: "M_16x4" mesh_id: 0 } }
    nodes { mesh { mesh_descriptor: "M_16x4" mesh_id: 1 } }
    channels { count: 8 policy: RELAXED }
  }
}

top_level_instance { graph { graph_descriptor: "G0" graph_id: 0 } }
