// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by run_csv.sh
// Degree 7, 1 segments, range [0.0, 10.0]
#include <array>
#include <cstdint>

#define EMBEDDED_LUT
constexpr uint32_t POLY_DEGREE = 7;
constexpr uint32_t NUM_SEGMENTS = 1;

constexpr float INPUT_MIN = 0.0000000000000000e+00f;
constexpr float INPUT_MAX = 1.0000000000000000e+01f;

constexpr uint32_t LUT_SIZE_BF16 = 10;
constexpr std::array<float, LUT_SIZE_BF16> LUT_DATA_BF16 = {
    {0.0000000000000000e+00f,
     1.0000000000000000e+01f,
     0.0000000000000000e+00f,
     1.1273097991943359e+00f,
     2.8920538723468781e-02f,
     -5.0188791751861572e-01f,
     1.8838477134704590e-01f,
     1.7677292227745056e-02f,
     -2.0371120423078537e-02f,
     2.8374409303069115e-03f}};

constexpr uint32_t LUT_SIZE_FP32 = 10;
constexpr std::array<float, LUT_SIZE_FP32> LUT_DATA_FP32 = {
    {0.0000000000000000e+00f,
     1.0000000000000000e+01f,
     0.0000000000000000e+00f,
     1.1273097991943359e+00f,
     2.8920538723468781e-02f,
     -5.0188791751861572e-01f,
     1.8838477134704590e-01f,
     1.7677292227745056e-02f,
     -2.0371120423078537e-02f,
     2.8374409303069115e-03f}};

#ifdef USE_BF16
// static: a namespace-scope constexpr REFERENCE has EXTERNAL linkage (the
// internal-linkage-for-const rule covers const objects, not references),
// so without static the reference symbol pins the whole LUT array into the
// local-data-memory image of every TRISC (~1.7KB free) -- s256+ configs
// then fail to link on any kernel that reads the LUT at runtime (segment
// overflows region:1). Internal linkage lets LTO discard the dead copy;
// compile-time consumers are unaffected.
static constexpr auto& LUT_DATA = LUT_DATA_BF16;
constexpr uint32_t LUT_SIZE = LUT_SIZE_BF16;
#else
static constexpr auto& LUT_DATA = LUT_DATA_FP32;
constexpr uint32_t LUT_SIZE = LUT_SIZE_FP32;
#endif

// eval_method: poly_cascade (default piecewise polynomial cascade)
#define TT_ACT_EVAL_KIND TT_ACT_EVAL_POLY_CASCADE
#define EVAL_METHOD_POLY_CASCADE

// basis_kind=signed_abs_poly: y = copysign(clamp(P(abs(x))), x)
#define BASIS_SIGNED_ABS_POLY
#define BASIS_INPUT_ABS_X
#define BASIS_POST_SIGN_X
#define BASIS_CLAMP_MAX
constexpr float BASIS_CLAMP_MAX_VALUE = 1.0000000000000000e+00f;

// Declared special-value policy from the typed activation specification.
// 0=NaN 1=+Inf 2=-Inf 3=+0 4=-0 5=finite_other(pass through)
#define TT_SPECIAL_VALUE_POLICY
#define TT_SPECIAL_NAN 0
#define TT_SPECIAL_POS_INF 5
#define TT_SPECIAL_NEG_INF 5
#define TT_SPECIAL_POS_ZERO 3
#define TT_SPECIAL_NEG_ZERO 4

#include "../piecewise_generic.cpp"
