hosts: {
  hall: "SC_Floor_1"
  aisle: "A"
  rack: 1
  shelf_u: 10
  node_type: "p150_qb_node"
  host: "tt-quietbox-2"
}
hosts: {
  hall: "SC_Floor_1"
  aisle: "A"
  rack: 1
  shelf_u: 20
  node_type: "p150_qb_node"
  host: "tt-quietbox-3"
}
hosts: {
  hall: "SC_Floor_1"
  aisle: "A"
  rack: 1
  shelf_u: 30
  node_type: "p150_qb_node"
  host: "tt-quietbox-4"
}
hosts: {
  hall: "SC_Floor_1"
  aisle: "A"
  rack: 1
  shelf_u: 40
  node_type: "p150_qb_node"
  host: "tt-quietbox-5"
}
