hosts: {
  hall: "SC_Floor_5"
  aisle: "A"
  rack: 1
  shelf_u: 12
  node_type: "N300_LB"
  host: "metal-wh-03"
}
hosts: {
  hall: "SC_Floor_5"
  aisle: "A"
  rack: 1
  shelf_u: 28
  node_type: "N300_LB"
  host: "metal-wh-08"
}
hosts: {
  hall: "SC_Floor_5"
  aisle: "A"
  rack: 1
  shelf_u: 18
  node_type: "N300_LB"
  host: "metal-wh-02"
}
hosts: {
  hall: "SC_Floor_5"
  aisle: "A"
  rack: 1
  shelf_u: 22
  node_type: "N300_LB"
  host: "metal-wh-01"
}
hosts: {
  hall: "SC_Floor_5"
  aisle: "A"
  rack: 1
  shelf_u: 4
  node_type: "N300_LB"
  host: "metal-wh-05"
}
