# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Pure-TTNN NemotronH top-k router for `nemotron_h_topk_router`.

HF reference (modeling_nemotron_h.py NemotronHTopkRouter.forward):

    hidden = hidden.view(-1, hidden_size)
    logits = F.linear(hidden.float(), weight.float())     # (T, n_experts)
    scores = logits.sigmoid()
    scores_for_choice = scores + e_score_correction_bias  # (T, n_experts)
    # group selection (n_group=1, topk_group=1 -> NO-OP for this config):
    topk_indices = topk(scores_for_choice, top_k, sorted=False)[1]   # (T, top_k)
    topk_weights = scores.gather(1, topk_indices)
    if norm_topk_prob: topk_weights /= (sum + 1e-20)
    topk_weights *= routed_scaling_factor
    return topk_indices, topk_weights

For this checkpoint n_group == topk_group == 1, so the group masking is a
no-op and routing reduces to a plain top-`top_k` over `sigmoid(logits)+bias`.

The selection is implemented with a FULLY-FP32 ALL-PAIRS RANK rather than
`ttnn.topk`: the graduated sibling `nemotron_h_m_o_e` measured that bf16
`ttnn.topk` rounds the 6th/7th-of-128 boundary scores equal and mis-selects,
capping PCC ~0.979. `rank_i = #{j : choice_j > choice_i}` is exact in fp32;
the index whose rank == r is the r-th largest expert. The PCC test compares
`out[0]` (indices) as a per-row sorted SET, so emitting indices in rank order
is sufficient.
"""
import torch
import ttnn


def _coerce_to_torch(x):
    try:
        import ttnn as _ttnn
        if isinstance(x, _ttnn.Tensor):
            import torch as _torch
            t = _ttnn.to_torch(x)
            if t.is_floating_point():
                if t.dtype != _torch.float32:
                    t = t.to(_torch.float32)
            elif t.dtype != _torch.bool:
                t = t.to(_torch.long)
            return t
    except Exception:
        pass
    if isinstance(x, tuple):
        return tuple(_coerce_to_torch(e) for e in x)
    if isinstance(x, list):
        return [_coerce_to_torch(e) for e in x]
    if isinstance(x, dict):
        return {k: _coerce_to_torch(v) for k, v in x.items()}
    return x


class NemotronHTopkRouter:
    def __init__(self, device, torch_module):
        self.device = device
        self.torch_module = torch_module.eval()

        self.top_k = int(getattr(torch_module, "top_k", 6))
        self.n_routed_experts = int(getattr(torch_module, "n_routed_experts", 128))
        self.routed_scaling_factor = float(getattr(torch_module, "routed_scaling_factor", 1.0))
        self.norm_topk_prob = bool(getattr(torch_module, "norm_topk_prob", True))

        sd = torch_module.state_dict()
        w = sd["weight"]  # (n_experts, hidden)
        self.hidden_size = int(w.shape[1])
        E = self.n_routed_experts

        # gate weight stored transposed (hidden, n_experts), fp32
        self._gate_w = self._dev(w.t().contiguous().float())
        bias = sd.get("e_score_correction_bias", None)
        if bias is None:
            bias = torch.zeros(E)
        self._bias = self._dev(bias.float().reshape(1, 1, E))

        # arange(E) index vector, fp32, broadcastable as (1,1,E)
        self._idx_vec = self._dev(torch.arange(E, dtype=torch.float32).reshape(1, 1, E))

        # Strictly-lower-triangular tie-break mask: jlti[i, j] == 1.0 iff j < i.
        # The all-pairs rank `rank_i = #{j : choice_j > choice_i}` uses a STRICT
        # `>`, so experts with EXACTLY EQUAL choice scores share a rank. Ties do
        # occur here: for large logits `sigmoid` saturates to 1.0 (bit-exact), so
        # choice == 1.0 + bias and any two experts whose biases tie (or whose
        # logits both saturate) collide. A shared rank corrupts the per-rank
        # one-hot extraction below — two experts sum their indices into one slot
        # while another rank slot finds no expert and defaults to index 0 — which
        # silently mis-selects the top-k SET (measured: 5/64 rows flip, PCC drops
        # to ~0.98). Counting a tie `j` as ranked-before `i` only when `j < i`
        # gives every expert a UNIQUE rank in {0..E-1} and orders ties by
        # ascending index, matching torch.topk's tie handling (restores PCC 1.0).
        jlti = torch.tril(torch.ones(E, E, dtype=torch.float32), diagonal=-1)
        self._jlti = self._dev(jlti.reshape(1, 1, E, E))

        self.ckc = ttnn.WormholeComputeKernelConfig(
            math_fidelity=ttnn.MathFidelity.HiFi4,
            math_approx_mode=False,
            fp32_dest_acc_en=True,
            packer_l1_acc=True,
        )

    # ----------------------------- helpers ---------------------------- #
    def _is_mesh(self):
        try:
            if isinstance(self.device, ttnn.MeshDevice):
                return True
        except AttributeError:
            pass
        return hasattr(self.device, "get_device_ids") or hasattr(self.device, "get_devices")

    def _upload(self, torch_tensor, dtype, layout=ttnn.TILE_LAYOUT):
        if self._is_mesh():
            try:
                return ttnn.from_torch(
                    torch_tensor, dtype=dtype, layout=layout, device=self.device,
                    mesh_mapper=ttnn.ReplicateTensorToMesh(self.device),
                )
            except Exception:
                pass
        return ttnn.from_torch(torch_tensor, dtype=dtype, layout=layout, device=self.device)

    def _dev(self, torch_tensor, layout=ttnn.TILE_LAYOUT):
        return self._upload(torch_tensor.float(), ttnn.float32, layout)

    def _fp32(self, t):
        if isinstance(t, ttnn.Tensor):
            if t.dtype != ttnn.float32:
                return ttnn.typecast(t, ttnn.float32)
            return t
        return self._dev(t)

    # ------------------------------ forward --------------------------- #
    def __call__(self, hidden_states, **kwargs):
        hs = self._fp32(hidden_states)
        if hs.layout != ttnn.TILE_LAYOUT:
            hs = ttnn.to_layout(hs, ttnn.TILE_LAYOUT)
        shape = list(hs.shape)
        if len(shape) == 2:
            hs = ttnn.reshape(hs, [1, shape[0], shape[1]])
            shape = list(hs.shape)
        B, T = shape[0], shape[1]
        E = self.n_routed_experts
        k = self.top_k

        # ---------------- router (fp32) ----------------
        logits = ttnn.matmul(hs, self._gate_w, compute_kernel_config=self.ckc)  # (B,T,E)
        scores = ttnn.sigmoid(logits)                                           # (B,T,E)
        ttnn.deallocate(logits)
        choice = ttnn.add(scores, self._bias)                                   # selection scores

        # ---- exact fp32 all-pairs rank: rank_i = #{j : choice_j > choice_i} ----
        bb = ttnn.reshape(choice, [B, T, 1, E])          # (B,T,1,E): [.,.,0,j]=choice_j
        b_full = ttnn.repeat(bb, [1, 1, E, 1])           # (B,T,E,E): [.,.,i,j]=choice_j
        ttnn.deallocate(bb)
        a_full = ttnn.transpose(b_full, 2, 3)            # (B,T,E,E): [.,.,i,j]=choice_i
        gt = ttnn.gt(b_full, a_full)                      # choice_j > choice_i
        eq = ttnn.eq(b_full, a_full)                      # choice_j == choice_i (ties)
        ttnn.deallocate(b_full)
        ttnn.deallocate(a_full)
        gt_f = ttnn.typecast(gt, ttnn.float32)
        ttnn.deallocate(gt)
        # Break exact ties by ascending expert index (see _jlti above): a tie `j`
        # is ranked before `i` only when j < i. gt and tie_before are disjoint,
        # so their sum over j gives each expert a UNIQUE rank in {0..E-1}.
        eq_f = ttnn.typecast(eq, ttnn.float32)
        ttnn.deallocate(eq)
        tie_before = ttnn.multiply(eq_f, self._jlti)      # (B,T,E,E)
        ttnn.deallocate(eq_f)
        order = ttnn.add(gt_f, tie_before)
        ttnn.deallocate(gt_f)
        ttnn.deallocate(tie_before)
        rank = ttnn.sum(order, dim=3)                     # (B,T,E)
        ttnn.deallocate(order)
        if list(rank.shape)[-1] != E:
            rank = ttnn.reshape(rank, [B, T, E])
        ttnn.deallocate(choice)

        # ---- extract indices (and gathered weights) in rank order ----
        idx_list = []
        w_list = []
        for r in range(k):
            eq = ttnn.eq(rank, float(r))                  # (B,T,E) 1.0 where rank==r
            if eq.dtype != ttnn.float32:
                eq = ttnn.typecast(eq, ttnn.float32)
            idx_r = ttnn.sum(ttnn.multiply(eq, self._idx_vec), dim=-1, keepdim=True)  # (B,T,1)
            w_r = ttnn.sum(ttnn.multiply(eq, scores), dim=-1, keepdim=True)           # (B,T,1)
            ttnn.deallocate(eq)
            idx_list.append(idx_r)
            w_list.append(w_r)
        ttnn.deallocate(rank)
        ttnn.deallocate(scores)

        idx = ttnn.concat(idx_list, dim=-1)               # (B,T,k)
        weights = ttnn.concat(w_list, dim=-1)             # (B,T,k)
        for t in idx_list:
            ttnn.deallocate(t)
        for t in w_list:
            ttnn.deallocate(t)

        # normalize + scale weights (HF semantics; only indices are PCC-checked)
        if self.norm_topk_prob:
            denom = ttnn.sum(weights, dim=-1, keepdim=True)
            denom = ttnn.add(denom, 1e-20)
            weights = ttnn.multiply(weights, ttnn.reciprocal(denom))
            ttnn.deallocate(denom)
        weights = ttnn.multiply(weights, self.routed_scaling_factor)

        # flatten leading batch -> (B*T, k) to match HF (T, top_k)
        idx = ttnn.reshape(idx, [B * T, k])
        weights = ttnn.reshape(weights, [B * T, k])
        return idx, weights


def build(device, torch_module):
    return NemotronHTopkRouter(device, torch_module)


_instance = None


def nemotron_h_topk_router(*args, **kwargs):
    global _instance
    if _instance is None:
        raise RuntimeError(
            'Synthesized TTNN module requires `build(device, torch_module)`. '
            'Call it from the PCC test\'s `_build_ttnn_port`.'
        )
    return _instance(*args, **kwargs)
