// SPDX-FileCopyrightText: © 2024 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#pragma once
#include "llk_math_common_api.h"
#include "llk_math_eltwise_unary_sfpu_abs.h"
#include "llk_math_eltwise_unary_sfpu_comp.h"
#include "llk_math_eltwise_unary_sfpu_unary_max_min.h"
#include "llk_math_eltwise_unary_sfpu_exp2.h"
#include "llk_math_eltwise_unary_sfpu_expm1.h"
#include "llk_math_eltwise_unary_sfpu_heaviside.h"
#include "llk_math_eltwise_unary_sfpu_init.h"
#include "llk_math_eltwise_unary_sfpu_log.h"
#include "llk_math_eltwise_unary_sfpu_log1p.h"
#include "llk_math_eltwise_unary_sfpu_max.h"
#include "llk_math_eltwise_unary_sfpu_power.h"
#include "llk_math_eltwise_unary_sfpu_rsqrt.h"
#include "llk_math_eltwise_unary_sfpu_rounding_ops.h"
#include "llk_math_eltwise_unary_sfpu_sigmoid.h"
#include "llk_math_eltwise_unary_sfpu_sign.h"
#include "llk_math_eltwise_unary_sfpu_signbit.h"
#include "llk_math_eltwise_unary_sfpu_silu.h"
#include "llk_math_eltwise_unary_sfpu_square.h"
#include "llk_math_eltwise_unary_sfpu_tanh.h"
#include "llk_math_eltwise_unary_sfpu_tiled_prod.h"
#include "llk_math_eltwise_unary_sfpu_topk.h"
#include "llk_math_eltwise_unary_sfpu_trigonometry.h"
#include "llk_math_eltwise_unary_sfpu_unary_comp.h"
#include "llk_math_eltwise_unary_sfpu_fill.h"
#include "llk_math_eltwise_unary_sfpu_prelu.h"
#include "llk_math_eltwise_unary_sfpu_i1.h"
#include "llk_math_eltwise_unary_sfpu_alt_complex_rotate90.h"
