// SPDX-FileCopyrightText: © 2023 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

enum class SfpuType {
    unused = 0,
    frac,
    swish,
    atanh,
    sinh,
    softcap,
    // Members referenced by third-party tt_llk headers
    equal_zero,
    not_equal_zero,
    less_than_zero,
    greater_than_equal_zero,
    greater_than_zero,
    less_than_equal_zero,
    topk_local_sort,
    typecast,
    signbit,
    isinf,
    isposinf,
    isneginf,
    isnan,
    isfinite,
    max,
    min,
    max_int,
    min_int,
    max_uint,
    min_uint,
    mul_int,
    mul_uint,
    unary_ne,
    unary_eq,
    unary_gt,
    unary_lt,
    unary_ge,
    unary_le,
    unary_max,
    unary_min,
    unary_max_int,
    unary_min_int,
    unary_max_uint,
    unary_min_uint,
    unary_max_int32,
    unary_min_int32,
    unary_max_uint32,
    unary_min_uint32,
    where,
};
