// SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.
//
// SPDX-License-Identifier: Apache-2.0

#pragma once
#include "llk_math_common_api.h"
#include "llk_math_eltwise_unary_sfpu_init.h"
#include "llk_math_eltwise_unary_sfpu_abs.h"
#include "llk_math_eltwise_unary_sfpu_comp.h"
#include "llk_math_eltwise_unary_sfpu_exp2.h"
#include "llk_math_eltwise_unary_sfpu_expm1.h"
#include "llk_math_eltwise_unary_sfpu_heaviside.h"
#include "llk_math_eltwise_unary_sfpu_log.h"
#include "llk_math_eltwise_unary_sfpu_max.h"
#include "llk_math_eltwise_unary_sfpu_power.h"
#include "llk_math_eltwise_unary_sfpu_rsqrt.h"
#include "llk_math_eltwise_unary_sfpu_tiled_prod.h"
#include "llk_math_eltwise_unary_sfpu_sigmoid.h"
#include "llk_math_eltwise_unary_sfpu_sign.h"
#include "llk_math_eltwise_unary_sfpu_signbit.h"
#include "llk_math_eltwise_unary_sfpu_floor.h"
#include "llk_math_eltwise_unary_sfpu_ceil.h"
#include "llk_math_eltwise_unary_sfpu_silu.h"
#include "llk_math_eltwise_unary_sfpu_square.h"
#include "llk_math_eltwise_unary_sfpu_tanh.h"
#include "llk_math_eltwise_unary_sfpu_topk.h"
#include "llk_math_eltwise_unary_sfpu_unary_comp.h"
#include "llk_math_eltwise_unary_sfpu_trigonometry.h"
#include "llk_math_eltwise_unary_sfpu_unary_comp.h"
#include "llk_math_eltwise_unary_sfpu_remainder.h"
#include "llk_math_eltwise_unary_sfpu_bitwise_xor.h"
#include "llk_math_eltwise_unary_sfpu_bitwise_not.h"
#include "llk_math_eltwise_unary_sfpu_fmod.h"
#include "llk_math_eltwise_unary_sfpu_bitwise_and.h"
#include "llk_math_eltwise_unary_sfpu_bitwise_or.h"
#include "llk_math_eltwise_unary_sfpu_right_shift.h"
#include "llk_math_eltwise_unary_sfpu_left_shift.h"
#include "llk_math_eltwise_unary_sfpu_fill.h"
