// SPDX-FileCopyrightText: © 2023 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

enum class SfpuType {
    unused = 0,
    frac,
    swish,
    atanh,
    sinh,
    softcap,
    mul_int32,
    mul_uint16,
    equal_zero,
    not_equal_zero,
    less_than_zero,
    greater_than_equal_zero,
    greater_than_zero,
    less_than_equal_zero,
    isinf,
    isnan,
    isposinf,
    isneginf,
    isfinite,
    signbit,
    typecast,
    unary_ne,
    unary_eq,
    unary_gt,
    unary_lt,
    unary_ge,
    unary_le,
    topk_local_sort,
    max,
    min,
    eq,
    gt,
    lt,
    ge,
    le,
    where,
    max_int32,
    max_uint32,
    min_int32,
    min_uint32,
    unary_max,
    unary_min,
    unary_max_int32,
    unary_max_uint32,
    unary_min_int32,
    unary_min_uint32,
    add_top_row,
    lerp,
    quant_int32,
    dequant_int32,
    requant_int32,
    addcmul,
    addcdiv,
    gcd,
    lcm,
    div_int32,
    div_int32_floor,
    div_int32_trunc,
    fmod_int32,
    remainder_int32,
    max_pool_with_indices,
};
