set(HW_JIT_API_HEADERS
    inc/api/alignment.h
    inc/api/compile_time_args.h
    inc/api/remote_circular_buffer.h
    inc/api/socket_api.h
    inc/api/dataflow/dataflow_api.h
    inc/api/debug/assert.h
    inc/api/debug/dprint.h
    inc/api/debug/timing_perturbation.h
    inc/api/debug/device_print.h
    inc/api/debug/dprint_pages.h
    inc/api/debug/dprint_tensix.h
    inc/api/debug/dprint_tile.h
    inc/api/debug/eth_link_status.h
    inc/api/debug/noc_logging.h
    inc/api/debug/ring_buffer.h
    inc/api/debug/waypoint.h
    inc/api/numeric/bfloat16.h
    inc/api/numeric/float32.h
    inc/api/numeric/int32.h
    inc/api/tensor/tensor_accessor.h
    inc/api/tensor/tensor_accessor_args.h
    inc/api/tensor/shard_pages_address_iterator.h
    inc/api/tensor/pages_address_iterator.h
    inc/api/tensor/page.h
    inc/api/compute/compute_kernel_api.h
    inc/api/compute/add_int_sfpu.h
    inc/api/compute/bcast.h
    inc/api/compute/binary_bitwise_sfpu.h
    inc/api/compute/binary_comp.h
    inc/api/compute/binary_max_min.h
    inc/api/compute/binary_shift.h
    inc/api/compute/blank.h
    inc/api/compute/cb_api.h
    inc/api/compute/common.h
    inc/api/compute/common_globals.h
    inc/api/compute/compute_kernel_hw_startup.h
    inc/api/compute/copy_dest_values.h
    inc/api/compute/cumsum.h
    inc/api/compute/div_int32_floor.h
    inc/api/compute/div_int32_sfpu.h
    inc/api/compute/eltwise_binary.h
    inc/api/compute/eltwise_binary_sfpu.h
    inc/api/compute/eltwise_unary/README.md
    inc/api/compute/eltwise_unary/activations.h
    inc/api/compute/eltwise_unary/addcdiv.h
    inc/api/compute/eltwise_unary/addcmul.h
    inc/api/compute/eltwise_unary/binop_with_scalar.h
    inc/api/compute/eltwise_unary/bitwise_and.h
    inc/api/compute/eltwise_unary/bitwise_not.h
    inc/api/compute/eltwise_unary/bitwise_or.h
    inc/api/compute/eltwise_unary/bitwise_xor.h
    inc/api/compute/eltwise_unary/cbrt.h
    inc/api/compute/eltwise_unary/clamp.h
    inc/api/compute/eltwise_unary/comp.h
    inc/api/compute/eltwise_unary/dropout.h
    inc/api/compute/eltwise_unary/eltwise_unary.h
    inc/api/compute/eltwise_unary/elu.h
    inc/api/compute/eltwise_unary/erf_erfc.h
    inc/api/compute/eltwise_unary/erfinv.h
    inc/api/compute/eltwise_unary/exp.h
    inc/api/compute/eltwise_unary/fill.h
    inc/api/compute/eltwise_unary/fmod.h
    inc/api/compute/eltwise_unary/gelu.h
    inc/api/compute/eltwise_unary/hardmish.h
    inc/api/compute/eltwise_unary/hardtanh.h
    inc/api/compute/eltwise_unary/i0.h
    inc/api/compute/eltwise_unary/i1.h
    inc/api/compute/eltwise_unary/identity.h
    inc/api/compute/eltwise_unary/isinf_isnan.h
    inc/api/compute/eltwise_unary/left_shift.h
    inc/api/compute/eltwise_unary/log1p.h
    inc/api/compute/eltwise_unary/logical_not.h
    inc/api/compute/eltwise_unary/negative.h
    inc/api/compute/eltwise_unary/prelu.h
    inc/api/compute/eltwise_unary/rand.h
    inc/api/compute/eltwise_unary/rdiv.h
    inc/api/compute/eltwise_unary/recip.h
    inc/api/compute/eltwise_unary/relu.h
    inc/api/compute/eltwise_unary/remainder.h
    inc/api/compute/eltwise_unary/reverseops.h
    inc/api/compute/eltwise_unary/right_shift.h
    inc/api/compute/eltwise_unary/rounding.h
    inc/api/compute/eltwise_unary/rpow.h
    inc/api/compute/eltwise_unary/rsqrt.h
    inc/api/compute/eltwise_unary/rsub.h
    inc/api/compute/eltwise_unary/selu.h
    inc/api/compute/eltwise_unary/sfpu_int_sum.h
    inc/api/compute/eltwise_unary/sfpu_split_includes.h
    inc/api/compute/eltwise_unary/softplus.h
    inc/api/compute/eltwise_unary/sqrt.h
    inc/api/compute/eltwise_unary/threshold.h
    inc/api/compute/eltwise_unary/trigonometry.h
    inc/api/compute/eltwise_unary/typecast.h
    inc/api/compute/eltwise_unary/where.h
    inc/api/compute/ema.h
    inc/api/compute/experimental/mul_reduce_scalar.h
    inc/api/compute/binary_fmod.h
    inc/api/compute/gcd.h
    inc/api/compute/layernorm.h
    inc/api/compute/lcm.h
    inc/api/compute/logsigmoid.h
    inc/api/compute/mask.h
    inc/api/compute/matmul.h
    inc/api/compute/mul_int_sfpu.h
    inc/api/compute/pack.h
    inc/api/compute/pack_untilize.h
    inc/api/compute/quantization.h
    inc/api/compute/reconfig_data_format.h
    inc/api/compute/reduce.h
    inc/api/compute/reduce_custom.h
    inc/api/compute/reg_api.h
    inc/api/compute/remainder_int32.h
    inc/api/compute/reshuffle.h
    inc/api/compute/sentinel/compute_kernel_sentinel.h
    inc/api/compute/sentinel/sentinel_core.h
    inc/api/compute/sentinel/testing_spy.h
    inc/api/compute/softmax.h
    inc/api/compute/sub_int_sfpu.h
    inc/api/compute/tile_move_copy.h
    inc/api/compute/tilize.h
    inc/api/compute/transpose_wh.h
    inc/api/compute/transpose_wh_dest.h
    inc/api/compute/untilize.h
    inc/api/compute/welford.h
    inc/api/compute/xlogy.h
    inc/experimental/lock.h
    inc/experimental/noc.h
    inc/experimental/circular_buffer.h
    inc/experimental/dataflow_buffer.h
    inc/experimental/noc_semaphore.h
    inc/experimental/endpoints.h
    inc/experimental/core_local_mem.h
    inc/experimental/tensor.h
    inc/hostdev/dev_msgs.h
    inc/hostdev/device_print_common.h
    inc/hostdev/device_print_structures.h
    inc/hostdev/fabric_telemetry_msgs.h
    inc/hostdev/rta_constants.h
    inc/hostdev/socket.h
    inc/internal/hw_thread.h
    inc/internal/atomic_rwptr.h
    inc/internal/bit_utils.h
    inc/internal/circular_buffer_interface.h
    inc/internal/circular_buffer_init.h
    inc/internal/dataflow_buffer_interface.h
    inc/internal/dataflow_buffer_init.h
    inc/internal/firmware_common.h
    inc/internal/mod_div_lib.h
    inc/internal/risc_attribs.h
    inc/internal/tensix_functions.h
    inc/internal/vptr_uint.h
    inc/internal/dataflow/dataflow_api_addrgen.h
    inc/internal/dataflow/dataflow_api_common.h
    inc/internal/dataflow/dataflow_cmd_bufs.h
    inc/internal/debug/dprint_buffer.h
    inc/internal/debug/fw_debug.h
    inc/internal/debug/sanitize.h
    inc/internal/debug/stack_usage.h
    inc/internal/debug/watcher_common.h
    inc/internal/ethernet/dataflow_api.h
    inc/internal/ethernet/erisc.h
    inc/internal/ethernet/tt_eth_api.h
    inc/internal/ethernet/tt_eth_ss_regs.h
    inc/internal/ethernet/tunneling.h
    inc/internal/tensor/array_wrapper.h
    inc/internal/tensor/const.h
    inc/internal/tensor/dspec.h
    inc/internal/tensor/helpers.h
    inc/internal/tt-1xx/blackhole/c_tensix_core.h
    inc/internal/tt-1xx/blackhole/cfg_defines.h
    inc/internal/tt-1xx/blackhole/core_config.h
    inc/internal/tt-1xx/blackhole/dev_mem_map.h
    inc/internal/tt-1xx/blackhole/eth_chan_noc_mapping.h
    inc/internal/tt-1xx/blackhole/eth_fw_api.h
    inc/internal/tt-1xx/blackhole/eth_l1_address_map.h
    inc/internal/tt-1xx/blackhole/noc/noc.h
    inc/internal/tt-1xx/blackhole/noc/noc_overlay_parameters.h
    inc/internal/tt-1xx/blackhole/noc/noc_parameters.h
    inc/internal/tt-1xx/blackhole/noc_nonblocking_api.h
    inc/internal/tt-1xx/blackhole/stream_interface.h
    inc/internal/tt-1xx/blackhole/stream_io_map.h
    inc/internal/tt-1xx/blackhole/tdma_xmov.h
    inc/internal/tt-1xx/blackhole/tensix.h
    inc/internal/tt-1xx/blackhole/tensix_types.h
    inc/internal/tt-2xx/quasar/c_tensix_core.h
    inc/internal/tt-2xx/quasar/cfg_defines.h
    inc/internal/tt-2xx/quasar/core_config.h
    inc/internal/tt-2xx/quasar/dev_mem_map.h
    inc/internal/tt-2xx/quasar/eth_chan_noc_mapping.h
    inc/internal/tt-2xx/quasar/eth_fw_api.h
    inc/internal/tt-2xx/quasar/eth_l1_address_map.h
    inc/internal/tt-2xx/quasar/noc/noc.h
    inc/internal/tt-2xx/quasar/noc/noc_overlay_parameters.h
    inc/internal/tt-2xx/quasar/noc/noc_parameters.h
    inc/internal/tt-2xx/quasar/noc_nonblocking_api.h
    inc/internal/tt-2xx/quasar/stream_interface.h
    inc/internal/tt-2xx/quasar/stream_io_map.h
    inc/internal/tt-2xx/quasar/tdma_xmov.h
    inc/internal/tt-2xx/quasar/tensix.h
    inc/internal/tt-2xx/quasar/tensix_types.h
    inc/internal/tt-1xx/risc_common.h
    inc/internal/tt-1xx/wormhole/c_tensix_core.h
    inc/internal/tt-1xx/wormhole/core_config.h
    inc/internal/tt-1xx/wormhole/dev_mem_map.h
    inc/internal/tt-1xx/wormhole/eth_chan_noc_mapping.h
    inc/internal/tt-1xx/wormhole/eth_fw_api.h
    inc/internal/tt-1xx/wormhole/eth_l1_address_map.h
    inc/internal/tt-1xx/wormhole/noc/noc.h
    inc/internal/tt-1xx/wormhole/noc/noc_overlay_parameters.h
    inc/internal/tt-1xx/wormhole/noc/noc_parameters.h
    inc/internal/tt-1xx/wormhole/noc_nonblocking_api.h
    inc/internal/tt-1xx/wormhole/stream_interface.h
    inc/internal/tt-1xx/wormhole/stream_io_map.h
    inc/internal/tt-1xx/wormhole/tdma_xmov.h
    inc/internal/tt-1xx/wormhole/tensix.h
    inc/internal/tt-1xx/wormhole/wormhole_b0_defines/cfg_defines.h
    inc/internal/tt-1xx/wormhole/wormhole_b0_defines/tensix_types.h
    toolchain/erisc-b0-app.ld
    toolchain/erisc-b0-app-sections.ld
    toolchain/erisc-b0-memory.ld
    toolchain/erisc-b0-kernel.ld
)
