# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# AUTO-GENERATED by the tt-dm-codegen agentic port pipeline (phase 8 emit_test).
# Contracts: (1) every coverage-ledger case the codegen gate rejects falls back to native under
# `auto`; (2) an accepted case dispatched twice under forced `codegen` stays a program-cache hit and
# rebinds its buffers; (3) a perf-demoted case still lands on native under `auto`; (4) an accepted,
# non-demoted case under `auto` compiles the codegen program; (5) an unknown `implementation` is
# rejected. Regenerated per port; edit the emitter, not this file, for systematic
# changes. Hand-add off-grid regressions below the generated block.

import pytest
import torch

import ttnn
from tests.ttnn.utils_for_testing import assert_equal

_NATIVE = "native"  # forced-native golden leg
_CODEGEN = "codegen"  # forced-codegen leg
_ROUTED = "auto"


def _make_input(shape, dtype):
    if dtype in (ttnn.int32, ttnn.uint32):
        return torch.randint(0, 100, shape, dtype=torch.int32)
    return torch.rand(shape, dtype=torch.bfloat16)


_DEMOTED = [
    (
        [1, 1, 64, 64],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.uint16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [1, 10, 64, 64],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.bfloat16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [1, 32, 64],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.uint16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [1, 32, 64],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.uint16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [1, 4, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.bfloat16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [1, 4, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.bfloat16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 1, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.int32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 1, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.uint16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 1, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.uint32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 1, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.int32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 1, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.uint16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 1, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.uint32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 12, 64, 96],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.bfloat16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 32, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.int32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 32, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.uint16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 32, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.uint32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 32, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.int32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 32, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.uint16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 32, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.uint32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.float32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [2, 96, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.float32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [224, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.bfloat16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [224, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)},
        ttnn.bfloat16,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
    (
        [3, 2, 128, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.float32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
]
_DEMOTED_IDS = [
    "[1, 1, 64, 64]|memory_config=l1|uint16|row_major",
    "[1, 10, 64, 64]|memory_config=dram|bfloat16|row_major",
    "[1, 32, 64]|memory_config=dram|uint16|row_major",
    "[1, 32, 64]|memory_config=l1|uint16|row_major",
    "[1, 4, 96, 32]|memory_config=dram|bfloat16|row_major",
    "[1, 4, 96, 32]|memory_config=l1|bfloat16|row_major",
    "[2, 1, 96, 32]|memory_config=dram|int32|row_major",
    "[2, 1, 96, 32]|memory_config=dram|uint16|row_major",
    "[2, 1, 96, 32]|memory_config=dram|uint32|row_major",
    "[2, 1, 96, 32]|memory_config=l1|int32|row_major",
    "[2, 1, 96, 32]|memory_config=l1|uint16|row_major",
    "[2, 1, 96, 32]|memory_config=l1|uint32|row_major",
    "[2, 12, 64, 96]|memory_config=dram|bfloat16|row_major",
    "[2, 32, 32]|memory_config=dram|int32|row_major",
    "[2, 32, 32]|memory_config=dram|uint16|row_major",
    "[2, 32, 32]|memory_config=dram|uint32|row_major",
    "[2, 32, 32]|memory_config=l1|int32|row_major",
    "[2, 32, 32]|memory_config=l1|uint16|row_major",
    "[2, 32, 32]|memory_config=l1|uint32|row_major",
    "[2, 96, 32]|memory_config=dram|float32|row_major",
    "[2, 96, 32]|memory_config=l1|float32|row_major",
    "[224, 32]|memory_config=dram|bfloat16|row_major",
    "[224, 32]|memory_config=l1|bfloat16|row_major",
    "[3, 2, 128, 32]|memory_config=dram|float32|row_major",
]


@pytest.mark.parametrize("shape,kwargs,dtype,layout", _DEMOTED, ids=_DEMOTED_IDS)
def test_tilize_codegen_demotion(device, shape, kwargs, dtype, layout):
    x = _make_input(shape, dtype)
    xt = ttnn.from_torch(x, dtype=dtype, layout=layout, device=device)
    golden = ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_NATIVE))
    entries_before = device.num_program_cache_entries()
    out = ttnn.tilize(xt, **kwargs, implementation=_ROUTED)
    assert_equal(golden, ttnn.to_torch(out))
    msg = "auto routed a perf-demoted case to codegen (program cache grew); expected native fallback"
    assert device.num_program_cache_entries() == entries_before, msg


_ACCEPTED = [
    (
        [1, 32, 64],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.int32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
]
_ACCEPTED_IDS = [
    "[1, 32, 64]|memory_config=dram|int32|row_major",
]


@pytest.mark.parametrize("shape,kwargs,dtype,layout", _ACCEPTED, ids=_ACCEPTED_IDS)
def test_tilize_codegen_routes_accepted_to_codegen(device, shape, kwargs, dtype, layout):
    x = _make_input(shape, dtype)
    xt = ttnn.from_torch(x, dtype=dtype, layout=layout, device=device)
    golden = ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_NATIVE))
    entries_before = device.num_program_cache_entries()
    out = ttnn.tilize(xt, **kwargs, implementation=_ROUTED)
    assert_equal(golden, ttnn.to_torch(out))
    # The golden warms only the native program, so a routed dispatch that lands on
    # codegen must compile it. An unchanged cache means `auto` fell back to native and
    # the port's wins are unreachable through the public entry point.
    msg = "auto fell back to native for an accepted case (program cache did not grow); expected the codegen path"
    assert device.num_program_cache_entries() > entries_before, msg


_CACHE_HIT = [
    (
        [32, 32],
        {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
        ttnn.int32,
        ttnn.ROW_MAJOR_LAYOUT,
    ),
]
_CACHE_HIT_IDS = [
    "[32, 32]|memory_config=dram|int32|row_major",
]


@pytest.mark.parametrize("shape,kwargs,dtype,layout", _CACHE_HIT, ids=_CACHE_HIT_IDS)
def test_tilize_codegen_program_cache_hit(device, shape, kwargs, dtype, layout):
    x = _make_input(shape, dtype)
    xt = ttnn.from_torch(x, dtype=dtype, layout=layout, device=device)
    golden = ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_NATIVE))
    assert_equal(golden, ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_CODEGEN)))
    entries_after_miss = device.num_program_cache_entries()
    # Same spec, a distinct allocation: the cached program must rebind its Buffer*s
    # instead of reusing the first dispatch's addresses.
    yt = ttnn.from_torch(_make_input(shape, dtype), dtype=dtype, layout=layout, device=device)
    second_golden = ttnn.to_torch(ttnn.tilize(yt, **kwargs, implementation=_NATIVE))
    assert_equal(second_golden, ttnn.to_torch(ttnn.tilize(yt, **kwargs, implementation=_CODEGEN)))
    msg = "second forced-codegen dispatch missed the program cache"
    assert device.num_program_cache_entries() == entries_after_miss, msg


_SELECTOR_CASE = (
    [32, 32],
    {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
    ttnn.int32,
    ttnn.ROW_MAJOR_LAYOUT,
)


@pytest.mark.parametrize("selector", ["", "Codegen", "codgen", "default"])
def test_tilize_codegen_rejects_an_unknown_implementation(device, expect_error, selector):
    shape, kwargs, dtype, layout = _SELECTOR_CASE
    xt = ttnn.from_torch(_make_input(shape, dtype), dtype=dtype, layout=layout, device=device)
    # The selector is parsed on every call, including ones a front-end shortcut would
    # otherwise answer without dispatching, so an unknown value never passes silently.
    with expect_error(RuntimeError, "unknown implementation selector"):
        ttnn.tilize(xt, **kwargs, implementation=selector)


# --- hand-added, off-grid: execution controls -------------------------------
# The emitter is ledger-driven and every leg above varies only tensors/memory_config, so no
# generated case can reach these: they are call parameters that control WHERE work lands and with
# what tile geometry, not what the result contains. None of the codegen builders honours either one
# (they all place work over the full compute_with_storage_grid_size() with the standard 32x32 tile,
# and TilizeCodegenParams carries neither a core set nor a tile shape), so `auto` must leave them to
# native and forced `codegen` must refuse by name rather than accept the call and ignore the
# control — which would land work on cores the caller reserved.
#
# The base case is the _ACCEPTED one above, i.e. a shape that provably DOES reach codegen under
# `auto` without a control set; that is what makes an unchanged program cache here evidence of the
# control, not of the shape.
_CONTROL_CASE = (
    [1, 32, 64],
    {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)},
    ttnn.int32,
    ttnn.ROW_MAJOR_LAYOUT,
)


def _sub_core_grids():
    return ttnn.CoreRangeSet({ttnn.CoreRange(ttnn.CoreCoord(0, 0), ttnn.CoreCoord(1, 1))})


def test_tilize_codegen_sub_core_grids_falls_back_to_native(device):
    shape, kwargs, dtype, layout = _CONTROL_CASE
    x = _make_input(shape, dtype)
    xt = ttnn.from_torch(x, dtype=dtype, layout=layout, device=device)
    control = {"sub_core_grids": _sub_core_grids()}
    golden = ttnn.to_torch(ttnn.tilize(xt, **kwargs, **control, implementation=_NATIVE))
    entries_before = device.num_program_cache_entries()
    out = ttnn.tilize(xt, **kwargs, **control, implementation=_ROUTED)
    assert_equal(golden, ttnn.to_torch(out))
    msg = "auto routed a sub_core_grids call to codegen (program cache grew); the codegen builders ignore the restriction and would use the whole grid"
    assert device.num_program_cache_entries() == entries_before, msg


@pytest.mark.parametrize(
    "control,named",
    [
        (
            {"sub_core_grids": ttnn.CoreRangeSet({ttnn.CoreRange(ttnn.CoreCoord(0, 0), ttnn.CoreCoord(1, 1))})},
            "sub_core_grids",
        ),
        ({"tile": ttnn.Tile([16, 32])}, "tile"),
    ],
    ids=["sub_core_grids", "tile"],
)
def test_tilize_codegen_rejects_unhonourable_execution_controls(device, expect_error, control, named):
    shape, kwargs, dtype, layout = _CONTROL_CASE
    xt = ttnn.from_torch(_make_input(shape, dtype), dtype=dtype, layout=layout, device=device)
    # Naming the control in the message is the contract: a bare "unsupported" would let a caller
    # believe the restriction was applied on some other path.
    with expect_error(RuntimeError, f"cannot honour '{named}'"):
        ttnn.tilize(xt, **kwargs, **control, implementation=_CODEGEN)
