# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# AUTO-GENERATED by the tt-dm-codegen agentic port pipeline (phase 8 emit_test).
# Routing-fallback coverage: every coverage-ledger case the codegen gate rejects must fall back
# to native under `auto`. Regenerated per port; edit the emitter, not this file, for systematic
# changes. Hand-add off-grid regressions below the generated block.

import pytest
import torch

import ttnn
from tests.ttnn.utils_for_testing import assert_equal

_NATIVE = "native"  # forced-native golden leg
_ROUTED = "auto"


def _make_input(shape, dtype):
    if dtype in (ttnn.int32, ttnn.uint32):
        return torch.randint(0, 100, shape, dtype=torch.int32)
    return torch.rand(shape, dtype=torch.bfloat16)


_ROUTING = []
_ROUTING_IDS = []


@pytest.mark.parametrize("shape,kwargs,dtype,layout", _ROUTING, ids=_ROUTING_IDS)
def test_tilize_codegen_routing(device, shape, kwargs, dtype, layout):
    x = _make_input(shape, dtype)
    xt = ttnn.from_torch(x, dtype=dtype, layout=layout, device=device)
    golden = ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_NATIVE))
    # The golden call warms the native program, so a correct fallback leaves the cache
    # unchanged; only a mis-route to codegen compiles a new program and grows it.
    entries_before = device.num_program_cache_entries()
    out = ttnn.tilize(xt, **kwargs, implementation=_ROUTED)
    assert_equal(golden, ttnn.to_torch(out))
    msg = "auto routed an out-of-scope case to codegen (program cache grew); expected native fallback"
    assert device.num_program_cache_entries() == entries_before, msg
