# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# AUTO-GENERATED by the tt-dm-codegen agentic port pipeline (phase 8 emit_test).
# Contracts: (1) every coverage-ledger case the codegen gate rejects falls back to native under
# `auto`; (2) an accepted case dispatched twice under forced `codegen` stays a program-cache hit and
# rebinds its buffers; (3) a perf-demoted case still lands on native under `auto`; (4) an accepted,
# non-demoted case under `auto` compiles the codegen program; (5) an unknown `implementation` is
# rejected. Regenerated per port; edit the emitter, not this file, for systematic
# changes. Hand-add off-grid regressions below the generated block.

import pytest
import torch

import ttnn
from tests.ttnn.utils_for_testing import assert_equal

_NATIVE = "native"  # forced-native golden leg
_CODEGEN = "codegen"  # forced-codegen leg
_ROUTED = "auto"

_DRAM = {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.DRAM)}
_L1 = {"memory_config": ttnn.MemoryConfig(ttnn.TensorMemoryLayout.INTERLEAVED, ttnn.BufferType.L1)}


def _make_input(shape, dtype):
    if dtype in (ttnn.int32, ttnn.uint32):
        return torch.randint(0, 100, shape, dtype=torch.int32)
    return torch.rand(shape, dtype=torch.bfloat16)


_ACCEPTED = [
    ([4, 7, 32, 64], _L1, ttnn.bfloat16, ttnn.ROW_MAJOR_LAYOUT),
]
_ACCEPTED_IDS = [
    "[4, 7, 32, 64]|memory_config=l1|bfloat16|row_major",
]


@pytest.mark.parametrize("shape,kwargs,dtype,layout", _ACCEPTED, ids=_ACCEPTED_IDS)
def test_tilize_codegen_routes_accepted_to_codegen(device, shape, kwargs, dtype, layout):
    x = _make_input(shape, dtype)
    xt = ttnn.from_torch(x, dtype=dtype, layout=layout, device=device)
    golden = ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_NATIVE))
    entries_before = device.num_program_cache_entries()
    out = ttnn.tilize(xt, **kwargs, implementation=_ROUTED)
    assert_equal(golden, ttnn.to_torch(out))
    # The golden warms only the native program, so a routed dispatch that lands on
    # codegen must compile it. An unchanged cache means `auto` fell back to native and
    # the port's wins are unreachable through the public entry point.
    msg = "auto fell back to native for an accepted case (program cache did not grow); expected the codegen path"
    assert device.num_program_cache_entries() > entries_before, msg


_CACHE_HIT = [
    ([4, 7, 32, 64], _L1, ttnn.bfloat16, ttnn.ROW_MAJOR_LAYOUT),
]
_CACHE_HIT_IDS = [
    "[4, 7, 32, 64]|memory_config=l1|bfloat16|row_major",
]


@pytest.mark.parametrize("shape,kwargs,dtype,layout", _CACHE_HIT, ids=_CACHE_HIT_IDS)
def test_tilize_codegen_program_cache_hit(device, shape, kwargs, dtype, layout):
    x = _make_input(shape, dtype)
    xt = ttnn.from_torch(x, dtype=dtype, layout=layout, device=device)
    golden = ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_NATIVE))
    assert_equal(golden, ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_CODEGEN)))
    entries_after_miss = device.num_program_cache_entries()
    # Same spec, a distinct allocation: the cached program must rebind its Buffer*s
    # instead of reusing the first dispatch's addresses.
    yt = ttnn.from_torch(_make_input(shape, dtype), dtype=dtype, layout=layout, device=device)
    second_golden = ttnn.to_torch(ttnn.tilize(yt, **kwargs, implementation=_NATIVE))
    assert_equal(second_golden, ttnn.to_torch(ttnn.tilize(yt, **kwargs, implementation=_CODEGEN)))
    msg = "second forced-codegen dispatch missed the program cache"
    assert device.num_program_cache_entries() == entries_after_miss, msg


# Perf-demoted ledger cases: in scope for codegen (so forced `codegen` still runs them and verify
# keeps measuring them), but routed to native under `auto`. One row per is_demoted() branch — the
# Wt == 1 predicate and the enumerated Wt >= 2 table.
_DEMOTED = [
    ([32, 32], _DRAM, ttnn.int32, ttnn.ROW_MAJOR_LAYOUT),
    ([2, 12, 64, 96], _DRAM, ttnn.bfloat16, ttnn.ROW_MAJOR_LAYOUT),
    ([6, 224, 160], _DRAM, ttnn.bfloat16, ttnn.ROW_MAJOR_LAYOUT),
]
_DEMOTED_IDS = [
    "[32, 32]|memory_config=dram|int32|row_major",
    "[2, 12, 64, 96]|memory_config=dram|bfloat16|row_major",
    "[6, 224, 160]|memory_config=dram|bfloat16|row_major",
]


@pytest.mark.parametrize("shape,kwargs,dtype,layout", _DEMOTED, ids=_DEMOTED_IDS)
def test_tilize_codegen_demoted_case_stays_native(device, shape, kwargs, dtype, layout):
    x = _make_input(shape, dtype)
    xt = ttnn.from_torch(x, dtype=dtype, layout=layout, device=device)
    golden = ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_NATIVE))
    entries_before = device.num_program_cache_entries()
    out = ttnn.tilize(xt, **kwargs, implementation=_ROUTED)
    assert_equal(golden, ttnn.to_torch(out))
    # The golden already warmed this exact native program, so a routed dispatch that stays on
    # native is a cache hit and cannot grow the count. Growth means `auto` compiled the codegen
    # program for a case measured slower there.
    msg = "auto routed a perf-demoted case to codegen (program cache grew past the native golden)"
    assert device.num_program_cache_entries() == entries_before, msg


@pytest.mark.parametrize("shape,dtype", [([64, 64], ttnn.bfloat16)], ids=["[64, 64]|bfloat16"])
def test_tilize_codegen_rejected_case_falls_back_to_native(device, expect_error, shape, dtype):
    # Sharded input: rejected by supported_by_codegen() (TilizeCodegenParams has no shard fields and
    # no codegen builder for the shard-backed CBs is ported), while native serves it from its own
    # sharded factory. The ledger's own vectors are interleaved, so this leg has to be built here.
    core = ttnn.CoreCoord(0, 0)
    shard_grid = ttnn.CoreRangeSet({ttnn.CoreRange(core, core)})
    shard_spec = ttnn.ShardSpec(shard_grid, shape, ttnn.ShardOrientation.ROW_MAJOR)
    sharded = ttnn.MemoryConfig(ttnn.TensorMemoryLayout.HEIGHT_SHARDED, ttnn.BufferType.L1, shard_spec)

    xt = ttnn.from_torch(
        _make_input(shape, dtype), dtype=dtype, layout=ttnn.ROW_MAJOR_LAYOUT, device=device, memory_config=sharded
    )
    golden = ttnn.to_torch(ttnn.tilize(xt, memory_config=sharded, implementation=_NATIVE))
    entries_before = device.num_program_cache_entries()
    out = ttnn.tilize(xt, memory_config=sharded, implementation=_ROUTED)
    assert_equal(golden, ttnn.to_torch(out))
    msg = "auto routed an out-of-scope (sharded) case to codegen instead of falling back to native"
    assert device.num_program_cache_entries() == entries_before, msg

    # Forced codegen must refuse the same inputs rather than silently degrading to native.
    with expect_error(RuntimeError, "not supported by the codegen implementation"):
        ttnn.tilize(xt, memory_config=sharded, implementation=_CODEGEN)


# ---------------------------------------------------------------------------
# Hand-added off-grid regressions (not emitter-generated).
#
# Execution controls: parameters of ttnn::tilize that decide WHERE work lands or with what tile
# geometry. Every codegen builder places work over the full compute_with_storage_grid_size() with the
# standard 32x32 tile, so accepting such a call on codegen would land work on cores the caller
# reserved, or produce the wrong tile geometry. `auto` must stay on native and forced `codegen` must
# refuse, naming the control (unsupported_execution_control() in tilize_codegen_supported.cpp). The
# ledger cannot reach these: sweep vectors vary tensors, never execution controls.
# ---------------------------------------------------------------------------

# In scope and not demoted (NC 28, Ht 1, Wt 2), so only the control can move it off codegen.
_CONTROL_SHAPE = [4, 7, 32, 64]
_CONTROL_DTYPE = ttnn.bfloat16


def _control_kwargs(name):
    if name == "sub_core_grids":
        return {
            "sub_core_grids": ttnn.CoreRangeSet({ttnn.CoreRange(ttnn.CoreCoord(0, 0), ttnn.CoreCoord(1, 1))}),
        }
    # Tiny tile: native supports a tile height below 32 (tilize_device_operation.cpp), the codegen
    # kernels hardcode TILE_HEIGHT/TILE_WIDTH.
    return {"tile": ttnn.Tile([16, 32])}


@pytest.mark.parametrize("control", ["sub_core_grids", "tile"])
def test_tilize_codegen_execution_control_stays_native(device, control):
    xt = ttnn.from_torch(
        _make_input(_CONTROL_SHAPE, _CONTROL_DTYPE),
        dtype=_CONTROL_DTYPE,
        layout=ttnn.ROW_MAJOR_LAYOUT,
        device=device,
    )
    kwargs = {**_DRAM, **_control_kwargs(control)}
    golden = ttnn.to_torch(ttnn.tilize(xt, **kwargs, implementation=_NATIVE))
    entries_before = device.num_program_cache_entries()
    out = ttnn.tilize(xt, **kwargs, implementation=_ROUTED)
    assert_equal(golden, ttnn.to_torch(out))
    # Same args as the golden, so a native dispatch is a cache hit; growth means `auto` accepted the
    # call on codegen and ignored the control.
    msg = f"auto routed a call with {control} set to codegen, which cannot honour it"
    assert device.num_program_cache_entries() == entries_before, msg


@pytest.mark.parametrize("control", ["sub_core_grids", "tile"])
def test_tilize_codegen_execution_control_rejects_forced_codegen(device, expect_error, control):
    xt = ttnn.from_torch(
        _make_input(_CONTROL_SHAPE, _CONTROL_DTYPE),
        dtype=_CONTROL_DTYPE,
        layout=ttnn.ROW_MAJOR_LAYOUT,
        device=device,
    )
    kwargs = {**_DRAM, **_control_kwargs(control)}
    with expect_error(RuntimeError, f"cannot honour '{control}'"):
        ttnn.tilize(xt, **kwargs, implementation=_CODEGEN)


_SELECTOR_CASE = ([32, 32], _DRAM, ttnn.int32, ttnn.ROW_MAJOR_LAYOUT)


@pytest.mark.parametrize("selector", ["", "Codegen", "codgen", "default"])
def test_tilize_codegen_rejects_an_unknown_implementation(device, expect_error, selector):
    shape, kwargs, dtype, layout = _SELECTOR_CASE
    xt = ttnn.from_torch(_make_input(shape, dtype), dtype=dtype, layout=layout, device=device)
    # The selector is parsed on every call, including ones a front-end shortcut would
    # otherwise answer without dispatching, so an unknown value never passes silently.
    with expect_error(RuntimeError, "unknown implementation selector"):
        ttnn.tilize(xt, **kwargs, implementation=selector)
