multihost_config:
  enabled: true
  num_workers: 16
  socket_type: fabric
  pipeline_parallel_config:
    num_blocks: 126
    blocks_per_rank:
      0: 7
      1: 8
      2: 8
      3: 8
      4: 8
      5: 8
      6: 8
      7: 8
      8: 8
      9: 8
      10: 8
      11: 8
      12: 8
      13: 8
      14: 8
      15: 7
