# Maps each pipeline stage to a (host, slice) pair.

stage_to_slice_mapping:
  0:
    host: bh-glx-d08u08
    slice: 3
  1:
    host: bh-glx-d08u08
    slice: 2
  2:
    host: bh-glx-d08u08
    slice: 1
  3:
    host: bh-glx-d08u08
    slice: 0
  4:
    host: bh-glx-d08u02
    slice: 3
  5:
    host: bh-glx-d08u02
    slice: 2
  6:
    host: bh-glx-d08u02
    slice: 1
  7:
    host: bh-glx-d08u02
    slice: 0
  8:
    host: bh-glx-d07u02
    slice: 3
  9:
    host: bh-glx-d07u02
    slice: 2
  10:
    host: bh-glx-d07u02
    slice: 1
  11:
    host: bh-glx-d07u02
    slice: 0
  12:
    host: bh-glx-d07u08
    slice: 3
  13:
    host: bh-glx-d07u08
    slice: 2
  14:
    host: bh-glx-d07u08
    slice: 1
  15:
    host: bh-glx-d07u08
    slice: 0

mesh_graph_desc_path: models/demos/deepseek_v3_b1/scaleout_configs/blitz_decode_single_pod_mesh_graph_descriptor.textproto
rank_binding_file: blitz_decode_pipeline_rank_binding_single_pod.yaml
rank_file: blitz_decode_pipeline_rank_file_single_pod
