// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

// Test-local operation selector.  Keeping the test harness independent of the
// production SfpuType dispatch lets parity tests name every public SFPI entry
// without changing a production call site's selector type.
enum class QuasarSfpuTestOperation
{
    abs,
    square,
    rsqrt,
    exponential,
    gelu,
    relu,
    reciprocal,
    sqrt,
    sqrt_custom,
    log,
    log1p,
    tanh,
    sigmoid,
    silu,
    clamp,
    negative,
    softplus,
    typecast,
    sine,
    cosine,
    tan,
    atan,
    asin,
    acos,
    sinh,
    cosh,
    acosh,
    asinh,
    atanh,
    equal_zero,
    not_equal_zero,
    less_than_zero,
    greater_than_zero,
    less_than_equal_zero,
    greater_than_equal_zero,
    hardsigmoid,
    add1,
    cast_fp32_to_fp16a,
    cbrt,
    celu,
    digamma,
    elu,
    erf,
    erfc,
    erfinv,
    exp2,
    expm1,
    hardmish,
    hardshrink,
    hardtanh,
    heaviside,
    i0,
    i1,
    identity,
    lgamma,
    polygamma,
    prelu,
    rdiv,
    rpow,
    selu,
    sign,
    softshrink,
    softsign,
    tanhshrink,
    unary_ne,
    unary_eq,
    unary_gt,
    unary_lt,
    unary_ge,
    unary_le,
    power,
    left_shift,
    right_shift,
    xielu,
};
