// SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <cstdint>

// Test-only compile-time op keys for the tt-llk Python/C++ harness.
//
// These enums are NOT production types. Production SFPU ops are selected by
// per-op structs (sfpu::Exp, sfpu::Where, ...) and per-family mode enums
// (ckernel::sfpu::ZeroCompMode, UnaryCompMode, BinaryCompMode, IsInfNanMode,
// TrigOp). The enumerators below are the union of the names previously
// published as the production op-key enum in the WH/BH metal llk_api headers and the Quasar
// llk_defs.h copy, spelled identically so OpSpec names in
// python_tests/helpers/llk_params.py stay unchanged.
//
// To add a harness-visible op:
// 1. Add the enumerator here (SfpuUnaryOp or SfpuTernaryOp).
// 2. Add the struct / SfpuUnaryFn adapter to the dispatch tables in
//    sfpu_operations.h (and sfpu_operations_quasar.h when the op is on Quasar).

namespace test_utils
{

enum class SfpuUnaryOp : std::uint32_t
{
    tanh,
    hardtanh,
    gelu,
    gelu_tanh,
    exponential,
    exp_with_base,
    sigmoid,
    reciprocal,
    sqrt,
    lrelu,
    prelu,
    power,
    square,
    tanh_derivative,
    log,
    log_with_base,
    log1p,
    equal_zero,
    not_equal_zero,
    less_than_zero,
    greater_than_equal_zero,
    less_than_equal_zero,
    greater_than_zero,
    clamp,
    gelu_derivative,
    dropout,
    abs,
    abs_int32,
    sign,
    max,
    sine,
    cosine,
    cosh,
    sinh,
    tan,
    relu_max,
    relu_min,
    relu,
    stochround,
    add,
    swiglu,
    mul_int,
    cast_fp32_to_fp16a,
    sigmoid_appx,
    gelu_appx,
    elu,
    min,
    exp2,
    heaviside,
    expm1,
    signbit,
    asin,
    acos,
    acosh,
    atan,
    asinh,
    atanh,
    erf,
    erfc,
    rsqrt,
    isfinite,
    isinf,
    isposinf,
    isneginf,
    isnan,
    logical_not_unary,
    erfinv,
    i0,
    i1,
    silu,
    mask,
    negative,
    quant_int32,
    requant_int32,
    dequant_int32,
    add_int32,
    add_uint32,
    add_uint16,
    add1,
    sub_int32,
    sub_uint16,
    mul_uint16,
    mul_int32,
    div_int32,
    div_int32_floor,
    div_int32_trunc,
    remainder_int32,
    remainder_uint32,
    fmod_int32,
    lt,
    gt,
    ge,
    le,
    lt_int,
    gt_int,
    le_int,
    ge_int,
    eq_int,
    ne_int,
    eq,
    topk_local_sort,
    topk_merge,
    topk_rebuild,
    unary_ne,
    unary_eq,
    unary_gt,
    unary_lt,
    unary_ge,
    unary_le,
    unary_max,
    unary_min,
    softplus,
    tiled_prod,
    bitwise_xor,
    bitwise_not,
    bitwise_and,
    bitwise_or,
    right_shift,
    floor,
    trunc,
    frac,
    left_shift,
    remainder,
    fmod,
    ceil,
    isclose,
    unused,
    reshuffle_rows,
    cumsum,
    fill,
    alt_complex_rotate90,
    round,
    cpy_values,
    gcd,
    lcm,
    softshrink,
    tanhshrink,
    hardshrink,
    hardsigmoid,
    threshold,
    where,
    softsign,
    celu,
    max_pool_with_indices,
    selu,
    rpow,
    cbrt,
    hardmish,
    reduce,
    add_top_row,
    rdiv,
    typecast,
    addcmul,
    max_int32,
    min_int32,
    max_uint32,
    min_uint32,
    unary_max_int32,
    unary_min_int32,
    unary_max_uint32,
    unary_min_uint32,
    addcdiv,
    lerp,
    snake_beta,
    mac,
    xielu,
    lgamma,
    polygamma,
    mish,
    ne,
    digamma,
    identity,
    sqrt_custom,
    tanh_derivative_lut,
    rsqrt_compat,
    reciprocal_compat,
    expm1_cw,
    softcap,
    situ_glu,
};

enum class SfpuTernaryOp : std::uint32_t
{
    where,
    addcmul,
    addcdiv,
    lerp,
    snake_beta,
    mac,
};

} // namespace test_utils

// Global using so emitted kernel code can spell `SfpuUnaryOp::x` / `SfpuTernaryOp::x`
// the same way it previously spelled the production op-key enum.
using test_utils::SfpuTernaryOp;
using test_utils::SfpuUnaryOp;
