name: "Build TT-Metalium Evaluation Image"

on:
  push:
    branches:
      - evaluation-improvements

jobs:
  build-evaluation-image:
    name: "📦 Evaluation Image"
    uses: ./.github/workflows/build-evaluation-image.yaml
    secrets: inherit
    with:
      buildkit: true
      build-args: |
        BUILD_METAL_ARGS=--build-type Release --build-all
