name: "(Galaxy) Choose your pipeline"

on:
  workflow_dispatch:
    inputs:
      trigger_type:
        description: "'manual' = custom selection below; other options = predefined configs. ⚠️ Resource intensive!"
        required: true
        type: choice
        options:
          - manual
          - models-mandatory
          - models-extended
          - op-pr
          - nightly
          - hw-self-test
        default: "manual"
      extra-tag:
        required: true
        type: string
        default: "in-service"
      galaxy-quick:
        required: false
        type: boolean
        default: false
      galaxy-unit:
        description: "Unit tests: Select all, specific model, or disabled"
        required: false
        type: choice
        options:
          - disabled
          - all
          - unit
          - fabric
          - multiprocess
          - llama3-70b
          - prefetcher
          - distributed-ops
          - gpt-oss
        default: "disabled"
      galaxy-demo:
        description: "Demo tests: Select all, specific model, or disabled"
        required: false
        type: choice
        options:
          - disabled
          - all
          - llama3
          - llama3_long_context
          - llama3_evals
          - llama3_8b_dp
          - llama3_70b_dp
          - falcon7b
          - sentence_bert
          - whisper
          - sd35
          - flux1
          - gpt-oss
          - motif
          - wan22
          - mochi
          - qwen3_32b
          - qwen3_32b_long_context
          - deepseek_v3
          - qwenimage
        default: "disabled"
      galaxy-integration:
        description: "Integration tests: Select all, specific model, or disabled"
        required: false
        type: choice
        options:
          - disabled
          - all
          - llama3
          - resnet50
          - unit
          - sd35
          - wan22
          - mochi
          - flux1
          - motif
          - qwenimage
        default: "disabled"
      galaxy-perf:
        description: "Perf tests: Select all, specific model, or disabled"
        required: false
        type: choice
        options:
          - disabled
          - all
          #          - cnn
          #          - llama70b
          #          - llama_unit_tests
          #          - llama70b_prefill
          - sd35
          - flux1-dev
          - motif
          #          - sentence_bert
          - wan2-2
          - mochi
          - qwenimage
        default: "disabled"
      platform:
        required: false
        type: choice
        default: "Ubuntu 22.04"
        options:
          - "Ubuntu 22.04"
          - "Ubuntu 24.04"
        description: "Platform to build and test"
      build-type:
        required: false
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - ASan
          - TSan
        default: "Release"
      enable-lto:
        required: false
        type: boolean
        default: false
        description: "Enable Link Time Optimization (LTO)"
run-name: ${{ inputs.description }}
jobs:
  # Centralized logic to determine what should run
  determine-tests:
    runs-on: ubuntu-latest
    outputs:
      run-quick: ${{ steps.logic.outputs.run-quick }}
      run-unit: ${{ steps.logic.outputs.run-unit }}
      run-integration: ${{ steps.logic.outputs.run-integration }}
      run-demo: ${{ steps.logic.outputs.run-demo }}
      run-model-perf: ${{ steps.logic.outputs.run-model-perf }}
    steps:
      - name: Determine test execution
        id: logic
        # Skip all but galaxy-quick if trigger-type is not manual
        env:
          INPUT_TRIGGER_TYPE: ${{ inputs.trigger_type }}
          INPUT_GALAXY_QUICK: ${{ inputs.galaxy-quick }}
          INPUT_GALAXY_UNIT: ${{ inputs.galaxy-unit }}
          INPUT_GALAXY_INTEGRATION: ${{ inputs.galaxy-integration }}
          INPUT_GALAXY_DEMO: ${{ inputs.galaxy-demo }}
          INPUT_GALAXY_PERF: ${{ inputs.galaxy-perf }}
        run: |
          case "$INPUT_TRIGGER_TYPE" in
            "manual")
              printf '%s\n' "run-quick=${INPUT_GALAXY_QUICK}" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-unit=$([[ "$INPUT_GALAXY_UNIT" != "disabled" ]] && echo "true" || echo "false")" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-integration=$([[ "$INPUT_GALAXY_INTEGRATION" != "disabled" ]] && echo "true" || echo "false")" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-demo=$([[ "$INPUT_GALAXY_DEMO" != "disabled" ]] && echo "true" || echo "false")" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-model-perf=$([[ "$INPUT_GALAXY_PERF" != "disabled" ]] && echo "true" || echo "false")" >> "${GITHUB_OUTPUT}"
              ;;
            "models-mandatory")
              printf '%s\n' "run-quick=true" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-unit=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-integration=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-demo=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-model-perf=false" >> "${GITHUB_OUTPUT}"
              ;;
            "models-extended")
              printf '%s\n' "run-quick=true" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-unit=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-integration=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-demo=true" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-model-perf=true" >> "${GITHUB_OUTPUT}"
              ;;
            "op-pr")
              printf '%s\n' "run-quick=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-unit=true" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-integration=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-demo=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-model-perf=false" >> "${GITHUB_OUTPUT}"
              ;;
            "nightly")
              printf '%s\n' "run-quick=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-unit=true" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-integration=true" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-demo=true" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-model-perf=true" >> "${GITHUB_OUTPUT}"
              ;;
            "hw-self-test")
              printf '%s\n' "run-quick=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-unit=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-integration=true" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-demo=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-model-perf=true" >> "${GITHUB_OUTPUT}"
              ;;
            *)
              printf '%s\n' "run-quick=true" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-unit=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-integration=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-demo=false" >> "${GITHUB_OUTPUT}"
              printf '%s\n' "run-model-perf=false" >> "${GITHUB_OUTPUT}"
              ;;
          esac
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    permissions:
      packages: write
    secrets:
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    needs: determine-tests
    with:
      build-type: ${{ inputs.build-type || 'Release' }}
      enable-lto: ${{ inputs.enable-lto || false }}
      tracy: ${{ needs.determine-tests.outputs.run-model-perf == 'true' }}
      build-wheel: true
      build-umd-tests: true
      platform: ${{ inputs.platform || 'Ubuntu 22.04' }}
  galaxy-quick:
    if: ${{ needs.determine-tests.outputs.run-quick == 'true' }}
    needs: [build-artifact, determine-tests]
    secrets:
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    uses: ./.github/workflows/galaxy-quick-impl.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
  galaxy-unit-tests:
    if: ${{ needs.determine-tests.outputs.run-unit == 'true' }}
    needs: [build-artifact, determine-tests]
    secrets:
      SFTP_BENCHMARK_WRITER_KEY: ${{ secrets.SFTP_BENCHMARK_WRITER_KEY }}
      SFTP_FABRIC_BENCHMARK_WRITER_HOSTNAME: ${{ secrets.SFTP_FABRIC_BENCHMARK_WRITER_HOSTNAME }}
      SFTP_FABRIC_BENCHMARK_WRITER_USERNAME: ${{ secrets.SFTP_FABRIC_BENCHMARK_WRITER_USERNAME }}
      SFTP_FABRIC_LATENCY_WRITER_USERNAME: ${{ secrets.SFTP_FABRIC_LATENCY_WRITER_USERNAME }}
      SLACK_METAL_INFRA_PIPELINE_STATUS_ALERT: ${{ secrets.SLACK_METAL_INFRA_PIPELINE_STATUS_ALERT }}
    uses: ./.github/workflows/galaxy-unit-tests-impl.yaml
    with:
      extra-tag: ${{ inputs.extra-tag }}
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      model: ${{ inputs.trigger_type == 'manual' && inputs.galaxy-unit || 'all' }}
      topology: "topology-6u"
  galaxy-integration-tests:
    if: ${{ needs.determine-tests.outputs.run-integration == 'true' }}
    needs: [build-artifact, determine-tests]
    secrets:
      SLACK_METAL_INFRA_PIPELINE_STATUS_ALERT: ${{ secrets.SLACK_METAL_INFRA_PIPELINE_STATUS_ALERT }}
    uses: ./.github/workflows/galaxy-integration-tests-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      enabled-skus: wh_galaxy
      model: ${{ inputs.trigger_type == 'manual' && inputs.galaxy-integration || 'all' }}
  galaxy-demo-tests:
    if: ${{ needs.determine-tests.outputs.run-demo == 'true' }}
    needs: [build-artifact, determine-tests]
    secrets:
      SLACK_METAL_INFRA_PIPELINE_STATUS_ALERT: ${{ secrets.SLACK_METAL_INFRA_PIPELINE_STATUS_ALERT }}
    uses: ./.github/workflows/galaxy-demo-tests-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      enabled-skus: wh_galaxy
      model: ${{ inputs.trigger_type == 'manual' && inputs.galaxy-demo || 'all' }}
  galaxy-model-perf-tests:
    if: ${{ needs.determine-tests.outputs.run-model-perf == 'true' }}
    needs: [build-artifact, determine-tests]
    secrets:
      SFTP_BENCHMARK_WRITER_HOSTNAME: ${{ secrets.SFTP_BENCHMARK_WRITER_HOSTNAME }}
      SFTP_BENCHMARK_WRITER_KEY: ${{ secrets.SFTP_BENCHMARK_WRITER_KEY }}
      SFTP_BENCHMARK_WRITER_USERNAME: ${{ secrets.SFTP_BENCHMARK_WRITER_USERNAME }}
      SLACK_METAL_INFRA_PIPELINE_STATUS_ALERT: ${{ secrets.SLACK_METAL_INFRA_PIPELINE_STATUS_ALERT }}
    uses: ./.github/workflows/galaxy-perf-tests-impl.yaml
    with:
      docker-image: ${{ needs.build-artifact.outputs.dev-docker-image }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      enabled-skus: wh_galaxy
      model: ${{ inputs.trigger_type == 'manual' && inputs.galaxy-perf || 'all' }}
