name: PR Gate
# This pipeline is the minimum bar a PR must pass before it can be merged.
# It is intended to be fast and lightweight to trigger automatically on every
# change in every PR and provide quick feedback without overloading the CI.

# Requirements for all jobs in this workflow:
# - A new job must cancel a previously scheduled/running job.
#   PRs only care about the latest commit and multiple pushes may happen in quick succession.
# - End-to-end (excluding wait times for runners) must be less than 5mins.
#   This includes the cost of checking out the code, preparing a runner, etc.
# - Individual test cases must be less than 1s.

on:
  workflow_dispatch:
  push:
    branches:
      - afuller/tests-shift-left

  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      docker-image.ci-build.tag:
        description: "Docker tag for the CI Build Docker image for building TT-Metalium et al"
        value: ${{ jobs.build.outputs.ci-build-tag }}
      docker-image.ci-test.tag:
        description: "Docker tag for the CI Test Docker image for testing TT-Metalium et al"
        value: ${{ jobs.build.outputs.ci-test-tag }}

#  pull_request:
#    types:
#      - opened
#      - reopened
#      - synchronize
#      - ready_for_review
#    branches:
#      - "main"

#concurrency:
#  # Use github.run_id on main branch (or any protected branch)
#  # This ensure that no runs get cancelled on main
#  # Use github.event.pull_request.number on pull requests, so it's unique per pull request
#  # and will cancel obsolete runs
#  # Use github.ref on other branches, so it's unique per branch
#  # Possibly PRs can also just use `github.ref`, but for now just copy/pasting from
#  # https://www.meziantou.net/how-to-cancel-github-workflows-when-pushing-new-commits-on-a-branch.htm
#  # group: ${{ github.workflow }}-${{ github.ref_protected && github.run_id || github.event.pull_request.number || github.ref }}
#  # cancel-in-progress: true

jobs:
  build:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    uses: ./.github/workflows/build-artifact.yaml
    with:
      os: "ubuntu-22.04-amd64"

  metal-tests:
    needs: build
    runs-on:
      - in-service
      - cloud-virtual-machine
      - BH
    container:
      image: ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-22.04-amd64:dev-afuller-tests-shift-left
      env:
        ENV_VAR: foo
      volumes:
        - ${{ github.workspace }}/docker-job:/work # subdir to workaround https://github.com/actions/runner/issues/691
        - /dev/hugepages-1G:/dev/hugepages-1G
      options: --device /dev/tenstorrent
    defaults:
      run:
        shell: bash
        working-directory: /work # https://github.com/actions/runner/issues/878
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: TTMetal_build_any
          path: /work/
      - name: Extract files
        run: tar -xvf ttm_any.tar
      - name: Srsly
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
          path: docker-job/deleteme # Here be dragons; keep it scoped to our desired volume, yet must be under github.workspace
      - name: Proper packaging can't come soon enough
        run: |
          mkdir -p tt_metal
          ls -al tt_metal
          cp -a deleteme/tt_metal/soc_descriptors tt_metal/
          cp -a deleteme/tt_metal/core_descriptors tt_metal/
          mkdir -p tt_metal/hw/firmware
          cp -a deleteme/tt_metal/hw/firmware/src tt_metal/hw/firmware/
          cp -a deleteme/tt_metal/hw/inc tt_metal/hw/
          mkdir -p tt_metal/api/tt-metalium
          cp deleteme/tt_metal/api/tt-metalium/dev_msgs.h tt_metal/api/tt-metalium/
          mkdir -p tt_metal/hostdevcommon
          cp -a deleteme/tt_metal/hostdevcommon/api tt_metal/hostdevcommon/
          ls -al tt_metal/hostdevcommon/api/hostdevcommon

          find . -iname 'ckernel.h'

          mkdir -p tt_metal/third_party/tt_llk_wormhole_b0/common
          cp -a deleteme/tt_metal/third_party/tt_llk_wormhole_b0/common/inc tt_metal/third_party/tt_llk_wormhole_b0/common/
          cp -a deleteme/tt_metal/third_party/tt_llk_wormhole_b0/llk_lib tt_metal/third_party/tt_llk_wormhole_b0/
          mkdir -p tt_metal/third_party/tt_llk_grayskull/common
          cp -a deleteme/tt_metal/third_party/tt_llk_grayskull/common/inc tt_metal/third_party/tt_llk_grayskull/common/
          cp -a deleteme/tt_metal/third_party/tt_llk_grayskull/llk_lib tt_metal/third_party/tt_llk_grayskull/
          mkdir -p tt_metal/third_party/tt_llk_blackhole/common
          cp -a deleteme/tt_metal/third_party/tt_llk_blackhole/common/inc tt_metal/third_party/tt_llk_blackhole/common/
          cp -a deleteme/tt_metal/third_party/tt_llk_blackhole/llk_lib tt_metal/third_party/tt_llk_blackhole/

      - name: Run a test
        env:
          # TODO: None of these should be necessary
          LD_LIBRARY_PATH: /work/build/lib
          TT_METAL_HOME: /work
        run: |
          ./build/test/tt_metal/unit_tests_noc

      - name: Cleanup
        if: always()
        run: |
          set -x
          echo "pre rm"
          ls -al /__w/tt-metal/tt-metal
          rm -rf /__w/tt-metal/tt-metal/deleteme
          rm -rf /__w/tt-metal/tt-metal/docker-job
          rm -rf /__w/tt-metal/tt-metal/foo
          echo "post rm"
          ls -al /__w/tt-metal/tt-metal

          cat /__w/tt-metal/tt-metal/semicolon_delimited_script
