name: "Publish packages"

on:
  workflow_dispatch:

jobs:
  smoke:
    name: Debian packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        timeout-minutes: 10
        with:
          name: ${{ inputs.package-artifact-name || 'packages artifact unresolved!' }}
          path: /work/pkgs/
      - name: Push
        id: push
        uses: cloudsmith-io/action@7af394e0f8add4867bce109385962dafecad1b8d # v0.6.14
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "deb"
          owner: "tenstorrent"
          repo: "tt-metalium"
          distro: "ubuntu"
          release: "22.04"
          # republish: "true" # needed ONLY if version is not changing
          # file: "test/fixture/cloudsmith-debian-example_1.0.0_amd64.deb"
          # apt install -y ./pkgs/tt-metalium_*.deb ./pkgs/tt-metalium-jit_*.deb ./pkgs/${{ inputs.product }}_*.deb ./pkgs/${{ inputs.product }}-validation_*.deb
