name: "[temp] CCache test"

on:
  workflow_dispatch:

jobs:
  check-harbor:
    uses: ./.github/workflows/check-harbor.yaml
  build-artifact:
    needs: check-harbor
    uses: ./.github/workflows/build-artifact.yaml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      harbor-prefix: ${{ needs.check-harbor.outputs.harbor-prefix }}
      build-type: Release
      build-wheel: true
      tracy: true
      platform: "Ubuntu 22.04"
      skip-tt-train: false

  ttnn-unit-tests:
    needs: [check-harbor, build-artifact]
    uses: ./.github/workflows/ttnn-sanity-tests-impl.yaml
    secrets: inherit
    with:
      enabled-skus: wh_n150_civ2
      docker-image: ${{ format('{0}{1}', needs.check-harbor.outputs.harbor-prefix, needs.build-artifact.outputs.ci-test-docker-image) }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
      timeout-minutes-override: 45
