name: "[post-commit] ttnn unit tests"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  static-checks:
    uses: ./.github/workflows/all-static-checks.yaml
    secrets: inherit
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  ttnn-unit-tests-e150:
    needs: build-artifact
    uses: ./.github/workflows/ttnn-post-commit.yaml
    secrets: inherit
    with:
      arch: grayskull
      runner-label: E150
  ttnn-unit-tests-n150:
    needs: build-artifact
    uses: ./.github/workflows/ttnn-post-commit.yaml
    secrets: inherit
    with:
      arch: wormhole_b0
      runner-label: N150
  ttnn-unit-tests-n300:
    needs: build-artifact
    uses: ./.github/workflows/ttnn-post-commit.yaml
    secrets: inherit
    with:
      arch: wormhole_b0
      runner-label: N300
