name: "[internal] ttnn stress tests impl"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 45
      docker-image:
        required: true
        type: string
      build-artifact-name:
        required: true
        type: string
      wheel-artifact-name:
        required: true
        type: string

jobs:
  ttnn:
    name: ttnn stress tests ${{ inputs.arch }} ${{ inputs.runner-label }}
    runs-on:
      - "in-service"
      - "${{ inputs.runner-label }}"
      - "${{ (inputs.runner-label == 'config-tg' || inputs.runner-label == 'topology-6u') && 'bare-metal' || 'cloud-virtual-machine' }}"


    container:
      image: ${{ inputs.docker-image }}
      env:
        ARCH_NAME: ${{ inputs.arch }}
        LOGURU_LEVEL: INFO
        PYTHONPATH: /work
      volumes:
        - ${{ github.workspace }}/docker-job:/work # Subdir to workaround https://github.com/actions/runner/issues/691
        - /dev/hugepages-1G:/dev/hugepages-1G
      options: "--device /dev/tenstorrent"
    defaults:
      run:
        shell: bash
        working-directory: /work # https://github.com/actions/runner/issues/878
    steps:
      - name: ⬇️  Setup Job
        uses: tenstorrent/tt-metal/.github/actions/setup-job@main
        timeout-minutes: 10
        with:
          wheel-artifact-name: ${{ inputs.wheel-artifact-name }}

      - name: Run Stress Tests
        timeout-minutes: ${{ inputs.timeout }}
        run: |
          # Health check loop
          for i in {1..10}; do
            echo "Health check attempt $i"
            if tt-smi -r 0,1,2,3 && ./build/test/tt_metal/tt_fabric/test_system_health; then
              echo "Health checks passed"
              break
            fi
            if [ $i -eq 10 ]; then
              echo "Health checks failed after 10 attempts"
              exit 1
            fi
            echo "Health checks failed, retrying..."
            sleep 5
          done
          pytest tests/ttnn/stress_tests/

      - uses: tenstorrent/tt-metal/.github/actions/cleanup@main
        if: always()
