name: "[impl] TTSim unit tests impl"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 5
      docker-image:
        required: true
        type: string
      build-artifact-name:
        required: true
        type: string
      wheel-artifact-name:
        required: true
        type: string
      build-suffix:
        required: true
        type: string
      soc-desc:
        required: true
        type: string
      ttsim-ref:
        required: false
        type: string
        default: "4f05a65a961d4a3ca14f65ff9633030e0a35358e"

jobs:
  ttsim-cpp-unit-tests:
    runs-on: ${{ inputs.runner-label }}
    name: "TTSim C++ tests - ${{ inputs.arch }}"
    strategy:
      fail-fast: false
    container:
      image: harbor.ci.tenstorrent.net/${{ inputs.docker-image || 'docker-image-unresolved!'}}
      volumes:
        - ${{ github.workspace }}/docker-job:/work
    defaults:
      run:
        shell: bash
        working-directory: /work # https://github.com/actions/runner/issues/878
    env:
      TT_METAL_SIMULATOR_HOME: /work/sim
      TT_METAL_SIMULATOR: /work/sim/libttsim.so
      TT_METAL_SLOW_DISPATCH_MODE: 1
    steps:
      - name: Setup Job
        uses: tenstorrent/tt-metal/.github/actions/setup-job@5b5c6ff5b54025e165d189371cda93d2b9ef6115
        timeout-minutes: 10
        with:
          build-artifact-name: ${{ inputs.build-artifact-name }}
          wheel-artifact-name: ${{ inputs.wheel-artifact-name }}

      - name: Checkout ttsim
        uses: actions/checkout@v4
        with:
          repository: tenstorrent/ttsim
          ref: ${{ inputs.ttsim-ref }}
          path: docker-job/ttsim
          token: ${{ secrets.TTSIM_TOKEN }}

      - name: Build ttsim
        run: |
          cd /work/ttsim/src
          ../scripts/make.py _out/${{ inputs.build-suffix }}/libttsim.so

      - name: Install ttsim
        run: |
          mkdir -p $TT_METAL_SIMULATOR_HOME
          cp /work/ttsim/src/_out/${{ inputs.build-suffix }}/libttsim.so $TT_METAL_SIMULATOR_HOME/
          cp /work/tt_metal/soc_descriptors/${{ inputs.soc-desc }} $TT_METAL_SIMULATOR_HOME/soc_descriptor.yaml

      - name: C++ tests
        run: |
          ./build/test/tt_metal/unit_tests_api --gtest_filter="MeshDeviceFixture.IdleEthTestNocStreamRegs"
          ./build/test/tt_metal/unit_tests_api --gtest_filter="MeshDispatchFixture.IdleEthDRAMLoopbackSingleCore"
          ./build/test/tt_metal/unit_tests_debug_tools --gtest_filter="DPrintMeshFixture.IdleEthTestPrint"
          # BH doesn't work on watcher, triggers: ERROR: decode_and_execute_fence: unsupported fence_mode=0x31
          if [[ "${{ inputs.arch }}" != "blackhole" ]]; then
            # WH works (very long test, by default for erisc runs at least 0x5f5e1000U cycles)
            # ./build/test/tt_metal/unit_tests_debug_tools --gtest_filter="MeshWatcherFixture.TensixTestWatcherPause"
            ./build/test/tt_metal/unit_tests_debug_tools --gtest_filter="MeshWatcherFixture.TestWatcherRingBufferIErisc"
            ./build/test/tt_metal/unit_tests_debug_tools --gtest_filter="MeshWatcherFixture.TestWatcherStackUsage0"
            ./build/test/tt_metal/unit_tests_debug_tools --gtest_filter="MeshWatcherFixture.TestWatcherStackUsage16"
          fi
          ./build/test/tt_metal/unit_tests_dispatch --gtest_filter="MeshDispatchFixture.TensixIdleEthTestSemaphores"
          ./build/test/tt_metal/unit_tests_dispatch --gtest_filter="MeshDispatchFixture.EthTestBlank"
          ./build/test/tt_metal/unit_tests_eth --gtest_filter="BlackholeSingleCardFixture.IdleEthKernelOnIdleErisc0"
          ./build/test/tt_metal/unit_tests_eth --gtest_filter="BlackholeSingleCardFixture.IdleEthKernelOnIdleErisc1"
          ./build/test/tt_metal/unit_tests_eth --gtest_filter="BlackholeSingleCardFixture.IdleEthKernelOnBothIdleEriscs"
