name: "[internal] UMD Unit tests"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 15
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options:
          - wormhole_b0
          - blackhole
      runner-label:
        required: true
        type: choice
        options:
          - N150
          - N300
          - BH
      timeout:
        required: false
        type: number
        default: 15

jobs:
  umd-unit-tests:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        runner-label: ["P150-quad-01", "P150-quad-02", "P150-quad-03", "P150-quad-04", "P150-173", "P150-174", "P150-175", "P150-194", "P150-178", "P150-199", "P150-206", "P150-201", "P150-209", "P150-195", "P150-196", "P150-197", "P150-198", "P150-200", "P150-207", "P150-208", "P150-210", "P150-211", "P150-212", "P150-213", "P150-214"]
    name: ${{ inputs.arch }} ${{ matrix.runner-label }}
    runs-on:
      - ${{ matrix.runner-label }}
      - cloud-virtual-machine
      # - in-service
    env:
      ARCH_NAME: ${{ inputs.arch }}
      LOGURU_LEVEL: INFO
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build UMD device and tests
        run: |
          cmake -B build -G Ninja -DTT_UMD_BUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=cmake/x86_64-linux-clang-17-libcpp-toolchain.cmake
          cmake --build build --target umd_tests
      - name: Run UMD unit tests
        timeout-minutes: ${{ inputs.timeout }}
        run: build/test/umd/${{ inputs.arch }}/unit_tests
