set(TTNN_OP_EXPERIMENTAL_DEEPSEEK_PREFILL_HIGH_BW_ALL_GATHER_API_HEADERS high_bw_all_gather.hpp)

set(TTNN_OP_EXPERIMENTAL_DEEPSEEK_PREFILL_HIGH_BW_ALL_GATHER_SRCS
    device/high_bw_all_gather_device_operation.cpp
    device/high_bw_all_gather_unicast_factory.cpp
    high_bw_all_gather.cpp
)

set(TTNN_OP_EXPERIMENTAL_DEEPSEEK_PREFILL_HIGH_BW_ALL_GATHER_NANOBIND_SRCS high_bw_all_gather_nanobind.cpp)
