# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

# autoflake: skip_file

# utility_functions.py has been moved to models/common. This is a temporary redirecting file.
# Update your imports accordingly as soon as possible.
# Use: models.common.utility_functions

from models.common.utility_functions import (
    Profiler,
    _comp_nonfinite,
    _nearest_32,
    _nearest_y,
    blocked_mm_with_conv_act,
    comp_allclose,
    comp_allclose_and_pcc,
    comp_equal,
    comp_pcc,
    comp_ulp,
    convert_act_2d_matrix,
    convert_weights_2d_matrix,
    disable_memory_reports,
    disable_persistent_kernel_cache,
    divup,
    enable_memory_reports,
    enable_persistent_kernel_cache,
    float_to_bits,
    get_debug_tensor,
    get_devices_for_t3000,
    get_mesh_device,
    get_oom_of_float,
    is_blackhole,
    is_close,
    is_conv_supported_on_device,
    is_e75,
    is_grayskull,
    is_single_chip,
    is_wormhole_b0,
    is_x2_harvested,
    nearest_32,
    nearest_y,
    pad_activation,
    pad_and_fold_conv_filters_for_unity_stride,
    pad_by_zero,
    pad_weight,
    print_diff_argmax,
    print_diff_tt_pyt,
    profiler,
    read_conv_act_into_mm_act_block,
    read_conv_weight_into_mm_weight_block,
    roundup,
    roundup32,
    run_for_blackhole,
    run_for_grayskull,
    run_for_wormhole_b0,
    skip_for_blackhole,
    skip_for_grayskull,
    skip_for_wormhole_b0,
    tilize,
    tilize_to_list,
    torch2tt_tensor,
    torch_random,
    torch_random_with_zeros,
    torch_to_tt_tensor,
    torch_to_tt_tensor_rm,
    tt2torch_tensor,
    tt_tensors_to_torch_tensors,
    tt_to_torch_tensor,
    ttl_complex_2_torch_complex,
    ttP,
    ulp,
    unpad_from_zero,
    untilize,
)
