system_graph {
  asic_connectivity_graph {
    host_name: "g14glx03"
    asic_topologies {
      asic_id: 375260265646665814
      topology {
        asic_connections {
          dst_asic_id: 447317859684593750
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87029889494954070
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375260265646665795
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375261330798555467
          eth_connections {
            src_chan: 4
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 303202671608737878
      topology {
        asic_connections {
          dst_asic_id: 591433047760449622
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303203736760627531
          eth_connections {
            src_chan: 11
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 8
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231145077570809942
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 231145077570809942
      topology {
        asic_connections {
          dst_asic_id: 519375453722521686
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303202671608737878
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159087483532882006
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 303203736760627531
      topology {
        asic_connections {
          dst_asic_id: 591434112912339275
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303202671608737878
          eth_connections {
            src_chan: 11
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 8
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231146142722699595
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 87029889494954065
      topology {
        asic_connections {
          dst_asic_id: 375260265646665809
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159087483532882001
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87029889494954051
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 4
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 375261330798555467
      topology {
        asic_connections {
          dst_asic_id: 447318924836483403
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87030954646843723
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375260265646665809
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375260265646665814
          eth_connections {
            src_chan: 4
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 159087483532882001
      topology {
        asic_connections {
          dst_asic_id: 447317859684593745
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231145077570809937
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87029889494954065
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 447318924836483403
      topology {
        asic_connections {
          dst_asic_id: 519376518874411339
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159088548684771659
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 447317859684593745
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375261330798555467
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 231145077570809937
      topology {
        asic_connections {
          dst_asic_id: 519375453722521681
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303202671608737873
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159087483532882001
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 519376518874411339
      topology {
        asic_connections {
          dst_asic_id: 591434112912339275
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231146142722699595
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 519375453722521681
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 447318924836483403
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 591434112912339275
      topology {
        asic_connections {
          dst_asic_id: 591433047760449622
          eth_connections {
            src_chan: 11
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 8
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303203736760627531
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 591433047760449617
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 519376518874411339
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 447317859684593731
      topology {
        asic_connections {
          dst_asic_id: 447317859684593750
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159087483532881987
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375260265646665795
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 519375453722521667
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 159087483532881987
      topology {
        asic_connections {
          dst_asic_id: 447317859684593731
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231145077570809923
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87029889494954051
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 375260265646665809
      topology {
        asic_connections {
          dst_asic_id: 375261330798555467
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87029889494954065
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375260265646665795
          eth_connections {
            src_chan: 4
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 447317859684593745
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 447317859684593750
      topology {
        asic_connections {
          dst_asic_id: 519375453722521686
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159087483532882006
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 447317859684593731
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375260265646665814
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 231146142722699595
      topology {
        asic_connections {
          dst_asic_id: 519376518874411339
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303203736760627531
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159088548684771659
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 303202671608737873
      topology {
        asic_connections {
          dst_asic_id: 591433047760449617
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303202671608737859
          eth_connections {
            src_chan: 11
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 8
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231145077570809937
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 87029889494954051
      topology {
        asic_connections {
          dst_asic_id: 375260265646665795
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159087483532881987
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87029889494954065
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 4
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 591433047760449622
      topology {
        asic_connections {
          dst_asic_id: 591434112912339275
          eth_connections {
            src_chan: 11
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 8
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303202671608737878
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 591433047760449603
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 519375453722521686
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 159088548684771659
      topology {
        asic_connections {
          dst_asic_id: 447318924836483403
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231146142722699595
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87030954646843723
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 519375453722521686
      topology {
        asic_connections {
          dst_asic_id: 591433047760449622
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231145077570809942
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 519375453722521667
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 447317859684593750
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 87030954646843723
      topology {
        asic_connections {
          dst_asic_id: 375261330798555467
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159088548684771659
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87029889494954070
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 4
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 231145077570809923
      topology {
        asic_connections {
          dst_asic_id: 519375453722521667
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303202671608737859
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159087483532881987
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 447317859684593745
      topology {
        asic_connections {
          dst_asic_id: 447318924836483403
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159087483532882001
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375260265646665809
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 519375453722521681
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 87029889494954070
      topology {
        asic_connections {
          dst_asic_id: 375260265646665814
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 159087483532882006
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87030954646843723
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 4
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 303202671608737859
      topology {
        asic_connections {
          dst_asic_id: 591433047760449603
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303202671608737873
          eth_connections {
            src_chan: 11
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 8
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231145077570809923
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 519375453722521681
      topology {
        asic_connections {
          dst_asic_id: 519376518874411339
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231145077570809937
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 447317859684593745
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 591433047760449617
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 159087483532882006
      topology {
        asic_connections {
          dst_asic_id: 447317859684593750
          eth_connections {
            src_chan: 15
            dst_chan: 3
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 2
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 1
            is_local: true
          }
          eth_connections {
            src_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231145077570809942
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87029889494954070
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 375260265646665795
      topology {
        asic_connections {
          dst_asic_id: 375260265646665814
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 87029889494954051
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 375260265646665809
          eth_connections {
            src_chan: 4
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 7
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 447317859684593731
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 591433047760449617
      topology {
        asic_connections {
          dst_asic_id: 591434112912339275
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303202671608737873
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 519375453722521681
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 591433047760449603
          eth_connections {
            src_chan: 8
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 11
            dst_chan: 11
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 519375453722521667
      topology {
        asic_connections {
          dst_asic_id: 519375453722521686
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 231145077570809923
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 447317859684593731
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 591433047760449603
          eth_connections {
            src_chan: 8
            dst_chan: 4
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 5
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 6
            is_local: true
          }
          eth_connections {
            src_chan: 11
            dst_chan: 7
            is_local: true
          }
        }
      }
    }
    asic_topologies {
      asic_id: 591433047760449603
      topology {
        asic_connections {
          dst_asic_id: 591433047760449622
          eth_connections {
            src_chan: 15
            dst_chan: 15
            is_local: true
          }
          eth_connections {
            src_chan: 14
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 13
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 12
            dst_chan: 12
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 303202671608737859
          eth_connections {
            dst_chan: 12
            is_local: true
          }
          eth_connections {
            src_chan: 1
            dst_chan: 13
            is_local: true
          }
          eth_connections {
            src_chan: 2
            dst_chan: 14
            is_local: true
          }
          eth_connections {
            src_chan: 3
            dst_chan: 15
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 519375453722521667
          eth_connections {
            src_chan: 4
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 5
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 6
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 7
            dst_chan: 11
            is_local: true
          }
        }
        asic_connections {
          dst_asic_id: 591433047760449617
          eth_connections {
            src_chan: 8
            dst_chan: 8
            is_local: true
          }
          eth_connections {
            src_chan: 9
            dst_chan: 9
            is_local: true
          }
          eth_connections {
            src_chan: 10
            dst_chan: 10
            is_local: true
          }
          eth_connections {
            src_chan: 11
            dst_chan: 11
            is_local: true
          }
        }
      }
    }
  }
  host_connectivity_graph {
    src_host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 375260265646665814
  asic_descriptor {
    tray_id: 1
    asic_location: 5
    board_type: 9
    unique_id: 375260265646665814
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 303202671608737878
  asic_descriptor {
    tray_id: 1
    asic_location: 4
    board_type: 9
    unique_id: 303202671608737878
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 231145077570809942
  asic_descriptor {
    tray_id: 1
    asic_location: 3
    board_type: 9
    unique_id: 231145077570809942
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 159087483532882006
  asic_descriptor {
    tray_id: 1
    asic_location: 2
    board_type: 9
    unique_id: 159087483532882006
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 87029889494954070
  asic_descriptor {
    tray_id: 1
    asic_location: 1
    board_type: 9
    unique_id: 87029889494954070
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 591433047760449603
  asic_descriptor {
    tray_id: 2
    asic_location: 8
    board_type: 9
    unique_id: 591433047760449603
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 519375453722521667
  asic_descriptor {
    tray_id: 2
    asic_location: 7
    board_type: 9
    unique_id: 519375453722521667
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 447317859684593731
  asic_descriptor {
    tray_id: 2
    asic_location: 6
    board_type: 9
    unique_id: 447317859684593731
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 375260265646665795
  asic_descriptor {
    tray_id: 2
    asic_location: 5
    board_type: 9
    unique_id: 375260265646665795
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 591433047760449617
  asic_descriptor {
    tray_id: 4
    asic_location: 8
    board_type: 9
    unique_id: 591433047760449617
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 303202671608737859
  asic_descriptor {
    tray_id: 2
    asic_location: 4
    board_type: 9
    unique_id: 303202671608737859
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 519375453722521681
  asic_descriptor {
    tray_id: 4
    asic_location: 7
    board_type: 9
    unique_id: 519375453722521681
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 231145077570809923
  asic_descriptor {
    tray_id: 2
    asic_location: 3
    board_type: 9
    unique_id: 231145077570809923
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 447317859684593745
  asic_descriptor {
    tray_id: 4
    asic_location: 6
    board_type: 9
    unique_id: 447317859684593745
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 231146142722699595
  asic_descriptor {
    tray_id: 3
    asic_location: 3
    board_type: 9
    unique_id: 231146142722699595
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 303203736760627531
  asic_descriptor {
    tray_id: 3
    asic_location: 4
    board_type: 9
    unique_id: 303203736760627531
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 375261330798555467
  asic_descriptor {
    tray_id: 3
    asic_location: 5
    board_type: 9
    unique_id: 375261330798555467
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 447318924836483403
  asic_descriptor {
    tray_id: 3
    asic_location: 6
    board_type: 9
    unique_id: 447318924836483403
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 519376518874411339
  asic_descriptor {
    tray_id: 3
    asic_location: 7
    board_type: 9
    unique_id: 519376518874411339
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 591434112912339275
  asic_descriptor {
    tray_id: 3
    asic_location: 8
    board_type: 9
    unique_id: 591434112912339275
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 87029889494954065
  asic_descriptor {
    tray_id: 4
    asic_location: 1
    board_type: 9
    unique_id: 87029889494954065
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 159087483532882001
  asic_descriptor {
    tray_id: 4
    asic_location: 2
    board_type: 9
    unique_id: 159087483532882001
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 231145077570809937
  asic_descriptor {
    tray_id: 4
    asic_location: 3
    board_type: 9
    unique_id: 231145077570809937
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 87029889494954051
  asic_descriptor {
    tray_id: 2
    asic_location: 1
    board_type: 9
    unique_id: 87029889494954051
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 303202671608737873
  asic_descriptor {
    tray_id: 4
    asic_location: 4
    board_type: 9
    unique_id: 303202671608737873
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 159087483532881987
  asic_descriptor {
    tray_id: 2
    asic_location: 2
    board_type: 9
    unique_id: 159087483532881987
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 375260265646665809
  asic_descriptor {
    tray_id: 4
    asic_location: 5
    board_type: 9
    unique_id: 375260265646665809
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 447317859684593750
  asic_descriptor {
    tray_id: 1
    asic_location: 6
    board_type: 9
    unique_id: 447317859684593750
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 87030954646843723
  asic_descriptor {
    tray_id: 3
    asic_location: 1
    board_type: 9
    unique_id: 87030954646843723
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 519375453722521686
  asic_descriptor {
    tray_id: 1
    asic_location: 7
    board_type: 9
    unique_id: 519375453722521686
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 159088548684771659
  asic_descriptor {
    tray_id: 3
    asic_location: 2
    board_type: 9
    unique_id: 159088548684771659
    host_name: "g14glx03"
  }
}
asic_descriptors {
  asic_id: 591433047760449622
  asic_descriptor {
    tray_id: 1
    asic_location: 8
    board_type: 9
    unique_id: 591433047760449622
    host_name: "g14glx03"
  }
}
host_to_mobo_name {
  host_name: "g14glx03"
  mobo_name: "S7T-MB"
}
host_to_rank {
  host_name: "g14glx03"
}
exit_node_connection_table {
  host_name: "g14glx03"
}
ethernet_firmware_version {
  major: 7
  minor: 2
}
pcie_devices_per_tray {
  host_name: "g14glx03"
  pcie_devices_per_tray {
    tray_id: 2
    pcie_device_ids: 8
    pcie_device_ids: 9
    pcie_device_ids: 15
    pcie_device_ids: 13
    pcie_device_ids: 14
    pcie_device_ids: 11
    pcie_device_ids: 12
    pcie_device_ids: 10
  }
  pcie_devices_per_tray {
    tray_id: 3
    pcie_device_ids: 20
    pcie_device_ids: 21
    pcie_device_ids: 16
    pcie_device_ids: 22
    pcie_device_ids: 17
    pcie_device_ids: 23
    pcie_device_ids: 19
    pcie_device_ids: 18
  }
  pcie_devices_per_tray {
    tray_id: 4
    pcie_device_ids: 24
    pcie_device_ids: 31
    pcie_device_ids: 29
    pcie_device_ids: 27
    pcie_device_ids: 28
    pcie_device_ids: 30
    pcie_device_ids: 26
    pcie_device_ids: 25
  }
  pcie_devices_per_tray {
    tray_id: 1
    pcie_device_ids: 2
    pcie_device_ids: 6
    pcie_device_ids: 4
    pcie_device_ids: 5
    pcie_device_ids: 1
    pcie_device_ids: 7
    pcie_device_ids: 3
    pcie_device_ids: 0
  }
}
pcie_id_to_asic_location {
  host_name: "g14glx03"
  pcie_id_to_asic_location {
    pcie_id: 2
    asic_location: 5
  }
  pcie_id_to_asic_location {
    pcie_id: 6
    asic_location: 4
  }
  pcie_id_to_asic_location {
    pcie_id: 4
    asic_location: 3
  }
  pcie_id_to_asic_location {
    pcie_id: 22
    asic_location: 4
  }
  pcie_id_to_asic_location {
    pcie_id: 23
    asic_location: 6
  }
  pcie_id_to_asic_location {
    pcie_id: 19
    asic_location: 7
  }
  pcie_id_to_asic_location {
    pcie_id: 18
    asic_location: 8
  }
  pcie_id_to_asic_location {
    pcie_id: 27
    asic_location: 1
  }
  pcie_id_to_asic_location {
    pcie_id: 28
    asic_location: 2
  }
  pcie_id_to_asic_location {
    pcie_id: 17
    asic_location: 5
  }
  pcie_id_to_asic_location {
    pcie_id: 30
    asic_location: 3
  }
  pcie_id_to_asic_location {
    pcie_id: 1
    asic_location: 1
  }
  pcie_id_to_asic_location {
    pcie_id: 25
    asic_location: 5
  }
  pcie_id_to_asic_location {
    pcie_id: 7
    asic_location: 6
  }
  pcie_id_to_asic_location {
    pcie_id: 3
    asic_location: 7
  }
  pcie_id_to_asic_location {
    pcie_id: 26
    asic_location: 4
  }
  pcie_id_to_asic_location {
    asic_location: 8
  }
  pcie_id_to_asic_location {
    pcie_id: 29
    asic_location: 6
  }
  pcie_id_to_asic_location {
    pcie_id: 16
    asic_location: 3
  }
  pcie_id_to_asic_location {
    pcie_id: 21
    asic_location: 2
  }
  pcie_id_to_asic_location {
    pcie_id: 20
    asic_location: 1
  }
  pcie_id_to_asic_location {
    pcie_id: 31
    asic_location: 7
  }
  pcie_id_to_asic_location {
    pcie_id: 24
    asic_location: 8
  }
  pcie_id_to_asic_location {
    pcie_id: 10
    asic_location: 1
  }
  pcie_id_to_asic_location {
    pcie_id: 12
    asic_location: 2
  }
  pcie_id_to_asic_location {
    pcie_id: 11
    asic_location: 3
  }
  pcie_id_to_asic_location {
    pcie_id: 14
    asic_location: 4
  }
  pcie_id_to_asic_location {
    pcie_id: 13
    asic_location: 5
  }
  pcie_id_to_asic_location {
    pcie_id: 15
    asic_location: 6
  }
  pcie_id_to_asic_location {
    pcie_id: 9
    asic_location: 7
  }
  pcie_id_to_asic_location {
    pcie_id: 8
    asic_location: 8
  }
  pcie_id_to_asic_location {
    pcie_id: 5
    asic_location: 2
  }
}
