import argparse
import time
import random
from itertools import chain
from functools import partial

from loguru import logger

from tests.scripts.common import run_single_test, run_process_and_get_result, report_tests, TestEntry, error_out_if_test_report_has_failures, TestSuiteType
from tests.scripts.cmdline_args import get_cmdline_args, get_llrt_arguments_from_cmdline_args

from tests.tt_metal.llrt.test_run_llrt import LLRT_TEST_ENTRIES, SHORT_SILICON_DRIVER_TEST_ENTRIES, SILICON_DRIVER_TEST_ENTRIES, SKIP_LLRT_ENTRIES, SKIP_LLRT_WORMHOLE_ENTRIES


def run_single_llrt_test(test_entry, timeout, tt_arch):
    run_test = partial(run_single_test, "llrt", timeout=timeout, tt_arch=tt_arch)

    logger.info(f"\n\n=============== RUNNING LLRT TEST - {test_entry}")

    return run_test(test_entry)


def run_llrt_tests(llrt_test_entries, timeout, tt_arch):
    make_test_status_entry = lambda test_entry_: (test_entry_, run_single_llrt_test(test_entry_, timeout, tt_arch))

    seed = time.time()

    random.seed(seed)
    random.shuffle(llrt_test_entries)
    logger.info(f"SHUFFLED LLRT TESTS - Using order generated by seed {seed}")

    test_and_status_entries = map(make_test_status_entry, llrt_test_entries)

    return dict(test_and_status_entries)


def get_llrt_test_entries(short_driver_tests, tt_arch):
    llrt_test_entries = LLRT_TEST_ENTRIES - SKIP_LLRT_ENTRIES

    if tt_arch == "wormhole_b0":
        llrt_test_entries -= SKIP_LLRT_WORMHOLE_ENTRIES

    return list(
        chain.from_iterable([llrt_test_entries, SHORT_SILICON_DRIVER_TEST_ENTRIES if short_driver_tests else SILICON_DRIVER_TEST_ENTRIES])
    )


if __name__ == "__main__":
    cmdline_args = get_cmdline_args(TestSuiteType.LLRT)

    timeout, tt_arch, short_driver_tests, = get_llrt_arguments_from_cmdline_args(cmdline_args)

    llrt_test_entries = get_llrt_test_entries(short_driver_tests=short_driver_tests, tt_arch=tt_arch)

    test_report = run_llrt_tests(llrt_test_entries, timeout, tt_arch)

    report_tests(test_report)

    error_out_if_test_report_has_failures(test_report)
