#!/bin/bash -x
if [[ -z "${TT_METAL_HOME}" ]];
then
   exit "need environment variable ${TT_METAL_HOME}"
fi
if [ $# -ne 2 ];
then
  echo "Usage: tt-stress-test {test type} {runs}"
  echo "options for test type are: post-commit, models, or performance"
  echo "runs option can take any positive value"
  echo "e.g.  tt-stress-test post-commit 5"
  echo "      will run the test post-commit on the set architecture 5 times and log the results"
  exit -1
fi
testtype=$1
runs=$2
if [ $runs -le 0 ];
then
  echo "runs variable should be a positive integer"
  exit -2
fi
python3 ${TT_METAL_HOME}/tests/scripts/tt_bisect.py --good HEAD --bad HEAD --test $testtype --runs $runs
